### ISSUE TITLE
Ban the use of any?

### ISSUE THREAD

**Issue by gamedevsam** [phaserjs/phaser#1]
`any` is a dangerous type that reduces the value of using a compiler that typechecks your codebase. I think tsconfig should be set up to disallow implicit `any`, and we should avoid using it except where we import untyped JS modules.

**Comment by photonstorm** [comment]
It's not something I'm using internally unless something is coming in from outside the API, the type of which is just completely unknown, i.e. callback context scope in the EventEmitter, or the `data` property of the `File` base class, as these could literally hold anything. I guess they could be overridden on a per-case basis though.

**Comment by gamedevsam** [comment]
I've found a small number of `any` in the current codebase, so I'm making a suggestion to set `noImplicitAny` setting in tsconfig, and avoid `any` type unless absolutely necessary. The `any` type has its place, but it should only be used very sparingly, so we actually benefit from the TS compiler.
