### ISSUE TITLE
Ban the use of default exports?

### ISSUE THREAD

**Issue by gamedevsam** [phaserjs/phaser#2]
Named exports are superior to default exports in a few ways:

It's easier to find all uses of a function / property through the project, easier to rename across project, less confusion around names / mental load.

Adopting named exports will pay dividends down the road as the number of modules and exported properties are added.

More info: https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

```
// instead of this export / import
export default function AddChild (parent: IParent, child: IGameObject | IGameObject[])
import AddChild from '../src/gameobjects/container/AddChild';`

// I suggest we use named exports
export function AddChild (parent: IParent, child: IGameObject | IGameObject[])
import { AddChild } from '../src/gameobjects/container/AddChild';

// it's more consistent with importing from an index, ex:
import { AddChild, SetParent } from '../src/gameobjects/container';
```

Having 1 way of importing things is better than having 2 ways of importing things imo.

**Comment by gamedevsam** [comment]
Also with default exports you no longer need to maintain an index.ts for each directory, ex:

```
// for this export
export default function AddChild (parent: IParent, child: IGameObject | IGameObject[])

// we currently support both options by exporting default and manually managing an index.js per directory
import { AddChild } from '../src/gameobjects/container';
import AddChild from '../src/gameobjects/container/AddChild';`

// I suggest we do this instead and not worry about managing an index.js per directory
export function AddChild (parent: IParent, child: IGameObject | IGameObject[])

import { AddChild } from '../src/gameobjects/container/AddChild';
```

**Comment by photonstorm** [comment]
Surely with the current set-up, both of these approaches are allowed? I don't use `export default` for indexes, but I do for the functions and classes themselves.

**Comment by gamedevsam** [comment]
Well, we may disagree, but I'm a big stickler for simplicity. Reasonable people might disagree, but in my view having one way of importing modules is better than having two ways. I wouldn't be heartbroken if you just closed this issue though :-P

**Comment by photonstorm** [comment]
I like the consistency of always having to use curly braces when importing, but despise the redundancy when it's just a single item being imported! However, if it means we can shave off hundreds of `default` words across the codebase, it may be worth it just for the small byte saving it would give.

**Comment by bhgsbatista** [comment]
Usually VScode inserts the import statements for me anyways. Another advantage named exports is that if you use "Go To Definition" a lot to navigate code, you'll get taken to the actual function / property instead of the export default clause, which saves a bit of time while navigating the code.

**Comment by photonstorm** [comment]
I've updated the whole codebase to use named exports. It took quite a while, this had better be worth it :)

**Comment by bhgsbatista** [comment]
If nothing else, you made me very happy 😄
