### ISSUE TITLE
Setting volume on audio sprite is ignored first time when playing (+ related issues)

### ISSUE THREAD

**Issue by SBCGames** [phaserjs/phaser#3814]
Hi, when setting volume on audio sprite, it is ignored first time when playing.

Test scenario (WebAudio):
 1. create any audio sprite: ```let as = this.sound.addAudioSprite("MyAudioSprite");```
 2. set volume:  ```as.volume = 0.2;```
 3. ```as.play("MyMarker");```
 => result: audio sprite MyMarker from MyAudioSprite is played with full volume 1.0
 4. set volume: ```as.volume = 0.2;```
 5. ```as.play("MyMarker");```
 => result: audio sprite MyMarker from MyAudioSprite is played with full volume 0.2

Reason for this is, that when audio sprite is created, it has default config created in BaseSound and this config is set as currentConfig. When volume is set first time (ad 2.), then volume in this base config is changed. Then, when playing (ad 3.), config for marker is set as currentConfig - so it overwrites volume. 
When in 4. is volume set again it overwrites volume in currentConfig, which is now refering marker's config. In 5. currentConfig (marker's config) is overwriten with marker's config (= no change) and audio sprite is played with volume 0.2.

My current workaround for this is to set volume directly into marker config like this:
 2. ```as.markers["MyMarker"].config.volume = 0.2;```
then, correct volume is played first time.

As a sidenote, currently none of these proerties/methods: volume, setVolume(), loop, setLoop(), seek, setSeek(), mute, setMute(), detune, setDetune() are exposed in Typescript defs for BaseSound. Reason is, it is defined and then exposed only for BaseSound subclasses WebAudioSound and HTML5AudioSound. volume, loop, mute, seek and detune are defined and exposed for NoAudioSound (but set...() methods are not). It is more than TS defs problem, because setVolume(), setLoop(), setSeek(), setMute() and setDetune() are not defined for NoAudioSound.
 As a result: most methods are using parent BaseSound for arguments / return type:
 1. in TS you do not get properties and methods described above (cosmetic problem: you do not have to make complicated cast to WebAudioSound / HTML5Sound / NoAudioSound in code, you can use brackets like: ```sound["volume"] = 0.2```),
 2. if you use methods on NoAudioSound, then you get runtime error (like "setVolume is not function")

Last things I encountered:
 - I noted when writting this report: currently "audio" property is not in JSDoc in Config.js, so it does not get into TS defs and when used in GameConfig, it is marked as error,
 - definition of AudioSpriteSound in BaseSoundManager is strange... it results into: ```type AudioSpriteSound = ()=>void;```. Changing it to this in defs solved my problem (not sure, how to correctly write it into JSDoc): ```type AudioSpriteSound = BaseSound & {spritemap : object};```

**Comment by SBCGames** [comment]
This is minimal working example - any audioSprite will work (mine has sound named "win")

```javascript
        public preload(): void {
            // sfx
            this.load.audioSprite("Sfx", AUDIO_SPRITE_JSON, AUDIO_SPRITE_JSON.resources);
        }

        public create(): void {

            // audio sprite
            let as = this.sound.addAudioSprite("Sfx");

            // rect to click / fire sound
            let graphics = this.add.graphics();
            graphics.fillStyle(0xffff00, 1);
            graphics.fillRect(100, 100, 100, 100);
            graphics.setInteractive(new Phaser.Geom.Rectangle(100, 100, 100, 100), Phaser.Geom.Rectangle.Contains);

            graphics.on("pointerdown", function () {
                // want to play with volume 0.2. First time ignored, second time OK - explanation in issue description
                as["volume"] = 0.2;
                as.play("win");
            }, this);
        }
```

**Comment by pavle-goloskokovic** [comment]
@SBCGames try this:
```javascript
as.play('win', { volume: 0.2 });
```

**Comment by SBCGames** [comment]
@pavle-goloskokovic if calling as you suggested, then volume is correct for first time already.

**Comment by pavle-goloskokovic** [comment]
I agree. Then the best solution is:

```javascript
as.play('win');
as.volume = 0.2;
```
