### ISSUE TITLE
Use strict mode?

### ISSUE THREAD

**Issue by gamedevsam** [phaserjs/phaser#4]
Setting `strict` to true in tsconfig.json enables the enforcement of type safety in the project, it's designed so that the compiler helps avoid null access errors at runtime. At the moment, I don't think this is possible, I got too many errors when I attempted, ex:

```
./src/index.ts → ./dist/Phaser4.esm.js, ./dist/Phaser4.js, ./dist/Phaser4.min.js...
[!] (plugin rpt2) Error: C:/Users/Samuel/Dev/HTML/Phaser/phaser/src/scenes/Scene.ts(9,5): semantic error TS2564: Property 'key' has no initializer and is not definitely assigned in the constructor.
```

To be fair, enabling strict mode reduces some flexibility in how you structure the code, but I think it's worth it in the long run.

**Comment by photonstorm** [comment]
Closing this as it's now enabled via your PR.
