### ISSUE TITLE
iPad tilemap small camera zoom stops rendering (WEBGL)

### ISSUE THREAD

**Issue by robbeman** [phaserjs/phaser#4743]
## Version
* Phaser Version: Phaser v3.19.0-FB (WebGL | Web Audio)
* Operating system: iOS 12.3.1 (iPad Pro 10.5-inch)
* Browser: Safari

## Description
When zooming out to very small zoom levels on a larger tilemap the rendering just stops. This only occurs when rendering in WEBGL, but I can not use canvas rendering in this project due to other rendering issues with canvas.

## Example Test Code
https://codesandbox.io/s/phaser-disappearing-tilemaps-fxrfm?fontsize=14

## Additional Information
The reason this to such a small level is to create a minimap overview of the entire level without having to replicate the entire level. In this example I have isolated the issue down to a single camera zooming out to a level where it disappears. You will see it happens somewhere between 0.03 and 0.02.

Another important note is that (even though extremely slow) this does not happen on an iOS simulator.

**Comment by robbeman** [comment]
Hi everybody, I'm currently revisiting this project and noticed that after updating phaser to v3.21.0 this is still an issue (as you can see in the updated codesandbox). I'm still trying to figure out if I can fix this or if I need to remake the minimap system in this project altogether.

**Comment by photonstorm** [comment]
Sorry we didn't get around to looking at this at the time, but the issue was iOS version specific and no longer manifests on modern Apple devices:

<img width="991" alt="image" src="https://github.com/phaserjs/phaser/assets/164476/54e2e40d-1aba-474d-a9b0-53a53e181c16">
