### ISSUE TITLE
Sound object sometimes throws error on calling stop

### ISSUE THREAD

**Issue by RollinSafary** [phaserjs/phaser#4954]
## Version

* Phaser Version: 3.20.1

* Operating system: Windows 10

* Browser: Google Chrome

## Description

This often happens when tab is muted from browser.
Throws error `Uncaught (in promise) TypeError: Cannot read property 'pause' of null`
![image](https://user-images.githubusercontent.com/30594036/72243050-45f9f680-3604-11ea-8139-907f5799fa20.png)

## Example Test Code

```
this.sfxs = []
for(const key of sfxKeys){
const sfx = this.sound.add(key)
}
```
```
function playSfx(key){
const sfx = this.sfxs.find((sfx) => sfx.key === key);
sfx.play()
}
```
```
function stopAll(){
for(const sfx of this.sfxs){
sfx.stop();
}
```
Possible that this error throws on not played sfx.
## Additional Information

Sound manager type is `Phaser.Sound.HTML5AudioSoundManager`.

**Comment by photonstorm** [comment]
Closing this issue due to age and lack of ability to replicate.
