### ISSUE TITLE
Delete dist and add it to .gitignore

### ISSUE THREAD

**Issue by gamedevsam** [phaserjs/phaser#5]
The `dist` folder contains the build artifacts and is currently checked into the repro. I noticed while working on the engine I was generating a lot of changes that slowed down git during commit / staging process.

I recommend deleting the dist folder and adding it to `.gitignore`. I already did that with the files:

`dev/index.js`
and 
`dev/index.js.map`

which are artifacts from the dev build in PR https://github.com/phaserjs/phaser/pull/3

**Comment by photonstorm** [comment]
The `dist` folder is the _only_ folder that is published to npm, so I don't want it missing from the git repo either.
