### ISSUE TITLE
GameObject.Polygon with negative numbers in path renders in wrong place?

### ISSUE THREAD

**Issue by michal-bures** [phaserjs/phaser#5441]
## Version
* Phaser Version: 3.50.0-beta.12
* Operating system: Ubuntu 18.04

## Description

When I create GameObject.Polygon and use some negative coordinates in the path data, the polygon bounds don't match where the polygon is actually rendered.

## Example Test Code

```
﻿var config = { width: 800, height: 600, scene: { create } };
var game = new Phaser.Game(config);

function create() {
    var circle = this.add.circle(100,100,20)
        .setStrokeStyle(1, 0xffffff)

    var redPoly = this.add.polygon(100,100, [[-20,-20], [20, -20], [20, 20], [-20,20]])
        .setStrokeStyle(1, 0xff0000)

    var greenPoly = this.add.polygon(100,100, [[0,0], [40, 0], [40, 40], [0,40]])
        .setStrokeStyle(1, 0x00ff00)


    console.log("Circle bounds:", circle.getBounds())
    console.log("Red Polygon bounds:", redPoly.getBounds())
    console.log("Green Polygon bounds:", greenPoly.getBounds())
}
```
When I paste this in https://labs.phaser.io/edit.html:
- **expected behavior**: there are a few possibilities that would make sense to me
  a) all three objects have same bounds and render over each other
  b) the red polygon is rendered at -20px relative to the other two objects and its bounds are therefore also different
  c) using negative coordinates when drawing polygon is not supported and I should get an exception
- **actual behavior**: all three objects have same bounds **but** the red polygon renders outside its bounds

**Comment by photonstorm** [comment]
The bounds are calculated based on the size of the AABB that fits around the points of the Polygon combined with the objects position. Both values are correct in and of themselves, but means, as you've pointed out, they're incorrect as a display bounds.

The correct bounds would be:

```js
const bounds = Phaser.Geom.Polygon.GetAABB(polygon.geom);
bounds.x += polygon.x;
bounds.y += polygon.y;
```

While I could make this change internally by overriding `getBounds` with something like the code above, it would only work for `getBounds` itself and would still fail for `getBottomCenter`, `getTopRight` and so on. Which is such a huge amount of code to add to the Polygon class 😥 I think, in this case specifically, I'll have to rely on updating the docs instead to make it clear.
