### ISSUE TITLE
[3.50] Spine, TypeScript & types

### ISSUE THREAD

**Issue by bbrockschmidt** [phaserjs/phaser#5463]
With the new Version of Phaser 3.50 my spine integration in TypeScript did not work any more.

Not sure if it is the best way, but it worked for me in Phaser 3.24.1

1. Add own typeRoots to the tsconfig.json
`    "typeRoots": [
      "@types",
      "./node_module/phaser/types"
    ]`
    
2. Build an index.d.ts in folder @types\phaser with the following content:
`/// <reference path="../../node_modules/phaser/types/SpineGameObject.d.ts" />`
`/// <reference path="../../node_modules/phaser/types/SpinePlugin.d.ts" />`

A request: Could you please write a short tutorial / best practice, how to use spine plugin in a typescript environment?

The errors in my build apparently originate to wrong types in Phaser 3.50. 
If i open node-modules/phaser/types in Visual Studio Code directly i get the following errors:

- SpineContainer.d.ts
![image](https://user-images.githubusercontent.com/64723972/102777211-70197400-4390-11eb-972d-3d3c2074c25c.png)

- SpineGameObject.d.ts
![image](https://user-images.githubusercontent.com/64723972/102777333-ace56b00-4390-11eb-97d3-e92297f2a49b.png)

It seems, that the d.ts files are outdated since the 3.50 Spine Plugin Release

**Comment by bbrockschmidt** [comment]
@photonstorm Is there any news, apparently the bug exists also in the latest version 3.52.0

**Comment by Pong420** [comment]
I am using Phaser version `3.52.0`. Just import the SpinePlugin and its types. 
```ts
import 'phaser/plugins/spine/dist/SpinePlugin';
import 'phaser/types/SpineContainer';

const game = new Game({
    plugins: {
      scene: [
        {
          key: SpinePlugin.name,
          plugin: SpinePlugin,
          mapping: 'spine'
        }
      ]
    }
  })
```
If not work, maybe you could take a look at this repo
https://github.com/ourcade/phaser3-typescript-spine

**Comment by bbrockschmidt** [comment]
First of all thanks for the hint. 
Unfortunately, this does not work for me. 
After compiling with tsc there are about 24 errors in my project that some interfaces are implemented incorrectly. 

`
Property 'moveTo' in type 'SpineContainer' is not assignable to the same property in base type 'Container'.
Property 'remove' in type 'SpineContainer' is not assignable to the same property in base type 'Container'.
Class 'SpineGameObject' incorrectly implements interface 'Transform'.
'addToCache', which lacks return-type annotation, implicitly has an 'any' return type.
`
The example in the repository is based on Phaser 3.22 this ran exactly the same for me without errors. 

I suspect that in the big update to 3.5 something has changed fundamentally and that the *.d.ts are not up to date.
If it is your repository, could you may try to update it? Did you do something special in the Typescript configuration?

**Comment by Pong420** [comment]
My `tsconfig.json` and i am using typescript version `4.2.2` and wepback5.
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
    "allowUnreachableCode": false,
    "sourceMap": true,
    "strictPropertyInitialization": false,
    "allowJs": false,
    "lib": ["dom", "es5", "esnext"],
    "jsx": "react",
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": ["node_modules", "public/lib/*.js", "dist", "webpack"]
}
```

**Comment by Pong420** [comment]
You could take a look at my [repo](https://github.com/Pong420/phaser3-spine-typescript). It is base on [yandeu/phaser-project-template](https://github.com/yandeu/phaser-project-template)

`src/scripts/game.ts`
```js 
import 'phaser/plugins/spine/dist/SpinePlugin'
// ...
```

import spine typing in a standalone ` typings/spine-plugins.d.ts` ( I am not well understanding typescript, but it works... )
```ts
import 'phaser/types/SpineContainer'

// you could also extends SpinePlugin if necessary
declare global {
  interface SpinePlugin {
    bootWebGL(): void;
    gameDestroy(): void;
    spineFileCallback(this: Phaser.Loader.LoaderPlugin): void;
  }
}
```

**Comment by aaron-human** [comment]
I poked through Pong420's the files a bit (thanks for the example code!) and I suspect the `"skipLibCheck": true,` in the `tsconfig.json` is what's preventing these errors from showing up. According to the [documentation](https://www.typescriptlang.org/tsconfig#skipLibCheck), it disables type checking for the `*.d.ts` files.

From what I remember of seeing this issue a little while ago the core problem is that `SpineContainer` extends `Container` imperfectly; as per [the docs](https://photonstorm.github.io/phaser3-docs/SpineContainer.html) `SpineContainer` should only contain `SpineGameObject` objects (where as a generic `Container` can contain any `GameObject`). TypeScript considers this a violation of the [Liskov Substitution Principal](https://en.wikipedia.org/wiki/Liskov_substitution_principle) since someone could grab a `Container` (that's actually a `SpineContainer`) and assume they can add `GameObject`s to it. I don't see a simple way to rework things to avoid this typing issue, though I'm not a TypeScript authority by any means.

**Comment by bbrockschmidt** [comment]
`"skipLibCheck": true` seems to do the magic for now. 
Thank you guys for the help. I'll see how my common-game-elements work in my new game in the next weeks.

**Comment by phamconganh** [comment]
I use phaser v3.55 with angular 12, it's still exist, although use "skipLibCheck": true
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom",
      "scripthost"
    ],
    "skipLibCheck": true
  },
  "typeRoots": [
		"@types",
		"node_modules/@types",
		"node_module/phaser/types"
  ],
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  },
}
```

**Comment by photonstorm** [comment]
Beyond `skipLibCheck` there's no easy fix for this. The actual JS code is valid, it's just TypeScript's interpretation of it. There's no point leaving this issue open I'm afraid. You could also now use the official Esoteric Phaser Spine runtimes, instead of our plugin - then you can use the TS defs they have created, which _might_ not have this issue.
