### ISSUE TITLE
Bug in the Collision between a Player Sprite and a Non-Static Group of Enemy Sprites in a Platform Game 

### ISSUE THREAD

**Issue by afslucass** [phaserjs/phaser#5544]
## Version

* Phaser Version: 3.24.1

* Operating system: Windows 10

## Description

The bug happens when I try put collision in a non static group of enemies to interact with the player in my platform game. It dont have the expected effect (initially, it looks that the collision will work but the players sprite ends up entering in the enemy)

![GIF 04-02-2021 09-42-14](https://user-images.githubusercontent.com/63973334/106894316-8c1d6e80-66cd-11eb-9547-f16eba639c45.gif)

## Code Example

`this.enemies = this.physics.add.group({
            key: "player",
            setXY: { x: 300, y: 20, stepX: 400 },
            repeat: 2,
        })
        this.enemies.children.iterate((child) => {
            child.setScale(0.1, 0.1)
            child.refreshBody()
            
            child.setTint(0xFF0000)
            child.anims.play("walking")
            child.body.setDragX(300)
            child.body.setAllowRotation(false)
            child.flipX = true
        })

        this.physics.add.collider(this.backgroundLayer, this.player, null, null, this)
        this.physics.add.collider(this.obstaclesLayer, this.player, null, null, this)
        
        this.physics.add.collider(this.backgroundLayer, this.enemies, null, null, this)
        this.physics.add.collider(this.obstaclesLayer, this.enemies, null, null, this)
        this.physics.add.collider(this.enemies, this.enemies, null, null, this)
        this.physics.add.collider(this.player, this.enemies, null, null, this)`

### My Solution:

![Capturar](https://user-images.githubusercontent.com/63973334/106890331-ee737080-66c7-11eb-8e61-519565f9be94.PNG)

- Duplicate the 'this.physics.add.collides' as show in the image

**Comment by photonstorm** [comment]
Your solution basically runs the separation function twice, which looks to be enough for your use-case. This isn't something we can change internally though.
