### ISSUE TITLE
Constant Window Resizing (No Scale + Auto Center) in Firefox

### ISSUE THREAD

**Issue by kainage** [phaserjs/phaser#5703]
## Version

* Phaser Version: 3.54

* Operating system: macOS, Ubuntu

* Browser: FIrefox 88.0.1

## Description

Constant window resizing in Firefox with scale manager set to **no scale** and **auto center**. This issue is made much worse when your game is resizing to the available window space. In this case the issue will happen no matter what size your screen is.

## Example Test Code

View this labs example in firefox with the window _almost_ the size of the canvas.

http://labs.phaser.io/100.html?src=src\scalemanager\no%20scale%20with%20auto%20center.js

## Additional Information

https://user-images.githubusercontent.com/80168/118528732-8a653d00-b6f7-11eb-8dac-66ceb76b4823.mov

**Comment by photonstorm** [comment]
Not sure if this issue resolved itself as a result of FF or Phaser updates, but it doesn't happen in FF 122 and Phaser 3.70.
