### ISSUE TITLE
Event orientationchange being fired with wrong orientation on iOS Chrome

### ISSUE THREAD

**Issue by meetpatel1989** [phaserjs/phaser#5762]
## Version
* Phaser Version: 3.55.2
* Operating system: iOS 14.6 iPhone 8 Plus
* Browser: Chrome

## Description

The orientation change event is being fired on the chrome browser but with the wrong orientation. [This exmaple](https://labs.phaser.io/view.html?src=src/scalemanager%5Corientation%20check.js) works fine in the safari but not on the chrome browser. 

<code>this.game.scale.on("orientationchange", ()=>{ alert("orientation changed"); });</code>

## Additional Information
* Open [this](https://labs.phaser.io/view.html?src=src/scalemanager%5Corientation%20check.js) in the ios chrome browser in Portrait mode. (Expected behavior)
* Rotate the device to the landscape but still it will show to landscape message. (Wrong behavior)
* Again rotate to portrait. This time it will not show any message while it should show the message for landscape rotation. (Wrong behavior)

My observation: The event is not being fired for the first time only after that event is fired but with the wrong orientation.

**Comment by meetpatel1989** [comment]
BUMP! Did anyone face this issue? Or has anyone checked?

**Comment by photonstorm** [comment]
The `ScaleManager.orientationChange` event listener will now directly refresh the Scale Manager internals. This fixes an issue where the orientation change event would fire after the window resize event, causing the Scale Manager to incorrectly report the new orientation on Chrome on iOS. See #6484 for the commit link.
