### ISSUE TITLE
Warn for file processing failures

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#5862]
I reproduced #5851. If you load an aseprite animation from an invalid image (e.g. wrong type or zero-length file), the files are complete, the animations are missing, but there are no other errors.

Generally I think the problem is that most file process failures are silent, which is a little confusing for users.

https://codepen.io/samme/pen/yLoLJVE?editors=0010

![load aseprite with invalid image](https://user-images.githubusercontent.com/435681/136669042-890d51cf-1902-476c-81fd-5938aec7464a.png)

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
