### ISSUE TITLE
#Tilemap Tiled exported JSON not loading

### ISSUE THREAD

**Issue by stanleyseow** [phaserjs/phaser#5865]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows, Mac
* Browser: Chrome 94.xx
## Description
Tiled exported JSON not loading

I reported this in Tiled forum,  after saving a file, Phaser3 cannot read the map.
https://stanleyseow.github.io/js/phaser/scene-victorian-map/

![Screenshot 2021-10-11 at 11 20 23 AM](https://user-images.githubusercontent.com/539857/136973420-cac52cbd-c1bf-494e-b73d-61df2d5e3b8b.png)

_"In the “not working” version, there are **two custom properties added**, and they’re saved in the new JSON format that became the default in Tiled 1.2. Mostly likely your version of Phaser does not support this format.

If the latest version of Phaser does support this format, I’d recommend upgrading. If not, I’d recommend making sure they have an issue open about this.

To avoid the issue, you can save to the old JSON format. To do this, go into Preferences > Plugins and disable the “json” plugin while enabling the “json1” plugin. Both plugins support either format when loading maps, but the “json1” plugin will use the JSON format of Tiled 1.1 when saving / exporting."_

I tried exporting JSON on both 1.1 and 1.2 Tiled format, still the same results. 

I m using Tiled 1.7.2

 
[Link](https://discourse.mapeditor.org/t/cant-load-map-on-phaser3-after-adding-tile-properties/5302) to the question opened in  discourse.mapeditor.org

## Additional Information

**working** [victorian.json](https://github.com/stanleyseow/js/blob/gh-pages/phaser/scene-victorian-map/assets/victorian.json)
**not working** [victorian-preview.json](https://github.com/stanleyseow/js/blob/gh-pages/phaser/scene-victorian-map/assets/victorian-preview.json)

**Comment by photonstorm** [comment]
I need the TMX file and associated tile sets, please.
