### ISSUE TITLE
Pointer-out bug

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#5867]
## Version

* Phaser Version: 3.60.0, or previous

* Operating system: win10

* Browser: chrome, firefox

## Description

See [this test](https://codepen.io/rexrainbow/pen/VwzLEyX)
- `scene.input.topOnly` sets to `false`, 
- When **touch pointer moves out of canvas**, 2 game objects are [picked](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L1808), 
- In `sortGameObjects` method, [`pointer.camera`](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L2645) is `undefined` -> `Uncaught TypeError: Cannot read properties of undefined (reading 'renderList')`

This bug won't occur when [only 1 game object is pointer-out](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L2640-L2643)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
