### ISSUE TITLE
Video with audio replays automatically after switching tabs.

### ISSUE THREAD

**Issue by marcusx2** [phaserjs/phaser#5873]
http://labs.phaser.io/edit.html?src=src/game%20objects/video/play%20video.js
change the code so it's just vid.play() (and commented out the setPaused line)

Then, use this video https://www.appsloveworld.com/wp-content/uploads/2018/10/Sample-Mp4-Videos.mp4.

Wait for the video to end, switch tabs and come back. The video will restart.

**Comment by photonstorm** [comment]
Can you test this please, because I'm struggling to reproduce this:

https://labs.phaser.io/view.html?src=src%5Cbugs%5C5873%20video.js&v=dev

This is using 3.60 Beta 4 and a video that lasts 10 seconds and has audio. The code has been changed as you prompted.

**Comment by photonstorm** [comment]
The Video Game Object has been fully recoded in v3.60 and now works very differently from before, and this bug is no longer present.
