### ISSUE TITLE
Scene config should be optional.

### ISSUE THREAD

**Issue by ghost** [phaserjs/phaser#5874]
![image](https://user-images.githubusercontent.com/53160891/137584336-e3b07d2f-805e-4c44-9467-067e913edd60.png)

Following the Phaser examples you don't have to do that. I think all configs are optional. But the argument itself is required. This is one of the most common mistakes made with TypeScript. You have to either mark the argument as optional or set a default (empty) object. 

**Solution A**

```ts
class Scene {
  constructor(config?: string | Phaser.Types.Scenes.SettingsConfig)
}
```

I think this is what you want / how the code works. You have to handle nullish values (undefined).

**Solution B**

```ts
class Scene {
  constructor(config: string | Phaser.Types.Scenes.SettingsConfig = {}) // or string in this case
}
```

`phaser: '3.55.2'`

Trivia: You don't need the `constructor` if you don't use it. Empty constructors which only contains super or nothing can be omitted.

Btw. a question: What do you think of rewrite Phaser in TypeScript or modern JavaScript?

**Comment by orjandh** [comment]
I think the constructor requires an argument on purpose. This can either be a scene config object or a string which is the scene key. I don't think the scene key is optional. Correct me if I'm wrong :) Also maybe it's a good idea to link to one of the phaser examples you are referring to.

Also Phaser 4 is being written in TypeScript!

**Comment by ghost** [comment]
This case is always optional in TS definition file when you compile the following code:

```ts
export function example(options: Options = {}): void {/*...*/}
export function example(options?: Options): void {options = options ?? {}}
```

Both variants alsways compiled to (d.ts):

```ts
export declare function example(options?: Options): void;
```

It's not important for API if the value has a default value set directly in argument line or inside the function.

But currently the scene (and maybe other?) has a required options argument.

As workaround, I have to pass an empty object `{}`.

You can find this in (almost) every example on the website. For example the [Grid Align](https://phaser.io/examples/v3/view/actions/grid-align).

The related definition file (d.ts) shows that config is required. But accepts an empty object. It's optional at runtime. It's just a type issue. And if not or in general: In such cases, the argument should alsways options. Because the argument is an object which has all properties set as optional. It's not good to force the developer to provide an empty object to suppress the error.

Ok great to see that Phaser uses TypeScript. This makes definition files easier to create. I guess the definition file at Phaser 3 is crafted by hand or from doc comments. It's error prone.
But TypeScript or not. The issue above can also happen in TypeScript. You have to set / know optional properties. And in a case of options object, you should consider to set `options: Options = {}` or `options?: Options` and handle it intern (inside function).

**Comment by ghost** [comment]
Ok it seems that [Phaser 4 Scene.ts](https://github.com/phaserjs/phaser/blob/main/src/scenes/Scene.ts) already handles it. But it's the Phaser 3 repo and Phaser 4 is not yet ready. Shall we wait? I mean this issue can be dealt within 5 minutes. ^^ It's trivial ... I hope. Not yet reviewed the complete code. Not sure how the d.ts files are generated... If manually, we have just to add `?`. Or / and add `[propName]` to the doc comment. To indicate optional. See [docs](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values).

```ts
/**
 * @param {(string|Phaser.Types.Scenes.SettingsConfig)} [config] - Scene specific configuration settings.
 */
```

Same for `Systems.js` and `Settings.js`. See [Settings.create](https://github.com/photonstorm/phaser/blob/master/src/scene/Settings.js#L34). It handles `undefined`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
