### ISSUE TITLE
Option to make World space not have inverted y-axis with origin at bottom left

### ISSUE THREAD

**Issue by kevo1ution** [phaserjs/phaser#5875]
Currently, world space by default has origin set to top-left with an inverted y-axis. This means that for objects to move up in world space, they need to move in the negative y-direction. Although this mirrors how the canvas is drawn, this feels unintuitive when programming how objects move in the game world and makes server code more confusing when representing player/game object velocities and coordinates.

It would be nice to have an option for world space to have a non-inverted y-axis with the origin at the bottom left.

**Comment by photonstorm** [comment]
This will never happen for Phaser 3, so please add it to the [Phaser 4 repo](https://github.com/phaserjs/phaser)

I can't move issues between repos, otherwise, I would do so to save you posting it again.
