### ISSUE TITLE
Touch zone misplacing in mobile fullscreen

### ISSUE THREAD

**Issue by necrokot** [phaserjs/phaser#5878]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 10 x64 2004

* Browser:

## Description

Problem actual only for mobile and fullscreen. Bug was reproduced on Samsung Galaxy M31 and Redmi Note 8t.
Steps to reproduce:
1. Create graphics and hit area with same sizes.
2. Put graphics into container.
3. Enable interactive for graphics with corresponding hit area.

Expected: click zone is equal to graphics.
Result: click zone is displaced a bit.

Bug also reproduces if set interactive for container.
## Example Test Code

https://codepen.io/necrokot/pen/QWMEGrx

If bug don't reproduces on codepen you can clone [repo](https://github.com/necrokot/Phaser3MobileFullscreenBugExample) and run 
`npm run serve`
to launch local web server.

**Comment by omniowl** [comment]
I tried on my own phone using the codepen and I cannot reproduce this error as described. The click zone seems to be exactly as the graphic indicates.

**Comment by photonstorm** [comment]
Tested this on a Samsung Galaxy M32 and it works as I would expect. However, you cannot start fullscreen on 'pointerdown', it has to be on 'pointerup'. Here is the fork I was using to test with (with an added hit counter):

https://codepen.io/photonstorm/pen/KKeQoVM?editors=0010

https://user-images.githubusercontent.com/164476/203306337-1d45cb1b-d0d2-49af-918a-43cdd5d273a9.mp4

**Comment by rogermark321** [comment]
Hey,
You can watch any tutorial on YouTube it may help you to solve your problem. You can also try [Alight motion app on your iPhone](https://alightmotionguru.com/alight-motion-pro-ios/).
