### ISSUE TITLE
Remove optional [ ] notation in typedefs for GroupCreateConfig key property as it is not optional

### ISSUE THREAD

**Issue by austinlyon** [phaserjs/phaser#5880]
https://github.com/photonstorm/phaser/blob/d67c93646cbfe8ba5997954f8af29a8f3f9e8e91/src/gameobjects/group/typedefs/GroupCreateConfig.js#L14

If the key property is missing in the first (or only) config object supplied to createMultiple, it fails silently. It's even stated in the same document that the key is required, but shows in the property table as optional. There may be a technical reason for this to remain as optional that I'm not aware of, and in that case I apologize!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
