### ISSUE TITLE
Game object on a camera-ignored layer is still touchable

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#5883]
## Version

* Phaser Version: v3.60.0

* Operating system: win10

* Browser: Chrome, firefox

## Description

See [this test](https://codepen.io/rexrainbow/pen/oNeZgKp), 

1. Create a layer game object
2. This layer game object is ignored by main camera 
3. Create a circle shape game object, with pointer-down event.
4. Add this circle shape to layer. Because that this layer is ignored by main camera, this circle shape game object child is not visible.

There has another red dot inside the circle shape for clicking. Ideally invisible game object won't be touchable. But the pointer-down event is fired, you can see the log text on a text game object.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
