### ISSUE TITLE
Video element doesn't work with getDisplayMedia() or WebRTC streams

### ISSUE THREAD

**Issue by mshopf** [phaserjs/phaser#5885]
* Phaser Version: 3.55.2
* Operating system: Linux Ubuntu 20.04.3
* Patreon name: Matthias Hopf

## Description

The phaser video element works fine with local web cams, but when using screen shares the element does not fire the 'created' event, and has no width. I'm not sure whether the html video element (accessed by video.video) is completely initialized, as video.video.videoHeight is always 1080p (even when sharing a 1440p screen). video.height is 0 even after some time.

Example does not work on the usual suspects as jsbin due to security constraints.
Find it here: https://me.efi.th-nuernberg.de/test_phaser.html vs. https://me.efi.th-nuernberg.de/test_phaser_broken.html

The only difference is the getUserMedia() vs getDisplayMedia() calls in the minimal example below. The same code is working fine in both variants in html video element context.

## Example Test Code
```
<html><head>
    <title>Phaser and video streaming example</title>
    <script src="//cdn.jsdelivr.net/npm/phaser@3.55.2/dist/phaser.min.js"></script>
</head><body>
    <script>
        // Parameters for camera
        const mediaConstraints = {
            audio: {},
            video: {            // min, ideal, max, exact; just a value/string is a suggestion
                 width:      { ideal: 1280, max: 4096 },
                 height:     { ideal: 720,  max: 2160 },
                 frameRate:  { max: 30 },
                 facingMode: "user" },
        };
        // Paramters for display capture
        const displayConstraints = {
            video: {
                cursor:         'always',           // always | motion | never,
                displaySurface: 'monitor',          // application | browser | monitor | window
            }
        };

        var video;                                  // global by intention for debugging
        class MainScene extends Phaser.Scene
        {
            constructor() {
                super('loading-scene');
            }

            create() {
                this.openVideo();
            }

            async openVideo () {
                try {
                    var stream = await navigator.mediaDevices.getDisplayMedia (displayConstraints);
                    //var stream = await navigator.mediaDevices.getUserMedia (mediaConstraints);
                } catch (error) {
                    console.log ('could not get user media: '+error);
                }
                // create video object and open stream
                video = this.add.video ();
                video.loadMediaStream (stream);
                video.on ('created', function (evt) {
                    console.log ('created');
                    // resize, position, and play video
                    var width  = video.width / video.height * 200;
                    var height = 200;
                    if (width > 200) {
                        width = 200;
                        height = video.height / video.width * 200;
                    }
                    video.setDisplaySize (width, height);
                    video.setPosition    (100, 100);
                    video.play           ();
                });
            }
        }

        var config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            scene: [ MainScene ],
        };
        var game = new Phaser.Game(config);

        </script>
</body></html>
```

## Additional Information

video.loadURL() and video.loadMediaStream() (in https://github.com/photonstorm/phaser/blob/v3.55.2/src/gameobjects/video/Video.js#L805 ) seem to have a parameter loadEvent, that is not used in the remainder of the functions. I assume this is either a leftover from a phaser 2 function, or it hasn't been implemented yet. I wanted to test whether a different event as 'canplay' would help, but as video.video.width / height isn't filled yet, this is probably irrelevant.

getDisplayMedia() is actually only a side problem - main issue for me is that WebRTC streams don't work either. However, examples are much more involved when using WebRTC...

**Comment by mshopf** [comment]
Wow. It does work in the provided example now. Guess what, you have to switch to a different tab, and then back to the phaser tab.
Maybe this is a reinitialization issue? Or a browser bug...
Haven't tried WebRTC yet. I'll have to double check.

**Comment by mshopf** [comment]
Ok, tried WebRTC again, does work now. Sorry for the fuzz. Can't figure out anymore why it didn't work before.

The only issue remaining is that getDisplayMedia() streams only show up after a tab switch. Don't know whether one can do anything about that....

It is also a very minor issue. I'm leaving it open for reference, feel free to close if you consider this a browser bug.

**Comment by michaeltnguyen** [comment]
are you in chrome?  This is likely because chrome throttles `requestAnimationFrame` when you're not the active tab (and thus any sort of webRTC you're trying to do from within phaser).  Not a phaser bug.

**Comment by mshopf** [comment]
Happens in Vivaldi and Chrome (both Chromium). But the issue is, the Screenshare video isn't visible after calling getDisplayMedia() (in contrast to getUserMedia()). You have to switch *away* from the tab and then *back* to the tab, and then the video is visible. I doubt this is due to throttling, rather expose events or similar.
As the code works with DOM elements (without phaser), I can only assume that this is not *only* a browser bug.

**Comment by mshopf** [comment]
BTW - if you want to add my code as an example for how to display Webcam video in phaser 3, feel free to do so. It's public domain.
I could even provide code for WebRTC conferencing using phaser game objects, but that one requires server support (Websocket message broadcasting), as all WebRTC code does.

**Comment by mshopf** [comment]
I found out, that the culprit was that video.width and video.height are not necessarily filled out correctly even after a "created" event. You have to wait for "timeupdate" events, and then for 'reasonable' width and height information.
I guess in the long term phaser could use a more robust video event handling here...
Closing now.
