### ISSUE TITLE
Parsing of Rotation/Flipping of Tiled map does not properly handle FlipY

### ISSUE THREAD

**Issue by Olliebrown** [phaserjs/phaser#5893]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows

## Description
When loading a tilemap that was created in Tiled, you can flip and rotate tiles as you place them.  Phaser currently accounts for this visually (so that the sprite for the tile is properly flipped and rotated) but it does not account for this with any custom colliders (as was already mentioned in #4360).

The fix mentioned in the above issue is still not implemented in the latest beta version or the main dev branch.

More importantly, the fix above does not work in all cases.  If a tile only has 'flipY' on it, for some reason the tile that is created does not get its flipY properly set.  I haven't yet found the source of this but I suspect it is a bug inside the Matter world code that attempts to create tiles for the tilemap.

## Example Test Code
(coming soon! I will update with a minimal example)
In Phaser Examples there is a flipped visual test map that is very handy for this!  Presently it does not have any custom colliders on it so I will add those, turn on Matter debugging, and show how the colliders do not match the outline.

## Additional Information
(coming soon! I will update with screenshots soon)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
