### ISSUE TITLE
GetLineToLine Intersection incomplete

### ISSUE THREAD

**Issue by inf0matics** [phaserjs/phaser#5894]
## Version
* Phaser Version: v3.55.2
* Operating system: OS

## Description
* File: phaser/src/geom/intersects/GetLineToLine.js
* Function: var GetLineToLine = function (line1, line2, out) {

**Problem:** If line1 is horizontal (line1.x1 == line1.x2) the function returns false. It does not care if the line2 is intersecting or not.

In the comments I found (Line45 - 47)
```
//  Make sure there is not a division by zero - this also indicates that the lines are parallel.
//  If numA and numB were both equal to zero the lines would be on top of each other (coincidental).
//  This check is not done because it is not necessary for this implementation (the parallel check accounts for this).
```

imho this is a wrong assumption. The lines can still intersect if dx1 === 0 --> this just means line1 is horizontal.

Workaround to this to run GetLineToLine(line2, line1)

## Example Test Code
[Code Pen for Testing ](https://codepen.io/informatics/pen/YzxYVJw)

```
const l1 = new Phaser.Geom.Line(200, 150, 200, 50);
const l2 = new Phaser.Geom.Line(50, 100, 250, 100);

let resultLine1WithLine2 = Phaser.Geom.Intersects.GetLineToLine(l1, l2);
console.log(`Line1 with Line2: ${resultLine1WithLine2}`);
// Console: "Line1 with Line2: false"

let resultLine2WithLine1 = Phaser.Geom.Intersects.GetLineToLine(l2, l1);
console.log(`Line2 with Line1: ${resultLine2WithLine1}`);
// Console: "Line2 with Line1: [object Object]"
```

## Current Workaround
```
let result = Phaser.Geom.Intersects.GetLineToLine(line1, line2);
if (result === false) {
    result = Phaser.Geom.Intersects.GetLineToLine(line2, line1);
}
```

**Comment by photonstorm** [comment]
Yeah, I had already found this when realizing the PR that modified this function had broken line to ray intersection too. 

Please could you try doing a build from the main branch, where it should now work correctly, and let me know what you get?

**Comment by inf0matics** [comment]
I am just building prototypes in Codepen. I was using:
https://cdn.jsdelivr.net/gh/photonstorm/phaser@3.60.0-beta.3/dist/phaser.min.js

✅  Work's like a charm --> User is happy 😅

I removed the workaround and it works. Projekt:
[Phaser3 Riddle Untangled](https://codepen.io/informatics/pen/yLogarO)
