### ISSUE TITLE
ios 12 safari graphic glitch phaser 3.60 beta 3 

### ISSUE THREAD

**Issue by EmilSV** [phaserjs/phaser#5924]
* Phaser Version: 3.60 beta 3 
* Operating system: ios 12
* Browser: safari

## Description
Moving image from multiable texture atlas leads to graphic glitches.
I did some tests and this bug is only fund in beta 3 not beta 2 and if i reverted 
"The Multi Tint fragment shader now uses the new getSampler function approach from Phaser 4" and 
"Removed GenerateSrc, removed need for forloop declaration"
it also worked properly again

https://user-images.githubusercontent.com/3351370/141824729-633c3673-4dd2-4afe-a39b-29493cb7e0d9.mp4

## Example Test Code
```
class Demo extends Phaser.Scene
{
    constructor()
    {
        super();
    }

    preload()
    {   
        this.load.multiatlas('megaset', 'assets/loader-tests/texture-packer-multi-atlas.json', 'assets/loader-tests/');
    }

    create()
    {
        var atlasTexture = this.textures.get('megaset');

        var frames = atlasTexture.getFrameNames();

        for (var i = 0; i < frames.length; i++)
        {
            var x = Phaser.Math.Between(0, 1024);
            var y = Phaser.Math.Between(0, 768);

            let image = this.add.image(x, y, 'megaset', frames[i]);
            image.setDepth(i);
            this.add.tween({
                targets: image,
                x: x + Phaser.Math.Between(-100, 100),
                y: y + Phaser.Math.Between(-100, 100),
                yoyo: true,
                repeat: -1
            });
        }
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    backgroundColor: '#2d2d6d',
    scene: Demo
};

const game = new Phaser.Game(config);
```

**Comment by photonstorm** [comment]
Tested on the latest version of iOS and it doesn't glitch at all, but it is _super_ slow. Like 5 fps. But I also get the same response from Safari on my M1 iMac, yet Chrome on the same machine is 60 fps perfect. So it has to be something in the shader that Apple software, and Apple alone, doesn't like. Just wonderful.

**Comment by photonstorm** [comment]
In short, it can't handle 16 texture units (which is what WebGL says it can support). If I limit it to 8 then both iOS and the iMac run ok. It's still not perfect, I can visually see it drop a few frames, but it runs. The 3.55 shader however works fine on iOS, which is very frustrating. I'll have a look further to see if there are any known causes for this. It's a very simple shader function, you'd think Apple could handle it, but I guess not.

**Comment by photonstorm** [comment]
Ok, this is now fixed in the master branch. Works fine in Safari on iMac and iPhone, even using all 16 texture units. Drops the for loop from before and goes for a hybrid approach.
