### ISSUE TITLE
Timeline inconsistent behavior

### ISSUE THREAD

**Issue by mariogarranz** [phaserjs/phaser#5925]
## Version

* Phaser Version:

Phaser 3.55.2 

* Operating system:

MacOs

* Browser:

Chrome 95.0.4638.69

## Description

The timeline randomly plays its tweens wrongly. Seemingly some of the tweens get merged, but this happens randomly. 

I created a test example where 2 sprites (squares) are displayed in the view. Then each one of them is assigned a timeline with 3 steps:

1 - Move the square closer to the edge of the screen
2 - Move the square closer to the center of the screen, up to a position where both squares would collide
3 - Move the square back simulating a bounce effect after colliding

Then I added an interval so this animation is played several times to be able to spot the issue. You will notice that the animation plays OK most of the time, but other times, somewhere around 10-20%, the squares seem to bounce back way before they reach the collision point.

The fact that both timelines fail at the same time makes me believe this could be something caused by performance, so that if calculations take longer, the tween data from step 2 collides with step 3 somehow.

## Example Test Code

https://codepen.io/mariogarranz/pen/MWvxpOw

**Comment by mariogarranz** [comment]
I just modified the Codepen example to add a second test that does the same animation but using chained tweens through their "complete" signals. Those are played on red squares below the white ones.

You can see the issue more clearly in this gif with slower motion:

![isgn4-4dotb](https://user-images.githubusercontent.com/2812529/142656504-18decdba-79b9-4f20-9a4f-31fbd65deebc.gif)

Both animations have exactly the same parameters, but the white one uses Timeline and the red one chained Tweens. As you can see, the Timeline sometimes fails to play properly and the squares do not get to collide, while the chained Tweens as far as I have seen perform as expected every time.

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
