### ISSUE TITLE
Keys become sticky when the "menu"/"command" key is pressed

### ISSUE THREAD

**Issue by moufmouf** [phaserjs/phaser#5929]
## Version
* Phaser Version: 3.55.2
* Operating system: tested on MacOS and Linux
* Browser: Reproduced in both Chrome and Firefox

## Description

In special conditions, keys can become sticky.

In order to reproduce the bug:

- Press a key (and keep the key pressed)
- Now, press the "command" key (on MacOS) or the "Menu" key (on Linux) and keep this key pressed.
- Release the first key

You will see that Phaser does not detect the key was released at all.

You can reproduce this in the Phaser examples:

https://phaser.io/examples/v3/view/input/keyboard/add-key

- Open the console.
- Press the A key (and keep the key pressed)
- You should see "A" piling up in the console.log
- Now, press the "command" key (on MacOS) or the "Menu" key (on Linux) and keep this key pressed.
- Release the "A" key

You will see "A"s are keeping piling up.
 
That's it! I'm not sure why this is happening but it is reproducible on different OSes and different browsers.

If I can be of any help to fix this issue, let me know how I can help.

**Comment by photonstorm** [comment]
Yes, annoyingly, this is just how macOS (and Linux) works - when the Meta key is held down, you no longer get any `keyup` events at all until the Meta key is released. This is an OS-level setting and cannot be overridden.

It would be incorrect to assume that if Meta is released, we should reset all other keys, too, as that may simply not be the case.

I guess we could detect if the keydown was as part of a Meta key combo and log that in the Key object, but I'm not sure of the benefit as the OS is actively blocking the information we need (the keyup event), so it'd just be pure guess-work as to if the key is actually still down or not. Very frustrating, to be honest. Phaser is not alone here:

https://stackoverflow.com/questions/11818637/why-does-javascript-drop-keyup-events-when-the-metakey-is-pressed-on-mac-browser

https://github.com/electron/electron/issues/5188
