### ISSUE TITLE
DOM game object is disappeared in full screen mode

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#5940]
## Version

* Phaser Version: 3.55.2

* Operating system: win11

* Browser: chrome, firefox

## Description

See this [test code](https://codepen.io/rexrainbow/pen/ZEXOENR)
- Click text *Full screen* to toggle full screen mode
- In full screen mode, dom game object is disappeared

**Comment by photonstorm** [comment]
Yes, you can only full-screen _one_ DOM element, so ideally you should full screen the parent container I guess.

**Comment by rexrainbow** [comment]
Got it. Test code fixed.
