### ISSUE TITLE
`processOverOutEvents` throws error

### ISSUE THREAD

**Issue by jcyuan** [phaserjs/phaser#5943]
v3.60.0-beta.4

the event was set for GAMEOBJECT_DRAG, and when you move your mouse out side of the canvas it will throw an error.

call stack:
![image](https://user-images.githubusercontent.com/850854/145557941-a241268e-fa3c-42b0-ae18-33e9650e26c8.png)

caused by:

![image](https://user-images.githubusercontent.com/850854/145557984-9e4eb517-2fa3-4372-82b2-f5d3be7998dc.png)

**Comment by jcyuan** [comment]
the canvas has a fixed size and set to center_both of the browser screen. so my mouse can be moved outside of the canvas easily.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release.
