### ISSUE TITLE
Test Report on IE9

### ISSUE THREAD

**Issue by jcyuan** [phaserjs/phaser#5947]
challenge!!

first let me report the result: failed to run on IE9.
here is my test report: one key feature missing and some small mistakes:

1, ![image](https://user-images.githubusercontent.com/850854/146742434-e40f3388-c740-4233-8632-3d5e195e3969.png)
![image](https://user-images.githubusercontent.com/850854/146742516-09a958c7-7bcc-4f45-b593-f5e607816717.png)
not sure why it reports this error, but actually it seems nothing affected.

2, these two missing in polyfill.js
![(9{4T~ZOET2)2$WHZTVJ7VT](https://user-images.githubusercontent.com/850854/146734609-41eeacce-ab14-4325-9bd6-17452ea847a9.png)
![75%U{VFLOM3`Q)RJ8HG9445](https://user-images.githubusercontent.com/850854/146734634-32c323be-7797-488b-804b-96e0677259c3.png)

~~3, key feature missing: FileReader.~~
~~this will be used to convert blob as an URL, but blob and FileReader both are not avaialbe in IE9, so the loading process stops there.~~
~~but i'm sure the engine was booted up successfully, but just stuck on the processing of file loading.~~
**(detect if blob is supported, provide 'imageLoadType': 'HTMLImageElement' in the loader config solved this.**

4, didnot test on other features, because the Scene can't be launched.

Env Info:
render type: CANVAS / Html Audio
browser: IE11 (in F12 on simulator tab select IE9)

btw: IE10 works with no any problems. (Canvas)

**Comment by jcyuan** [comment]
about item1, i found the reason,

in IE9 IE10, you can't directly use function alias...

var body = document.body;
var bodyAdd = body.addEventListener;
bodyAdd(...);   // SCRIPTS65535

but directly call document.body.addEventListener(..) will work fine...

https://stackoverflow.com/questions/1007340/javascript-function-aliasing-doesnt-seem-to-work

**Comment by jcyuan** [comment]
on IE11:

Phaser3.6.0
![image](https://user-images.githubusercontent.com/850854/146776834-f0305c3f-37b9-4838-8256-626b8a508bdb.png)

cannot launch.. the error is caused by link Multi.shader
and the reason is still the problem of indexer in webgl1....
i tried to use the naive if else if else way and it works.....

**Comment by jcyuan** [comment]
btw, there is a lot of `console.log` in HTML5AudioFile / HTML5AudioSoundManager

**Comment by jcyuan** [comment]
fix item 1,2 and IE 9 10 passed!
i'll try to submit a PR soon

on IE 11 because it's a little big change on multi-pipeline so i think i will probably miss something if i try to fix it... and hope you can have a look on this issue, thank you very much sir.

**Comment by photonstorm** [comment]
Sorry, should have closed this after merging your fixes in. As we've reverted back to the if/else block in 3.60 that should resolve the IE11 issue as well.
