### ISSUE TITLE
Possible bug in latest GetValue method

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#5952]
## Version

* Phaser Version: 3.60.0

* Operating system: win11

* Browser: chrome, firefox

## Description

See this [test code](https://codepen.io/rexrainbow/pen/poWrGyj).
It try to get value at path 'a.b.c', from sourceA: `{a: c:{100} }` and sourceB `{b: {} }`. The result is `100`, in sourceA's 'a.c'. Which is incorrect.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
