### ISSUE TITLE
hitAreaCallback type definition

### ISSUE THREAD

**Issue by SylvainBreton** [phaserjs/phaser#5954]
## Version

* Phaser Version: 3.55 but same code on 3.60

* Operating system: Ubuntu

## Description

In phaser/types/phaser.d.ts, Phaser.Types.Input.HitAreaCallback is defined as follow :

type HitAreaCallback = (hitArea: any, x: number, y: number, gameObject: Phaser.GameObjects.GameObject)=>void;

I think that there is an issue here as the definition is different from the one given in As this definition is different from the one given in phaser/src/input/typedefs/HitAreaCallback.js

## Additional Information

Change phaser/types/phaser.d.ts l62860 to 
type HitAreaCallback = (hitArea: any, x: number, y: number, gameObject: Phaser.GameObjects.GameObject)=>boolean;

**Comment by samme** [comment]
I think this is from a problem in the tsgen parser. It has all the function types return `void`.

**Comment by xmahle** [comment]
I have a fix for this issue, but I can't make a pull request: `ERROR: Permission to photonstorm/phaser.git denied to xmahle.

cc @samme @photonstorm

**Comment by xmahle** [comment]
Also noticed that you are not returning `null` types, so `nullable` flag is ignored in the parser. I fixed that also...

**Comment by samme** [comment]
@xmahle Push to your own origin remote <https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork>

**Comment by xmahle** [comment]
Nice...

**Comment by photonstorm** [comment]
Sorry, forgot to close this issue after merging this PR a while ago!
