### ISSUE TITLE
`frame` of TileSpriteConfig should accept `number` in TypeScript

### ISSUE THREAD

**Issue by Fake** [phaserjs/phaser#5955]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows 10
* Browser: Google Chrome 96.0.4664.110

## Description
In phaser.d.ts, the `frame` of `TileSpriteConfig` type is defined as `string`. But `frame` parameter should also accept `number`.

## Example Test Code

In create() of Scene
```
this.make.tileSprite({
  x: 0,
  y: 0,
  width: 32,
  height: 32,
  key: "keyOfTexture",
  frame: 0,  <<- type error!
})
```

## Additional Information

GameObjectFactory accepts both `string` and `number` for `frame` parameter.
So below code is working.
```
this.add.tileSprite(0, 0, 32, 32, "keyOfTexture", 0)
```

Also `// @ts-ignore` is a workaround for `this.make` way.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
