### ISSUE TITLE
this.scale.setGameSize(w, h) doesn't change canvas size the second time a phaser game is launched

### ISSUE THREAD

**Issue by nfernand** [phaserjs/phaser#5959]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows 10
* Browser: 96.0.4664.110

## Description

The first time a phaser game is launched, setting up a handler on 'resize' event that scales canvas by using `this.scale.setGameSize(w, h);` is working fine and the canvas actually reflects the size set by phaser.

However, the second time the game is launched, although phaser seems to think the canvas size is modified, it does not actually change in the dom.

## Example Test Code

https://codepen.io/nicofaya/pen/XWeVjMy

Also, repo with minimal code to reproduce : https://gitlab.com/faya/phaser-resize-debug

## Additional Information

Steps to reproduce issue :
* Click Start button
* Resize the window
* Notice the canvas size resizes to match the container size
* Click Stop button
* Click Start button again to launch the game a second time
* Resize the window
* Notice the canvas size stays unmodified

See video below to illustrate issue described :
https://user-images.githubusercontent.com/818404/147473405-1d316a6d-0fd1-46b0-8bd2-b5695897695a.mp4

**Comment by samme** [comment]
I think the problem is caused by

    if (!resizeHandler) resizeHandler = this.setupGameSize.bind(this);

That function is modifying the first game canvas and is never replaced.

**Comment by nfernand** [comment]
That was it. Thanks and sorry for the bother.
