### ISSUE TITLE
ios input stack on disable/enable input

### ISSUE THREAD

**Issue by ddanushkin** [phaserjs/phaser#5962]
## Version
* Phaser Version: 3.55.2
* Operating system: iOS

## Description
Pointer is always down if input was disabled (and then enabled) while pointer is down.

## Example Test Code
https://codepen.io/ddanushkin/pen/bGWxyVz

**Comment by natureofcode** [comment]
Test it using the latest **3.60.0** beta **4** build: [https://cdn.jsdelivr.net/gh/natureofcode/phaser@build/3.60.0-beta.4/dist/phaser.js](https://cdn.jsdelivr.net/gh/natureofcode/phaser@build/3.60.0-beta.4/dist/phaser.js)

**Comment by d-kozlov** [comment]
> Test it using the latest **3.60.0** beta **4** build: https://cdn.jsdelivr.net/gh/natureofcode/phaser@build/3.60.0-beta.4/dist/phaser.js

Same, iOS 14.3, iPhone 6s
https://codepen.io/d-kozlov/pen/MWEqRON

**Comment by photonstorm** [comment]
This is such an edge case that I'm happy to leave it working like this. Toggling a boolean like that isn't going to reset the entire input system. As of 3.60 you can now call the new method `InputPlugin#resetPointers` which you can use to reset all the Pointers in a Scene. So invoke this method if you want to do this enable/disable toggle.
