### ISSUE TITLE
Phaser.Scale is undefined

### ISSUE THREAD

**Issue by 915-nistor-robert** [phaserjs/phaser#5967]
## Version

* Phaser Version: 3.55

* Operating system: Windows 10

* Browser: Firefox

## Description

Hello, I want to resize my game to be the exact same size like the browser window, and if the window resizez, the game will resize too and the text aswell.
Anyway, to do that I need the ScaleManage, but it does not work for me, the error I get in the console is:
TypeError: Phaser.Scale is undefined
The version of my Phaser is 3.11 but I don't know hot to update it, I just clone the repository and thought it would be the latest version, can someone explain how to switch from 3.11 to 3.16 or higher?

## Example Test Code

var config = {
    type: Phaser.AUTO,
    backgroundColor: '#000000',
    width: 800,
    height: 600,

    scale:{
        mode: Phaser.Scale.FIT,
        // MODE: Phaser.Scale.FIT,
         width: 800,
         height:600
    },
    scene:{
        preload: preload,
        create: create
    }
}

**Comment by photonstorm** [comment]
The Scale Manager isn't part of 3.11, so you definitely need to upgrade. If you have cloned _this_ repository, you will find the latest build in the `dist` folder. Or you can just download them directly from the releases page: https://github.com/photonstorm/phaser/releases/tag/v3.55.2
