### ISSUE TITLE
DOMElement can not prevent propagating mouse event

### ISSUE THREAD

**Issue by patrikturi** [phaserjs/phaser#5969]
## Version
* Phaser Version: 3.55.2
* OS version: Ubuntu 20 (but not OS dependent)
* Browser: not browser dependent

## Description
I have a phaser DOMElement, I want to prevent the GameObject behind it from getting mousedown/mouseup events.

Expected: GameObject behind DOMElement does NOT get mousedown event

Actual: both the DOMElement and the GameObject behind it receive mousedown event

## Example Test Code
I tried:
1. `event.stopPropagation()` on mousedown / touchstart / click events
2. `domObject.setInteractive()`
neither worked

Example / demo: https://codepen.io/PatrikT/pen/VwMxoVq?editors=0011

## Additional Notes:

This other example works fine, but it creates the HTML Element outside of Phaser. This is not what I want. I would like to use a Phaser DOMElement.
https://codepen.io/samme/pen/LvYrEo?editors=0010

**Comment by samme** [comment]
I think you need to stop propagation of (at least) the `mousedown` `mouseup` `touchstart` `touchend` DOM events, and not `pointerdown` `pointerup` (because Phaser doesn't use those).

https://codepen.io/samme/pen/jOGvqyq?editors=0010

**Comment by patrikturi** [comment]
@samme Thank you! It's confusing that Phaser calls the event `pointerup` but actually using the `mouseup` event.
