### ISSUE TITLE
`scale.mode` in game config is ignored

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#5970]
## Version

* Phaser Version: v3.60.0-beta.4 (063e8c78ef2791be9b589d31482dbfa9b78778a6)

## Description

If you create a game with a config value in `scale.mode` the value is ignored.

## Example Test Code

```
new Phaser.Game({
  scale: {
    mode: Phaser.Scale.FIT,
    width: 800,
    height: 600
  },
  callbacks: {
    postBoot: function (game) {
      console.assert(
        game.scale.scaleMode === Phaser.Scale.FIT,
        "Expected scaleMode %s but got %s",
        Phaser.Scale.FIT,
        game.scale.scaleMode
      );
    }
  }
});
```

## Additional Information

The problem is in

https://github.com/photonstorm/phaser/blob/08bc8284938546afbd67b4745fa924727745c867/src/core/Config.js#L76

because the desired properties are in `scaleConfig.mode` or `config.scaleMode` but not `scaleConfig.scaleMode`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
