### ISSUE TITLE
Spine 4.X Export bug

### ISSUE THREAD

**Issue by raimon-segura** [phaserjs/phaser#5972]
## Version
* Phaser Version:3.55.2
* Operating system: Ubuntu
* Browser: Chrome

## Description
Exports using version 4.X of Spine software show the above message. But, If I set the "legacy output" in pack-settings it works well, also it works with spine 3.X.

```
SpinePlugin.js?cbaa:26671 Uncaught Error: Unknown texture filter true
    at Function.window.SpinePlugin.Texture.filterFromString (VM5344 290:26671)
    at TextureAtlas.window.SpinePlugin.TextureAtlas.load (VM5344 290:26760)
    at new TextureAtlas (VM5344 290:26736)
    at SpinePlugin.getAtlasWebGL (VM5344 290:13053)
    at SpinePlugin.createSkeleton (VM5344 290:13458)
    at SpineGameObject.setSkeleton (VM5344 290:33114)
    at new SpineGameObject (VM5344 290:32825)
    at GameObjectFactory.add [as spine] (VM5344 290:12811)
    at VueComponent.createMeRoby (PuzzlePlugin.vue?0373:1068)
    at VueComponent.createObject (PuzzlePlugin.vue?0373:575)
```

The exported atlas with version 4.X starts with:

```
XXXXX.png
size:1024,128
filter:Linear,Linear
pma:true
scale:0.15
br/l_br/body
bounds:713,87,39,41
rotate:90
```

The exported atlas with version 3.X starts with:

```
XXX.png
size: 1024,128
format: RGBA8888
filter: Linear,Linear
repeat: none
br/l_br/body
  rotate: true
  xy: 713, 87
  size: 39, 41
  orig: 39, 41
  offset: 0, 0
  index: -1
```

## Example Test Code
In case it has not an easy solution or needs a bug fix, I'll provide a simple online test code as soon as possible.

## Additional Information
Similar error: http://es.esotericsoftware.com/forum/ERROR-Unknown-texture-filter-true-16273

Thanks!

**Comment by photonstorm** [comment]
This is correct as the Spine Runtimes we use are for Spine 3.

Someone had offered to fund the upgrade to Spine 4 but this has since fallen through, so there is no current timescale for when it will be done. The issue is that we will need to maintain both versions of the plugin in parallel (Spine 3 and 4) which doubles the amount of work required for even a simple fix :(

**Comment by badlogic** [comment]
Hit us up at contact@esotericsoftware.com regarding maintenance/upgrades/funding if you are interested, or DM on Twitter @badlogicgames.

**Comment by justintien** [comment]
@raimon-segura 

I did spine4.1 plugin

You can try:

phaser 3.55.2
https://github.com/justintien/phaser/tree/3.55.2/plugins/spine4.1

phaser 3.60.0-beta.17
https://github.com/justintien/phaser/tree/add-spine4.1-plugin/plugins/spine4.1

**Comment by raimon-segura** [comment]
@justintien  That's great!!! ..we will test it asap, 

many thanks!

**Comment by raimon-segura** [comment]
> I did spine4.1 plugin
> You can try:
> phaser 3.55.2 https://github.com/justintien/phaser/tree/3.55.2/plugins/spine4.1
> phaser 3.60.0-beta.17 https://github.com/justintien/phaser/tree/add-spine4.1-plugin/plugins/spine4.1

Hi @justintien !..

it works great!

Thanks!
