### ISSUE TITLE
`createBitmapMask()` is inconsistent when used on Shapes

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#5976]
## Version

* Phaser Version: 3.55.2

## Description

When called on a Shape game object, `createBitmapMask(shape)` makes a working mask but `createBitmapMask()` doesn't.

## Example Test Code

Given a Shape:

    const rect = this.add.rectangle(0, 0, 200, 150, 0xffff00);

This makes a working mask:

    const mask = rect.createBitmapMask(rect);

This doesn't:

    const mask = rect.createBitmapMask();

Both calls succeed, but only the first mask has a visual effect.

**Comment by rexrainbow** [comment]
#5918

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
