### ISSUE TITLE
Body Center is wrong when reset(x,y) and collideWorldBounds is enabled

### ISSUE THREAD

**Issue by lukasharing** [phaserjs/phaser#5978]
https://github.com/photonstorm/phaser/blob/d67c93646cbfe8ba5997954f8af29a8f3f9e8e91/src/physics/arcade/Body.js#L1393-L1395

`this.checkWorldBounds()` calculation should be called when reseting to avoid flickering

**Comment by samme** [comment]
Can you solve this with

```js
body.reset(x, y);
body.checkWorldBounds();
```

? If so it doesn't really seem a problem with `reset()`.

**Comment by lukasharing** [comment]
I guess this should be made automatically when you reset, I know you can fix this by using `checkWorldbounds`, but doesn't seem correct if have to do it by hand. Because when it updates, world bounds are checked, so that frame is a flicker.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
