### ISSUE TITLE
Tween Duration is 0 when totalDuration is set in timeline

### ISSUE THREAD

**Issue by lukasharing** [phaserjs/phaser#5982]
It seems that this line does always set to 0 the duration
https://github.com/photonstorm/phaser/blob/d67c93646cbfe8ba5997954f8af29a8f3f9e8e91/src/tweens/tween/TweenData.js#L61

**Comment by lukasharing** [comment]
Calling `.init()` seems to calculate each duration

**Comment by samme** [comment]
I think that's expected.

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
