### ISSUE TITLE
Phaser.GameObject.Polygon ignores closePath with Phaser.CANVAS

### ISSUE THREAD

**Issue by optimumsuave** [phaserjs/phaser#5983]
## Version
* Phaser Version: 3.55.2

## Description
Phaser.GameObjects.Polygon ignores the `closePath` boolean when GameConfig.type === Phaser.CANVAS

![Screen Shot 2022-01-26 at 1 50 08 PM](https://user-images.githubusercontent.com/8495746/151252828-8e715b5a-b7b2-4cec-9774-1fe38ee63627.png)

## Example Test Code
https://codepen.io/optimumsuave/pen/abVzweR

## Additional Information
I have forked the repo and will be opening a PR.

### Problem
PolygonCanvasRenderer always calls `closePath()` - does not check for `src.closePath` boolean.
https://github.com/photonstorm/phaser/blob/master/src/gameobjects/shape/polygon/PolygonCanvasRenderer.js#L59
```
ctx.closePath();
```

### Solution
StrokePathWebGL (called from PolygonWebGLRenderer when type === Phaser.WEBGL) checks for closePath ([here](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/shape/StrokePathWebGL.js#L59))
A solution which can be found in [`ArcCanvasRenderer`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/shape/arc/ArcCanvasRenderer.js#L47) & [`CurveCanvasRenderer`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/shape/curve/CurveCanvasRenderer.js#L59) wraps closePath() with a check:
```
if(src.closePath) {
  ctx.closePath();
}
```

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
