### ISSUE TITLE
Phaser 3 API Docs link is broken

### ISSUE THREAD

**Issue by fguillen** [phaserjs/phaser#5993]
## Version

* Phaser Version: 3

## Description

I am looking for the Phaser 3 API Docs.. but all links bring me to this page:

- https://photonstorm.github.io/phaser3-docs/index.html

But this is not an API Docs

I am looking for something like this: 

- https://phaser.io/docs/2.6.2/index

But for Phaser 3

Thanks

**Comment by photonstorm** [comment]
That _is_ the API documentation - just pick from any of the menus at the top.

Alternatively, this is the new format: https://newdocs.phaser.io/docs/3.55.2

The same applies here though. Pick from the menus at the top.

**Comment by fguillen** [comment]
I totally missed the top menus.. thanks!
