### ISSUE TITLE
Use json data with dataKey in Pack loader

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6001]
## Version

* Phaser Version: 3.55.2

* Operating system: win11

* Browser: Chrome. firefox

## Description

[Here](https://codepen.io/rexrainbow/pen/gOXRQGd) is the test code. It load assets by Pack with json data.
- Without dataKey, it works fiine
- With datakey `test1`, it won't work. 

It might because that, [redundant reading dataKey in JSONFile loader](https://github.com/photonstorm/phaser/blob/v3.60.0-beta.4/src/loader/filetypes/JSONFile.js#L77), therefore [this.data](https://github.com/photonstorm/phaser/blob/v3.60.0-beta.4/src/loader/filetypes/PackFile.js#L65) will be incorrect.

**Comment by photonstorm** [comment]
Hmm... removing this `this.data = GetValue(url, dataKey);` fixes `load.pack` and breaks `load.json` :)

Will dig a little deeper.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
