### ISSUE TITLE
GAMEOBJECT_POINTER_OUT is not emitted to previously hovered Game Objects

### ISSUE THREAD

**Issue by robinheidrich** [phaserjs/phaser#6006]
## Version

* Phaser Version: 3.60.0-beta.4

* Operating system: Windows 11

* Browser: Google Chrome 98.0.4758.102

## Description

When the pointer leaves the canvas, the event `GAMEOBJECT_POINTER_OUT` should be emitted for previously hovered game objects, [as this code suggests](https://github.com/photonstorm/phaser/blob/5e40753da201e411b9f4871d5fd4926bbe7e520a/src/input/InputPlugin.js#L1850).

However, it does not work. The game object remains hovered.

_If this is intended behavior, it should be changed so that when the cursor leaves the canvas the event is emitted._

## Example Test Code

You can use [this example](https://labs.phaser.io/edit.html?src=src/input/game%20object/over%20and%20out%20events.js&v=3.55.2). Add `height: 300` to the game config.

## Additional Information

Only when the cursor goes back into the canvas, the game object loses the hover state.

![capture](https://user-images.githubusercontent.com/23118399/153952930-bf7dbf8e-aba2-4c87-b12f-5bea3a6dc6e9.gif)

**Comment by photonstorm** [comment]
Hmm, this isn't as obvious as it looks.

If you leave the canvas, the Game Object should remain in the 'over' state - if you were to then re-enter the canvas with the pointer back over the Game Object again, the 'over' state would be correct. It shouldn't, in this instance, re-fire an 'over' state or lose its over state, as it protects against a user quickly / accidentally mousing out of the canvas while playing something and having it not reset their input state as they do so.

We used to have it (a long time ago) that if you left the canvas, then all input was reset, but it feels extremely counter-intuitive when actually playing a game, especially if you've objects close to the canvas borders.

So I'm going to leave it how it works. I think what would be useful, though, is the ability to 'reset' the 'over state' of a Game Object, so you can target it and unset it directly as part of the game-out input handler. Something that isn't easily possible at the moment.

**Comment by photonstorm** [comment]
This can now be done using the new `InputPlugin.forceState` methods - such as `forceOverState` or `forceOutState`.
