### ISSUE TITLE
Spritsheet to texture is reversed

### ISSUE THREAD

**Issue by Grandnainconnu** [phaserjs/phaser#6008]
## Version

* Phaser Version: 3.55.2

* Operating system: Mac OS

* Browser:

## Description

When creating a texture from a spritesheet, then drawing the sprite, the frame order is reversed.
For example, if a spritesheet has 8 drawings of each 32x32 pixels, when drawing the sprite from the created texture, frame 0 will  display the drawing number 8.
Also, on the example below, the frame size is not applied correctly, the 2nd image is cropped.

## Example Test Code

https://codepen.io/Hetarnam/pen/zYPEPVB

**Comment by photonstorm** [comment]
Your sprite sheet does not match the frame sizes you've given it. [The image](https://i.imgur.com/2P6No1t.png) is 100x140 in size, you've used the frame size 20 x 14, but that isn't the way the guns are drawn. Here is a shot from Photoshop where you can see a 20x20 grid overlaid on the png:

<img width="853" alt="Capto_Annotation" src="https://user-images.githubusercontent.com/164476/154804297-88d87262-e4cb-43eb-91d1-97d77b42ec4b.png">

and the same image with a 14x14 grid:

<img width="864" alt="Capto_Annotation" src="https://user-images.githubusercontent.com/164476/154804330-0bdaa633-7637-4a23-afce-45b1c893935a.png">

As you can see, the gun sprites do not fit these grid sizes at all. Hence, why Phaser can't display them like this either.

**Comment by Grandnainconnu** [comment]
Ok my bad for the cropping then. But the order on display is still reversed, though. What is the problem for that? I tried with another sprite with correct cutting and the problem is still there.
