### ISSUE TITLE
Spritsheet to texture is reversed

### ISSUE THREAD

**Issue by Grandnainconnu** [phaserjs/phaser#6017]
## Version

* Phaser Version: 3.55.2

* Operating system: Mac OS

* Browser: 

## Description

When creating a texture from a spritesheet, then drawing the sprite, the frame order is reversed.
For example, if a spritesheet has 8 drawings of each 32x32 pixels, when drawing the sprite from the created texture, frame 0 will display the drawing number 8.

## Example Test Code

https://codepen.io/Hetarnam/pen/zYPEPVB

## Additional Information

Following of issue #6008 that has been closed without answer about the main concern, so I changed the sprite to a correct one on the pen and the issue is still there.

**Comment by photonstorm** [comment]
Frames are never reversed.

Yet again the spritesheet in the codepen is invalid. The image is 249 x 497. You cannot divide this by 31 pixels evenly, so it won't  be split into frames as you expect it.

Use a properly sized spritesheet and it will display the correct frame.

**Comment by Grandnainconnu** [comment]
> Frames are never reversed.
> 
> Yet again the spritesheet in the codepen is invalid. The image is 249 x 497. You cannot divide this by 31 pixels evenly, so it won't be split into frames as you expect it.
> 
> Use a properly sized spritesheet and it will display the correct frame.

Ok my bad again ! I changed the image for one in a tutorial that is definitely the good size 32x32, and the problem is still there.
Frame one of the texture displays frame 92

**Comment by samme** [comment]
I reproduced this, I think, with the WEBGL renderer only:

<https://codepen.io/samme/pen/zYPLLyw?editors=0010>

**Comment by Grandnainconnu** [comment]
> I reproduced this, I think, with the WEBGL renderer only:
> 
> https://codepen.io/samme/pen/zYPLLyw?editors=0010

Yes you're right, when I switch to CANVAS the problem disappear

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
