### ISSUE TITLE
Spine objects cannot have the same texture atlas filename

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6022]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 11

* Browser: Chrome 98

## Description

When using the Spine plugin, two spine files cannot have the same texture atlas png filename.

Example:

assets/spine1/skeleton.json
assets/spine1/skeleton.atlas
assets/spine1/skeleton.png <- same filename

assets/spine2/skeleton.json
assets/spine2/skeleton.atlas
assets/spine2/skeleton.png <- same filename

For some reason, the two spine game objects will now share the same texture atlas png. The atlas definition itself will be different, so it will be rendered as a chopped up Picasso-esque image.

## Example Test Code

    this.load.spine('spine1', 'assets/spine1/skeleton.json', 'assets/spine1/skeleton.atlas', true);
    this.load.spine('spine2', 'assets/spine2/skeleton.json', 'assets/spine2/skeleton.atlas', true);

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by spayton** [comment]
does this also need applying to the spine41 plugin
