### ISSUE TITLE
fillRoundedRect on retina screens isn't rendering right

### ISSUE THREAD

**Issue by nick-tw** [phaserjs/phaser#6033]
## Version

* Phaser Version:3.55.2

* Operating system:iOS 15.3.1

* Browser: Safari 15.3

## Description

I created an overlayFade (a black screen with 50% opacity to fade the screen for an on-boarding tutorial screen). I created a mask to cut out a rectangle from the fade screen to highlight items on the screen.

The rounded corners work fine on 1x PC screens but when I view on the iPhone 13 Pro with a high density screen, the corners are not properly rendered.

I used a variable DPR (device pixel ratio) to multiply the values to have consistently sized items.

## Example Test Code

```               
                    const { width, height } = this.scale
                    this.overlayFade = this.add.rectangle(width / 2, height / 2, width, height, 0x000000); 
                    this.help1Mask = this.graphics.fillRoundedRect(0, 0, 115*DPR, 38*DPR, 16*DPR).setVisible(false)
                    var geoMask = this.help1Mask.createGeometryMask()
                    geoMask.invertAlpha = true
                    this.overlayFade.setMask(geoMask)
```

## Additional Information

1x screenshot: 
![Screen Shot 2022-03-04 at 7 50 35 PM](https://user-images.githubusercontent.com/46468291/156866634-e29d43d2-11ee-4b77-b1f9-226b54967dc0.png)

3x pixel density screenshot (via xcode iPhone 13 Pro simulator):
![Screen Shot 2022-03-04 at 7 41 22 PM](https://user-images.githubusercontent.com/46468291/156866640-16615647-29e1-4195-b023-7908cea0ae3f.png)

**Comment by photonstorm** [comment]
Tested under 3.60 Beta 15 on iPhone Pro 13 (iOS15) and it renders fine now. This is with a DPR of 3.0:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/164476/203439353-539d7713-35cd-4fc9-9f8d-d095b0739fb7.png">

Here is the test I'm using: https://labs.phaser.io/view.html?src=src/bugs/6033%20retina%20graphics.js&v=dev
