### ISSUE TITLE
Tab Switching Issue :

### ISSUE THREAD

**Issue by Rupesh-dev07** [phaserjs/phaser#6056]
window.addEventListener('load', function() {
    var config = {
        type: Phaser.CANVAS,
        width: 1024,
        height: 576,
        parent: 'GameContainer',
        dom: {
            createContainer: true
        },
        physics: {
            default: 'arcade',
            arcade: {
                debug: true,
                gravity: { y: 150 }
            }
        },
        scale: {
            mode: Phaser.Scale.FIT,
            autoCenter: Phaser.Scale.CENTER_BOTH
        },
        loader: {crossOrigin: true}
    };

    var game = new Phaser.Game(config);

    game.scene.add("Boot", Boot, true);
    game.scene.add("Preload", Preload);
    game.scene.add("Lobby", Lobby);
    game.scene.add("Gametable", Gametable);
    game.scene.add("Newgametable", Newgametable);

    init();

});

class Boot extends Phaser.Scene {

    preload() {
    //Images 
    }

    update() {
        this.scene.start("Preload");
           }
    }
On tab switching , it is gettig destroy , its a ludo main.js file . But when i start to gamepplay and switch the tab, gameplay gets stuck or paused whe browser loses focus .

**Comment by samme** [comment]
> In most modern browsers, when the document enters a hidden state, the Request Animation Frame and setTimeout, which control the main game loop, will automatically pause. There is no way to stop this from happening. It is something your game should account for in its own code, should the pause be an issue (i.e. for multiplayer games)

<https://newdocs.phaser.io/docs/3.55.2/Phaser.Core.Events.HIDDEN>
