### ISSUE TITLE
Text shadow is cut off for some letters

### ISSUE THREAD

**Issue by robinheidrich** [phaserjs/phaser#6063]
## Version

* Phaser Version: 3.60.0-beta.5

* Operating system: Windows 11

* Browser: Google Chrome 100.0.4896.60

## Description

For the letter "g", for example, the shadow is cut off, while this is not the case with other characters.

![image](https://user-images.githubusercontent.com/23118399/161312484-a7adabae-dc3b-4430-9bea-225bea37917b.png)

## Example Test Code

```js
const text = this.add.text(10, 10, "123 test g");
text.setStyle({"align":"center","fontFamily":"Verdana","fontSize":"24px","fontStyle":"bold","stroke":"#000","shadow.offsetY":1,"shadow.blur":4,"shadow.stroke":true,"shadow.fill":true});
```

## Additional Information

A workaround is to add a new line in the text.

![image](https://user-images.githubusercontent.com/23118399/161313533-4086e35f-d362-4e40-8398-a4fae9c4ad66.png)

**Comment by samme** [comment]
I think [padding](https://newdocs.phaser.io/docs/3.55.2/Phaser.GameObjects.Text#padding) is intended for this, since the shadow doesn't affect the line height.

**Comment by robinheidrich** [comment]
It should not be necessary to add padding to every text with shadow. Would be cool if Phaser could solve this somehow.

**Comment by photonstorm** [comment]
You need to add padding to your Text - it's impossible to know how big the shadow will be programmatically. Canvas does not make that information available.
