### ISSUE TITLE
disableContextMenu does not respect input.mouse.target

### ISSUE THREAD

**Issue by lukashass** [phaserjs/phaser#6064]
## Version

* Phaser Version: ^3.54.0

* Operating system: all

* Browser: all

## Description

When setting `disableContextMenu: true`, Phaser disables the context menu on `document.body` even when `input.mouse.target` ~`scale.parent`~ is set to something else.
This results in a disabled context menu on the whole page, even parts that should not be under the control of Phaser.

I think the context menu should only be disabled on `input.mouse.target` ~`scale.parent` when it is set (or maybe even the canvas itself?)~ .

## Example Test Code

Relevant code parts:

https://github.com/photonstorm/phaser/blob/59fbcc5ca3f45388b833b07f94aefbc25cd1e24e/src/input/mouse/MouseManager.js#L287

https://github.com/photonstorm/phaser/blob/59fbcc5ca3f45388b833b07f94aefbc25cd1e24e/src/input/touch/TouchManager.js#L212

## Additional Information

I'm happy to help with this, when there are no objections.

**Comment by samme** [comment]
That does seem incorrect, but I think the correct targets would be the `input.mouse.target` and `input.touch.target` config values, not `scale.parent`.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
