### ISSUE TITLE
Phaser's automatic scaling pushes content out of screen on iPhone Safari with addressbar open.

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6072]
## Version

3.55.2

win10

* Browser:
iPhone Safari

## Description
Phaser's automatic scaling of canvas using 'FitOutside', otherwise called ENVELOPE, on Safari, seems to be not calculating available vertical screen space correctly. When the addressbar appears on iPhone Safari browser, it pushes content down, pushing bottom part of the game out of view. 

Basically exactly as described here: https://www.html5gamedevs.com/topic/30297-mobile-firendly-safari-address-bar/

It was suggested in that thread, that using automatic scaling and calculating from window.innerHeight might solve the problem (idk what Phaser is using). 

Additionally, as is case in our App, it adds black borders to left/right of the app content area, which in turn makes the game vertically scrollable.

I'd like to avoid using manual scaling off window.innerHeight, but use Phaser's automatic scaling system (id like to avoid having to touch HTML - but if someone could provide an example code to use to scale to ENVELOPE considering window.innerHeight, i'd give it a shot).

Project scale settings:
`scale: {
    mode: Phaser.Scale.ENVELOP,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    zoom: 1
}`
Additionally, im pasting text from our internal bugtracker regarding this issue, along with some pictures:

![IMG_7320](https://user-images.githubusercontent.com/36237028/161692526-e7a1a610-977e-4827-932e-d827813f4434.jpg)
![IMG_7318](https://user-images.githubusercontent.com/36237028/161692533-a61191e2-b21b-4ba2-8a0f-ea4348359026.jpg)
![IMG_7319](https://user-images.githubusercontent.com/36237028/161692540-e13eacb2-50b8-4398-975c-eaf2912f9081.jpg)

Summary | 0000267: [Mobile/iOS] Game cut off / only partially playable on Safari iOS

Only part of the game is visible on iOS Safari in landscape mode - parts at the bottom are cut off.==> Game cannot be fully played on iOS right now.It doesn't really matter if Safari has only 1 page open or if there are multiple tabs (=tab bar visible): even without the tab bar the game still is not fully visible. Also there are black bars on the side (which are not a major issue itself, though would be nicer if the game used the full available screen). Note though, these bars make the game's canvas scrollable (though the game still stays cut off).

Safari on iOS 15.4iPhone 12 Pro Max

**Comment by michalfialadev** [comment]
As a followup, this is a known bug:
https://stackoverflow.com/questions/60795018/ios-13-safari-bugs-in-window-innerheight
https://www.html5gamedevs.com/topic/32213-browser-ui-problem-on-ios-safari/
Not Phaser related, except that when using Phaser's automatic ENVELOPE scaling, it might be handled by Phaser? (feature request?)

Reading up on ScaleManager docs, this should prob. not be handled by Phaser, but by CSS associated with scaling the 'parent container' (if one is defined in phaser config).

My knowledge on how this could be fixed by dynamically adjusting CSS of associated parent container using JS on resize is limited, the solution seems to be found somewhere in this file:
https://github.com/carlosrafaelgn/pixel/blob/master/scripts/main.ts
@see `adjustWindowSize`, @see `if(ifIOSOrSafari)`, but im unsure to what effect this would interfere with automatic scaling done by Phaser - perhaps this code could be used to improve automatic scaling done by Phaser on iOS Safari?

EDIT: for now i was simply using `{ width:100%; height:100%; padding:0; margin:0; overflow:hidden; }` on most containers (html. body, game's parent), which worked everywhere except Safari iOS. I suppose i could try using fixed pixel size computing width and height from `getBoundingClientRect` of `body` HTMLElement considering devicePixelRatio, as the example above does, see how that works.

**Comment by michalfialadev** [comment]
Was able to solve this, but manipulating parent container, that phaser instance resides within.

**Comment by thurnz** [comment]
What fixed for me is setting the parent size to window.innerWidth and window.innerHeight

`this.scale.setParentSize(window.innerWidth, window.innerHeight);`

**Comment by michalfialadev** [comment]
> What fixed for me is setting the parent size to window.innerWidth and window.innerHeight
> 
> `this.scale.setParentSize(window.innerWidth, window.innerHeight);`

Ah yes, i forgot to mention that, exactly what i used back then also.

**Comment by jcrooke** [comment]
@thurnz you are my Hero
