### ISSUE TITLE
Gamepad is not working on Tizen SmartTV after 3.24.1

### ISSUE THREAD

**Issue by sgxxa** [phaserjs/phaser#6077]
## Version

* Phaser Version: 3.24.1 and 3.55.2

* Operating system: TizenOS

* Browser: TizenOS Browser

## Description

The gamepad sample stops working on Tizen SmartTV (inside the Tizen Browser) after release 3.24.1 (excluded).

After version 3.24.1 until latest version 3.55.2, the gamepad plugged to the SmartTV is recognized in the sample application, but no input is received by the application. Up to version 3.24.1, gamepad is recognized and inputs are received correctly.

We have not experienced this issue on another Operating System so far.

## Example Test Code

We use the Phaser gamepad-debug application, which allows to choose the version of Phaser, and makes it easy to reproduce the issue.

https://phaser.io/examples/v3/view/input/gamepad/gamepad-debug

https://labs.phaser.io/edit.html?src=src/input/gamepad/gamepad%20debug.js&v=3.55.2

## Additional Information

If you do not have access to a Tizen SmartTV, we can definitely assist you in trying to reproduce and fix the problem.

**Comment by photonstorm** [comment]
I'm not sure there's a massive amount we can do about this here, as we don't have access to a Tizen Smart TV. So it will require debugging from your end I'm afraid.

I'm not sure a great deal changed in the Gamepad code between 3.24 and 3.55 however, so it likely isn't a big change we're looking for. In fact, I can only see 2 commits from Sep 11th 2020 that may have caused this:

https://github.com/photonstorm/phaser/commits/master/src/input/gamepad

**Comment by photonstorm** [comment]
Closing as we cannot fix this here. Happy to take a PR that does so, though.
