### ISSUE TITLE
Any plans to support Spine 4?

### ISSUE THREAD

**Issue by foliodev** [phaserjs/phaser#6079]
https://github.com/photonstorm/phaser/issues/5972#issuecomment-1012154805

Thanks

**Comment by justintien** [comment]
@supafoundation 

I did spine4.1 plugin

You can try:

phaser 3.55.2
https://github.com/justintien/phaser/tree/3.55.2/plugins/spine4.1

phaser 3.60.0-beta.17
https://github.com/justintien/phaser/tree/add-spine4.1-plugin/plugins/spine4.1
