### ISSUE TITLE
The PreUpdate/Update/PostUpdate events don't correctly coincide with Scene.update method calls.

### ISSUE THREAD

**Issue by kobaj** [phaserjs/phaser#6080]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 11

* Browser: Chrome Or Firefox

## Description

The PreUpdate/Update/PostUpdate events don't correctly coincide with Scene.update method calls.

That is, [the documentation](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.Events.html#event:UPDATE__anchor) states the following is supposed to happen.
1. [PRE_UPDATE](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.Events.html#event:PRE_UPDATE)
2. [UPDATE](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.Events.html#event:UPDATE)
3. The Scene.update method is called, if it exists
4. [POST_UPDATE](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.Events.html#event:POST_UPDATE)
5. [RENDER](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.Events.html#event:RENDER)

But I've found that this isn't the case. Specifically that steps 1,2 and 4 will happen without step 3. And that steps 1, 2, and 4 can happen even before Scene.create method is called.

## Example Test Code

I also have a running version here: https://codesandbox.io/s/hungry-feistel-nuorru

```
import Phaser from "phaser";

class Main extends Phaser.Scene {
  preload() {
    console.info("Preload Start");
    this.load.on("progress", (...args) =>
      console.info("Loading Progress", ...args)
    );
    this.load.on("complete", (...args) =>
      console.info("Loading Done", ...args)
    );

    this.load.svg(
      "test",
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg"
    );

    this.events.once("create", () => console.info("Create"), this);
    this.events.once("preupdate", () => console.info("PreUpdate"), this);
    this.events.once("postupdate", () => console.info("PostUpdate"), this);
    this.events.once("update", () => console.info("Update"), this);

    console.info("Preload Done");
  }

  create() {
    console.info("Create Start");
    console.info("Create Done");
  }

  update() {
    console.debug("Update Start");
  }
}

const config = {
  type: Phaser.AUTO,
  scale: {
    width: "100%",
    height: "100%",
    mode: Phaser.Scale.ScaleModes.RESIZE,
    expandParent: false
  },
  pixelArt: true,
  scene: [Main],
  title: "Test Game Thingo!"
};

const game = new Phaser.Game(config);

```

## Additional Information

I've found that this is only reproducible when there is something loading (in this case an svg file). 

Here is a screenshot in chrome that clearly shows the log statements out of order.

![image](https://user-images.githubusercontent.com/3144837/163724152-0cc97003-4d62-4cf9-8384-facd45696fcc.png)

Here are the log statements:

1. Scene.preload
2. loading progress (event)
3. preupdate (event)
4. update (event)
5. postupdate (event)
6. loading complete (event)
7. Scene.create
8. create (event)
9. Scene.update

Given the documentation, I would expect:

1. Scene.preload
2. loading progress (event)
3. loading complete (event)
4. Scene.create
5. create (event)
6. preupdate (event)
7. update (event)
8. Scene.update
9. postupdate (event)

**Comment by samme** [comment]
This is as designed. A scene begins updating and rendering (by the events) when it enters the `START` state. But the `update()` callback isn't called until the scene reaches `RUNNING`, as it's assumed to depend on `create()`.

I guess (3) should include _and the scene is running_.

**Comment by photonstorm** [comment]
This is working as intended. I have amended the documentation to make it clear the Scene must be in a running (not Preloading) state.
