### ISSUE TITLE
SSL Certificate on phaser.io expired

### ISSUE THREAD

**Issue by gokaygurcan** [phaserjs/phaser#6083]
Hi,

Self-explanatory title, I believe. Ask for more if you have any questions, but I assume you wont :) 

Best,
G.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/1509413/164107956-5866bc8b-9277-4e05-98b0-e6962f69de68.png">

**Comment by Npfries** [comment]
Came here to file this. Needs fixed asap

**Comment by photonstorm** [comment]
Fixed yesterday.
