### ISSUE TITLE
phaser.mjs for use in browser without a bundler

### ISSUE THREAD

**Issue by rndmcnlly** [phaserjs/phaser#6085]
I'm interested in having a `phaser.mjs` (ES6 module) bundle built and distributed so that Phaser can be used as part of projects that use native ES6 modules in the browser without the need to run a bundler tool on the game code. This would be a file suitable for use in `<script type="module" src="phaser.mjs"></script>` or `import Phaser from "phaser.mjs";`.

Prototype: https://github.com/rndmcnlly/ModularPhaserExample (implemented by manually editing the first and last few lines of a recent `phaser.js` to `export` the relevant stuff).

Context: I'm teaching class on developing web games, and I want my students to be able to directly edit the files that are used in the browser. Currently, students write plain JS scripts, and they need to maintain several script tags in their html file and get little editor support for linting or refactoring. Here's a sample of our typical project layout: https://github.com/nathanaltice/RocketPatrol 
 If I want them to get access to explict `import`/`export` features with strong editor support, most references suggest starting to use a bundler, which enormously complicates the setup for novice programmers. In 2022 this shouldn't be necessary because most browsers natively support ES6 modules (as illustrated in the prototype above).

Short-term solution: Create a new webpack config to build a `phaser.mjs`/`phaser.min.mjs`. I think this is possible with some small configuration file tweaks, but I couldn't figure it out, hence the manual edits above. Clue: https://webpack.js.org/configuration/experiments/#experimentsoutputmodule

Limitation: From the perspective of the language server in VSCode, the library defines a single untyped value `Phaser` without any inspectable substructure or attached documentation. The details are there are runtime, but they aren't visible to the editor because of how webpack has organized the bundled code. If there was a way to have the various JS files in the Phaser source bundled in a less-clever way, more documentation/autocomplete might be available to people who depend on that single `phaser.mjs` file. Surely doing something equivalent to inlining the results of every `require` is something that existing bundlers/optimizers are capable of doing. I think this area is underexplored because people are currently hesitant to use ES6 modules natively, but if it worked, it would be a huge benefits to novice programmers and experts alike.

**Comment by wesleytodd** [comment]
Technically if the umd build just didn't error on `this`/`root` being undefined in an es module you could use `import('./phaser.js')`. I just setup a new project and ran into this and the only thing I needed to edit in `node_modules` was to make it `this || window` in the UMD header. Frankly I am surprised that umd bundles have not been updated to support ESM, or maybe the tooling for this project is just outdated? I am quite out of touch with FE builds these days, so I am not sure what to expect.

Code:
```javascript
await import('../node_modules/phaser/dist/phaser.js');
const Phaser = window.Phaser;
```

worked after this edit:

```javascript
(function webpackUniversalModuleDefinition(root, factory) {
  // ...
})(this || window, function() {
```

**Comment by photonstorm** [comment]
Phaser uses Webpack 5.72.1 which is the absolute latest version, so I would expect its UMD generation to be perfect. But, I guess not.

**Comment by rndmcnlly** [comment]
With my new understanding, this is a much bigger project than I originally imagined. I'd recommend stalling on the idea until such time as we're open to converting the entire Phaser codebase from the CommonJS format to the new ECMAScript Modules format. I think this is a good idea long-term, but it require a lot of tiny mechanical changes plus some creativity around the plugin system.

Detailed justification below.

---

As I learn more, it looks like the "Universal" UMD format is [not](https://jameshfisher.com/2020/10/04/what-are-umd-modules/) compatible with ECMAScript modules (ESM), and the gap between them is pretty significant. The key idea is that `require`-style imports are assumed to be resolved at runtime (like Python's imports). You can call `require` inside of an an `if` block that depends on some runtime value. By contrast, `import`-style imports are unconditional, top-level declarations (like Java's imports).

[Moduloze](https://github.com/getify/moduloze) is a tool that can mechanically convert from CommonJS-style code (using `require(...)` to ESM-style code (using `import`), but it only works on projects that already follow a specific discipline in how they use `require`. For example, Moduloze can make the following kind of change to almost every Phaser source file without any special guidance.

Before (`AlignTo.js`):

	var QuickSet = require('../display/align/to/QuickSet');
	...
	module.exports = AlignTo;

After (`AlignTo.mjs`): 

	import QuickSet from "../display/align/to/QuickSet";
	...
	export default AlignTo;

However, it can't handle conditional imports (example from `phaser-arcade-physics.js`):

	if (typeof FEATURE_SOUND)
	{
	    Phaser.Sound = require('./sound');
	}

There's no obvious way to signal to Moduloze our intent that `FEATURE_SOUND` is a _compile-time_ constant.

You can mechanically convert a codebase that uses static imports into one that uses dynamic imports (ESM -> UMD), but you can't generally go the other way. It's possible to expose a UMD module as an ESM module (mostly just adding `export Phaser;` to the bottom of `phaser.js`), but this gives the TypeScript equivalent of `let Phaser: any;` -- there's a variable called `Phaser`, but I can't tell you anything about it at compile/import time. This was the situation demonstrated in my prototype: https://github.com/rndmcnlly/ModularPhaserExample (You can `import Phaser`, but editors can't discover any structure of this value.)

To build Phaser as an ESM module that offers programmers nice tool-support like autocomplete and auto-importing, we'd need to make sure the entire codebase used only unconditional imports. If the entire codebase were converted to ESM format (with or without the help of Moduloze), it might help both game programmers and engine programmers. However, I don't know enough about architecting ESM projects to recommend what's supposed to happen to the current uses of `if (typeof FEATURE_SOUND)` or the like.

- Short-term recommendation: Tell ESM-curious game programmers to continue using Phaser as a traditional script file. They can hack their `phaser.js` to be `import`-able, but it won't provide many of the benefits often associated with modules.
- Long-term recommendation: Either find a source-to-source converter that understands compile-time constants or change the format of the entire Phase codebase to from CommonJS to ESM. Because Webpack can convert the ESM format back to UMD, this change wouldn't effect clients at all despite involving an edit to almost every JavaScript file in the project.

**Comment by photonstorm** [comment]
@rndmcnlly the whole point of Phaser 4 is to be 100% ESM modules - but that certainly isn't possible with v3 (as you've alluded to in your post, that's just the tip of the iceberg!)

However, it _should_ be possible to generate an ESM compatible bundle - but honestly, I thought Webpack did that already.

**Comment by photonstorm** [comment]
I spent quite some time seeing if this was even possible (converting Phaser 3 to use proper ESM modules), and it's really tricky. The stand-alone core classes (like Utils or Math) can be ported without much fuss, but things that use shared components, such as all the Game Objects, are a nightmare. ES6 classes don't support multiple inheritance, so we'd still have to use mixins to inject all the components, which is quite frightening and far from clean.

Solve that, and we still need to address things like the plugins, Factories, and Loader filetypes, which all work by injecting methods directly into the class. As much as I'd love to do this for v3, it's not really practical - and given I've done it all for v4 already, it doesn't seem like a sensible use of time to be honest. As I'm looking to wind-down v3 issues I'm going to close this one off, but thank you for the input all the same.
