### ISSUE TITLE
camera.dirty flag is always true inside Phaser.Tilemaps.TilemapLayer.cullCallback

### ISSUE THREAD

**Issue by Waclaw-I** [phaserjs/phaser#6088]
## Version

* Phaser Version: v3.55.2

* Operating system: Windows 10 / WSL2

* Browser: Not browser specific, tested on: Chrome, Firefox

## Description

Hello! I am playing with adding my custom cullCallback for TilemapLayers, like here:
[cullCallback](https://newdocs.phaser.io/docs/3.55.2/focus/Phaser.Tilemaps.TilemapLayer-cullCallback)
I want to make use of `camera.dirty` flag but it is always true, even if nothing is happening on the screen, no camera movement etc
I figured out this is due to the camera's scrollX and scrollY fields being overwritten every frame in preRender method [here](https://github.com/photonstorm/phaser/blob/v3.16.2/src/cameras/2d/Camera.js#L755-L756) (and setting `camera.dirty` to true in setters).

## Example Test Code
[Custom CullTiles callback](https://jsfiddle.net/rfb51v6z/12/)
Uncomment `console.log` inside `customCullTiles` method to see `camera.dirty` state.

## Additional Information
Adding simple checks if values aren't the same seems to do the work.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
