### ISSUE TITLE
add image (height over 4100px) blank on Android

### ISSUE THREAD

**Issue by HZZformGD** [phaserjs/phaser#6089]
## Version

* Phaser Version: 3.55.2

* Operating system: Android 10

* Browser:  Chrome 78.0.3904.96

## Description

I loaded an image (height over 4100px, url is https://xiziyun-img.xizi.com/attachments/weGCQF4Ep2.jpeg) , and added it to the scene. I got nothing on my Android phone.  But it is successful  if i added an image (less than 4100px, for example 4000px ) . it is so weird. (ps: forgive my poor English)

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var image;
var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('einstein', 'https://xiziyun-img.xizi.com/attachments/weGCQF4Ep2.jpeg');
}

function create ()
{
    image = this.add.image(0, 0, 'einstein');
}

function update ()
{
}


```

**Comment by orjandh** [comment]
This is most likely due to the maximum texture size on your GPU. You can find this value from a scene using this.renderer.getMaxTextureSize(); or by checking the specs on your device. To mitigate this you can split your image up in multiple parts.

**Comment by HZZformGD** [comment]
> This is most likely due to the maximum texture size on your GPU. You can find this value from a scene using this.renderer.getMaxTextureSize(); or by checking the specs on your device. To mitigate this you can split your image up in multiple parts.

Thx,  i found the maximum is 4096. But how to split my image up in multiple parts ? using tool(like photoshop or other tools) to split and render them or phaser has some Api to do this? I'm a starter. ^_^

**Comment by photonstorm** [comment]
@HZZformGD you need to split it up _before_ it is loaded into Phaser, it can't be done at runtime. So yes, a tool like Photoshop would be just fine.

**Comment by HZZformGD** [comment]
> @HZZformGD you need to split it up _before_ it is loaded into Phaser, it can't be done at runtime. So yes, a tool like Photoshop would be just fine.

Ok, i Got it
