### ISSUE TITLE
key.enabled = false losing effect when changing window/tab

### ISSUE THREAD

**Issue by descodifica** [phaserjs/phaser#6098]
I use 'this.input.keyboard.keys[key.keyCode].enabled = false'' to disable control keys while the user types in a text field.

It works, but when I change the OS window or the browser tab, when I return to the game it becomes active again, even if I run the command 'this.input.keyboard.keys[key.keyCode].enabled = false'

How to ensure that the key remains inactive?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
