### ISSUE TITLE
Alpha property for tintFill

### ISSUE THREAD

**Issue by orcomarcio** [phaserjs/phaser#6101]
At the moment **tintFill** in **GameObject** it's either on or off.

I'd likean **alpha value** property for the tintFill to manipulate it's strenght. It would be very useful to create flash effects and similar things.

**Comment by osabol** [comment]
hello, id like to work on this. I do use Phaser in work but this is also part of school assignment

**Comment by osabol** [comment]
!assign

**Comment by photonstorm** [comment]
Sorry, but I don't want this feature added to Phaser 3. While I appreciate it would be useful, it would also require adding yet another piece of data to the vertex buffer, which every Game Object would have to pay the cost of, even though it's likely only to be used very rarely. I think this feature is best served via a custom shader / pipeline, so only those Game Objects that require it have to pay the cost of it.
