### ISSUE TITLE
Delay in dom element click event

### ISSUE THREAD

**Issue by meet-logicwind** [phaserjs/phaser#6105]
## Version

* Phaser Version: 3.55.2

* Operating system: Chrome Browser

* Browser:

## Example Test Code

I created a game which has a fixed resolution of 1920x1080. The game will be centred on the screen as I keep the mode to FIT and autoCenter to TRUE. I want the click event when the user clicks on the outside game canvas.

window.addEventListener("click", () => {
   // some funtion
});

var canvas = document.getElementById("phaser-app")
canvas.addEventListener('click', somefunction);

phaser-app is a div parent in which the game is being rendered. Above both are working fine but with a delay. I don't know why I'm getting a delay whenever I call the function from the above 2 functions. I'm using the scene's input pointerdown function which is working fine.

As this is client work, I have sent you an email with the game link in which you can check the delay of the input.

**Comment by photonstorm** [comment]
Phaser already creates a listener on the window for 'outside the canvas' events, specifically for this reason. They could possibly be conflicting. Or it could just be something in your app causing the delay. I assume you've profiled it with dev tools, etc?

**Comment by meet-logicwind** [comment]
> Phaser already creates a listener on the window for 'outside the canvas' events, specifically for this reason. They could possibly be conflicting. Or it could just be something in your app causing the delay. I assume you've profiled it with dev tools, etc?

@photonstorm Thank you for the information. After debugging I found that I was using the click event of the window instead of pointerdown.
