### ISSUE TITLE
Usage description of CHANGE_DATA_KEY event in the docs is wrong.

### ISSUE THREAD

**Issue by christian-post** [phaserjs/phaser#6113]
## Version
* Phaser Version: latest

## Description

https://newdocs.phaser.io/docs/3.55.2/Phaser.Data.Events.CHANGE_DATA_KEY

The docs for the CHANGE_DATA_KEY event are describing the usage as:
>So, to listen for the change of a specific data item from a Game Object you would use: sprite.data.on('changedata-key', listener), where key is the unique string key of the data item. For example, if you have a data item stored called gold then you can listen for sprite.data.on('changedata-gold').

However, this doesn't work. You either have to use `sprite.data.events.on` or simply `sprite.on` to listen to this event.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
