### ISSUE TITLE
TileSprite frame size

### ISSUE THREAD

**Issue by ddanushkin** [phaserjs/phaser#6116]
## Version
* Phaser Version: 3.55.2

## Description
Wrong frame size for trimmed atlas frames
Two gameobject, one on top of another
Tinted is Image
White is TileSprite
As you can see, TileSprite rendered without offsets, while Image rendered fine.

![image](https://user-images.githubusercontent.com/42466730/168846170-f60699d6-da53-42bb-a4c7-4d83c239677b.png)
![image](https://user-images.githubusercontent.com/42466730/168846311-bae74116-2352-4a2a-8a26-d506989c4e4e.png)

Maybe i am wrong and this is normal behaviour for TileSprite?)

## Example Test Code
```
  const image = this.add.image(0, 0, Atlas.Key, Atlas.Pattern).setTint(0xFF00FF);
  const tileSprite = this.add.tileSprite(0, 0, image.displayWidth, image.displayHeight, Atlas.Key, Atlas.Pattern).setAlpha(0.75);
  
  image.setInteractive()
  this.input.enableDebug(image);
  
  tileSprite.setInteractive()
  this.input.enableDebug(tileSprite);
```

**Comment by photonstorm** [comment]
You are correct, in that the TileSprite ought to take the trim into account when making its internal texture. However, as it has always worked like this, I'm reluctant to change it now - as it would be a visual breaking change that could be confusing. I think I'd rather wait until we swap out the TileSprite for a shader-based version in a new release.
