### ISSUE TITLE
Mistake in provided example in tutorial

### ISSUE THREAD

**Issue by ColombusAH** [phaserjs/phaser#6118]
## Version
* Phaser Version: Phaser v3.55.2 

* Operating system: mac 0S

* Browser: chrome

## Description

In the provided example (http://phaser.io/tutorials/making-your-first-phaser-3-game/part8)
we make use of child.setBounceY(Phaser.Math.FloatBetween(0.4, 0.8)) that cause an error , the example should be (if i not wrong)
in the creation of the group as follow (respecting the example ):

## Example Test Code

for all the group :
this.stars = this.physics.add.group({
      key: 'star',
      repeat: 11,
      setXY: { x: 12, y: 0, stepX: 70 },
      bounceY: Phaser.Math.FloatBetween(0.4, 0.8),
    });

for each :
    this.stars = this.physics.add.group({
      key: 'star',
      repeat: 11,
      setXY: { x: 12, y: 0, stepX: 70 },
    });
    this.stars.children.each(child => child.body.gameObject.setBounceY(Phaser.Math.FloatBetween(0.2, 0.8 )))

**Comment by samme** [comment]
```js
stars.children.iterate(function (child) {
  //  Give each star a slightly different bounce
  child.setBounceY(Phaser.Math.FloatBetween(0.4, 0.8));
});
```

is correct.

If you're getting a TypeScript error then you should use a type assertion.

```ts
(child as Phaser.Physics.Arcade.Sprite).setBounceY(/*…*/);
```
