### ISSUE TITLE
Possible Bug?? 

### ISSUE THREAD

**Issue by jcoppage** [phaserjs/phaser#6126]
The below line of code does NOT produce an error.  BUT it causes the physics system to not work properly while the game is running.  Collisions between other game objects stop working properly, which have nothing to do with the light object.
``` 
this.energyBlastLight = this.scene.lights.addLight(this.x, this.y, 500, 0x037EFC, 5 );
this.scene.physics.world.enable(this.energyBlastLight) // <----- THIS LINE
```

**Comment by samme** [comment]
It will spoil the collision tree.

Maybe `world.enableBody()` should reject objects with `body === undefined`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
