### ISSUE TITLE
Phaser 3 + MatterJS - how to set matterJS config to wireframes: false?

### ISSUE THREAD

**Issue by peteroravec** [phaserjs/phaser#6129]
There is no option to set wireframes: false for matterJS when using in Phaser 3. 
This will cause bug when render fillColor is ignored.

**Comment by photonstorm** [comment]
Are you sure? Please show some code demonstrating this, because the `wireframe` option is only part of the Matter Renderer class, which Phaser doesn't use at all.

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.
