### ISSUE TITLE
Input events are not typed correctly ('any', instead of 'string')

### ISSUE THREAD

**Issue by florestankorp** [phaserjs/phaser#6136]
## Version

* Phaser Version: 3.55.2
* Operating system: macOS Monterey 12.4

## Description

When trying to use the types for events I'm getting errors that the type is `any`, this should be fixed to `string`

## Example Test Code
![image](https://user-images.githubusercontent.com/22404695/172630003-f21564ba-3a28-458b-bcaf-10ea16e8d7d2.png)

**node_modules/phaser/types/phaser.d.ts**
```
const POINTER_MOVE: any;
const POINTER_UP: any;

```

**Comment by photonstorm** [comment]
This is only an issue in strict mode. However, we have set all events to have a type of string in 3.60 Beta 11.
