### ISSUE TITLE
Tilemap objects property is not always an array (as it is typed)

### ISSUE THREAD

**Issue by robbeman** [phaserjs/phaser#6139]
When only empty object layers are added in Tiled, this is an empty object instead of an empty array.

https://github.com/photonstorm/phaser/blob/1a086fc57c8faa53885fd1a4e20d617b958d3677/src/tilemaps/Tilemap.js#L260

Suggested solution:
```js
  this.objects = Array.isArray(mapData.objects) ? mapData.objects : [];
```

Maybe a little short-sighted? On the other hand, my game crashed because I relied on the type comment.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
