### ISSUE TITLE
Add generic types to setData()

### ISSUE THREAD

**Issue by florestankorp** [phaserjs/phaser#6140]
**The problem:**
At the moment `Phaser.GameObjects.GameObject.setData()` is typed as follows:
```typescript
setData(key: string | object, data?: any): this;
```

This results in situations that might be undesirable and prone to errors

![image](https://user-images.githubusercontent.com/22404695/173121760-60d4f2c3-60e0-41eb-865b-073bf4f16491.png)

**A possible solution:**
By adding generic types to the `setData` method developers can make sure they only pass in the intended values like so:
1. First we modify the type definition
**phaser.d.ts**
```typescript
setData<T>(key: string | T, data?: T): this;
```

2. Then we define an interface for the data we want to pass to our GameObject
```typescript
export interface ParallaxSettings {
    target: number;
    speed: number;
}
```

3. Now we can pass a type to out data and make sure it only accepts the desired type
```typescript
sprites.dreamer.setData<ParallaxSettings>({
    target: 156,
    speed: 0.4,
});
```

**TypeScript throws an error**

![image](https://user-images.githubusercontent.com/22404695/173124055-306e3448-e253-46c6-ab3c-ba759c817fa1.png)

![image](https://user-images.githubusercontent.com/22404695/173124138-1bc8de9b-1fcb-45f3-ab2e-c1a28eb6d436.png)

**Backwards compatibility**
Just use `any` 👍 

![image](https://user-images.githubusercontent.com/22404695/173124374-10ef51f7-4e02-40a3-b1f1-c7b18f1b0b19.png)

**[Optional] Do you want to help provide this feature?**

Sure. Let me know if this is something that would help the project and I can submit a PR...

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
