### ISSUE TITLE
GLOBAL_COMPLETE event on sound manager

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6147]
It would be nice if there was an event that fired when all currently playing sound have completed playback. There is the COMPLETE event, but it only works if you have references to the sound objects.

**Comment by photonstorm** [comment]
I've been thinking about this, and I'm struggling to find a use case for it. However, I have added `getAllPlaying` which will return an array of sounds, which you could then iterate and add COMPLETE listeners for.
