### ISSUE TITLE
ASTC texture doesn't work

### ISSUE THREAD

**Issue by Merfyn007** [phaserjs/phaser#6150]
Hello

The compression texture ASTC doesn't work, this is my code from beta 9:
```

       this.load.texture('fighter_v-300', {
            'ASTC': 'assets/test.pvr'
        });
```

It shows this message: 

```
No supported compressed texture format or IMG fallback mySprite
phaser.js:112656
```

I tried ASTC compression with PVRTexTool, "TexturePacker" and "astcenc", nothing work.

Thanks.

**Comment by photonstorm** [comment]
What browser / platform did you test this on? ASTC is for mobile device GPUs, it won't work on Windows, for example.

**Comment by Merfyn007** [comment]
> What browser / platform did you test this on? ASTC is for mobile device GPUs, it won't work on Windows, for example.

Ok i see.

What is the best alternative to ASTC for Desktop ? because i lose too much quality using DXT5/BC3 algorithm but the others aren't working.

Thanks.
