### ISSUE TITLE
The GO Polygon is missing a method for adding points

### ISSUE THREAD

**Issue by PhaserEditor2D** [phaserjs/phaser#6151]
Hi!

The `Phaser.GameObjects.Polygon` shape is missing a method for changing the points. It only allows setting the points in the constructor.

I think it could provide a method like the [Triangle.setTo(...)](https://github.com/photonstorm/phaser/blob/fed73569b0cbe9cfc1d2dc562afdb83791366f08/src/gameobjects/shape/triangle/Triangle.js#L96), for changing the underlying polygon's geom.

I can try implementing it the same way is implemented in the Triangle.

**Comment by photonstorm** [comment]
Ok, give the 3.60 version a go and see if it works out for you please.

**Comment by PhaserEditor2D** [comment]
Yes, it works! Thanks Richard!
