### ISSUE TITLE
Customizing Text shadow alpha

### ISSUE THREAD

**Issue by robinheidrich** [phaserjs/phaser#6154]
It would be great if you could set the alpha for text shadows yourself. Currently you can only set the blur and the higher it is, the lower the alpha becomes.

My problem is that I have a small text and you can hardly see the shadow because the alpha is so low.

Any chance this could be added to Phaser?

**Comment by vforsh** [comment]
you can do it using rgba format or any other [css color formal](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)
`this.text.setShadow(0, 3, "rgba(0,0,0,0.5)", 0)`

**Comment by robinheidrich** [comment]
This only changes the color and not the shadow's alpha. Even with `rgba(0,0,0,1)` it is still not visible enough.

**Comment by photonstorm** [comment]
The Canvas API only provides the following shadow options:

```js
context.shadowOffsetX = this.shadowOffsetX;
context.shadowOffsetY = this.shadowOffsetY;
context.shadowColor = this.shadowColor;
context.shadowBlur = this.shadowBlur;
```

and you can set all of these via the Text style functions, there's nothing further that can be added I'm afraid.
