### ISSUE TITLE
RenderTexture.fill appears to be broken

### ISSUE THREAD

**Issue by monteiz** [phaserjs/phaser#6159]
## Version

* Phaser Version:
3.55.2
* Operating system:
MacOS 10.14.6
* Browser:
Chrome Version 103.0.5060.53 (Official Build) (x86_64)

## Description

The [RenderTexture.fill](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.RenderTexture.html#fill__anchor) method seems to be broken.

In the [method's code](https://github.com/photonstorm/phaser/blob/v3.51.0/src/gameobjects/rendertexture/RenderTexture.js#L482) every color component is divided by 255, which result in always having a near to black color:
``` js
        var r = (rgb >> 16 & 0xFF) / 255;
        var g = (rgb >> 8 & 0xFF) / 255;
        var b = (rgb & 0xFF) / 255;
```
So if I pass 0xffffff, the result is `r = 1`, `g = 1`, `b = 1`. The result is black.

## Example Test Code
[https://jsfiddle.net/u5cogvzy/1/](https://jsfiddle.net/u5cogvzy/1/)

**Comment by rgk** [comment]
You have to render as WebGL.
In your config change Phaser.CANVAS to Phaser.WEBGL.

**Comment by monteiz** [comment]
I wish I could do that (also to benefit from the other WEBGL features), but WEBGL has not the same performance as CANVAS on mobile (and on desktop in fullscreen).

Anyway it should not be a method exclusive to WEBGL, since it was working on older version of Phaser even with the CANVAS render.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG-v3.60.md).
