### ISSUE TITLE
Pointer downX and downY not updated on right mouse click

### ISSUE THREAD

**Issue by Kosmoon** [phaserjs/phaser#6161]
## Version

3.55.2

## Description

You can test in the example i provided bellow that clicking with the left mouse populates correctly downX and downY but it's not the case when clicking with mouse right.

## Example Test Code

https://codesandbox.io/s/phaser-3-template-forked-5in2cg?file=/index.js

**Comment by photonstorm** [comment]
This is correct, as per the documentation: "X coordinate of the Pointer when Button 1 (left button), or Touch, was pressed, used for dragging objects."
