### ISSUE TITLE
[v3.54.0 - Tweens] Tween pause and resume doesn't work well

### ISSUE THREAD

**Issue by trynx** [phaserjs/phaser#6169]
## Version

* Phaser Version: 3.54.0

## Description

When initializing a tween, then do `.pause()`, and after some time(seconds-minutes) I call on that tween `.resume()`, it doesn't work... if I do `.pause()` and pretty immediately I do `.resume()`, it will work, even if I paused it and resume after some seconds-minutes.

If doing `paused: true` on the config, and then do resume after some time, it does work well.

## Example Test Code
```
// Create tween...
tween.pause();

//... wait a few seconds

tween.resume();

// It won't show, maybe it was GC?
```

## Additional Information

It works well if doing:
```
// Create tween...
tween.pause();
tween.resume();

//... wait a few seconds
tween.pause();

//... wait a few seconds
tween.resume();
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
