### ISSUE TITLE
Error stopping a scene: cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by evan-boissonnot** [phaserjs/phaser#6171]
## Version
* Phaser Version:
"phaser": "^3.55.2",

* Operating system:
Windows 10

## Description
Issue already exists and seems to be closed and merge in the 3.55.3 ...
but I have got the same issue like 
https://github.com/photonstorm/phaser/issues/5520

I got this error on console : 
phaser.js:166925 Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')
    at DisplayList.shutdown (phaser.js:166925:1)
    at EventEmitter.emit (phaser.js:1928:1)
    at Systems.shutdown (phaser.js:49454:1)
    at SceneManager.stop (phaser.js:100949:1)
    at SceneManager.processQueue (phaser.js:100024:1)
    at SceneManager.update (phaser.js:100278:1)
    at Game.step (phaser.js:162805:1)
    at TimeStep.step (phaser.js:89366:1)
    at step (phaser.js:89613:1)

## Example Test Code

I have just use : 
this.scene.start("loadingscene", { key: key });

when I see the code in phaser.js, the algo is not good.
because each element is destroyed and the loop is i--, there will necesary a prob.

better to use the solution.
while(list.length) {
  list[0].destroy(true);
}

## Additional Information
why don't I got the correct ?

in the 5520 it says it will be on the next MR ... but it's not :(
https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md

**Comment by photonstorm** [comment]
As I replied in #5520 - this fix is already merged in the master branch, so is part of any 3.60 Beta release.
