### ISSUE TITLE
this.add.rectangle is not a function

### ISSUE THREAD

**Issue by aderchox** [phaserjs/phaser#6175]
## Version

* Phaser Version: 3

* Operating system: Windows 10

* Browser: Chrome

## Description

Adding this to my create function:
```js
  this.add.rectangle(400, 300, 400, 300, 0xff0000);
```
causes the rest of my code not to work and also the rectangle itself is not drawn too. It seems that adding the above line anywhere in my code causes a freeze in my game. Checking the console, I see this error:
> this.add.rectangle is not a function.

`this.add` gives a GameObjectFactory and the GameObjectFactory class has a [rectangle method](https://newdocs.phaser.io/docs/3.52.0/Phaser.GameObjects.GameObjectFactory#rectangle) so this must work.

## Example Test Code

```js
        function create() {
            this.add.rectangle(400, 300, 400, 300, 0xff0000);
            //...
       }
```

## Additional Information

For the easiest reproduceability, you could just try adding a rectangle in the Phaser website's [starter project](https://phaser.io/tutorials/making-your-first-phaser-3-game/part10) code.

**Comment by photonstorm** [comment]
Exactly which version of Phaser are you using? Because it's almost certainly an early release that doesn't have this feature.

**Comment by photonstorm** [comment]
This feature was added in Phaser 3.13. Make sure you're using this version or above, or it won't work.
