### ISSUE TITLE
Audio and SpriteAudio are internally the same

### ISSUE THREAD

**Issue by lukasharing** [phaserjs/phaser#6183]
By looking at the cache, `Audio` and `SpriteAudio` are stored the same way. I suggest to add a flag to know what type of element is inserted. That should make `sound.addAudioSprite` be unifiable with `sound.add`, making `sound.add` branching depending on that flag

**Comment by photonstorm** [comment]
Having looked at this, you can detect it by checking for the existence of the `BaseSound.spritemap` property. If it exists, it's an `AudioSprite`.
