### ISSUE TITLE
geometryMask from createGeometryMask() returns undefined in phaser@3.60.0-beta.9

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6186]
## Version

* Phaser Version: phaser@3.60.0-beta.9

* Operating system: Win10

* Browser: Firefox

## Description

geometryMask from createGeometryMask() returns undefined.

You can use following labs code (just run in it 3.60.0-beta.9):
http://labs.phaser.io/edit.html?src=src/display\masks\geometry%20mask\multiple%20image%20mask.js

## Example Test Code

Apart from the above link, you can also create new project and place following code into create() method of a new/empty scene:
```ts
const contentMaskGraphics = this.make.graphics({});
contentMaskGraphics.fillStyle(0xffffff);
contentMaskGraphics.beginPath();
contentMaskGraphics.fillRect(50, 0, 50, 300);
contentMaskGraphics.fillRect(175, 0, 50, 300);
contentMaskGraphics.fillRect(0, 75, 275, 50);
contentMaskGraphics.fillRect(0, 200, 275, 50);
const mask = contentMaskGraphics.createGeometryMask();

// traces:
// Object { geometryMask: undefined, invertAlpha: false, isStencil: true, level: 0 }
console.log(mask);
```
## Additional Information

Tested: works ok in Phaser 3.24.1

**Comment by rexrainbow** [comment]
I run this code in `Phaser v3.60.0-beta.10-FB (WebGL | Web Audio)`, `Phaser v3.60.0-beta.10-FB (Canvas | Web Audio)`
and get result
```
GeometryMask {geometryMask: Graphics, invertAlpha: false, isStencil: true, level: 0}
```
It seems correctly.

**Comment by michalfialadev** [comment]
> I run this code in `Phaser v3.60.0-beta.10-FB (WebGL | Web Audio)`, `Phaser v3.60.0-beta.10-FB (Canvas | Web Audio)` and get result
> 
> ```
> GeometryMask {geometryMask: Graphics, invertAlpha: false, isStencil: true, level: 0}
> ```
> 
> It seems correctly.

thanks im a noob i just get npm/yarn beta.9, unsure where you got beta 10, cant npm/yarn it, so it was prob resolved already, thanks for feedback tho!

imma close this then and reopen later if still an issue.

**Comment by michalfialadev** [comment]
closing as completed for now
