### ISSUE TITLE
Scene "ready" event not emitted in Phaser3

### ISSUE THREAD

**Issue by keshav2010** [phaserjs/phaser#6189]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 11

* Browser: On All Browsers

## Description
The scene's "ready" event listener is not being invoked.

## Example Test Code
```
export class ResultScene extends BaseScene {
    constructor(){
        super(CONSTANT.SCENES.RESULT)
    }

    init(){
    }
    create() {

        this.events.on("ready", () => {
            this.markSceneAsActive();
        });
        this.events.on('shutdown ', (data)=>{
            console.log('shutdown ', data.config.key);
            this.events.removeAllListeners();
        })
    }
    preload(){

    }
}
```
When i start this scene or launch it from another Scene like this
`this.scene.start(CONSTANT.SCENES.RESULTSCENE);`
 the markSceneAsActive function is not invoked.

**Comment by samme** [comment]
The 'ready' event is fired before the scene's `init()` and `create()` methods.
