### ISSUE TITLE
`VIDEO_COMPLETE` event does not fire when video has finished playing. 

### ISSUE THREAD

**Issue by dino8890** [phaserjs/phaser#6192]
## Version

* Phaser Version: 3.55.2

* Operating system: Solus Linux 4.3

* Browser:  Firefox 103.0.2 and Google Chrome 101.0.4951.64

## Description

`VIDEO_COMPLETE` event does not fire when video has finished playing. The video itself plays until the end as expected, but it seems the event is never fired, and consequently the assigned handler is not executed.

## Example Test Code

```js
// MP4 file is loaded under `video` key.
let video = this.add.video(this.cameras.main.centerX, this.cameras.main.centerY, 'video');
video.on('complete', (video) => { console.log('Video reproduction complete.'); });
video.play();
```

## Additional Information

Somebody else experienced the same issue before, but the solution was not found. See thread below:
[https://phaser.discourse.group/t/video-event-on-complete-suddenly-stopped-working/9520](https://phaser.discourse.group/t/video-event-on-complete-suddenly-stopped-working/9520)

The forum post suggests this might occur intermittently.

**Comment by renaudcollet** [comment]
Also the setLoop(false) is not working, those are 2 very important functionality

**Comment by dino8890** [comment]
I worked around this by listening for `ended` event on the underlying `HTMLVideoElement`, e.g.:

```js
function onVideoEnd(event) { console.log('Video reproduction complete.'); }

// MP4 file is loaded under `video` key.
let video = this.add.video(this.cameras.main.centerX, this.cameras.main.centerY, 'video');
video.play();

video.video.addEventListener('ended', onVideoEnd); // should be called after play()
```

This is what the engine itself does, except that it uses `Function.prototype.bind` to set up `Video.completeHandler` which then dispatches `VIDEO_COMPLETE` event you can listen for. Why it does not work as intended is not clear to me.

**Comment by photonstorm** [comment]
The Video Game Object has been fully recoded in v3.60 and now works very differently from before, and this bug is finally no longer present in the testing we've done.
