### ISSUE TITLE
Press and hold left mouse button will not fire events when right mouse button is used

### ISSUE THREAD

**Issue by Farnsi** [phaserjs/phaser#6194]
## Version

* Phaser Version: 3.55.2

## Description

Hold down left mouse button and click once right mouse button.

The right click is not detected.

After release the right button and then left button, no event of `pointerup` is fired for left button.

## Example Test Code

Test it in the examples
https://phaser.io/examples/v3/view/input/mouse/right-mouse-button

Press & hold left key places an element, click right does than nothing.
update()-method detects the change (display rightButtonDown as text), but no event is fired.

## Additional Information

When you try it with left click and e.g. wheel click or mouse button 4, it works.

**Comment by photonstorm** [comment]
This works fine for me (Windows 11, SteelSeries mouse) as you can see in this screenshot I just took:

![image](https://user-images.githubusercontent.com/164476/185954557-b2490c1c-c5c5-47cd-a5f2-8bc0e7258127.png)

Because the blue floppy-disk image can only appear if you hold down left while clicking right. A left-click on its own places the Phaser logo image. A right click on its own places the Asuna sprite. Both together places the blue disk.

**Comment by Farnsi** [comment]
Thanks, i tested it only in vivaldi, in chrome it works. So it is a browser problem.
Have to switch the browser for developement.

**Comment by photonstorm** [comment]
It's possible Vivaldi has that combination locked for a shortcut? (or maybe a browser extension does) - but fundamentally, all I'm doing in Phaser is responding to the DOM events, but I can't do this if I don't get them, I'm afraid.

**Comment by Bgagger** [comment]
**Here is my solution to get around this limitation :**

var pinchRight = pinchLeft = pinchBoth = false;
var thingZone = this.add.zone(828, 1938).setCircleDropZone(344);
thingZone.on('pointerdown', function (pointer) {
         if (pointer.rightButtonDown() == true && pointer.leftButtonDown() == true && pinchBoth == false) {
            pinchBoth = true;
         } else if (pointer.rightButtonDown() == true && pointer.leftButtonDown() == false) {
            pinchRight = true;
            pinchLeft = false;
            pinchBoth = false;
         } else if (pointer.leftButtonDown() == true && pointer.rightButtonDown() == false) {
            pinchLeft = true;
            pinchRight = false;
            pinchBoth = false;
         }
         if (pinchBoth == true) {
            console.log("Right+Left");
            //Code that should happen when both mouse buttons are down.
         } else if (pinchLeft == false && pinchRight == true) {
            console.log("right");
            //Code that should happen when right mouse button is down.
         } else if (pinchLeft == true && pinchRight == false) {
            console.log("left");
            //Code that should happen when left mouse buttons is down.
         }
         //Note that technically right and both OR left and both will always trigger. It is impossible to detect a simultanious press of both without first detecting one or the other.
       } );
      thingZone.on('pointerup', function (pointer) {
         if (pointer.rightButtonReleased() == true) {
            pinchRight = false;
         }
         if (pointer.leftButtonReleased() == true) {
            pinchLeft = false;
         }
         if (pointer.rightButtonReleased() == true && pointer.leftButtonReleased() == true) {
            pinchBoth = false;
         }
      } );
