### ISSUE TITLE
Inaccurate typedef for TextStyle.fontSize

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6195]
## Version

* Phaser Version: 3.55.2

## Description

The typdef for TextStyle.fontSize is string (https://github.com/photonstorm/phaser/blob/v3.51.0/src/gameobjects/text/typedefs/TextStyle.js#L8). This is fine, but it also supports to be a number, as seen here (https://github.com/photonstorm/phaser/blob/v3.51.0/src/gameobjects/text/TextStyle.js#L408). Maybe the typedef should be changed to be the union of string and number so that the number argument can be used with typescript?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
