### ISSUE TITLE
removeAll() is undefined under NoAudioSoundManager

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6200]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 11

* Browser: Chrome 104

## Description

When using the NoAudioSoundManager, the removeAll function is undefined. This goes against the design of NoAudioSoundManager being a graceful degradation.

## Example Test Code

https://codepen.io/orjandh/pen/RwMmqKE

Click anywhere on the canvas and the error will trigger.

## Additional Information

This seems to also apply for sound.get().

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by samme** [comment]
For TypeScript the new methods in #6201 still need JSDocs.
