### ISSUE TITLE
Matter world bound collision not work

### ISSUE THREAD

**Issue by Farnsi** [phaserjs/phaser#6203]
## Version

* Phaser Version: 3.60.0-beta.9
* Browser: Chrome

## Description

As soon as i `setCollidesWith` the Ship moves outside the world bound and no event is fired on `collisionstart`.

Remove `setCollidesWith` and everything works fine.

Ship1 (right) move to Ship2 (left).
Ship1 thrust until it stop at world bound.
But Ship2 moves outside the bounds.

Ship3 only thrust to the left and ignores the world bound too.

## Example Test Code

[friendly-euclid-u1y8nq - CodeSandbox 2](https://codesandbox.io/s/friendly-euclid-u1y8nq?file=/main.scene.js:612-697)
(machine stuck many times for ~10 seconds, don't know why)

**Comment by photonstorm** [comment]
This is correct, you need to specify the world boundary collision mask as well as whatever other categories you want it to collide with in that `setCollidesWith` call. Calling this replaces the collision bitmask entirely, so it has to contain _everything_ you want it to collide with, not just a single item.

**Comment by Farnsi** [comment]
But why is one Item respecting the world bound and the others not?

And how can i set the collide with "world bound"?

A collisionstart event is not fired, i can not detect it.

**Comment by photonstorm** [comment]
Because `COLL_PLAYER` was set to 1, which is the same category as the World bounds, so anything using this category in its mask will still collide with the world bounds. Change your categories to 2 and 4, for example, and nothing will collide with the bounds any more.
