### ISSUE TITLE
tiledmap 什么时候才能支持外部资源呢

### ISSUE THREAD

**Issue by woshisheji** [phaserjs/phaser#6209]
现在每次都提示 资源没法外置 External tilesets unsupported. Use Embed Tileset and re-export

可以如下使用吗
    "orientation": "isometric",
    "renderorder": "left-up",
    "tileheight": 47,
    "tilesets": [
        {
            "firstgid": 1,
            "source": "mapData\\1011\\1011_tile.json"
        },
        {
            "firstgid": 1000,
            "source": "mapData\\1011\\1011_obj.json"
        }
    ],
    "tileversion": "1.2.2",
    "tilewidth": 64,
    "type": "map",
    "version": 1.2,
    "width": 30

////////////////
    "tiles": [
        {
            "id": 0,
            "image": "tile/1166_palet_00.cgp_6747.png",
            "imageheight": 47,
            "imagewidth": 64
        },
        {
            "id": 1,
            "image": "tile/1167_palet_00.cgp_6748.png",
            "imageheight": 47,
            "imagewidth": 64
        },
        {
            "id": 2,
            "image": "tile/1168_palet_00.cgp_6749.png",
            "imageheight": 47,
            "imagewidth": 64
        },

**Comment by photonstorm** [comment]
Hi - could you please describe the issue in English? I'm afraid I'm unable to read any other languages.

If, however, the issue is that you cannot use external tilesets - this is correct and not a bug. It's just how the tilemap system works.

**Comment by woshisheji** [comment]
The map editor supports the use of external resources by objects. Phaser not support this? Will this function be updated

**Comment by DevenWen** [comment]
@woshisheji You should check the “embed in map” when you new a tileset. And Phaser still  unsupport to load the Image in the tiled map json. Maybe there isn't a way to load the Collection-Of-Images tileset, isn't it? is It possible to add an example  for it? @photonstorm

**Comment by woshisheji** [comment]
例如：


&nbsp;"tilesets": [
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "firstgid": 1,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "source": "mapData\\1150\\1150_tile.json"
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "firstgid": 1000,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "source": "mapData\\1150\\1150_obj.json"
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; ],



//在引用其他Json时候内容
&nbsp;"margin": 0,
&nbsp; &nbsp; "name": "1150_obj",
&nbsp; &nbsp; "spacing": 0,
&nbsp; &nbsp; "tilecount": 34,
&nbsp; &nbsp; "tiledversion": "1.2.2",
&nbsp; &nbsp; "tileheight": 185,
&nbsp; &nbsp; "tiles": [
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "id": 0,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "image": "obj/10026_palet_00.cgp_7777.png",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imageheight": 95,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imagewidth": 40
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "id": 1,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "image": "obj/10027_palet_00.cgp_7778.png",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imageheight": 102,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imagewidth": 64
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "id": 2,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "image": "obj/10493_palet_00.cgp_7694.png",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imageheight": 87,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imagewidth": 64
&nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "id": 3,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "image": "obj/10503_palet_00.cgp_7704.png",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imageheight": 163,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "imagewidth": 84
&nbsp; &nbsp; &nbsp; &nbsp; },

&nbsp;


Www.55IDE.Com
***@***.***

55IDE官方
开发者


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Deven ***@***.***&gt;; 
发送时间: 2022年11月1日(星期二) 晚上11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [photonstorm/phaser] tiledmap 什么时候才能支持外部资源呢 (Issue #6209)






@woshisheji您应该在新建图块集时检查“嵌入地图”。并且 Phaser 仍然不支持在平铺地图 JSON ***@***.***

-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您被提及。Message ***@***.***与&gt;

**Comment by samme** [comment]
```js
function preload() {
  this.load.tilemapTiledJSON(
    "map",
    "assets/tilemaps/maps/multi-tileset-v12.json"
  );

  this.load.once(
    "filecomplete-tilemapJSON-map",
    function (key, type, data) {
      this.load.setPath("/assets/tilemaps/maps/");

      for (var tileset of data.data.tilesets) {
        this.load.image(tileset.name, tileset.image);
      }
    },
    this
  );
}
```

- [Load tileset images from tilemap](https://codepen.io/samme/pen/ZEvdzMe)
