### ISSUE TITLE
Cursor change to pointer, if using a PNG

### ISSUE THREAD

**Issue by Farnsi** [phaserjs/phaser#6210]
## Version

* Phaser Version: 3.55.2

## Description

If you use a png file as a cursor and move to the right / bottom border the cursor change to system default pointer.
The larger the image is, the wider is the border.

Not 100% a bug, cause cursor-files are normally .cur and not gif / png, but i think they should work as png too.

## Example Test Code

https://codesandbox.io/s/nifty-cloud-f9lou9?file=/src/Boot.js:187-199

**Comment by photonstorm** [comment]
That's just how the browser works, this isn't a Phaser setting, I'm afraid - all Phaser does is set a bit of CSS on the canvas, the browser controls when it no longer considers it applicable or not.
