### ISSUE TITLE
Depth sorting and rendering optimizations

### ISSUE THREAD

**Issue by JernejHabjan** [phaserjs/phaser#6215]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 11 (OS build 22000.856)

* Browser: Chrome Version 105.0.5195.102 (Official Build) (64-bit)

## Description

Hello,
I've discovered that depth sorting is running slow when rendering large number of sprites. Situation doesn't improve if sprite is not on the screen.

### Depth sorting:
I've first seen this issue when running [this game](https://github.com/neki-dev/izowave).
![image](https://user-images.githubusercontent.com/21958321/189166251-7f78f0f9-638e-4462-abf7-df23f2a095a9.png)

I've confirmed this also with following example:
http://labs.phaser.io/view.html?src=src/depth%20sorting/Depth%20Sorting.js&v=3.55.2
- Steps: 
  - Increased for loop from 2000 to 20_000

The performance drops because of depth sorting:
![image](https://user-images.githubusercontent.com/21958321/189166691-7173cd0f-f528-453a-8721-6bd74115633b.png)

Performance of stable sort may be the problem here.
I've "updated" the depthSort function like this:
```javascript
if (this.sortChildrenFlag)
{
    StableSort = (list, fn) => list.sort(fn); // note this override with native JS fn
    StableSort(this.list, this.sortByDepth);

    this.sortChildrenFlag = false;
}
```
And results:
![image](https://user-images.githubusercontent.com/21958321/189167242-9c7c7697-2eea-4065-b613-a626dd79b2cd.png)
Results look much better, but sorting may not be correct - right?

Is there a way we could improve this StableSort?
It seems that JS sort is [stable since ECMA 2019](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#sort_stability), and [twitter post](https://twitter.com/mathias/status/1036626116654637057) with [example](https://mathiasbynens.be/demo/sort-stability)

### Rendering:
I've also updated same [example](http://labs.phaser.io/view.html?src=src/depth%20sorting/Depth%20Sorting.js&v=3.55.2) with for loop like this
```javascript
for (let i = 0; i < 20000; i++)
{
    const image = this.add.image(100 + Math.random() * 6000, 100 + Math.random() * 4000, 'atlas', 'veg0' + Math.floor(1 + Math.random() * 9));
    image.depth = image.y;
}
```
Note that many of sprites won't be visible in camera, so they wouldn't need to be rendered - right?

But by checking `renderer` function, I see that `visibleChildren` count doesn't change, whether all sprites are visible on screen or not:
```javascript
var visibleChildren = this.getVisibleChildren(displayList.getChildren(), camera);
// visibleChildren.length -> this returns 20003
```
Is there a way these sprites can be occluded? 

I am just trying to create new isometric RTS game, where medium-sized grid can be used, and is only partially visible in the camera. So in this case, I have issues with depth sorting slowing down the game, plus renderer taking all sprites into account, and not only ones visible on camera.
Is there a way I can bypass these issues somehow?

**Comment by samme** [comment]
You should probably cull objects outside the camera viewport (toggling `visible`). Phaser doesn't do this itself.

**Comment by photonstorm** [comment]
Ok, please test the new StableSort I've put into the master branch (you'll need to do a Beta 11 build to get it, `npm run dist` will create that) - as for camera occlusion, that is out of scope for the v3 renderer, so you'll need to figure out a way to do this for your use-case I'm afraid.

**Comment by JernejHabjan** [comment]
@photonstorm fyi

For repo [Izowave](https://github.com/neki-dev/izowave) this greatly improves performance:

v3.55
avg depth sort:
**95ms** (on 200 tile width* 200 tile height map)

v3.6 beta 11 (self-built)
avg depth sort:
**20.8ms** (on 200 tile width* 200 tile height map)
