### ISSUE TITLE
Timer add event with loop and no delay

### ISSUE THREAD

**Issue by JernejHabjan** [phaserjs/phaser#6225]
## Version

* Phaser Version: 3.6.0.beta.1-beta.10

* Operating system: Windows 11

* Browser: Chrome 105

## Steps to reproduce
```javascript
this.time.addEvent({ loop: true });
```

This will create timer and trigger it constantly, as there is no delay defined

solved with:
```javascript
this.time.addEvent({ loop: true, delay: 1000  }); // update every second
```

Maybe it'd be wise to add some assert if loop is true, to make sure that some delay is provided as well. Otherwise all resources are consumed as event is looping constantly.

This issue occured after updating from 3.55.2 to 3.60.beta.1

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by JernejHabjan** [comment]
works great. Thanks
![image](https://user-images.githubusercontent.com/21958321/193449852-e5005661-7e1c-4427-b82b-56e50e563d2b.png)
