### ISSUE TITLE
Generic groups and enemies

### ISSUE THREAD

**Issue by JernejHabjan** [phaserjs/phaser#6226]
### Possible implementation
```javascript
const enemies: Phaser.GameObjects.Group<Enemy> = [];
enemies = this.add.group<Enemy>({
  classType: Enemy,
  runChildUpdate: true,
});
```

and then with iterator:
```javascript
enemies.children.iterate((enemy)=>{
  // enemy is of type GameObject<Enemy>
});
```

Make sure that type is optional
```javascript
group<T=any>(children?: Phaser.GameObjects.GameObject<T>[] | Phaser.Types....
```
and game object
```javascript
class GameObject<T=any> extends Phaser.Events.EventEmitter {
```

### The recommendation was discovered here:
Currently with 3.60.beta10 I get this issue:
![image](https://user-images.githubusercontent.com/21958321/191822072-8cc00aac-3c31-4349-9ac2-1d22155acd87.png)

It is solved, if I return back boolean, but boolean here makes no sense to me:

![image](https://user-images.githubusercontent.com/21958321/191822177-4ddd45aa-ecb5-4fe9-9500-aa60b208d020.png)

**Comment by photonstorm** [comment]
`iterate` expects the callback to provide a boolean. If it returns `false` the Set iteration is aborted immediately and no further children are processed. If it returns `true` it carries on.
