### ISSUE TITLE
Warning on initialization after Chrome 106 update

### ISSUE THREAD

**Issue by danikaze** [phaserjs/phaser#6231]
## Version

* Phaser Version: 3.55.2
* Operating system: Windows 10
* Browser: Chrome 106.0.5249.62 (Official Build) (64-bit)

## Description

Chrome shows the following warning on initialization:
> Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

## Example Test Code

Just including phaser triggers this on `init()`
Is reproducible in [any example](https://phaser.io/examples/v3/view/game-config/banner-colors).

**Comment by photonstorm** [comment]
Yes, this is already fixed in 3.60. However, Chrome isn't smart enough to remove both warnings, just the first one, even though we added the required attribute to both canvas elements we create in the Device class.
