### ISSUE TITLE
getBounds() does not detect BitmapText size in Container

### ISSUE THREAD

**Issue by likwidgames** [phaserjs/phaser#6237]
## Version

* Phaser Version: 3.55.2

* Operating system: macOS Venture 13.0

## Description

Using getBounds() on a container that contains only bitmapText returns 0 for height/width. It doesn't seem to calculate the size of the text. If I replace the text with an Image instead, it calculates the height/width just fine.

After some research, it seems BitmapText has a method .getTextBounds() instead of getBounds() like Text or Sprite.

## Example Test Code

[https://codepen.io/likwidgames/pen/vYjaOoo](url)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
