### ISSUE TITLE
Hold parameter has no effect when used with non-repeating tween in 3.60.0-beta.10

### ISSUE THREAD

**Issue by jerricko** [phaserjs/phaser#6239]
## Version

* Phaser Version: 3.60.0-beta.10

* Operating system: macOS Monterey 12.6

## Description

Using the new tween system in 3.60.0-beta.10, the `hold` parameter has no effect when using `yoyo: true` and no repeating. It does work when repeating is enabled.

## Example Test Code

https://labs.phaser.io/edit.html?src=src/tweens/yoyo%20delay.js&v=dev

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by jerricko** [comment]
I can confirm that a fresh build with the latest changes fixed the issue. Thanks!
