### ISSUE TITLE
renderer.resetTextures is not a function (3.60.0-beta.11)

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6241]
## Version

* Phaser Version:
3.60.0-beta.11

* Operating system:
win10

* Browser:
firefox (latest)

## Description

Running medium-sized project (built with 3.55.2) on 3.60.0-beta.11 gives black screen console outputs following error::
Uncaught TypeError: renderer.resetTextures is not a function
    RenderTextureWebGLRenderer phaser.js:172440
    ContainerWebGLRenderer phaser.js:170326
...

## Example Test Code

project is too big, unsure where/why this happens yet. might have more time to do simple repro later if necessary (looks like something basic however and perhaps can be assumed from the error log?). Leave it open for now, if it gets no reply ill look into small repro in a week.

**Comment by photonstorm** [comment]
Closing as this was the result of a 3rd party package that isn't compatible with 3.60.
