### ISSUE TITLE
myTweenRef.stop() on 'destroyed' tween throws 'TypeError: this.callbacks is null'

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6243]
## Version

* Phaser Version:
3.60.0-beta.11

* Operating system:
any

* Browser:
any

## Description

**ISSUE**
When creating a Tween and keeping a reference, then after the tween completes and we call:
`myTweenRef.stop()`

app crashes with following error log:
`TypeError: this.callbacks is null`

**NOTES**
- There might be use-cases for calling myTween.stop() on tween that already finished, or getting better feedback from Phaser that the tween has already finished when calling this code? (maybe not; in my case i run 2 async ops in parallel so i called myTween.stop() 'just in case' it was still running while the other op finished (and tween should be stopped). This worked ok in 3.55.2, stopping the tween (if running), or ignoring the stop() call (if no more running))
- Possibly not to be handled on Phaser side. 
- Possibly to be handled by a simple boolean flag check on Phaser side and ignored (avoid error trigger). 
- Possibly show warning from Phaser side
(will let Phaser creator decide this one)

## Example Test Code

NOTE: `this.animTween` has finished at this point.
```ts
console.log(">>>")
console.log(this.animTween.isFinished());       // false
console.log(this.animTween.isActive());         // false
console.log(this.animTween.isDestroyed());      // true
console.log(this.animTween.isPending());        // false
console.log(this.animTween.isPendingRemove());  // false
console.log(this.animTween.isPlaying());        // false
console.log(this.animTween.isRemoved());        // false
console.log(this.animTween.isPaused());         // false
console.log(this.animTween.isSeeking);          // false
console.log(this.animTween.isStartDelayed());   // false
try{
    this.animTween.stop();
}
catch(e:any) {
    console.log(e);
}
```

//////////////////////////////////////
// PHASER code in question that throws
//////////////////////////////////////

```ts
dispatchEvent: function (event, callback) {
        if (!this.isSeeking) {
            this.emit(event, this, this.targets);
            // following line throws (this.callbacks is null)
            var handler = this.callbacks[callback];
            if (handler) {
                handler.func.apply(this.callbackScope, [ this, this.targets ].concat(handler.params));
            }
        }
    }
```

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser, and it will be part of the next beta release.

**Comment by photonstorm** [comment]
For the record, the `stop` method now bails if the Tween destroy state has been set. Although really if the Tween is being re-used over and over, it should be set to `persist: true` in the tween config, but this will at least stop a runtime error.

**Comment by michalfialadev** [comment]
> For the record, the `stop` method now bails if the Tween destroy state has been set. Although really if the Tween is being re-used over and over, it should be set to `persist: true` in the tween config, but this will at least stop a runtime error.

`persist: true` is the proper way to do it, thanks!
