### ISSUE TITLE
Tween with null targets throws when killTweensOf is called.

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6244]
## Version

* Phaser Version:
3.60.0-beta.11

* Operating system:
any

* Browser:
any

## Description

When trying to invoke `killTweensOf` on a target, and when `myTween.targets` are null, `myTween.hasTarget()` throws null obj ref (via killTweensOf->getTweensOf->hasTarget).
**NOTE**: Possibly tied to wrong b11 tween ref handling on my side (or a reference to destroyed tween still present in scene.tweens?)

Partial error trace
```
Uncaught TypeError: this.targets is null
    hasTarget phaser.js:218849
    getTweensOf phaser.js:214974
    killTweensOf phaser.js:215099
```
## Example Test Code

```ts
// called from within container with a fadeIn/Out Tween Mixin (`this` target)
this.scene.tweens.killTweensOf(this);
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
