### ISSUE TITLE
Bitmap mask not working in 3.60.0-beta.12

### ISSUE THREAD

**Issue by quocsinh** [phaserjs/phaser#6248]
## Version
* Phaser Version: v3.60.0-beta.12

* Operating system: Windows 11

* Browser: Microsoft Edge Version 106.0.1370.42

## Description

Bitmap mask not working. There is a warning in the console:
![image](https://user-images.githubusercontent.com/13402645/195528380-4ff45004-7a7e-49ef-9355-061ea2de2f05.png)

## Example Test Code

https://codepen.io/quocsinh/pen/YzLBwZg

## Additional Information

However, it works fine in v3.55.2
https://codepen.io/quocsinh/pen/WNJPxrP

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
