### ISSUE TITLE
Phaser.GameObjects.RenderTexture#saveTexture

### ISSUE THREAD

**Issue by x-wk** [phaserjs/phaser#6250]
## Version

* Phaser Version:
Phaser v3.60.0-beta.12 (WebGL | HTML5 Audio)
* Operating system:
win10
* Browser:
Microsoft Edge 106.0.1370.34

## Description

I upgraded to the latest version today and the first problem I encountered was that it failed to start. The reason was that RenderTexture#saveTexture failed to execute(textureManager is undefined).
```ts
Uncaught TypeError: Cannot read properties of undefined (reading 'addDynamicTexture')
    at RenderTexture.saveTexture (phaser.js:60996:1)
    ...
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
