### ISSUE TITLE
Uncaught Error: Link Shader failed - Starting with Beta 11 - on Raspberry Pi 4

### ISSUE THREAD

**Issue by chrisl8** [phaserjs/phaser#6254]
## Version

* Phaser Version: Phaser v3.60.0-beta.13 (WebGL | Web Audio)

* Operating system: Ubuntu 22.04 Linux on Raspberry Pi 4

* Browser: Chromium

## Description

Immediately upon starting Phaser I see this error:  
```
Phaser v3.60.0-beta.12 (WebGL | Web Audio)  https://phaser.io

phaser.js:168613 Uncaught Error: Link Shader failed:

     at WebGLRenderer.createProgram (phaser.js:168613:19)
     at new WebGLShader (phaser.js:169592:38)
     at MultiPipeline.setShadersFromConfig (phaser.js:164876:34)
     at MultiPipeline.boot (phaser.js:164688:14)
     at MultiPipeline.boot (phaser.js:171833:38)
     at PipelineManager.add (phaser.js:162819:22)
     at phaser.js:162682:30
     at Map.each (phaser.js:190491:17)
     at PipelineManager.boot (phaser.js:162680:22)
     at WebGLRenderer.boot (phaser.js:167515:25)
```

Clicking the link in the console in my browser for "phser.js:168613" brings me to this section of code:  
```
if (!gl.getProgramParameter(program, gl.LINK_STATUS))
{
    throw new Error('Link ' + failed + gl.getProgramInfoLog(program));
}
```

Note that **everything works fine on this same system using 3.60.0-beta.10**

The error happens in Beta 11, Beta 12 and Beta 13.

## Example Test Code

This happens with any code that loads phaser, but I copied the above error from a copy of the "Hello World" example that I made here:  
Phaser 12: https://codepen.io/EkpyroticFrood/pen/NWMJzBa

## Additional Information

I am definitely using WebGL and expecting WebGL to work on this platform, as it always has.  
I know that the Raspberry Pi 4 isn't probably your highest priority, but as it worked fine up through Beta 10, I'm hoping this is a simple fix to get it working again before 3.60 release.  

## Firefox

I tried Firefox and the results are the same (works with Beta 10, does not work with Beta 11, 12 or 13), but I got one more line in the error output that might be useful:  

```
Uncaught Error: Link Shader failed:
error: sampler arrays indexed with non-constant expressions is forbidden in GLSL ES 100
```

## Update

Just adding a note that it also behaves the same in Beta 13, which isn't a surprise as I'm sure nobody has had time to look int it yet. This is mostly for my own benefit to track my testing.

If you have any testing you would like me to do let me know. I've done some digging, but I'm not smart enough to see what changes between Beta 10 and 11 relate to this issue. I'm definitely willing to try some suggestions and provide more testing output.

**Comment by chrisl8** [comment]
**The solution is to install the latest version of Raspbian instead of Ubuntu on the Pi 4.**

I wiped my SD card and installed the latest version of Raspbian on it, booted up my Pi 4, and Beta 13 works!

I cannot find anything different in the chrome://gpu info between the two, but clearly something is different with either the video driver itself, Chromium, or something else that helps Phaser run WebGL.

I'm going to go ahead and close this. While I'd like to make it work and/or know why it doesn't work on Ubuntu on the Pi 4, I certainly don't expect you to support an OS on a Single Board Computer that even the hardware maker doesn't directly support. If anything, this is an Ubuntu bug, not a Phaser bug.

**Comment by devops724** [comment]
i have same issue, i don't have this issue on system node, when i switch to nvm node i encounter exactly same error

**Comment by chrisl8** [comment]
@devops724
What OS do you have installed on the pi?
`cat /etc/lsb-release`
`cat /etc/os-release`

What browser are you using and what is the version?

Also, you say the node version affects it, but Phaser runs in the browser. Is this a build issue or a runtime issue?

**Comment by devops724** [comment]
i found this happen on chrome 114 only, in firefox i don't have issue
also after update to chrome 115 issue gone
