### ISSUE TITLE
gl-texture is y-inverted

### ISSUE THREAD

**Issue by vforsh** [phaserjs/phaser#6256]
## Version
Phaser 3.60 beta 12

## Description
I'm experimenting with basis texture compression. I load the textures themselves with extrernal non-Phaser loader and then add them via `TextureManager.addGLTexture` method. It works fine but when I try to display these textures they are flipped vertically. 

I can fix this by adding the following code but it would be nicer if this method would provide some analogue to `DynamicTexture.isSpriteTexture`:
```js
frame.setUVs(frame.width, frame.height, frame.u0, frame.v1, frame.u1, frame.v0)
```

## Example Test Code
https://github.com/vforsh/phaser-basis-test/blob/main/index.ts#L20

**Comment by photonstorm** [comment]
Your basis textures are actually the correct way up. It's PNGs/JPEGs that are 'upside down' (as far as OpenGL is concerned), but as we're a 2D framework we make this the norm.

When you create a TextureSource, you have the option to set the 'flipY' parameter, which is used when the WebGL texture is created. If the texture is already made outside of Phaser, then you'll have to flip the UVs like you're doing.

**Comment by vforsh** [comment]
Thanks for the explanation!

Is it possible to flip the texture source after creation? I have tried to set it after but it has no effect. Is it an expected behaviour?
```js
this.textures.get('basis').source.forEach(source => source.setFlipY(true))
```

If so may I suggest adding `flipY` flag to the Texture constructor and to the `TextureManager.addGLTexture` method?

**Comment by photonstorm** [comment]
That parameter is specifically for the creation of the texture. WebGL uses it [as the texture is made](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/WebGLRenderer.js#L1680).

It's not a 'run-time' setting, as such, which is why there is no point adding it to `addGLTexture` as it's too late by that point because this method expects a `WebGLTexture` instance to be passed to it, which should have been created with FLIP_Y set. Flipping a UV can be done at any point, though.

**Comment by BenjaminDRichards** [comment]
For reference, things have changed in Phaser as of version 3.80. The code for loading textures onto the GPU is all in `WebGLTextureWrapper` (https://github.com/phaserjs/phaser/blob/master/src/renderer/webgl/wrappers/WebGLTextureWrapper.js).

There, we use `gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, flipY);` to set the texture's vertical flip state, before invoking `gl.texImage2D`/`gl.compressedTexImage2D`. That's the key for making a texture with the correct flip - it has to be set before uploading the actual texture. 

An alternate method to get external textures into Phaser might be to call `TextureManager.addCompressedTexture()`, with a `CompressedTextureData` object composed with data from your parser. That's how we load PVR and KTX compressed textures. It's probably a lot simpler than loading your own textures into WebGL, and ensures that Phaser is managing everything (which is useful in cases like rendering context loss, where Phaser can restore the textures from the data). Note that you'd have to mark it `compressed: true`, even if it's using a texture format that's not compressed like various forms of RGBA.
