### ISSUE TITLE
Ability to define multiple image/spritesheet formats in the loader

### ISSUE THREAD

**Issue by vpmedia** [phaserjs/phaser#6258]
I would like to define multiple image formats in the asset pack manifest.

Is this possible using Phaser 3? So a feature detection can pick the compatible format to load?
Loading audio files work like that, but if I try this with images all entries are loaded at once and not the first supported format is loaded.

```
    {
        "type": "image",
        "key": "bg",
        "url": [
          "/asset/image/bg.avif",
          "/asset/image/bg.webp",
          "/asset/image/bg.png"
        ]
     }
```

**Comment by photonstorm** [comment]
There's no easy way to provide this because it's not possible to ask the browser, 'do you support webp? avif? etc.'

There are hacks to try and figure it out, but no browser API we can use, unlike with Audio, where we are given this.

**Comment by vpmedia** [comment]
Wouldn't be possible to use the same detection method as pixi.js does?
[https://github.com/pixijs/pixijs/tree/dev/packages/assets/src/detections/parsers](https://github.com/pixijs/pixijs/tree/dev/packages/assets/src/detections/parsers)

**Comment by photonstorm** [comment]
As I said, there are hacks you can use like Pixi does. We can't use `createImageBitmap` as it will break the older browsers we're compatible with. You can alternatively use `Canvas.toDataUrl` and parse the resulting data that way, but even with this, we'd need to change every file loader that takes images to support arrays, and I'm not willing to do this at this stage of Phaser 3s life. It's something we already support in Phaser 4.

If you need this now, you can detect it yourself and conditionally issue load requests. Or wrap `load.image` with your own function that does it, or create your own file type that supports it (sort of like `load.texture` does).

**Comment by vpmedia** [comment]
Ok,thanks for the explanation!

**Comment by samme** [comment]
See https://github.com/photonstorm/phaser-ce/blob/v2.19.2/src/loader/Loader.js#L2553

**Comment by photonstorm** [comment]
> See https://github.com/photonstorm/phaser-ce/blob/v2.19.2/src/loader/Loader.js#L2553

True, we could use the `picture` element. Again, it won't work on older browsers, but I guess as long as the dev doesn't care too much, it could be an option. I do think it'll over-complicate the Loader code a bit, though, especially when it comes to formats for atlas files, factoring in normal maps, automatic filename generation, pack files, etc. Realistically I'm happy to push this feature to v4.
