### ISSUE TITLE
Path Follower `startAt` causes an error

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6264]
## Version

* Phaser Version: 3.60.0-beta.12

## Description

Calling `pathFollower.startFollow({ startAt: … })` causes an error.

## Example Test Code

<https://labs.phaser.io/view.html?src=src/paths/followers/start%20at.js&v=3.60.0-beta.12>

> TypeError: undefined is not an object (evaluating 'tweenData.target[tweenData.key] = tweenData.current')

https://github.com/photonstorm/phaser/blob/5fdb91217ef0f01d7f8b44078ac5679d13aa32fd/src/gameobjects/components/PathFollower.js#L233

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
