### ISSUE TITLE
One more getAllTweens call that should be renamed

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6265]
## Version

* Phaser Version:
3.60b12

* Operating system:
any

* Browser:
any

## Description

Please open the links i provide in Chrome to make sure the redirects are working.

Bug:
Following function call doesn't exist anymore and should be renamed:
https://github.com/photonstorm/phaser/blob/4f7bbc8b610e1a91dc5e111b4efb6b6ee367930e/src/tweens/TweenManager.js#:~:text=%3F%20this.-,getAllTweens,-()%20%3A

Bug (i dont care Chrome):
https://github.com/photonstorm/phaser/blob/4f7bbc8b610e1a91dc5e111b4efb6b6ee367930e/src/tweens/TweenManager.js
line: 966
rename following:
        `var tweens = (this.processing) ? this.getAllTweens() : this.tweens;`
to following:
        `var tweens = (this.processing) ? this.getTweens() : this.tweens;`

I see in b10, that it was renamed (Chrome link):
https://github.com/photonstorm/phaser/releases/tag/v3.60.0-beta.10#:~:text=The%20TweenManager%23getAllTweens%20method%20has%20been%20renamed%20to%20TweenManager%23getTweens.%20Functionally%2C%20it%20is%20the%20same

In b12 im getting an error `Uncaught TypeError: this.getAllTweens is not a function` when calling `myScene.tweens.killAll();`

## Example Test Code

@see above section

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
