### ISSUE TITLE
Tilemap `destroyLayer()` fails with an error

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6268]
## Version

* Phaser Version: 3.60.0-beta.13 and earlier

## Description

Call `tilemap.destroyLayer(tilemapLayer)`, passing a layer belonging to the map.

> TypeError: layer.destroy is not a function

https://github.com/photonstorm/phaser/blob/23315044f74c27a97c73b2cf64a6e32b41c4b3de/src/tilemaps/Tilemap.js#L1767

## Example Test Code

TODO

## Additional Information

The `layer` variable is overwritten with a different value (LayerData).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
