### ISSUE TITLE
Uploaded videos can't be loaded in Safari

### ISSUE THREAD

**Issue by marcelobarreto** [phaserjs/phaser#6269]
## Version

* Phaser Version: 3.55.2

* Operating system: Mac OS 12

* Browser: Safari

## Description

I can't load (uploaded) videos using Safari while I can load the same videos in another browsers.

## Example Test Code

You can try to link [this video]() to a VideoObject and try to load it.

## Additional Information

The bug also can be reproducible at iOS devices. 

<img width="610" alt="image" src="https://user-images.githubusercontent.com/1276556/198414905-97899581-8165-4e35-9280-551c67538778.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/1276556/198414936-0a5dae56-9f86-4363-b55a-087707e0ae19.png">

**Comment by samme** [comment]
Try opening the video URL directly in Safari.

**Comment by marcelobarreto** [comment]
Sorry @samme my service has gone down, you can try opening it now

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1276556/198598692-e992ef1f-7102-4d75-af15-fa689fa8b32d.png">

**Comment by gabrigomez** [comment]
I'm also working with phaser and i've the exactly same problem at the moment :confused:

**Comment by samme** [comment]
Open the video URL directly in Safari. If it doesn't play there either, the problem isn't with Phaser. See discussion in

- https://stackoverflow.com/a/32998689
- https://stackoverflow.com/q/18103103

**Comment by marcelobarreto** [comment]
Oh yes, you're right, thank you @samme and sorry for it.
