### ISSUE TITLE
`mipmapFilter` stopped working since 3.60 beta 11

### ISSUE THREAD

**Issue by Antriel** [phaserjs/phaser#6270]
http://labs.phaser.io/view.html?src=src/textures\set%20mipmap%20filter.js

**Comment by photonstorm** [comment]
You sure about this? Looks fine to me (only tested on Chrome on macOS though)

![360nomip](https://user-images.githubusercontent.com/164476/198893254-f422c5ea-2220-453b-8ef0-6f90032f1a54.png)

![360mip](https://user-images.githubusercontent.com/164476/198893255-3efcea05-5b5e-4215-b903-9d563fdeba95.png)

![355mip](https://user-images.githubusercontent.com/164476/198893253-6c87aa32-2ecd-4706-9112-7e83fa158cd1.png)

**Comment by Antriel** [comment]
Yeah, not sure what's going on. Chrome on windows 7 and windows 10 both show the issue.
![image](https://user-images.githubusercontent.com/6341110/198900349-dcae542b-a5e5-4573-b3b9-12a895ef7777.png)
![image](https://user-images.githubusercontent.com/6341110/198900364-30e3f44c-2014-4e30-8401-b2d306e7d3c0.png)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
