### ISSUE TITLE
colorObj.setFromHSV() does not change members h,s,v

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6276]
## Version

* Phaser Version: 3.55.2

* Operating system: win11

* Browser: chrome, firefox

## Description

See this [test code](https://codepen.io/rexrainbow/pen/WNyRwwa)

```js
var colorObject = new Phaser.Display.Color(0xff, 0x0, 0x0);
console.log(colorObject.h, colorObject.s, colorObject.v);

colorObject.setFromHSV(0.5, 0.5, 0.5);
console.log(colorObject.h, colorObject.s, colorObject.v);
```

Expect h=0.5, s=0.5, v=0.5 after `colorObject.setFromHSV(0.5, 0.5, 0.5)`, but members h,s,v of color object do not change.
It might come from the last parameter ` updateHSV` = `false` from [`out.setTo(r, g, b, out.alpha, false)`](https://github.com/photonstorm/phaser/blob/master/src/display/color/HSVToRGB.js#L62).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
