### ISSUE TITLE
The tiles do not take into account the dimensions given to the Tilemap

### ISSUE THREAD

**Issue by Donorhan** [phaserjs/phaser#6277]
## Version

* Phaser Version: 3.60.0-beta.13 (since 3.60.0-beta.1)

* Operating system: macOS 12.6 (21G115)

* Browser: Google Chrome v107.0.5304.87

## Description

I have a different rendering as you can see on the screens. I have the following configuration: tilesets in 16x16 and in attribute of my map I have values in 48x48. I have the impression that the parameters "tileWidth" and "tileHeight" given to `make.tilemap` are problematic.

## Example Test Code

```
this.map = scene.make.tilemap({ width: 100, height: 100, tileWidth: 48, tileHeight: 48 });
this.map.addTilesetImage('tilesetId', 'fileId', 16, 16, 0, 0, 'GID');
```

## Additional Information
On 3.55:
<img width="959" alt="3 55" src="https://user-images.githubusercontent.com/3781087/200844025-1f321484-0cc9-49b2-a262-fbb9c6c28639.png">

On 3.60.beta1:
<img width="967" alt="3 60-beta1" src="https://user-images.githubusercontent.com/3781087/200844148-ef242eb7-cb35-46d6-a4b9-bb4b57a6d060.png">

**Comment by photonstorm** [comment]
Given that all the current Tilemap examples work fine in 3.60 (any beta version), it's not as simple as the 2 lines of code shown here. So this is going to need a proper test case we can reproduce with (and I suspect it'll need the assets too)

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample (and in this case, with assets) to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

**Comment by Donorhan** [comment]
Sorry for the wait, here is what I found regarding this problem.


The problem exists when `putTileAt` is called since version 3.60. Fetching the values from the tileset instead of the layer causes the rendering to fail. The changes that introduced the bug: https://github.com/photonstorm/phaser/pull/5657

```
    var sid = tiles[index][2];
    var set = layer.tilemapLayer.tileset[sid];

    newTile.width = set.tileWidth;
    newTile.height = set.tileHeight;
```

It works when I use the layer data:
```
    newTile.width = layer.tileWidth;
    newTile.height = layer.tileHeight;
```

Here is a working code: https://codesandbox.io/s/wandering-grass-cheint?file=/src/index.js
You need to change the phaser version to see the problem.

I have thought about doing a PR except that I am not sure of the changes to apply and the impact compared to the previous changes 😕
