### ISSUE TITLE
Spine game objects cause other image assets to not display

### ISSUE THREAD

**Issue by frissonlabs** [phaserjs/phaser#6280]
## Version

* Phaser Version: 3.60.0-beta.14

* Operating system: MacOS

* Browser: Chrome & Safari (only ones I've been able to test)

## Description

Once a Spine game object is added to a scene, all other image assets don't get rendered.

## Example Test Code

[CodePen](https://codepen.io/frissonlabs/pen/RwJVKdq?editors=1111)

[(Alternative) Github Repo](https://github.com/frissonlabs/phaser-spine-demo)

## Additional Information

![Screenshot 2022-11-11 at 7 42 13 PM](https://user-images.githubusercontent.com/2988351/201454706-5fbeb49d-f138-4392-bcf8-ee2d3a831fb4.png)
![Screenshot 2022-11-11 at 7 42 23 PM](https://user-images.githubusercontent.com/2988351/201454710-52e12352-0aaa-4b9f-ab6d-959a617218ed.png)

**Comment by Ariorh1337** [comment]
If nullifying "activeBuffer" inside "Phaser.Renderer.WebGL.PipelineManager#clear"
then this will allow later to make gl.bindBuffer again inside "Phaser.Renderer.WebGL.WebGLPipeline#setVertexBuffer"
we call this function from "Phaser.Renderer.WebGL.WebGLPipeline#rebind"


this will avoid mistakes:
- WebGL: INVALID_OPERATION: vertexAttribPointer: no ARRAY_BUFFER is bound and offset is non-zero
- WebGL: INVALID_OPERATION: bufferSubData: no buffer
- WebGL: INVALID_OPERATION: drawArrays: no buffer is bound to enabled attribute

but it will lead to the fact that we will not have the correct textures in place of the images
![image](https://user-images.githubusercontent.com/35579597/201490031-f1c3e9eb-4bcf-49b8-ba50-7d460a7db5cc.png)

**Comment by spayton** [comment]
I have missing images when mixing images and spines in beta14, was previously using beta12 which was fine.

This sort of problem has appeared before, and a test was created for it in labs, see it [here](https://labs.phaser.io/view.html?src=src/spine/last%20visible.js)

It shows a problem with beta14

**Comment by photonstorm** [comment]
This is a very different issue to 'last visible'. But I've reset the active textures and buffer in `rebind` and all the Spine tests work fine now (which you can confirm in the Labs by selecting the 'dev' build)

**Comment by Ariorh1337** [comment]
in beta.15 works great, thank's! https://labs.phaser.io/edit.html?src=src/3.60/spine/spine%20inside%20container.js&v=dev

**Comment by spayton** [comment]
Yep, currrent beta15 back to normal, working good

**Comment by photonstorm** [comment]
👍
