### ISSUE TITLE
Scene.Start just work for twice, after call it for third time, the whole canvas freeze and browser ram going to top on phaser@3.60-beta14

### ISSUE THREAD

**Issue by yaasinhamidi** [phaserjs/phaser#6282]
Hey Phaser Fellas 

Thanks a lot for new released and add new features with fixing bugs.
I tried the new 3.60 beta 14 on my game. after several days struggling, I figure out that `Scene.Start` will stuck on third call back.
but let me introduce my scenes before explaining issue :

`BootScene` : Load Primary Assets to prepare `PreloadScene`
`PreloadScene` :  Load `TitleScene` Assets and other shared library that should have to be load
`TitleScene` : Choose Game Type, Settings, Check latency for multiplayer and other things should be player have to see at first state.
`PreloadGameAssetsScene` : Prepare Game, base on Player's choose and setting.
`GameScene` : most famous scene in the whole project that player Coming for it (I mean Game Play Happen in this scene)

Allright! So imagine player open game page that run it so:
First `phaser.min.js` and `phaser-arcade.min.js` and other primary libraries load on page before create `Phaser Game Object`.
After that The Object have been created `BootScene` immediately start. Then when `preload` function have been done in this scene, it will be redirect to `PreloadScene` to load primary assets. after that preload function have been done like `BootScene` then redirect to `TitleScene`. after All these things happen, when player choose game type like playing  as **Single Player** when parameter and callback want to redirect , the whole things as canvas and webgl render have been frozen and browser's ram usage will be grow as rocket lunch to the top. (`BootScene` -> `PreloadScene` -> `TitleScene`.)

I tried other methods that maybe it could be my project's issue (P.S. whole project work perfectly on phaser@3.55.2 just with changing phaser to 3.60-beta14, these things happened)

then I checked everything, I skipped `TitleScene` this means direct scenes should happen with this priority: `BootScene` -> `PreloadScene` -> `PreloadGameAssetsScene`.
But third ( redirect to `GameScene` ) direction have been frozen again and whole things have been stuck!!!!!!!

I hope I was able to explain well.
if you want see how scenes look like you can visit [here](https://beta.reezball.com/?hl=en) 

Thank you again for your more powerful web game engine.

**Comment by photonstorm** [comment]
Could really do with a _simple_ test case for this. I'll see about making one next week if no one else provides one.

I honestly _massively_ doubt that just changing a Scene 3 times causes Phaser to lock up, as I've seen all the current 3.60 Betas used in a huge project with hundreds of Scenes without issue. Even so, we can check this assertion with a simple enough test.

**Comment by yaasinhamidi** [comment]
Thanks for answering Richard,

after these hours, checking for it and got ready a simple code example , I figure out that this thing happen on interactive callback you can check example on this link:

[https://github.com/yaasinhamidi/phaser-scenes-test/](https://github.com/yaasinhamidi/phaser-scenes-test/)

on that scenario before I explained when you push the button to getting to game scene, freezing happen. It doesn't matter what scene it is , when call back want to run `scene.start` whole things gonna be freeze, but if this method run by regular (I mean not on callback of interaction, like on `create` scene or other method) It's work well. this bug just happen on call back of interaction of object.

I tried example on phaser@3.55.2 and it's work well. maybe on phaser@3.60-beta14 cause of interactive update got buggy on this certain issue.

if anything that I can do, I so glad and my honor to help. I can not figure out yet what's happening in core and it doesn't give any errors on console.

**Comment by photonstorm** [comment]
Thanks for putting together the example. It's still quite complex (the Scenes are lovely and plain, but that button class is a bit of a bespoke monster!) - I've put together an example here that does what I think yours does:

https://labs.phaser.io/view.html?src=src/bugs/6282%20scene%20restart.js

And I'm struggling to replicate this. What's different between our two approaches? You can see I'm using `setInteractive` as well - and I can click the button (or spinning blade) to swap between the Title and Game scene as often as I like. Click Edit button on above link to see my code (it's all in one file to make it easier for us to debug)

**Comment by yaasinhamidi** [comment]
Yep!!! You're right!

But in component class like my example when call `scene.start` it will be freeze but in `scene` call it, it works fine.

I mean in `BounceButton` class when pass `scene` parameter for object and it `super` in constructor it look like below:

`
class BounceButton extends Phaser.GameObjects.Container {
    constructor(config) {
        super(config.scene)
        this.scene = config.scene;
    }
`

Alright! after these I tried to call it as straight call for debug like this ( `this.scene.scene.start('Game')` ) and as `Phaser.GameObjects.Container` it have been stuck.
I don't know why, when call `scene.start` in scene it works fine but like these component or other layer like these it will be freeze. just at phaser@3.60-beta14 there is no problem in phaser@3.55.2.

is there any way or something to solve it ? I got confused why this happen.

I will create new example like yours to make it easier to explain.

**Comment by yaasinhamidi** [comment]
Yep!!! You're right!

But in component class like my example when call `scene.start` it will be freeze but in `scene` call it, it works fine.

I mean in `BounceButton` class when pass `scene` parameter for object and it `super` in constructor it look like below:

`
class BounceButton extends Phaser.GameObjects.Container {
    constructor(config) {
        super(config.scene)
        this.scene = config.scene;
    }
`

Alright! after these I tried to call it as straight call for debug like this ( `this.scene.scene.start('Game')` ) and as `Phaser.GameObjects.Container` it have been stuck.
I don't know why, when call `scene.start` in scene it works fine but like these component or other layer like these it will be freeze. just at phaser@3.60-beta14 there is no problem in phaser@3.55.2.

is there any way or something to solve it ? I got confused why this happen.

I will create new example like yours to make it easier to explain.

**Comment by yaasinhamidi** [comment]
Greeting.

I found out what is going on!!

when add `destroy` method on `scenes` or other objects container these things happen 

I tried to create example like yours but I didn't find any create button in phaser lab but anyway example code in one page:

`        class ButtonComponent extends Phaser.GameObjects.Container {
            constructor(config) {
                super(config.scene);
                this.scene = config.scene;
                this.config = config;
                this.spawnButton();
            }
            spawnButton(){

                this.x = this.config.x; 
                this.y = this.config.y;

                this.background = this.scene.add.image(0,0,this.config.background);

                this.background.setInteractive();

                this.background.on('pointerdown',this.onPush, this);
                this.background.on('pointerup', this.onPull, this);
                this.background.on('pointerout', this.onOut, this);

                this.text = this.scene.add.text(0,0,'test',{
                    fontSize: 120 * this.scene.game.scaleHeight * 3,
                    fontFamily: 'Tahoma',
                    padding: 10,
                    lineSpacing: 20,
                    align: 'center',
                    fill: '#ffffff',
                    wordWrap: {
                        width: this.background.displayWidth - 10,
                    }
                });

                this.firstScale = this.background.scale;

                this.add(this.background);
                this.add(this.text);
                this.scene.add.existing(this);
            }

            // in Here when you drop it off scene start works fine 
            destroy(fromScene){

            }

            onPush(){
                this.tweenObject('push');
            }

            onPull() {
                if (typeof this.config.onPush === "function") {
                    this.config.onPush();
                    //this.scene.scene.start('Game');
                }
                this.tweenObject('pull');
            }

            onOut() {
                this.tweenObject('pull');
            }

            tweenObject(status) {
                const pressure = (status === "push" ? 0.9 : 1);
                if (typeof this.text !== "undefined") {
                    this.config.scene.tweens.add({
                        targets: this.text,
                        scale: this.firstScale * pressure,
                        ease: 'Linear',
                        duration: 100,
                    });
                }
                this.scene.tweens.add({
                    targets: this.background,
                    scale: this.firstScale * pressure,
                    ease: 'Linear',
                    duration: 100,
                });
            }
        }
        class Boot extends Phaser.Scene
        {
            constructor ()
            {
                super('Boot');
            }

            create ()
            {
                console.log('Boot.create');

                this.scene.start('Preloader');
            }
        }

        class Preloader extends Phaser.Scene
        {
            constructor ()
            {
                super('Preloader');
            }

            preload ()
            {
                this.load.image('bg', 'assets/skies/gradient21.png');
                this.load.image('logo', 'assets/sprites/phaser3-logo.png');
                this.load.image('button', 'assets/sprites/button-bg.png');
                this.load.image('blade', 'assets/sprites/blade.png');
            }

            create ()
            {
                console.log('Preloader.create');

                this.scene.start('Title');
            }
        }

        class Title extends Phaser.Scene
        {
            constructor ()
            {
                super('Title');
            }

            create ()
            {
                console.log('Title.create');

                this.add.image(400, 300, 'bg');
                const logo = this.add.image(400, -200, 'logo');

                this.tweens.add({
                    targets: logo,
                    y: 200,
                    ease: 'Bounce.out'
                });

                /*const button = this.add.image(400, 400, 'button');

                button.setInteractive();

                button.on('pointerup', () => {

                    this.scene.start('Game');

                });*/

                const button = new ButtonComponent({
                    scene: this,
                    x:400, y:400,
                    background: 'button',
                    onPush:this.goToGameScene.bind(this)
                })
            }

            goToGameScene() {
                this.scene.start('Game');
            }
        }

        class Game extends Phaser.Scene
        {
            constructor ()
            {
                super('Game');
            }

            create ()
            {
                console.log('Game.create');

                this.add.image(400, 300, 'bg');
                const blade = this.add.image(400, 300, 'blade');

                this.tweens.add({
                    targets: blade,
                    angle: 360,
                    repeat: -1,
                    ease: 'linear'
                });

                blade.setInteractive();

                blade.on('pointerup', () => {

                    this.scene.start('Title');

                });
            }
        }

        const config = {
            type: Phaser.AUTO,
            parent: 'phaser-example',
            width: 800,
            height: 600,
            backgroundColor: '#2d2d6d',
            scene: [ Boot, Preloader, Title, Game ],
            physics:{
                default: 'arcade'
            }
        };

        const game = new Phaser.Game(config);`

I attached example as TXT file in below.
[example-of-issue-6282.txt](https://github.com/photonstorm/phaser/files/10014366/example-of-issue-6282.txt)

**Comment by photonstorm** [comment]
I haven't tested your code yet, but this part worries me:

```js
        destroy(fromScene){

        }
```

because this is going to overwrite the `destroy` method that Container has (and needs!) - which means the Container never does any of the things it should to tidy itself up, like removing itself from the display and update lists, etc. At the very minimum, this method should be:

```js
        destroy(fromScene){
           super.destroy(fromScene);
        }
```

**Comment by photonstorm** [comment]
Closing this issue as my comment above was right. The Button `destroy` method incorrectly forgot to call `super.destroy()` causing the browser to lock-up. Fix that, and it works perfectly:

```js
    destroy(fromScene){
        super.destroy(fromScene);
    }
```
