### ISSUE TITLE
iOS16 pointerdown problem

### ISSUE THREAD

**Issue by keepinglight** [phaserjs/phaser#6283]
Phaser Version: 3.55.2
Operating system: iOS16

My event listener is as follows:
```JavaScript
let count = 0;
gameobject.on('pointerdown', () => {
  count++;
});
```
Before upgrading to iOS16, When I click the gameobject quickly, how many times I click Count will accumulate how many times. After the upgrade, I may have clicked the gameobject ten times, but the count does not add up to ten times, possibly 8 times or less. 

But when I press the phone screen with one finger and click the gameobject with the other, the problem doesn't appear.

**Comment by photonstorm** [comment]
@keepinglight why did you close this? (or rather, did you figure out what was going on?)

**Comment by keepinglight** [comment]
> @keepinglight why did you close this? (or rather, did you figure out what was going on?)

@photonstorm My colleague told me how to solve the problem, just by making the following changes in the game configuration object:
```JavaScript
const config: Phaser.Types.Core.GameConfig = {
  type: Phaser.WEBGL,
  // ...Other configuration
  input: {
    windowEvents: false,
    touch: {
      // Here is the point, just comment out the following configuration to solve the problem!!!
      // capture: false,
    },
    mouse: false,
  },
};
```
I've tested it now and found that this does solve the problem, but I still haven't figured out the reason.Can you tell me why?

Finally, Thank you very much for providing such a good game framework for everyone to use, it will definitely get better and better in the future

**Comment by photonstorm** [comment]
`capture: false` just stops it from doing `event.preventDefault` on the DOM events (the default is to disable this, or you can get really weird stuff going on when you add your game to a site).

I doubt if iOS16 cares tbh. To me, this smells like it's activated an OS or browser gesture they recently added.

**Comment by keepinglight** [comment]
@photonstorm I know that iOS has a 300ms click delay rule before, At that time, the introduction of the [fastclick](https://github.com/ftlabs/fastclick) tool could solve this delay problem. and in iOS16, fastclick will also have an effect but cannot completely solve the problem, In the process of testing, I also suspect that iOS16 has a new judgment on browser gestures.

**Comment by photonstorm** [comment]
Haven't needed FastClick for nearly 8 years now. It's not a thing on any modern mobile browser. Phaser uses touch events, not click events, and they are immediately passed through to your game (there's no queue or batching of events anymore, although we did in early versions of Phaser).

I'll test this on iOS16 on an iPad and iPhone, but I'm honestly doubtful it'll be easy to replicate unless they really did add a new gesture (quite what that could be, I don't know, I didn't see anything in their Safari change logs). Will re-open this and leave it until I've done that test.

**Comment by photonstorm** [comment]
Tested on an iPad Pro 12 with iOS16, and it will capture as many taps as I can manage, as fast as I can manage, so happy to close this one off.
