### ISSUE TITLE
Bobs can't receive Arcade Physics bodies

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6284]
## Version

* Phaser Version: 3.60.0-beta.9 to beta.14

## Description

Since https://github.com/photonstorm/phaser/commit/4f005e37011fc5946ff7d1e4dbe7401e13ad93d1 blitter bobs are rejected by `Phaser.Physics.Arcade.World#enableBody()`.

```js
this.physics.add.existing(bob);

console.assert(bob.body !== undefined);
```

## Example Test Code

Compare

- <https://labs.phaser.io/view.html?src=src/physics/arcade/40000%20world%20bodies.js&v=3.60.0-beta.14>
- <https://labs.phaser.io/view.html?src=src/physics/arcade/40000%20world%20bodies.js&v=3.55.2>

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
