### ISSUE TITLE
Phaser beta14: "Cannot play destroyed Tween" on not destroyed tween. Was working fine using beta9.

### ISSUE THREAD

**Issue by ProgrammingLife** [phaserjs/phaser#6287]
## Version
Migrating: phaser3.60.0b9.min.js -> phaser3.60.0b14.min.js

* Phaser Version:
phaser3.60.0b14.min.js

* Operating system:
Linux 

* Browser:
Firefox/Chrome

## Description
I just create tween, store it in global variable and do following:
```
// tween options: duration: 300, yoyo: true, repeat: 0, paused: true,
// ...
this._tween.play();
// ... after some time I repeat this action: 
this._tween.restart();
this._tween.play();
```
And here I get: **Cannot restart/play destroyed Tween**. I didn't destroy the tween, why does Phaser destroy the tween which I need it to restart and replay?
It worked in beta9 but doesn't work in beta14. How do I mark to not destroy this tween automatically?

## Example Test Code
Opened this example: https://labs.phaser.io/edit.html?src=src/3.60/tweens/tween%20sprite%20angle.js and made some changes:
```
class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    preload ()
    {
        this.load.image('bar', 'assets/sprites/longarrow.png');
    }

    create ()
    {
        const bar = this.add.image(400, 300, 'bar').setOrigin(0, 0.5);

        this._tween = this.tweens.add({
            targets: bar,
            angle: '+=360',
            duration: 500,
            repeat: 0
        });

        setTimeout( () => { 
            this._tween.restart(); //!!! Cannot restart destroyed Tween
            this._tween.play(); //!!! Cannot play destroyed Tween
        }, 1000 );
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: Example
};
const game = new Phaser.Game(config);
```

## Additional Information
-

**Comment by ProgrammingLife** [comment]
Trying to see how new tween's chain system works in examples but it doesn't work. 
In console I get: **Uncaught TypeError: tween.init is not a function**.
(v 3.60.0-beta.14)

Tested phaser example: https://labs.phaser.io/edit.html?src=src/3.60/tweens/chains/basic%20tween%20chain.js

All the tween examples has the same bug in the console. Here after click on any bat you'll have the same crash: https://labs.phaser.io/edit.html?src=src/3.60/tweens/chains/bat%20tween.js

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/blob/12992704e39837765ae99c0260abb8d5462e3cda/src/tweens/tween/BaseTween.js#L262

See documentation above this line. Needs to be in your tween config.

Chains working in Beta 15 (seal to dev version on labs to see this)
