### ISSUE TITLE
Issues using 'compressed multi texture atlas' (loader error texture not loading)

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6295]
## Version

3.60.0-beta.14

Windows 10
## Description

**EDIT**: Rest of this comment can be ignored in favor of my [second comment](https://github.com/photonstorm/phaser/issues/6295#issuecomment-1329835134).

------------------------

I've got some issues using compressed multi texture atlas.

Following example works correctly (no compression):
```ts
this.load.multiatlas(
    LoaderFileKeys.ui, 
    `${path}/ui-png.json`, 
    `${path}`
);
```
Following example also works correctly (supplying 3 textures):
```ts
this.load.texture(
    LoaderFileKeys.ui,
    {
        'PVRTC': { 
            type: 'PVR', 
            multiAtlasURL: `${path}/ui-pvrtc1.json`, 
            multiPath: `${path}` 
        },
        'S3TC': { 
            type: 'PVR',
            multiAtlasURL: `${path}/ui-dxt5.json`, 
            multiPath: `${path}` 
        },
        'IMG': {
            multiAtlasURL: `${path}/ui-png.json`, 
            multiPath: `${path}` 
        }
    }
);
```
But then when i remove some of the textures, weird things happen..

A) Following (removing first 2 textures) throws `Uncaught TypeError: loader is undefined`:
```ts
this.load.texture(
    LoaderFileKeys.ui,
    {
        'IMG': {
            ...
        }
    }
);
```
B) Following (removing second texture) throws `Uncaught TypeError: loader is undefined`:
```ts
this.load.texture(
    LoaderFileKeys.ui,
    {
        'PVRTC': { 
            ...
        },
        'IMG': {
            ...
        }
    }
);
```
C) Following (removed first texture) works OK:
```ts
this.load.texture(
    LoaderFileKeys.ui,
    {
        'S3TC': { 
            ...
        },
        'IMG': {
            ...
        }
    }
);
```
Same can be reproduced by simply commenting in/out lines in the following example: http://labs.phaser.io/edit.html?src=src/3.60/textures/compressed%20multi%20texture%20atlas.js
## Additional Information

Expected behavior: no matter how many arguments are provided (down to a single texture object argument - this is also useful for debugging and other use-cases), no matter in what order they are provided, processed from top down they are, without loader errors. If none of the supplied texture arguments are supported, perhaps display a warning/throw error.

**Comment by michalfialadev** [comment]
There seems to be a problem with loading the PNG/IMG atlas definition in compressed multi texture atlas. If you go to labs example:
http://labs.phaser.io/edit.html?src=src/3.60/textures/compressed%20multi%20texture%20atlas.js

And place IMG first:
```ts
this.load.texture('test', {
    'IMG': { multiAtlasURL: `${path}/multi.json`, multiPath: `${path}` },
    'PVRTC': { type: 'PVR', multiAtlasURL: `${path}/multi-pvr.json`, multiPath: `${path}` },
    'S3TC': { type: 'PVR', multiAtlasURL: `${path}/multi-dxt5.json`, multiPath: `${path}` }
});
```
You get an error. I can confirm that the PNG multi-atlas i'm using does load correctly using `this.load.multiatlas`, so the issue's prob. elsewhere (not in the `multi.json` content/path or the actual `PNG` file).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
