### ISSUE TITLE
Wrong types for Text.getWrappedText

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6296]
## Version

* Phaser Version: 3.60.0-beta.15

* Operating system: Windows 11

* Browser: Chrome 108

## Description

According to the docs of getWrappedText, the text argument can be unspecified, but the typescript typings does not allow this. https://github.com/photonstorm/phaser/blob/d67c93646cbfe8ba5997954f8af29a8f3f9e8e91/src/gameobjects/text/Text.js#L570

## Additional Information

Also, is there a way to get the number of lines of a Text object, with wrapping enabled, without rerunning wrapping math?

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

And no, there is no way to get the number of lines of wrapped text.
