### ISSUE TITLE
Incosistency between debug and actual behaviour of input with negative bounds

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6298]
## Version

* Phaser Version: 3.55.2

* Operating system: Windows 11

* Browser: Chrome 108

## Description

When using negative input bounds for an interactive object, the area shown when enabling debug is different than the actual interactive area.

## Example Test Code

https://labs.phaser.io/edit.html?src=src/input/game%20object/debug%20hitarea.js&v=3.55.2

To reproduce:

1. Change line 41 to: sprite4.setInteractive(new Phaser.Geom.Rectangle(-64, -64, 128, 128), Phaser.Geom.Rectangle.Contains);
2. Hover the mouse over different parts of the eye
3. Verify there is an inconsistency

## Additional Information

What I am trying to achieve is to increase the input size of small buttons without increasing the sprite size. Also I am not completely sure what the intended behaviour should be, but I can see that something here is wrong, at least.

**Comment by photonstorm** [comment]
You can use negative values, as you've done, just fine, and they work when scaled / rotated, etc. This can be seen in the example you linked by changing the hit area as you suggested. The actual hit area is 100% correct. What is incorrect is where the debug area is rendering, and there's another issue for this #4905 so I'm going to close this one, and you can track it in there.
