### ISSUE TITLE
Issue with POINTER_UP_OUTSIDE

### ISSUE THREAD

**Issue by sreadixl** [phaserjs/phaser#6305]
Version: Phaser Version: 3.55.2
Browser: Windows Chrome 107

I'm running into an interesting problem, and I think I have it narrowed down to the cause, and it's possible that it's expected behavior. I have a game that is running on our website, the game runs inside of an iframe where the contents are on a different domain than the website. We use to have document.domain set, but have recently removed it as it is getting deprecated. I noticed that some of our games weren't working correctly if you were dragging something in the game, dragged your mouse of the game area, and then released. Generally what would happen is the item wouldn't get "dropped" and would continue to follow your mouse.

It seems like the `mouseup` event is not firing for the game when you release outside of the game. After a bit of diving into Phaser's code, it looks like the `mouseup` listener for when the mouse is released outside of the game was being down by doing `window.top.addEventListener('mouseup')` which obviously doesn't work without document domain setting, so it falls back to just using `window.addEventListener`. The relevant code is found here: https://github.com/photonstorm/phaser/blob/v3.55.2/src/input/mouse/MouseManager.js#L475

I created a simple setup that results in the problem:
```
const contentWrapper = document.getElementById('contentWrapper');
const canvas = document.createElement('canvas');
canvas.width = 1024;
canvas.height = 768;
contentWrapper.appendChild(canvas);
canvas.addEventListener('mousedown', () => console.log('mouse down on canvas'));
window.addEventListener('mouseup', () => console.info('mouse up on window'));

class Example extends Phaser.Scene {
  create () {
    this.input.on(Phaser.Input.Events.POINTER_UP_OUTSIDE, () => console.info('phaser pointer up outside'));
    this.input.on(Phaser.Input.Events.POINTER_UP, () => console.info('phaser pointer up'));

    this.add.text(this.scale.width / 2,this.scale.height / 2, 'This is a test Phaser game', { align: 'center', color: '#ffffff', fontSize: '32px', fontFamily: 'Arial' }).setOrigin(0.5);
  }
}

/** @type {Phaser.Types.Core.GameConfig} */
const config = {
  type: Phaser.WEBGL,
  width: 1024,
  height: 768,
  parent: 'contentWrapper',
  canvas,
  scale: {
    mode: Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH
  },
  scene: Example
};

const game = new Phaser.Game(config);
```
I noticed if I didn't create the Phaser game (comment out the last line of code), the canvas/window listeners work - you get the "mouse up on window" if you click inside of the canvas, and then release outside of the canvas. Once the Phaser game is created, that stops working.

After a bit more digging, I found that adding the following to the config fixes the issue: `input:{mouse:{preventDefaultDown:false}}`. The relevant code that this is used is here: https://github.com/photonstorm/phaser/blob/v3.55.2/src/input/mouse/MouseManager.js#L391. I am assuming that what is happening is the event gets its "prevent default" called, which prevents it from correctly firing on the window. I'm not 100% sure why turning off the _down_ prevent default fixes it for the _up_ event, but turning off the prevent default for up doesn't fix it. I would assume the reason why the `window.top` version works is because that has its own mouse up event that is fired, so it wouldn't have prevent default set on it.

Again, this might be expected behavior. I'm not sure what ramifications turning off `preventDefaultDown` would have, so I'm hesitant to do that. In the meantime I'm going to look at other solutions but maybe someone can shed some light on why this happens the way it does, and whether there might be a solution.

An additional note: POINTER_UP_OUTSIDE works correctly on our website on Windows Firefox, but doesn't work correctly on Windows Edge. Not sure about Mac browsers, and the structure of our website on mobile is different so it "works" on mobile but the page setup is different so I don't think the issue is relevant on there.

Final note: I noticed that Phaser 2.11.0 works. After diving through that code, it doesn't seem like they prevent default on any of the events - there's a way for that to be turned on, but it looks like it is off by default.

**Comment by sreadixl** [comment]
The solution I ended up going with is
```
this.input.on(Phaser.Input.Events.GAME_OUT, (time, event) => {
  if (event instanceof MouseEvent) {
    this.input.manager.onMouseUp(event);
  }
});
```
The one "gotcha" with this is the event listener for ending drag has to be "drag end" instead of "pointer up", because if the pointer isn't over the game object when the pointer goes outside of the game window, the pointer up event doesn't fire on the gameobject, but the drag end event does (which makes sense).

**Comment by bilalnawaz072** [comment]
To fix this issue, you can try using the POINTER_UP event instead of the POINTER_UP_OUTSIDE event. The POINTER_UP event is triggered when a pointer is released, regardless of whether it was released inside or outside of the game canvas.

Here is an example of how you can use the POINTER_UP event in Phaser 3:

```
gameObject.on('pointerup', () => {
  // Pointer was released (inside or outside of the game canvas)
});
```

Alternatively, you can try setting the capture property of the InputPlugin to true to ensure that the POINTER_UP_OUTSIDE event is correctly triggered.

`this.input.setCapture(true);`

**Comment by SlimHajRomdhane** [comment]
Based on the information you provided, it seems like the issue you are experiencing with your game is related to the mouseup event not firing when you release the mouse outside of the game area. It looks like the mouseup listener for when the mouse is released outside of the game was being set by doing window.top.addEventListener('mouseup') which obviously doesn't work without document domain setting, so it falls back to just using window.addEventListener.

To fix this issue, you can try adding the following to the config: input:{mouse:{preventDefaultDown:false}}. This should prevent the event from getting its "prevent default" called, which is likely causing it to not fire correctly on the window.

However, it's important to note that turning off preventDefaultDown might have other ramifications, so be sure to test your game thoroughly after making this change. It's also worth considering other solutions to this problem, such as changing the structure of your website or game to avoid the use of iframes, or using a different approach to handling mouse events.

**Comment by zekeatchan** [comment]
After extensive testing, this does not seem to be an issue. The current version of Phaser no longer exhibits this problem.

We've made several improvements and fixes since the initial report, and it looks like this issue has been resolved.
