### ISSUE TITLE
[3.60 beta 15] input order sorting bug for deeper nested interactive elements

### ISSUE THREAD

**Issue by arbassic** [phaserjs/phaser#6306]
## Version

* Phaser Version: 3.60.0-beta.15

* Operating system: any

* Browser: any

## Description

When a button is tapped it never handles the touch event, when another overlapped element was added in the code before.

-----

InputPlugin's method `sortGameObjects` got a regression bug in one of the latest commits:

Details here:
https://github.com/photonstorm/phaser/commit/436a42cfb40a0430b13f9359d7603fbfa67381d4#r91901671

## Example Test Code

Pseudo code of the simplest scenario:

```
1) add a container to a scene with two elements:
2) an interactive full screen rect
3) an interactive small button placed in the center (or wherever in the screen)
```

When the button is tapped it never handles the event, because the rect handles the touch first. (its touch handler is added earlier and lands as the first in the list). The button should get the event because is rendered in the front, and that worked well before. Now the button is never getting the touch event.

I've investigated that a bit and it looks like in the `Phaser.Input.InputPlugin#sortGameObjects` method the `list` variable after the latest change has now just an element - the container from the step 1), so list.indexOf(rect) and list.indexOf(button) returns -1 and `this._temp` is not sorted correctly. Before another list was read, so maybe the change was unnecessary

**Comment by arbassic** [comment]
Just reverting previous change would undo the fix for https://github.com/photonstorm/phaser/issues/5507

The ideal solution would be to "flatten" displayList and each sub-tree recursively. But it sounds like a serious overhead on each sort-call. Maybe doing so only when `Input.alwaysEnabled` would be a good solution/trade-off?

**Comment by photonstorm** [comment]
There's no elegant solution for this. If we revert it breaks the previous issue again. If we flatten it's a huge overhead. Potentially we could include 'alwaysEnabled' in the render list, but that's heck of a hack just to support this. Might be easier to just remove the feature entirely.

**Comment by arbassic** [comment]
In [the docs](https://newdocs.phaser.io/docs/3.54.0/focus/Phaser.Cameras.Scene2D.Camera-renderList) the renderList is described as used internally (and exclusively?) by the input system - so it looks like the list is a dedicated property for Input only and (if so) - including 'alwaysEnabled' in the render list would be semantically correct... Hm... a tough row to hoe! :)

**Comment by photonstorm** [comment]
Looking at this further - the documentation is slightly misleading. Yes, the input system uses it, but the actual list is _created_ by the sweep that checks which objects should be rendered or not. This means I'd have to include objects that won't render at all in this list for them to get as far as the input system.

This is why I'm tempted to remove the feature entirely. I'm not sure it warrants such an invasive change of how the rendering pass works, and I'm not entirely convinced it is even used that much, anyway.

**Comment by photonstorm** [comment]
Thinking about it, if you need an 'alwaysEnabled' object that won't render, you can just use a Zone.
