### ISSUE TITLE
TypeScript Errors

### ISSUE THREAD

**Issue by subhoghoshX** [phaserjs/phaser#6307]
## Version

* Phaser Version: 3.55.2+

* Operating system: any

* Browser: any

## Description

When trying to recreate the game using the website's [guide](https://phaser.io/tutorials/making-your-first-phaser-3-game/part8), I encountered a couple of TypeScript errors.

In a section while iterating the stars it shows `setBounceY` not found.

```js
const stars = this.physics.add.group({
  key: "star",
  repeat: 11,
  setXY: { x: 12, y: 0, stepX: 70 },
});

stars.children.iterate((child) => {
  child.setBounceY(Phaser.Math.FloatBetween(0.4, 0.8)); // Here it says `setBounceY` doesn't exist.
  return null;
});
```

![image](https://user-images.githubusercontent.com/108616679/205630123-9cc12fc8-85eb-4eda-a504-33dca7839c1e.png)

And just after that, in the tutorial, where it shows how to detect overlap, the doc shows to use `null` and `this` as the 3rd & 4th arguments.

![image](https://user-images.githubusercontent.com/108616679/205633306-cbe8cca8-888f-4e47-81cf-9d3abb776cf9.png)

But it shows a type error when I pass `null`.

![image](https://user-images.githubusercontent.com/108616679/205633397-b90bea78-cba3-4d81-9c73-7574439d9ad5.png)

Looking at the type it look like it expects something else:

![type screenshot](https://user-images.githubusercontent.com/108616679/205635741-8efa65d2-7792-44a4-8aea-1aeedd625ee7.png)

I encountered the above errors in phaser@3.55.2+ including the latest beta 16.

**Comment by subhoghoshX** [comment]
PS: I know creating an issue is easier than fixing it. I'm quite familiar with JS/TS, if anyone can point me in the right direction, I can try fixing it.

**Comment by photonstorm** [comment]
You need to cast 'child' in the iterate handler or TS won't understand what it is.

**Comment by subhoghoshX** [comment]
Cast 'child' to what type?

**Comment by photonstorm** [comment]
To what it is - an `Phaser.Physics.Arcade.Sprite`.
