### ISSUE TITLE
[3.60 beta 16] iOS has no audio

### ISSUE THREAD

**Issue by klaritan** [phaserjs/phaser#6310]
## Version

* Phaser Version: [Phaser 3.60 Beta 16](https://github.com/photonstorm/phaser/releases/tag/v3.60.0-beta.16)

* Operating system: iPhone 11

* Browser: Safari, latest

## Description

iOS does not have any sound, using all default environment (WebAudio?).

## Example Test Code

`
        this.load.audio('jack',  'assets/audio/jack.wav');
        this.jackPlayer = this.sound.add('jack');
        this.jackPlayer .play();
`

**Comment by photonstorm** [comment]
Sure it does. Here is a video of an iPhone 14 with iOS16 running 3.60 Beta 16 from the Labs demos (https://labs.phaser.io). Audio on to hear it working in the video:

https://user-images.githubusercontent.com/164476/206224624-d9ce8492-80dd-412b-8c93-6a5ad7565146.mp4

Make sure you're using file formats iOS can actually play. Make sure the phone isn't set to 'silent mode' and make sure you tap/click the screen, playback will not start until you do.

**Comment by klaritan** [comment]
> Sure it does. Here is a video of an iPhone 14 with iOS16 running 3.60 Beta 16 from the Labs demos (https://labs.phaser.io). Audio on to hear it working in the video:

> Make sure you're using file formats iOS can actually play. Make sure the phone isn't set to 'silent mode' and make sure you tap/click the screen, playback will not start until you do.

We've tested on iPhone 11 and it wasn't playing. We tried with both .wav and .mp3.

**Comment by photonstorm** [comment]
Here's a video of an iPhone 11 (real device, not emulated) playing audio:

https://user-images.githubusercontent.com/164476/206314289-87b2d9fa-6d5a-4a44-8aa6-8f8c80e2494f.mp4
