### ISSUE TITLE
3.60b14->b15 (incl b16) scale.resize memory leak

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6311]
## Version

* Phaser Version:
3.60.0-beta.15 || 3.60.0-beta.16

* Operating system:
win10

* Browser:
Firefox || Chrome (to lesser extent)

## Description

I'm running a project with config:
```ts
{
  type: Phaser.WEBGL,
  width: 2,
  height: 2,
  scale: {
    mode: Phaser.Scale.NONE,
    zoom: 1,
  },
  render: {
    defaultPipeline: 'MobilePipeline',
  },
...
}
```

I'm calling following code to resize Phaser canvas to window physical size:
```ts
const physWidth = Math.ceil(curViewportSize.width * window.devicePixelRatio * this.screenScale);
const physHeight = Math.ceil(curViewportSize.height * window.devicePixelRatio * this.screenScale);
this.scene.scale.resize(physWidth , physHeight);
```
On b14, when i resize the browser window - which calls the above `scale.resize` function 60x per second, this causes no extra RAM allocations (i monitor this via windows taskmon) and results in a smooth resize (feels 'native'). The RAM consumption stays at stable ~500MB.

I'm also using multi atlas compressed textures (unsure if this matters, but might as well mention it) for all atlases: ASTC(PVR), ETC(PVR), S3TC(PVR) and IMG/PNG.

Starting at Phaser version  b15+, resizing browser window causes approx 1GB/sec RAM allocations (Firefox), which translates to approx 10GB of RAM allocated in 10 seconds of manually resizing he browser window. The resizing itself feels 'choppy'. This eventually leads to a huge spike, which freezes the browser and after ~1s GCs the extra allocations back to base ~500MB RAM allocated (game's baseline alloc size). Further resizes continue the same trend (10s to 10GB and a sharp spike with browser freeze down to 500MB reset). Alternatively, after OS hibernation, this crashes the game at full RAM (without freeze back to 500MB base consumption - and reports console log [can't repro now as ive just restarted] blaming `scale.resize` as the culprit). Same problem is present in b16. Chrome does seem to have the same problem, but the allocations seem to stabilize at around 600MB extra allocations (so the final alloc size seems to slightly vobble around 1100MB RAM allocated in Chrome. I suspect Chrome's GC handles the extra mem releases better in this case - tho it never seems to get down to <1100MB mem alloc).

I know this is rather vague description of a problem, which i think is related to the b15 code update (is manual canvas resize handled differently from then on, creating extra canvases or something?). I assume the issue to be easily reproducible or simply peeked from commits, but let me know if you need an example or something.

EDIT: skimmin through the b15 commits, it hit me the console error log mentioned FrameBuffer. Could [this one](https://github.com/photonstorm/phaser/commit/9357b8e609235bd917192917c65af3b585958349) have something to do with it? Hmm.. the new depth stencil buffer creation does run on resize(), so i guess that's it!

## Example Test Code

@see prior text

**Comment by photonstorm** [comment]
Nothing, and I mean _nothing_ changed in the Scale Manager between Beta 14 to 16. In fact nothing has changed there since October 26th (which would be Beta 13):

https://github.com/photonstorm/phaser/commits/master/src/scale

That doesn't mean this isn't happening, but it's nothing to do with the Scale Manager. Which means it's going to be significantly harder to track down.

**Comment by photonstorm** [comment]
Sorry, just saw your edit re: Depth Buffer - it's possible it could be this. If you're able to edit the master branch and disable that change, it would be a quick thing to test I guess?

**Comment by michalfialadev** [comment]
> Nothing, and I mean _nothing_ changed in the Scale Manager between Beta 14 to 16. In fact nothing has changed there since October 26th (which would be Beta 13):
> 
> https://github.com/photonstorm/phaser/commits/master/src/scale
> 
> That doesn't mean this isn't happening, but it's nothing to do with the Scale Manager. Which means it's going to be significantly harder to track down.

Have you seen my last **EDIT** text in the prev massage? Does that code not create a new depth stencil buffer object or something? It even runs in resize().. 3 unlikely converging 'coincidences' i'd say (tho i dont know what the code actually does:), is that really unrelated?

**Comment by michalfialadev** [comment]
> 



> Sorry, just saw your edit re: Depth Buffer - it's possible it could be this. If you're able to edit the master branch and disable that change, it would be a quick thing to test I guess?

Yep, setting last parameter back to `false` 'fixed' it. To reiterate, following produces no memory leaks:
```ts
this.framebuffer = renderer.createFramebuffer(width, height, this.texture, false);
```

**Comment by photonstorm** [comment]
Hmm, that's annoying, as it's a really, really useful feature! Enables so many cool things.

To be honest, I'm curious why this is even being called anyway - it's nothing to do with resizing.

**Comment by michalfialadev** [comment]
> 

That line of code i referenced is directly from inside the `resize` function - what do you mean it has nothing to do with it? You put it there, no? ^_^ 

Hmm.. yes, would be nice to have the ability to use those fancy new features.. wonder if there's a way around it somehow.

**Comment by photonstorm** [comment]
Try this:

```js
    /**
     * Deletes a WebGLFramebuffer from the GL instance.
     *
     * @method Phaser.Renderer.WebGL.WebGLRenderer#deleteFramebuffer
     * @since 3.0.0
     *
     * @param {WebGLFramebuffer} framebuffer - The Framebuffer to be deleted.
     *
     * @return {this} This WebGLRenderer instance.
     */
    deleteFramebuffer: function (framebuffer)
    {
        if (framebuffer)
        {
            var gl = this.gl;

            gl.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);

            var renderBuffer = gl.getParameter(gl.RENDERBUFFER_BINDING);

            if (renderBuffer)
            {
                gl.deleteRenderbuffer(renderBuffer);
            }

            gl.bindFramebuffer(gl.FRAMEBUFFER, null);

            gl.deleteFramebuffer(framebuffer);

            ArrayRemove(this.fboStack, framebuffer);

            if (this.currentFramebuffer === framebuffer)
            {
                this.currentFramebuffer = null;
            }
        }

        return this;
    },
```

**Comment by michalfialadev** [comment]
Unsure what i should do with that - i did add the function manually to master's RenderTarget.js. 

Should i toggle last parameter back to true now?
```ts
this.framebuffer = renderer.createFramebuffer(width, height, this.texture, true);
```
And the new `deleteFramebuffer`, when should i call it?

I call it once in init of first scene, but i assume when i resize the framebuffer is recreated, should i call it every time resize() triggers? Should icall it right after the previous line eg add it inside master's RenderTarget::resize after creation of frameBuffer? Sorry just dont know what im doing :)

Sure enough, just calling it once in scene's init() and reverting last flag to true brings back the mem leak.

**Comment by photonstorm** [comment]
Sorry, entirely replace the existing function (in WebGLRenderer.js) with the one above.

**Comment by photonstorm** [comment]
And then, yes, toggle the parameter back on again. Basically I think what was happening was that the render buffer wasn't being deleted while the frame buffer was, and this tries to fix it.

**Comment by michalfialadev** [comment]
This fixed it, thank you very much! <3

**Comment by photonstorm** [comment]
Lovely. Now, stop spamming that poor canvas so much 😁
