### ISSUE TITLE
Typescript: Incorrect return type declaration for Phaser.Geom.Line.GetShortestDistance

### ISSUE THREAD

**Issue by MaffDev** [phaserjs/phaser#6322]
## Version

* Phaser Version: 3.55.2 (but seems unfixed in v3.60 Beta 17 Release)

## Description

The method computes a distance (single numeric value) between a line and a point. However, the TypeScript declaration takes the form:

>  static GetShortestDistance\<O extends Phaser.Geom.Point>(line: Phaser.Geom.Line, point: Phaser.Geom.Point | object): O;

when (I think?) it should just be:

>  static GetShortestDistance (line: Phaser.Geom.Line, point: Phaser.Geom.Point | object): number;

## Example Test Code

This causes a TypeScript error ("Type 'Point' is not assignable to type 'number'"): 

> let shortestDistance: number = Phaser.Geom.Line.GetShortestDistance(line, point); 

This cast is required to remove the error:

> let shortestDistance: number = Phaser.Geom.Line.GetShortestDistance(line, point) as unknown as number;

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
