### ISSUE TITLE
x based stagger axis not supported for hexagonal tilemaps

### ISSUE THREAD

**Issue by edushare** [phaserjs/phaser#6326]
## Version

* Phaser Version: Phaser 3.55.2

* Operating system: Windows 111

* Browser: Chrome

## Description

the render result in hexagonal mode is so different with tiled.
result from Phaser
![image](https://user-images.githubusercontent.com/9190552/208580143-5d57b70a-2f93-4f09-9d6e-3818665bf18f.png)
result from Tiled
![image](https://user-images.githubusercontent.com/9190552/208580249-29140f8b-c815-47b4-b5ee-ac72fa3b5823.png)

seems there are addition space added in both direction.

## Example Tes
![titled52](https://user-images.githubusercontent.com/9190552/208580313-a7db7bae-5ca4-4fb2-b99c-efc4f56e79d5.png)
t Code

relative tiled tmx file, not able to attach , so just copy over

`<?xml version="1.0" encoding="UTF-8"?>`
`<map version="1.9" tiledversion="1.9.2" orientation="hexagonal" renderorder="right-down" width="14" height="14" tilewidth="52" tileheight="24" infinite="0" hexsidelength="12" staggeraxis="x" staggerindex="odd" nextlayerid="4" nextobjectid="1">`
` <editorsettings>`
 ` <export target="anhui..tmj" format="json"/>`
` </editorsettings>`
` <tileset firstgid="1" name="titled" tilewidth="52" tileheight="24" tilecount="12" columns="12">`
  `<image source="titled52.png" width="624" height="24"/>`
` </tileset>`
` <layer id="1" name="图块层 1" width="14" height="14">`
 ` <data encoding="csv">`
`3,3,3,3,3,7,3,3,3,3,3,3,3,3,`
`3,3,3,3,3,7,3,3,9,9,3,3,3,3,`
`3,3,3,3,3,7,3,1,3,3,9,3,3,9,`
`3,3,3,3,3,7,7,7,7,7,9,9,9,3,`
`3,3,3,3,3,7,3,3,1,7,3,7,3,7,`
`3,1,3,3,3,3,8,3,3,1,7,1,7,3,`
`1,1,1,9,9,9,7,7,7,3,1,3,3,3,`
`1,11,11,3,9,3,9,9,7,7,3,3,3,9,`
`11,1,1,3,3,3,3,9,9,9,9,9,9,9,`
`3,3,3,3,3,9,9,9,9,9,9,9,9,3,`
`9,9,9,9,9,9,9,3,3,8,7,7,7,7,`
`9,9,9,9,9,3,3,1,3,7,3,1,1,1,`
`3,3,3,3,3,1,1,1,7,3,1,1,1,3,`
`3,3,3,3,1,3,1,3,7,1,1,3,3,3`
`</data>`
 `</layer>`
`</map>`

**Comment by edushare** [comment]
checked the code, seems, staggerAxis is not handled at all. 

In my case, staggerAxis is x, which is different with nomal case “y"

**Comment by photonstorm** [comment]
X based stagger axis isn't supported in Phaser 3. I'll mark it down as a Feature Request, but it's going to need to be contributed by the community.

**Comment by photonstorm** [comment]
Closing this as it's not a feature I want to support in Phaser 3. Leaving the tag so if anyone submits a PR I'll be happy to look at it, but closing as part of tidying up around here.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. Rex has implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
