### ISSUE TITLE
LoaderPlugin: improved dynamic asset loading

### ISSUE THREAD

**Issue by TomorrowToday** [phaserjs/phaser#6328]
I'm working on a game that needs to frequently and dynamically load a lot of assets while players are playing. Preloading most assets up front is not possible. Blobbing and URL encoding seem to be the culprits.

Blob caching in Phaser is great, but each assets blob encoding process wreaks havoc on the main thread which then causes animation stutter. Limiting the max parallel downloads can help, but ultimately blobs stack up and block the main loop.

Might be a couple approaches:
* Run Blob creation and URL.createObjectURL inside a webworker. These are heavy operations to run on the main thread
* Queue and RAF Blob creation and URL.createObjectURL to minimize their impact on the main loop.

My current workaround around feeds the loader one asset then waits for the loader to complete and repeats. It doesn't give much control over when the blob gets created and encoded so animation stutter still occurs on weak devices, but is generally better.

**Comment by photonstorm** [comment]
This isn't something I'm going to implement for Phaser 3, and we've already addressed it in Phaser 4.

Ultimately, though, the Phaser cache system only requires the final end files - so you're free to load them via your own scripts however you like (via a webworker if that is best for your use case). Then you can just populate the Phaser cache with the final decoded files. For example, to add an Image into the cache you'd call (from within a Scene):

```js
this.textures.addImage(key, data);
```

Where `key` is your string-based key used for the texture-lookup and `data` is just a standard DOM Image object. It doesn't matter _how_ that object was loaded. You're free to provide it in whatever way suits your game.

It's a very similar situation for most other file types. Look at the `src/loader/filetypes` source code, specifically the `addToCache` functions, to see what's required explicitly.

**Comment by TomorrowToday** [comment]
Oh interesting, I hadn't considered bypassing the loader entirely. Thanks for pointing me in the right direction!

**Comment by photonstorm** [comment]
Yeah, you don't have to use it at all. There are some cases where the loader will pass the data off to a Parser, before it gets added to a cache, but you can call all of those parsers directly - none of them are tied into the Loader itself.

Also, there is this Loader property, which bypasses using XHR for image files, that might be enough on its own:

```js
        /**
         * Optional load type for image files. `XHR` is the default. Set to `HTMLImageElement` to load images using the Image tag instead.
         *
         * @name Phaser.Loader.LoaderPlugin#imageLoadType
         * @type {string}
         * @since 3.60.0
         */
        this.imageLoadType = GetFastValue(sceneConfig, 'imageLoadType', gameConfig.loaderImageLoadType);
```

**Comment by TomorrowToday** [comment]
Not sure we can handle all the additional image elements in the DOM. If I could pass it a customized XHRLoader, that would be cool

**Comment by photonstorm** [comment]
Closing this issue off as I feel it was suitably answered, and I'm trying to tidy up the house a little bit before the 3.60 release :)
