### ISSUE TITLE
Arcade Physics: maxSpeed not applied consistently

### ISSUE THREAD

**Issue by Bambosh** [phaserjs/phaser#6329]
## Version

* Phaser Version: v3.55.2

* Operating system: Windows 11

* Browser: All browsers

## Description

When using the `maxSpeed` property with a given body in arcade physics, the expected behaviour is that the speed of that body will be capped on each physics update step. In practice, it appears that this only applies on every other step. As a result, arcade bodies with a `maxSpeed` value will end up moving slightly faster than they should.

## Example Test Code

https://codesandbox.io/s/phaser-3-max-speed-issue-iu9beh

## Additional Information

The cause of this behaviour [appears to be in the 'computeVelocity' function.](https://github.com/photonstorm/phaser/blob/master/src/physics/arcade/World.js#L1340) When deciding whether to scale the body's velocity, a comparison is made to confirm that `speed > maxSpeed`. At this point, speed has not actually been updated to represent the body's new velocity.  As far as I can tell, changing this comparison to `body.velocity.length() > maxSpeed` should fix the undesired behaviour.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
