### ISSUE TITLE
Error while importing scene in Phaser 3

### ISSUE THREAD

**Issue by ikenna8317** [phaserjs/phaser#6335]
## Version

* Phaser Version: 3.50.0

* Operating system: Debian linux Virtual Machine on Chrome OS

* Browser:

## Description

When trying to import the Scene class from phaser using the es6 import format i.e. "import { Scene } from 'phaser'" I always get an error: "[!] Error: 'Scene' is not exported by node_modules/phaser/src/phaser.js, imported by src/scenes/demo2.ts" saying the scene is not exported by phaser.js, meanwhile i double check the source code and lo and behold Scene is directly exported from the phaser 3 object. However, if i import "phaser" directly and then call scene using "Phaser.Scene" e.g. "export default class MyScene extends Phaser.Scene" it works.

## Example Test Code

//generates error
import { Scene } from "phaser"

export default class MyScene extends Scene {
...
}

//works just fine
import "phaser"

export default class MyScene extends Phaser.Scene {
...
}

**Comment by samme** [comment]
You should use

    import Phaser from 'phaser';

and `Phaser.Scene`. Phaser exports only one value, the Phaser namespace. `Scene` is on it but it's not a named export.
