### ISSUE TITLE
Runtime BitmapFont generator

### ISSUE THREAD

**Issue by vpmedia** [phaserjs/phaser#6346]
**Feature request:**
I would like to have the ability to create runtime bitmap fonts.

**Examples:**
https://github.com/pixijs/pixijs/blob/dev/packages/text-bitmap/src/BitmapFont.ts#L383
https://github.com/jjcapellan/phaser3-bitmapfont-factory

**Comment by photonstorm** [comment]
A BitmapFont is just an XML file and a PNG (which could also be a CanvasTexture), so you already have this ability. You just need to code your own means of generating the XML data in the right format using a CanvasTexture as the backing for it.
