### ISSUE TITLE
NineSlice not updating after changing the `leftWidth` property [Phaser 3.60 beta]

### ISSUE THREAD

**Issue by PhaserEditor2D** [phaserjs/phaser#6350]
## Version

* Phaser Version: 3.60.0-beta.18

* Operating system: macOS Ventura

* Browser: Chrome & Safari

## Description

I'm testing here the new Nine Slice object. I think I found a bug: the object is not updated If I change the `leftWidth` property. I see in the docs that I should call the `updateVertices()` method, but even in that case the change is not reflected well. I found that the `updateUVs()` method fixes the issue but it is a private method.

## Example Test Code

```javascript
class Example extends Phaser.Scene {

    constructor() {
        super();
    }

    preload() {

        this.load.image("green-button", "green-button.png");
    }

    create() {

        this.add.text(400, 100, "OK", {fill: "white"});

        // create a 9slice object for reference
        this.add.nineslice(400, 200,
            "green-button", undefined, 255, 114, 5, 70, 10, 10);

        this.add.text(400, 300, "Wrong", {fill: "white"});
        
        // create same 9slice but, but with leftWidth=70
        const btn = this.add.nineslice(400, 400,
            "green-button", undefined, 255, 114, 70, 70, 10, 10);

            // let's set back leftWidth to 5, as the reference object
        btn.leftWidth = 5;
        // I call this method because I modified the leftWidth property,
        // but it doesn't work.
        btn.updateVertices();

        // so I have to call the updateUVs() for update the change
        // btn.updateUVs();
    }
}

const game = new Phaser.Game({
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: "#00746b",
    scene: Example
});
```

## Additional Information

I attach here the example with the assets: 
[nineslice-bug.zip](https://github.com/photonstorm/phaser/files/10448013/nineslice-bug.zip)

**Comment by photonstorm** [comment]
Hmm, I do document this as:

```js
        /**
         * The size of the left vertical bar (A).
         *
         * You should treat this property as read-only.
         *
         * @name Phaser.GameObjects.NineSlice#leftWidth
         * @type {number}
         * @since 3.60.0
         */
```

Because they're never meant to be changed after creation. `updateUVs` isn't private, so you can call it safely if needed.

I guess we could add a `resize` method that bundles this together? I think I'll actually properly jsdoc the properties as `readOnly`, though, because changing them directly shouldn't do anything or be expected to.

**Comment by PhaserEditor2D** [comment]
Oh, yes, it says in the docs the `leftWidth` is readonly. It just confuses me because the docs of the `updateVertices()`:

```
     * You should not typically need to call this method directly, but it
     * is left public should you find a need to modify one of those properties
     * after creation.
```

>  updateUVs isn't private, so you can call it safely if needed.

Well... I can't find it in the typescript definitions. Maybe because it is missing the `@name` tag in jsdoc? 

Anyway, I don't get why both methods are public if the properties are read only.

> I guess we could add a resize method that bundles this together?

Yes, please, if possible. From an editor point of view, you need to change the properties of the object pretty often.

Thanks!

**Comment by PhaserEditor2D** [comment]
BTW, in the case of the 3-slice configuration. I see once the object is created, it doesn't allow to change the height of the object. It would be great to have a way of changing the height and texture of a 3 slice object too.

**Comment by PhaserEditor2D** [comment]
Well, maybe not changing the height because it is always the same as the frame. Maybe what it should allow is to change the texture of the 3-slice object, so it auto-updates the height.

**Comment by PhaserEditor2D** [comment]
If I overwrite the setTexture method in the editor's implementation, it works:

```javascript
setTexture(key: string | Phaser.Textures.Texture, frame?: string | number): this {

            super.setTexture(key, frame);

            if (this.is3Slice) {
                
                const height = this.frame.height;

                (this as any)._height = height;
                this.topHeight = height;
                this.bottomHeight = 0;
            }

            return this;
        }
```

But I feel it is like a hack and anyway it isn't available to the user.

**Comment by photonstorm** [comment]
Ok, I've added `setSlices` and hooked `setSizeToFrame` to allow it to change a 3-slice height.

You cannot change a 3-slice to a 9-slice (or vice versa) and I'm not adding that option, so in that case you'll need to destroy the Game Object and make a new one.

Have also flagged the properties as readonly in the jsdocs.

**Comment by arianfornaris** [comment]
Thanks Rich!

**Comment by arianfornaris** [comment]
Now I can edit nine slice objects pretty well on the editor :)

<img width="420" alt="image" src="https://user-images.githubusercontent.com/65058659/214999589-9af4b2a7-e50a-4b23-b7e8-ebe17955f447.png">
