### ISSUE TITLE
Tilemap putTilesAt crashes in 3.60.0-beta*

### ISSUE THREAD

**Issue by IlTimido** [phaserjs/phaser#6353]
## Version
* Phaser Version: 3.60.0-beta.18
* Operating system: Windows 10

## Description
This is the error that I get when I switch to 3.60.0-beta.18 (or more in general to 3.60.0-beta*) while it works fine with 3.55.2.
I've put "debugger" before invoking "putTilesAt" from my code.

The zip file contains a Visual Studio Code project, just open "test.code-workspace" and npm install (for default I've set 3.60.0-beta.18 to see it running correctly "npm i phaser@3.55.2")
Then start the npm script "dev" and once compiled if you have Live Server extension just click "go live" and all should start (and then hang).
So open the developer tools and reload and the execution should pause at line 107 of src\js\pages\game\scenes\MazeScene.js
Please note that I've reduced this project in order to isolate the error so there are a lot of functions that points to nothing but obviously they are not necessary for showing the bug. 

If you follow the code you'll end up at the definition of PutTileAt somewhere inside Phaser library.
Near the end of that method you should find these 2 lines:
var sid = tiles[index][2];
var set = layer.tilemapLayer.tileset[sid];
the "sid" value is wrong ando set becomes undefined and then crashes at the next line.

I just don't know what I did wrong on the tileset definition that instead works perfectly with 3.55.2 and I haven't a clue. 
I've also made static the json that contains the layers data and you can find it on the console, I've done a console.log of it (there are many layers but it hangs at once on the first one named "colliders").

Thanks

## Example Test Code

The zip attached contains a Visual Studio Code project, just open "test.code-workspace" and npm install (for default I've set 3.60.0-beta.18 to see it running correctly "npm i phaser@3.55.2")

[_bug_putTilesAt.zip](https://github.com/photonstorm/phaser/files/10460589/_bug_putTilesAt.zip)

**Comment by Arcanorum** [comment]
Wow, this is still broken. How isn't everyone else using tilemaps running into this problem?
We had to make a fork and revert these changes to get it working again: https://github.com/photonstorm/phaser/commit/f686a9674b7eddbe2db6337aed9c173e857c0f44

**Comment by photonstorm** [comment]
> Wow, this is still broken. How isn't everyone else using tilemaps running into this problem? We had to make a fork and revert these changes to get it working again: [f686a96](https://github.com/photonstorm/phaser/commit/f686a9674b7eddbe2db6337aed9c173e857c0f44)

Because it's not the same thing? This issue is about 3.60 Beta specifically. The given example works fine in 3.55.

**Comment by samme** [comment]
@IlTimido could you possibly zip up just the `dist` or `public` folder and upload?

**Comment by IlTimido** [comment]
@samme 
Here it is the package that (for example) I upload as is on itch.io.
It's the dev version (I mean compiled by webpac)
Let me know if it's what you expected

P.S. it's compiled with the latest Phaser release 3.60.0-beta.21

[_bug_putTilesAt_DEV.zip](https://github.com/photonstorm/phaser/files/11069854/_bug_putTilesAt_DEV.zip)

**Comment by samme** [comment]
The problem is from passing `null` (within `tilesArray`) to putTilesAt().

If you pass `-1` instead of `null`, you get the same error, unfortunately.

**Comment by samme** [comment]
To clarify: use `-1` in `putTilesAt()`, never `null`.

**Comment by IlTimido** [comment]
As talked with @samme here it is an updated version with  3.60.0-beta.23 that still crashes.
[_bug_putTilesAt_DEV_23.zip](https://github.com/photonstorm/phaser/files/11160586/_bug_putTilesAt_DEV_23.zip)

**Comment by DeLm0re** [comment]
@samme  & @IlTimido, can confim, I also have an issue with `putTilesAt`.

I'm using `-1` for empty tile and everything was working fine on `3.55.2` but crash on `3.60.0-beta.23`.
Either using `-1` or `null` (null causing a ts error btw).

Whatever, the exact same use of this  method brokes by upgrading to beta.

Here is my stacktrace 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'tileWidth')
    at PutTileAt (phaser.js:222763:29)
    at Object.PutTilesAt (phaser.js:222879:13)
    at TilemapLayer2.putTilesAt (phaser.js:218911:27)
    at Home.create (Home.ts:56:21)
    at SceneManager2.create (phaser.js:192658:26)
    at SceneManager2.loadComplete (phaser.js:192565:14)
    at LoaderPlugin2.emit (phaser.js:200:35)
    at LoaderPlugin2.loadComplete (phaser.js:117571:14)
    at LoaderPlugin2.fileProcessComplete (phaser.js:117537:18)
    at ImageFile2.onProcessComplete (phaser.js:116336:21)
```

**Comment by samme** [comment]
@DeLm0re if you're using multiple tilesets, you need to pass a suitable `gid` in [addTilesetImage()](https://newdocs.phaser.io/docs/3.60.0-beta.22/focus/Phaser.Tilemaps.Tilemap-addTilesetImage).

**Comment by IlTimido** [comment]
Hi @samme 
Here it is a new version, without multiple tileset (on 3.55.2 it works also if then there are black spots on the map).
Instead in the 3.60.23 unluckily it crashes at the same line.

[_bug_putTilesAt_DEV_23_singleTileset.zip](https://github.com/photonstorm/phaser/files/11178010/_bug_putTilesAt_DEV_23_singleTileset.zip)

**Comment by DeLm0re** [comment]
@samme Given an unique `gid` for each `addTilesetImage()` (starting from 0 and incr.) does not solve the issue...

Maybe I did not understand what you meant by _suitable_

**Comment by samme** [comment]
@DeLm0re the `gid` argument needs to be larger than the global ID of the last tile in any previous tileset.

If each tileset has less than 100 tiles, you could use `gid`s of 0, 100, 200, etc. for each successive tileset.

**Comment by DeLm0re** [comment]
@samme Yeah i also tried that way as it seems more logical but with no succes.

water tileset defines 1 tile
grass tileset define 20 tiles
bushes tileset defines 1 tile
tree tileset defines 1 tile

So i went for something like this for `gid` 0 => 1 => 21 => 22.

As i have no solution and this thread is my only hope here is my code

```ts
import Phaser from 'phaser';

export default class Home extends Phaser.Scene {
	constructor() {
		super(Home.name);
	}

	preload() {
                this.load.image('grass', 'Terrain/Ground/Grass_Flat.png');
		this.load.image('water', 'Terrain/Water/Water.png');
                /** TODO merge decorations in one tileset */
                this.load.image('bushes', 'Terrain/Decorations/Bush_03.png');
                this.load.image('tree', 'Terrain/Decorations/Tree.png');
	}

	create() {
	// Entire tilemap defined by succession of layers
        const tilemapDef: Record<string, number[][]> = {
            water: [
            //          1   2   3   4   5   6   7   8   9  10  11
            /*  1 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  2 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  3 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  4 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  5 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  6 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  7 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  8 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /*  9 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /* 10 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            /* 11 */ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
            ],
            grass: [
            //          1   2   3   4   5   6   7   8   9  10  11
            /*  1 */ [  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2],
            /*  2 */ [  5,  5,  5,  5,  9,  9,  9,  5,  5,  5,  6],
            /*  3 */ [  5,  5,  5,  6, -1, -1, -1,  4,  5,  5,  6],
            /*  4 */ [  5,  5,  5,  6, -1, -1, -1,  4,  5,  5,  6],
            /*  5 */ [  5,  5,  5,  6, -1, -1, -1,  4,  5,  5,  6],
            /*  6 */ [  5,  5,  5,  5,  1,  1,  1,  5,  5,  5,  6],
            /*  7 */ [  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6],
            /*  8 */ [  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6],
            /*  9 */ [  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6],
            /* 10 */ [  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6],
            /* 11 */ [  8,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10],
            ],
            bushes:[
            //          1   2   3   4   5   6   7   8   9  10  11
            /*  1 */ [ -1, -1, -1, -1, -1, -1, 21, -1, -1, -1, -1],
            /*  2 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  3 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  4 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  5 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  6 */ [ 21, 21, 21, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  7 */ [ -1, -1, -1, -1, -1, -1, -1, 21, -1, -1, -1],
            /*  8 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  9 */ [ -1, -1, -1, -1, 21, -1, -1, -1, -1, -1, -1],
            /* 10 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /* 11 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            ],
            trees: [
            //          1   2   3   4   5   6   7   8   9  10  11
            /*  1 */ [ 22, 22, 22, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  2 */ [ -1, 22, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  3 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  4 */ [ 22, 22, 22, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  5 */ [ -1, 22, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  6 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  7 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  8 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /*  9 */ [ -1, 22, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            /* 10 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, 22, -1],
            /* 11 */ [ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
            ],
        };

        // Initialize tilemap with tile size
        const tilemap = this.make.tilemap({
            tileWidth: 64,
            tileHeight: 64,
            width: import.meta.env.VITE_APP_WIDTH_IN_TILES,
            height: import.meta.env.VITE_APP_HEIGHT_IN_TILES,
        });

        // Load each tileset
        const waterTileset = tilemap.addTilesetImage('water');
	const grassTileset = tilemap.addTilesetImage('grass', undefined, undefined, undefined, undefined, undefined, 1);
        const bushesTileset = tilemap.addTilesetImage('bushes', undefined, undefined, undefined, undefined, undefined, 21);
        const treeTileset = tilemap.addTilesetImage('tree', undefined, 128, 192, undefined, undefined, 22);

        // Initialize each blank layer loading each tileset (one tileset by layer)
        const waterLayer = tilemap.createBlankLayer('waterLayer', waterTileset!);
	const grassLayer = tilemap.createBlankLayer('grassLayer', grassTileset!, undefined, undefined, undefined, undefined, 64, 64);
        const bushesLayer = tilemap.createBlankLayer('bushesLayer', bushesTileset!);
        const treeLayer = tilemap.createBlankLayer('treesLayer', treeTileset!, -32, -127, undefined, undefined, 128, 192);

        // Put tiles in each layer using respective tilemap layer definition
        waterLayer!.putTilesAt(tilemapDef.water, 0, 0);

        // **************************************************************************
        grassLayer!.putTilesAt(tilemapDef.grass, 0, 0); // ====> ERROR HERE
        //bushesLayer!.putTilesAt(tilemapDef.bushes, 0, 0);
        //treeLayer!.putTilesAt(tilemapDef.trees, 0, 0);
        // **************************************************************************

	}
}

```

**Comment by samme** [comment]
@DeLm0re that may be https://github.com/photonstorm/phaser/pull/6474

**Comment by DeLm0re** [comment]
@samme Yes maybe it is, I was not able to fix the crash since then. I'm still running on last stable version before 3.60.

I will try to apply this fix locally and come back to you

**Comment by IlTimido** [comment]
> @samme Yes it is, I was not able to fix the crash since then. I'm still running on last stable version before 3.60

Hello @DeLm0re, I can confirm it now works.
I copy paste here a conversation I had on Discord where I explained how it works now.
I hope it fix things for you too!

IlTimido — 14/04/2023 21:56
Hi AnotherUser, I had the same problem but I solved. Tell me, are you using more than a tileset?

AnotherUser — 14/04/2023 21:56
Yeah

IlTimido — 14/04/2023 21:56
okay I tell you how to fix this, just give me a minute
First of all you must create the tilesets in this way
    this.tileset = this.map.addTilesetImage("tiles" + this.sets, null, MazeConst.TILE_W, MazeConst.TILE_H, 0, 0, 0);
    this.tilesetPaving = this.map.addTilesetImage("paving", null, MazeConst.TILE_W, MazeConst.TILE_H, 0, 0, this.DELTA_TILESET);
now the important part is the last param
In my example the first tileset contains 112 tiles so they are numbered from 0 to 111.
So the first tile of the second tileset is the number 112
in my code this.DELTA_TILESET = 112;
Is this clear until now?

AnotherUser — 14/04/2023 22:00
damn, okay. little bit of a refactor
or re-read, more likely

IlTimido — 14/04/2023 22:00
yes also for me, I had to add that DELTA_TILESET to every tile I used of the second tileset
however it's not finished yet
the next thing you have to do
that is the most important one

AnotherUser — 14/04/2023 22:01
any way to get the number of tiles programmatically? after loading a tileset

IlTimido — 14/04/2023 22:01
you can divide the width and the height of the image
however let me finish because that is not sufficient

AnotherUser — 14/04/2023 22:02
alright

IlTimido — 14/04/2023 22:02
The most important thing is that when you create a blank layer
I imagine you do that

AnotherUser — 14/04/2023 22:02
yep

IlTimido — 14/04/2023 22:03
for the layers that use only the first tileset
it's okay to do this:
layer = map.createBlankLayer(layer${x}, tileset);
(obviously that line of code is from a for iteration)
but
if you want to create a layer that uses the second tileset
you must do this:
        floor = map.createBlankLayer(floor${x}, [tileset, tilesetPaving]);
you have to pass the entire array of tilesets

AnotherUser — 14/04/2023 22:04
okay i dont think im ever mixing tilesets inside an individual layer

IlTimido — 14/04/2023 22:04
me neither

AnotherUser — 14/04/2023 22:04
i still need to do that though?

IlTimido — 14/04/2023 22:04
that was the problem
I didn't mix them
but to make it work I had to pass the array

AnotherUser — 14/04/2023 22:05
alright thanks for your help!
ill try it and see if it works

IlTimido — 14/04/2023 22:05
this fixed the problem for me, I think that this can solve it for you too
it seems it's really similar
I opened an issue on github and samme and the team helped me in debugging that
let me know if this worked for you, I really hope, my knowledge about that has been exhausted ^_^

AnotherUser — 14/04/2023 22:16
I actually didn't need to use the GID, i dont think. seems to have worked with just the array added!
now to just untangle my particle code

IlTimido — 14/04/2023 22:17
really? ahahah it's much better! Thanks for telling me, but the array is the last thing I discovered!
my code stays as is right now however!
I'm glad it worked for you

**Comment by hunkydoryrepair** [comment]
This is a pretty big change, right?
There used to be a GID for each tilemaplayer, but now it is on the tilemap instead.

Do I understand that right?

For me, it seems to be crashing because I incremented the GID for each tileset within a layer.

Going to 3.60, I believe it needs to increment regardless of layer.
