### ISSUE TITLE
Add support for Unity bones definition format

### ISSUE THREAD

**Issue by BelkaDev** [phaserjs/phaser#6357]
It seems there is only support for Spine2d rigging system when it comes to [bones interaction](https://phaser.io/examples/v3/view/spine/control-bones).  

While Unity (among other tools) also offers this feature, it's only limited to predefined animations that are tied to the character, [like seen here](https://phaser.io/examples/v3/view/loader/texture-atlas-unity/load-unity-spritesheet-animation). There currently is no way to manipulate the bones dynamically at runtime.

Is there a possibility to parse `.meta` files to extract bones informations in the same fashion as Spine?
![image](https://user-images.githubusercontent.com/49416514/213785904-47132573-bb0f-4fb5-b833-09a20f0fa464.png)

**Comment by photonstorm** [comment]
I'm not really sure what benefit extracting that meta data would be? There is no bone system within Phaser, so unless you wanted to create one yourself, it would just be extra data hanging around. I'll leave this as a feature request, but it's a massive undertaking really, so I'm not too sure of the reality of it being fulfilled.
