### ISSUE TITLE
Creating a Spine object without adding it to the scene results in Spine atlas PNG being displayed

### ISSUE THREAD

**Issue by frissonlabs** [phaserjs/phaser#6362]
## Version

* Phaser Version: 3.60.0-beta.18

* Operating system: MacOS

* Browser: Chrome & Safari (only ones I've been able to test)

## Description

IF an image is added as an image, sprite, or tile sprite
AND THEN, using `setTimeout`, a Spine game object is created but not added to the scene (via `scene.make.spine` with `addToScene` set to false),
THEN the Spine atlas PNG image will replace the initial image.

Note: This also happens for a frame when `addToScene` is set to true OR when using `scene.add.spine` instead of `scene.make.spine`.

## Example Test Code

[CodePen](https://codepen.io/frissonlabs/pen/RwJVKdq)

## Additional Information

Expected:
<img width="1723" alt="Screenshot 2023-01-23 at 2 48 35 AM" src="https://user-images.githubusercontent.com/2988351/214022916-1f129230-ee1b-401e-b15b-bce8d0ffb857.png">

Current:
<img width="1726" alt="Screenshot 2023-01-23 at 2 48 19 AM" src="https://user-images.githubusercontent.com/2988351/214022907-64baf180-87c9-43ea-9668-c9f03f94ea36.png">

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
