### ISSUE TITLE
hitarea debug only to be visible if the object is visible

### ISSUE THREAD

**Issue by orjandh** [phaserjs/phaser#6364]
When using enableDebug for input hitarea maybe it would be best if the debug rectangle is hidden when the gameobject is set to not visible. The reason for this is that pointer inputs are not fired for hidden gameobjects.

Maybe it could be achieved by using the renderFlags of the gameobject.

**Comment by SlimHajRomdhane** [comment]
Yes, you can achieve this by using the renderFlags property of the game object. The renderFlags property is an integer that determines the render behavior of a game object. You can use the RENDER_MASK constant to set the bit value that corresponds to the DEBUG flag.

Here's an example of how you can modify the setHitArea function of a sprite to enable debug mode only when the sprite is visible:
Phaser.GameObjects.Sprite.prototype.setHitArea = function (shape) {
    this.input = this.input || {};
    this.input.hitArea = shape;

    if (this.input.hitArea) {
        // Enable debug mode only when the sprite is visible
        if (this.visible) {
            this.input.hitAreaDebug = this.scene.add.graphics().setAlpha(0.75);
            this.input.hitAreaDebug.lineStyle(2, 0xffff00);
            this.input.hitAreaDebug.strokeRectShape(this.input.hitArea);
            this.input.hitAreaDebug.setVisible(true);
            this.renderFlags |= Phaser.GameObjects.GameObject.RENDER_MASK;
        }
    } else {
        if (this.input.hitAreaDebug) {
            this.input.hitAreaDebug.destroy();
            delete this.input.hitAreaDebug;
        }
        this.renderFlags &= ~Phaser.GameObjects.GameObject.RENDER_MASK;
    }

    return this;
};

This function first sets the hitArea property of the sprite to the specified shape. Then it checks if the hitArea is defined and creates a graphics object for debugging. It sets the visible property of the debug graphics object to true only when the sprite is visible. Finally, it sets the renderFlags property of the sprite to enable debug rendering. If the hitArea is not defined, it destroys the debug graphics object and clears the renderFlags property to disable debug rendering.

I hope this helps!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
