### ISSUE TITLE
3.6 animation chain function broken

### ISSUE THREAD

**Issue by OdinvonDoom** [phaserjs/phaser#6365]
## Version

* Phaser Version: 3.60.0-beta.18

* Operating system: Windows

* Browser:

## Description

Animation chaining appears to be broken, per the given example:
3.55 working: https://labs.phaser.io/edit.html?src=src/animation/chained%20animation.js&v=3.55.2
3.60 not working: http://labs.phaser.io/edit.html?src=src\animation\chained%20animation.js

I've tracked it to the point where "stop()" is called after the first animation runs/completes.

In 3.55, "stop()" is called once, wherein "this.nextAnim" is set to the first element of "this.nextAnimsQueue". After that, each animation plays and completes, and the same process occurs in the "complete()" function.

But in 3.60, "stop()" is called repeatedly, back-to-back, depleting "this.nextAnimsQueue" until "this.nextAnim" is set to undefined. So, when "complete()" runs, there's nothing in the queue to transition to.

I didn't dig deep enough to find out why "stop()" is called so many times. That would be a little too deep of a dive for me right now I'm afraid.

## Example Test Code

Use Phaser examples above. And video provided.

## Additional Information

https://user-images.githubusercontent.com/112023704/214660518-1bb9ff0f-ec55-4589-a666-47c64a98beec.mp4

**Comment by samme** [comment]
It's cycling through `stop()` → `play()` → `startAnimation()` → `load()` → `stop()`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
