### ISSUE TITLE
Cannot add Dynamic Texture as texture to TileSprite

### ISSUE THREAD

**Issue by drunkcat** [phaserjs/phaser#6368]
## Version

* Phaser Version: 3.60.0-beta.18

* Operating system: Windows 11

* Browser: Firefox

## Description

Creating Tile Sprite with Dynamic Texture key breaks the game. Generating image or spite with the same texture works fine.

## Example Test Code

This generates error:
```
let _image = this.add.image(10, 10, 'test_image').setOrigin(0);
let _texture = this.textures.addDynamicTexture('abcd', 400, 400);
_texture.draw(_image );
this.add.tileSprite(100, 0, 500, 500, 'abcd').setOrigin(0);
```

but sprite works fine:
```
this.add.sprite(100, 0, 'abcd');
```

## Additional Information

the snippet of the error that appears
```
batchTexture http://127.0.0.1:5500/src/js/phaser.min.js:1
    exports http://127.0.0.1:5500/src/js/phaser.min.js:1
    render http://127.0.0.1:5500/src/js/phaser.min.js:1
    render http://127.0.0.1:5500/src/js/phaser.min.js:1
    render http://127.0.0.1:5500/src/js/phaser.min.js:1
    render http://127.0.0.1:5500/src/js/phaser.min.js:1
    step http://127.0.0.1:5500/src/js/phaser.min.js:1
    step http://127.0.0.1:5500/src/js/phaser.min.js:1
    e http://127.0.0.1:5500/src/js/phaser.min.js:1
    setTimeout handler*e http://127.0.0.1:5500/src/js/phaser.min.js:1
```

**Comment by photonstorm** [comment]
There's no way to make this work as TileSprite uses a canvas internally and DT uses a frame buffer. It should probably throw a warning for you though. It would work in canvas mode as then DT uses a canvas but not in webgl.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
Now throws a console warning if you try to do this instead of crashing the game.
