### ISSUE TITLE
Event "pointerlockchange" not triggered

### ISSUE THREAD

**Issue by Teoz98** [phaserjs/phaser#6370]
## Version
* Phaser Version: 3.55.2

* Operating system: Windows

* Browser: Firefox, Chrome

## Description

Adding a listener for the 'pointerlockchange' event no longer seems to work.

## Example Test Code

            // works
            addEventListener('pointerlockchange', function(e) {
                console.log(e);
            })

            // Not works
            this.input.on('pointerlockchange', function (event) {
                console.log(e);
            }, this);

## Additional Information

I have tried the example [link](https://phaser.io/examples/v3/view/input/mouse/pointer-lock) with different versions but it doesn't work.   
Adding a generic event listener on that event is triggered correctly.

**Comment by photonstorm** [comment]
This is an Input Manager Event, not an Input Plugin one, so it needs listening to differently (and still works in 3.55, etc)

```js
this.input.manager.events.on('pointerlockchange', (pointer) => {});
```
