### ISSUE TITLE
Camera ignore most of game objects except some...

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6372]
Camera will render all game object except ignored game objects (via `camera.ignore(gameObject)`). 
A use case is creating a new camera which only render some new game objects.
Current solution might be :

A. Ignore older game objects via `camera.ignore(gameObject)`. This solution might need lots of work.
B. Use container to render these new game objects. However, container might not equal to camera.
C. Add these new game objects at another scene. Multiple scene might be more complex than single scene.

How about adding a property of camera, which will ignore all game objects by default, only `camera.accpet(gameObject)` would be rendering?

**Comment by photonstorm** [comment]
There is also

D. Use a Layer - then you have no Container like position issues and can camera ignore the entire Layer and automatically ignore all children, to any depth. Whole Game can be split into 2 Layers, one per Camera perhaps.

**Comment by rexrainbow** [comment]
It's a great solution, thanks.
Since layer can be nested in 3.60, it can put any kind of game object into layer, include sub-layer.
