### ISSUE TITLE
Kindle Fire 7 2019 - App crashes frequently when we background and foreground the app.

### ISSUE THREAD

**Issue by anabebs** [phaserjs/phaser#6378]
* Phaser Version:
3.5.0

## Description
Bug effecting many Kindle devices particularly Kindle 7 2019

## Additional Information

**We are working on children's Apps at the BBC. Our game supplier agency have reported this bug which we believe affects many of our games and many upcoming planned releases. It would be brilliant if you had any advice or suggestions on how to resolve this.**

https://github.com/bbc/cbeebies-go-explore-app-numberblocks-mathematics/issues/153
We’re pretty sure now this issue is being caused by a bug in Phaser 3.x on this device and is not memory related at all. We have tried hugely reducing the memory imprint of the game- made no difference. We discovered in fact that the game is crashing with the WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost error the moment it is backgrounded, not when foregrounded as you might expect if we were running out of memory.

We then investigated what apps/games this is happening to and if there was commonality- and on the Go Explore games at least- the two games with the issue are Numberblocks and JoJo and Gran Gran, both of which use Phaser 3.5.x. Games using older version 2.x of Phaser such as Biggleton or Alphablocks are not showing the issue.

We then tested some basic Phaser 3 demos on the device (in the Silk browser) and they are crashing in the exact same way- the moment you background the browser, contexts are lost, the demo crashes and the browser reloads. This Phaser 3 benchmark test is a good example- it’s not remotely heavy memory wise, but has the issue on the Kindle 7 2019-
https://phaser.io/examples/v3/view/game-objects/blitter/benchmark-test-3

Phaser 3.5 does have some methods for testing for CONTEXT_LOST and we tried listening for this to see if we could catch the error before the crash, but that has not worked. We also tried updating the game to use the latest Beta version of Phaser 3.6- but that did not help. In fact in the release notes for 3.6 we found the following:

The CONTEXT_RESTORED Game Event has been removed and the WebGL Renderer no longer listens for the contextrestored DOM event, or has a contextRestoredHandler method. This never actually worked properly, in any version of Phaser 3 - although the WebGLRenderer would be restored, none of the shaders, pipelines or textures were correctly re-created. If a context is now lost, Phaser will display an error in the console and all rendering will halt. It will no longer try to re-create the context, leading to masses of WebGL errors in the console. Instead, it will die gracefully and require a page reload.

This never actually worked properly, in any version of Phaser 3 - although the WebGLRenderer would be restored, none of the shaders, pipelines or textures were correctly re-created.

We have also tried the beta version of Phaser 3.6

**Comment by vforsh** [comment]
If your game doesn't rely on webgl-specific features you can force canvas renderer for troublesome devices/browsers.

**Comment by anabebs** [comment]
@vforsh Thanks for your response

We have tried switching to Canvas rendering, but the game uses the Spine runtime in Phaser for environments and animation and this does not have support for using meshes in Canvas- you must use WebGL for this as described here:

http://en.esotericsoftware.com/forum/Problem-with-Canvas-rendering-12727

Unfortunately there's no way now the game could be rebuilt to not use meshes.

**Comment by photonstorm** [comment]
@anabebs hi - is this an internal BBC project? Or do you work for a company contracting to BBC Children's? As you can see from the Change Log, I had written off fully supporting this because it was a large internal undertaking that touched a lot of vital areas. However, if the BBC has budget (and it wouldn't take much compared to the typical cost of your game commissions) to consider funding this work, then I could definitely look into this further. Feel free to email me directly (rdavey@gmail.com) rather than discuss it in public if the idea appeals.

**Comment by anabebs** [comment]
I do work at the BBC. Leave it with me and I'll see what might be possible and will let you know via email.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
