### ISSUE TITLE
`anims.staggerPlay` doesn't work since beta 14

### ISSUE THREAD

**Issue by Antriel** [phaserjs/phaser#6381]
See http://labs.phaser.io/edit.html?src=src/3.60/animation/stagger%20play%201.js.

Furthermore seems like something changed with `GridAlign` since beta 13? The positions in the example are different.

**Comment by samme** [comment]
I think this is the same cause as #6365 — `stop()` is clearing the delay.

**Comment by photonstorm** [comment]
Yeah it is. Although the `GridAlign` is now working correctly, it was incorrect in 3.55, but this demo hasn't been updated to account for it.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
