### ISSUE TITLE
3.60b19 preFX.addGlow causes massive slowdowns on 'my gpu' :-/

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6393]
## Version

* Phaser Version: 3.60b19

* Operating system: Windows

* Browser: Chrome (newest), Firefox (newest)

## Description

The new `preFX.addGlow` shader effect causes massive slowdown on my GPU (8fps), but other effects that we tested: `addVignette`, `addBokeh` and `addBlur` run at stable 60fps. All the effects were tested applied to a 1024x896 image. Restarting the browser or computer has no effect on performance. Related discord discussion linked [here](https://discord.com/channels/244245946873937922/416623653741133837/1076299528963117156).

Exact tests performed (one by one):
```ts
const fx = this.logo.preFX.addGlow(0x000000, 64, 0, 3);
const fx = this.logo.preFX.addVignette(0,0,64, 32);
const fx = this.logo.preFX.addBokeh(16,2);
const fx = this.logo.preFX.addBlur();
```

GPU is quite old. Full specs:
Model: ATI AMD Radeon R9 280x
Subvendor: Gigabyte (1458)
GPU Clock: 1100MHz
Memory: 3072MB

I'll try to do more tests on other devices and post them here later.

**Comment by michalfialadev** [comment]
I've created a fresh new project to test this again. Single scene, single 1024x896 image, with above effects applied. Because originally this was tested in a large existing project, empty scene with a single image performed better. I was also able to test this on an iPhone7.

Reuslts on R9 280x (same code as before):
preFX.addGlow: 15fps
preFX.addVignette: 60fps
preFX.addBokeh: 60fps
preFX.addBlur: 60fps

iPhone7/iOS12:
no effect: 60fps, image displays correctly.
preFX.addGlow: 3fps, image does not display. effect does not display.
preFX.addVignette: 60fps, image does not display. effect does not display.
preFX.addBokeh: ~12-24fps (seems to run at 24 stable, after 30s switches to 12 stable), image does not display. effect does not display.
preFX.addBlur: 60fps, image does not display. effect does not display.

I guess the shader doesn't work on iPhone7 GPU, but the perf impact is there still - so perhaps the addGlow shader might be further improved perf-vise. Unfortunately i wont be able to use these for current project as they are right now (iPhone7 is quite old, but we still have to support it). It would be great to have some kind of HW support / performance reference table and perhaps fallback shaders for old GPUs (i know, i could dream.. :P). Alternatively, is there a way to - using JS/Phaser - check if specific preFX/postFX shader is supported on a device? To display fallback content or animation. Atm if unsupported, both the effect and the Image it is applied to disappear. If not, should i file feature request for this?

**Comment by samme** [comment]
Same for me, iMac NVIDIA GeForce GT 650M 512 MB.

**Comment by michalfialadev** [comment]
> 



> Same for me, iMac NVIDIA GeForce GT 650M 512 MB.

That is also quite old (just like mine) card from 2012 (mine is 2013). IPhone7 is 2016. So to TLDR a list (in terms of further bug reports or feature requests):
1) improve preFX.addGlow perf
2) provide a way to check for HW support of specific preFX/postFX shader (from within Phaser, on device running it)
3) (ideally) provide fallback shaders for older hardware (this would work alongside (2))

**Comment by photonstorm** [comment]
In the master branch you'll see I've used a modified shader that doesn't do a for-loop discard. This alone should be enough to help performance. However, you can also set the `quality` and `distance` parameters of the glow. For a PreFX these are done in the game config:

```js
    fx: {
        glow: {
            distance: 32,
            quality: 0.1
        }
    }
```

For a PostFX you can do it via the `addGlow` method call:

```js
bomb.postFX.addGlow(0xffffff, 0, 0, false, 0.1, 32);
```

You'll see examples of this in the labs.

By tweaking the quality and distance settings you can assist older GPUs. However, the core shader change should also do that quite significantly.

**Comment by dbousamra** [comment]
This is still an issue in latest "^3.87.0"
