### ISSUE TITLE
Support setInteractive in Mesh/Plane game object

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6394]
From the document we know that Mesh/Plane game object does not support `setInteractive` method. 
According to this [demo](https://labs.phaser.io/edit.html?src=src/3.60/game%20objects/plane/click%20plane.js), it uses `mesh.hasFaceAt` method to detect clicking.

```javascript
const result = this.cards.find(card => card.hasFaceAt(pointer.worldX, pointer.worldY));
```

How about providing a specific *hitAreaCallback*, which counting hitting like

```javascript
function(shape, localX, localY, gameObject) {
    // worldX = ...
    // worldY = ..
    return gameObject.hasFaceAt(worldX, worldY);
}
```

So that user can still use `setInteractive` method and gameObject's pointer events, like normal game objects do.

I tried to create a PR for this feature but missing something like
- Getting `displayOriginX`, `displayOriginY`, for `inputManager.pointWithinHitArea` method.
- Transfer `localX`, `localY` position to `worldX`, `worldY` for `hasFaceAt` method.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
