### ISSUE TITLE
link in the shown javascript in line 5 is wrong.

### ISSUE THREAD

**Issue by Sathvik1007** [phaserjs/phaser#6395]
in file `phaser/src/physics/matter-js/typedefs/MatterWorldConfig.js` the 5th line link is not shown .
![aa](https://user-images.githubusercontent.com/124372859/219956615-d41a293e-6899-490a-905e-5c5bc907eac4.jpg)

**Comment by photonstorm** [comment]
Thanks for reporting this. It's fixed in our JSDocs and now appears correctly: https://newdocs.phaser.io/docs/3.70.0/Phaser.Types.Physics.Matter.MatterWorldConfig
