### ISSUE TITLE
ParticleEmitter.getEmitZone() error

### ISSUE THREAD

**Issue by paulsymphony** [phaserjs/phaser#6401]
## Version

* Phaser Version: 3.60.0-beta.19

* Operating system: MacOS 13.2.1

* Browser: Chrome

## Description

Uncaught TypeError: Cannot read properties of undefined (reading 'getPoint')

At completion of Phaser 3 Examples: 
https://labs.phaser.io/edit.html?src=src/3.60/game%20objects/particle%20emitter/emitter%20zone%20total.js

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by paulsymphony** [comment]
confirmed fixed in v3.60.0-beta.22 build
