### ISSUE TITLE
TypeError: sprite.onFXCopy is not a function

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6403]
## Version

* Phaser Version: 3.60.0-beta.19

## Description

> TypeError: sprite.onFXCopy is not a function

in [PreFXPipeline#copySprite](https://newdocs.phaser.io/docs/3.60.0-beta.19/Phaser.Renderer.WebGL.Pipelines.PreFXPipeline#copySprite).

## Example Test Code

```js
this.add.image(0, 0, '__DEFAULT').preFX.addBloom();
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
