### ISSUE TITLE
Gradient fx colors are dark gray

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6404]
## Version

* Phaser Version: 3.60.0-beta.19

## Example Test Code

```js
this.add
  .image(0, 0, '__WHITE')
  .setOrigin(0, 0)
  .setDisplaySize(128, 128)
  .preFX.addGradient(0xffff00, 0x0000ff);
```

Should appear yellow–blue, but it's dark gray.

## Additional Information

The `glcolor` values are in range 0–255 but the `color` setters are in range 0–1.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
