### ISSUE TITLE
Type improvement on Phaser.Events.EventEmitter.on(…)

### ISSUE THREAD

**Issue by DerZyklop** [phaserjs/phaser#6405]
## Issue

Here i use `Phaser.Events.EventEmitter`s `on()` method. 

<img width="499" alt="Screenshot 2023-02-26 at 10 55 41" src="https://user-images.githubusercontent.com/912344/221410693-7821086e-3533-4de9-9609-ddac5f9462fd.png">

It errors because I (and typescript) don’t like the type `any` in my project.

The documentation does not tell, but I figured out, that in my case the correct type would have been `Phaser.Input.Pointer`.  

The method is currently defined as:

```typescript
class EventEmitter {
            …
            on(event: string | symbol, fn: Function, context?: any): this;
```

The issue is that the type is `Function` where it should be `(input : Phaser.Input.Pointer) => void`.

## My proposed solution

A solution would be to have an overload. Example:

```typescript
class EventEmitter {
            …
            on(event: "pointerdown", fn: (input : Phaser.Input.Pointer) => void, context?: any): this;
            on(event: string | symbol, fn: Function, context?: any): this;
```

Or even better, in most cases a template literal type in that overload would do a great job. 

```typescript
class EventEmitter {
            …
            on(event: `pointer${string}`, fn: (input : Phaser.Input.Pointer) => void, context?: any): this;
            on(event: string | symbol, fn: Function, context?: any): this;
```

**Comment by photonstorm** [comment]
In essence, it sounds simple, but we would need nearly **300** overloads to handle this task, as the EventEmitter is used everywhere internally. for virtually every single system. And that's without even adding support for custom events (which you can easily create) or the dynamically named events (such as `Loader.Events#FILE_KEY_COMPLETE` - which could be a candidate for a template literal approach).

**Comment by photonstorm** [comment]
Going to close this issue as there's no practical solution as it currently stands, sorry.
