### ISSUE TITLE
Can't resize in renderTexture

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6411]
## Version

* Phaser Version: v3.60.0-beta.19

* Operating system: win10

* Browser: chrome/firefox

## Description

In this [test code](https://codepen.io/rexrainbow/pen/abaWBaX), RenderTexture will be resized from 64x64 to 128x128, to paste 4 images (each image is 64x64).
- v3.55.2 can resize correctly
- v3.60.0-beta.19 seems only set display size to 128x128, the size of DynamicTexture is not changed.

The root cause might be [this line](https://github.com/photonstorm/phaser/blob/master/src/renderer/webgl/RenderTarget.js#L211) : `renderTarget.autoResize` is set to `false` for DynamicTexture. So it can't resize ( re-create ) frame buffer correctly.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
