### ISSUE TITLE
Make camera.cull work with Containers

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6412]
Containers and container trees with display list items/leaves like Image are excluded from `camera.cull` completely, where the function always returns the items as 'visible on screen'. Its a bit hopium to think this should be included in the frame computations, because there is a cost included in recalculating the container tree children's rectangles, with their transforms etc, but perhaps a Utility to accept input array of any displayobject type (including containers) could be made, if user needs to specifically check for Rect intersection (not just camera) for those children to assist them in their own culling implementation. This would allow them to call it at any ti,me eg on per-frame basis (or otherwise).

Most likely i'm going to do this myself right now, so i might just share the code in discord's #code-snippets anyways..

Also, this downside to camera's `cull` for containers could be mentioned in the docs: https://newdocs.phaser.io/docs/3.55.2/focus/Phaser.Cameras.Scene2D.Camera-cull

```ts
// following logs array length: 1
const c:Phaser.GameObjects.Container = this.add.container(10000, 10000);
console.log(this.cameras.main.cull([c]));

// following logs array length: 0
const img: Phaser.GameObjects.Image = this.add.image(10000, 10000, "ui", "dealerChip.png");
console.log(this.cameras.main.cull([img]));
```

**Comment by photonstorm** [comment]
Containers have an infinite size, so they can never be culled as they stand. If you call `setSize` on them, they would be culled then (based on their size, not their children).

I guess `Camera.cull` could have a `useBounds` parameter, but even then it would still fail for a Container that had a Graphics object in it, for example, as those don't have sizes either.

**Comment by michalfialadev** [comment]
I see, i thought containers have their size calculated automatically based on children already. But im looking for more granular culling, where camera culls the leaves unless they are a graphics (that leaf would always render).

In my use-case, i have a container based vertical ScrollPane that is masked, and 90% of which is off screen (as it scrolls). I am looking to disable rendering of the 90% of leaf images and expensive dynamic Texts (that do have a getSize) that are the visible leaves that are off screen. As it stands, 90% of the 200-or-so images/texts are still rendered, even off screen. When i pass those images into camera.cull, they always trace 'visible in camera rect', even though they are outside of camera bounds. The simple way would be to forEach all container children that have a getSize and cull those (after accounting for their transforms i guess eg child.getWorldTransformMatrix). Its a bummer to not be able to think of a Container as 'something transparent behind the scenes that makes my life easier by providing structured layout', but have to deal with these extras myself to achieve visual parity with how scene objects render. Since it is more expensive to achieve visual parity between scene children/container children in terms of rendering output, perhaps making it available through an Util or optional parameters would solve for it.

I think next i will implement a culling Util, that can be called every frame in needed, which accepts list of objects, which can be a container with other renderable objects or containers. It will then check all the children that have their size available, and those that do, will transform their rect to world space and intersect against the camera bounds (or Rect supplied). Will invisible those outside of said rect. Or remove it from rendering if there is a method for that. That way you dont have to make Phaser's frame code more expensive, and its optional to do container tree culling using a Util.

**Comment by michalfialadev** [comment]
This is actually quite easy to do as the `getBounds` for container items already accounts for container tree transforms - something i didn't think worked before. Mentioned it here: https://discord.com/channels/244245946873937922/416623653741133837/1081309648801517578
Either way this can be closed.
