### ISSUE TITLE
SceneManager getScenes called after add is run

### ISSUE THREAD

**Issue by XanGrab** [phaserjs/phaser#6413]
## Version

* Phaser Version: v 3.60.0-beta.19

* Operating system: Linux-Ubuntu

* Browser: Non-specific (Firefox & Chrome)

## Description

When attempting to access the array of scenes from the `SceneManager` with the function `getScenes` after a scene is added to the game, an empty array is returned.

## Example Test Code

```
class MyScene extends Phaser.Scene {

    constructor (config)
    {
        super(config);
    }

    preload ()
    {
        this.load.image('face', 'assets/pics/bw-face.png');
    }

    create (data)
    {
        this.face = this.add.image(data.x, data.y, 'face');
    }

}

var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600
};

var game = new Phaser.Game(config);

game.scene.add('myScene', MyScene, true, { x: 400, y: 300 });
console.dir(game.scene.scenes);
console.dir(game.scene.getScenes(false));
```

## Steps to reproduce:

1. clone: https://github.com/photonstorm/phaser3-examples
2. modify the scene: "add scene after game.js" to console log the games' scenes through both direct access and from the getter method .getScenes()

expected: Both results return the same array
output: the getScenes() method returns an empty array, even directly after a scene has been added.

## Additional Information

![Screenshot from 2023-03-03 12-30-51](https://user-images.githubusercontent.com/60899653/222799687-deca81b0-f73b-4a8c-8e6c-0d4a3c769d74.png)

**Comment by photonstorm** [comment]
This is to be expected as the game has not yet booted, so the Scene Manager hasn't yet run. Run the same test after the game boot event and it will be populated.
