### ISSUE TITLE
Particles are slow for first 2 seconds

### ISSUE THREAD

**Issue by paulsymphony** [phaserjs/phaser#6415]
## Version

* Phaser Version: 3.60.0.beta-19

* Operating system:
* MacOS 13.2.1

* Browser:
Chrome

## Description

All Particles are slow at the start, then seem to pick up speed after a couple of seconds of running.

## Example Test Code

The code in the 'fire effects' demo shows this behavior clearly:
https://labs.phaser.io/view.html?src=src\3.60\game%20objects\particle%20emitter\fire%20effects.js

Note that the speed of the particles increases drastically after a couple of seconds. Also, if you focus on the URL bar, the particles slow down again, and you need to re-establish focus on the demo in order for them to speed up again.

**Comment by samme** [comment]
Try with

    { fps: { smoothStep: false } }

in game config.

**Comment by paulsymphony** [comment]
That works! Thank you.
