### ISSUE TITLE
TypeScript: Layer#add() doesn't accept an array

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6416]
## Version

* Phaser Version: 3.60.0-beta.19 and earlier

## Example Test Code

    this.add.layer().add([this.add.graphics()]);

> Argument of type 'Graphics[]' is not assignable to parameter of type 'GameObject'.

https://github.com/photonstorm/phaser/blob/b093ece6202e50b1354c67e57461e7114c8bd011/src/structs/List.js#L107

**Comment by Gathaa** [comment]
I think i understood the problem ,For example, if you have an array of layers called Array and you want to add them to a Layer object called myLayer, you can use a loop to add them one by one: 

We can use for loop:

const myLayer = new Layer();
for (const layer of Array) {
  myLayer.add(layer);
console.log(Array);
};

Also you can use foreach function : 

const myLayer = new Layer();
Array.forEach(layer => {
  myLayer.add(layer);
console.log(Array);
});

**Comment by photonstorm** [comment]
This should be ok now that `Layer.add` has been removed, which exposes `List.add` which is `@param {*|Array.<*>} child - The item, or array of items, to add to the list.`
