### ISSUE TITLE
Arcade physics has console logs on circle body overlaps

### ISSUE THREAD

**Issue by leha-games** [phaserjs/phaser#6420]
## Version

* Phaser Version: 3.60 beta 20

* Operating system: Windows 10

* Browser: Chrome

## Description

Arcade physics has console logs on circle body overlaps. It spams console including in production

## Additional Information
https://github.com/photonstorm/phaser/blob/v3.60.0-beta.20/src/physics/arcade/World.js#L1560
https://github.com/photonstorm/phaser/blob/v3.60.0-beta.20/src/physics/arcade/World.js#L1605
https://github.com/photonstorm/phaser/blob/v3.60.0-beta.20/src/physics/arcade/World.js#L1613
https://github.com/photonstorm/phaser/blob/v3.60.0-beta.20/src/physics/arcade/World.js#L1622
https://github.com/photonstorm/phaser/blob/v3.60.0-beta.20/src/physics/arcade/World.js#L1638

Maybe more. Thanks

**Comment by photonstorm** [comment]
Using beta releases in production is a pretty brave move tbh. Logs need to remain until I've resolved the issue they are related to, but your bundler can strip them out if you need (most have options for this, webpack certainly does).
