### ISSUE TITLE
ParticleEmitter renders flickering squares

### ISSUE THREAD

**Issue by EmilSV** [phaserjs/phaser#6425]
## Version
* Phaser Version: 3.60 beta 20

## Description
![billede](https://user-images.githubusercontent.com/3351370/227007287-888a7f09-9fb8-4351-a787-b64ade337d8c.png)
When a lot of Particle Emitter is on screen squares will begin to appear in weird patterns.
This only happen in the newest version of phaser after the updated particle system around beta 18

## Example Test Code
```javascript
class ParticlesSquare
    extends Phaser.Scene
{
     preload()
    {
        this.load.image("smokeTest", "https://labs.phaser.io/assets/particles/smoke0.png");
    }

     create()
    {

        const mainCam = this.cameras.main;
        const width = 1600;
        const height = 1200;

        mainCam.setBackgroundColor("#FFFFFF");
        mainCam.setZoom(0.50);
        mainCam.centerOn(width/2,height/2)

        for (let x = 0; x < width; x +=100)
        {
            for (let y = 0; y < height; y += 200)
            {
                this.add.particles(0, 0, "smokeTest", {
                    x,
                    y,
                    lifespan: { min: 3000, max: 5000 },
                    speed: { min: 5, max: 25 },
                    angle: { min: 270 - 10, max: 270 + 10 },
                    timeScale: 0.35,
                    gravityX: -2,
                    gravityY: -5,
                    scale: {
                        start: 0.33,
                        end: 1.2,
                        ease: Phaser.Math.Easing.Cubic.In
                    },
                    rotate: { min: 0, max: 360 },
                    alpha: { start: 0.6, end: 0 },
                    quantity: 1,
                    tint: [0x000000, 0x141414, 0x292929, 0x2e2e2e],
                    frequency: 25,
                    blendMode: Phaser.BlendModes.NORMAL,
                    particleBringToTop: true,
                });

            }
        }

    }
}
const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    parent: 'phaser-example',
    scene: ParticlesSquare
};

const game = new Phaser.Game(config);
```

**Comment by Gathaa** [comment]
Hi , the first issue maybe because of the hardware because rendering a lot of particles require good specs , also update the latest version of phaser then test it  .
another potential solution is to use a **Particle Container** in Phaser. A Particle Container is a container that can be used to group and render large numbers of particles efficiently 

Code :
const particleContainer = this.add.particles().createEmitter({...});
for (let x = 0; x < width; x +=100)
{
    for (let y = 0; y < height; y += 200)
    {
        particleContainer.setPosition(x, y);
    }
}
Hopefully This Works For You !

**Comment by photonstorm** [comment]
@Gathaa there's no such thing as a Particle Container in Phaser. The code given is entirely wrong for 3.60 as well. Is this more ChatGPT spam?

**Comment by Gathaa** [comment]
> @Gathaa there's no such thing as a Particle Container in Phaser. The code given is entirely wrong for 3.60 as well. Is this more ChatGPT spam?



Honestly , i looked online for the solution , the problem with the hardware and the phaser version was mentionnes , but the code given below is indeed using chatgpt legit i googled it did not find a good soluttion related to coding .

**Comment by jtsorlinis** [comment]
Not sure if this is related but I can replicate something similar in beta 23.

```
this.emitter = this.add.particles(10, 10, "particle", {
      frequency: 0.1,
      lifespan: Number.MAX_VALUE,
    });
```

It seems as soon as there's more than 4096 particles alive the textures start being replaced by white squares whenever a new particle is spawned.

**Comment by EmilSV** [comment]
thx @jtsorlinis the number 4096 helps.
 4096 is the default WebGL Batch size and i made some test and the bugs comes when Phaser.Renderer.WebGL.WebGLPipeline#flush is run doing particle rendering.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
