### ISSUE TITLE
RenderTexture repositioning texture in different locations for CANVAS and WEBGL

### ISSUE THREAD

**Issue by davesmg** [phaserjs/phaser#6428]
## Version

* Phaser Version: 3.55.2

* Operating system: Mac OS 13.0

* Browser: Chrome, Firefox and Safari (these were tested).

## Description

I'm trying to use a RenderTexture to mix 3 images to generate my character.
However, the alignment of the image within the RenderTexture changes according to the type defined in the Game() settings.
- If I select Phaser.CANVAS everything happens as expected.
- If I select Phaser.WEBGL (or AUTO, in my case) it is as if the origin of Y was centered and not at 0, that is, instead of selecting the character from the FIRST ROW it is selecting the one from the THIRD (as shown in the images).

Steps taken:
- Create a RenderTexture and save it.
- Draw all loaded frames on the loaded texture/image.
- Add the frames in the saved texture
- Finally add the texture to my character's Sprite.

## Example Test Code

    preload() {
        this.load.spritesheet('bodies', 'assets/bodies.png', {
            frameWidth: 16,
            frameHeight: 32
        });
    }

    
    create() {
        const rtx = this.make.renderTexture({
            width: 3008,
            height: 160,
        }, false);
        const ptx = rtx.saveTexture("RT_BODY");

        const frames = this.textures.get('bodies').getFramesFromTextureSource(0, false);
        
        for (const f of frames) {
            rtx.drawFrame('bodies', f.name, f.cutX, f.cutY);
        }

        for (const f of frames) {
            ptx.add(f.name, 0, f.cutX, f.cutY, f.width, f.height);
        }

        const player = this.add.sprite(0, 0, 'RT_BODY').setOrigin(0);
        player.setFrame(1);
    }

## Additional Information

My asset:
<img width="480" alt="Captura de Tela 2023-03-24 às 21 14 18" src="https://user-images.githubusercontent.com/29420207/227668511-39da00b6-d639-495e-a093-84fa3d7826e1.png">

Sprite frame loaded in CANVAS (correct alignment):
<img width="22" alt="Captura de Tela 2023-03-24 às 21 16 13" src="https://user-images.githubusercontent.com/29420207/227668555-10b39381-4da8-46a0-9f2c-bf4bcd38919f.png">

Sprite loaded in WEBGL (issue):
<img width="20" alt="Captura de Tela 2023-03-24 às 21 16 39" src="https://user-images.githubusercontent.com/29420207/227668602-0c37383d-17c8-4b5b-8b2f-f0034a7546d0.png">

I thank the attention!

**Comment by SlimHajRomdhane** [comment]
This issue may be related to the differences in how WebGL and Canvas handle texture coordinates. It's possible that the coordinates of the sprites in your RenderTexture are not being correctly translated from Canvas to WebGL coordinates.

One solution you could try is to manually adjust the Y-coordinates of the frames you're drawing to the RenderTexture, to account for the difference in origin. You could try something like this:

const yOffset = this.game.config.type === Phaser.WEBGL ? rtx.height / 2 : 0;
for (const f of frames) {
    rtx.drawFrame('bodies', f.name, f.cutX, f.cutY + yOffset);
}

This code checks if the game type is set to WebGL, and if so, adds a Y-offset to the coordinates of each frame. This offset should be half the height of the RenderTexture, to account for the fact that the Y-origin is centered in WebGL.
I hope this helps!
-SlimHR

**Comment by davesmg** [comment]
Thanks for the reply, @SlimHajRomdhane !
I really thought about changing the position of the frames on the texture but I thought it wouldn't be a good practice.
I didn't know that WEBGL and CANVAS treated texture placement differently, can you tell me if this is commented on in the documentation? I really searched before opening this issue but I didn't find it.
I'll follow your advice, switch positions, and compare with the interim solution I'm using, which is using CanvasTexture.

Thank you so much!

**Comment by photonstorm** [comment]
@davesmg have you tested this under 3.60 at all?

**Comment by davesmg** [comment]
@photonstorm yes, I tested it in several different versions and this behavior started to appear from version 3.50 and persists until the current one.  Before this version the positioning is perfect since the version where RenderTexture was implemented.

**Comment by photonstorm** [comment]
@davesmg looking at your code - you cannot use `Frame.cutX` and `Frame.cutY` like this. Those values are going to be different between Canvas and WebGL because in WebGL the Y axis is inverted (0x0 is the bottom left, not top left). This is just how WebGL works. You'll need to adjust for it in your code, or use a fixed value to draw the frame at, rather than one taken from the Frame object.
