### ISSUE TITLE
createFromAseprite() consecutively

### ISSUE THREAD

**Issue by yahoai** [phaserjs/phaser#6434]
I am using Phaser version 3.55.2 and there is a bug where only one animation exists when the createFromAseprite function is used consecutively.

For example:

```
const BodyTags = s.anims.createFromAseprite("Body");
const HeadTags = s.anims.createFromAseprite("Head");

console.log(BodyTags[0].frames[0], HeadTags[0].frames[0]);
```

When used like this, the output is as shown in the screenshot. How can I fix this issue?

![image](https://user-images.githubusercontent.com/2654930/227780727-bd377eeb-4f94-4ed8-aee9-6a6bac7ee6ac.png)

**Comment by photonstorm** [comment]
I need the assets to reproduce this, because it doesn't happen with the files I've got in the Phaser 3 Examples repo.

**Comment by yahoai** [comment]
A sample asset file has been included. An "Idle" animation exists.
It is being loaded and used as follows:
```
scene.load.aseprite(
      "Head",
      "aseprite/player/test/MainChrHead.png",
      "aseprite/player/test/MainChrHead.json"
    );

    scene.load.aseprite(
      "Body",
      "aseprite/player/test/MainChr.png",
      "aseprite/player/test/MainChr.json"
    );

```

Please check it. Thank you.

[Archive.zip](https://github.com/photonstorm/phaser/files/11107176/Archive.zip)

**Comment by photonstorm** [comment]
The problem is that both of your frameTags are called `Idle` and you're trying to add these to the same Sprite. So the second time you do it (with Head) it ignores it, because an animation with the key 'Idle' already exists (the one from Body).

If you want to use both animations on the same sprite you're going to have to rename them within Aseprite (BodyIdle, HeadIdle, etc) because in Phaser animations are key based and keys must be unique.

**Comment by yahoai** [comment]
If customization is required for each part, it is expected to be more efficient to make common animation keys.

Any thoughts on updating?

**Comment by photonstorm** [comment]
No, this cannot be changed. _Everything_ in Phaser 3 is string-key based, from textures to sounds to animations. If you want to add two animations to a single Sprite, they will need unique keys. It's as fundamental as that, I'm afraid.
