### ISSUE TITLE
3.60 cost doubled cpu than 3.55.2 in Nest.js?

### ISSUE THREAD

**Issue by ruanhaodong** [phaserjs/phaser#6437]
## Version
3.60beta21 

* Phaser Version:  3.60beta21 

* Operating system: MBP 2023 16G RAM

* Browser: Chrome

## Description

I loaded same TiledMap  with same code in Next.js project, the cpu cost doubled from 3.55.2 to 3.60(beta1-beta21)

![image](https://github.com/CesaerRyan/nextjs-phaser-cpu-diff/raw/main/public/3.55.2.png)
![image](https://github.com/CesaerRyan/nextjs-phaser-cpu-diff/raw/main/public/3.60.beta-21.png)

I think this problem is only in Next.js. 
I have tested 3.55.2 and 3.60  in CSR React (Vite+React) they don't have such problem (cpu has no dramatic difference )
Can anyone give a clue how to debug the problem? I even not sure this is a Phaser issue or Next.js issue.

## Example Test Code
To reproduce the issue, clone the repo 
https://github.com/CesaerRyan/nextjs-phaser-cpu-diff

**Comment by photonstorm** [comment]
As you can appreciate, there's no code related to Next.js inside of Phaser. I would suggest re-checking, if it's still an issue, against Phaser v3.70 / v3.80 and the latest version of Next.js too. Maybe device performance profiling will help narrow down what it's lagging on.
