### ISSUE TITLE
Remove/clear postFX's pixelate effect

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6440]
## Version

* Phaser Version: 3.60-beta 21

* Operating system: win10

* Browser: chrome, firefox

## Description

[Test code](https://codepen.io/rexrainbow/pen/dyqLpRq),

- Add then remove preFX 's pixelate effect works fine
- Can add postFX's pixelate effect , but remove/clear seems not work. No error message shown.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
