### ISSUE TITLE
Phaser3.60-beta22: What's your experience of using ESM? I see no difference

### ISSUE THREAD

**Issue by ProgrammingLife** [phaserjs/phaser#6444]
- Phaser 3.60 beta 22 is installed
- `production` mode in webpack. 
- `es2015` for "module" in tsconfig.ts
- Some simple code to test:
```js
import { AUTO, Scene, Game } from "phaser";
class Test extends Scene {
    constructor () { super(); }
    public create () {
        this.add.text(10, 10, 'Welcome to Phaser ESM');
    }
}
const config = {
    type: AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: [ Test ]
};
const game = new Game(config);
```

Webpack's build log:
```
asset index.js 13 MiB [emitted] [minimized] [big] (name: main) 1 related asset
runtime modules 663 bytes 3 modules
cacheable modules 7 MiB
  ./src/index.ts 438 bytes [built] [code generated]
  ../../node_modules/phaser/dist/phaser.js 7 MiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  index.js (13 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (13 MiB)
      index.js

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.72.0 compiled with 3 warnings in 42477 ms
```

And I get a js bundle of size: 1.1mb for such a simple code. Looks it gets all the Phaser's functions without properly making the shaking tree feature, it just pushes the whole source code. But what's the profit in using ESM then? 😀

**Comment by photonstorm** [comment]
I never claimed the ESM version would tree shake. It won't, and it can't. That's nothing to do with the module system being used and everything to do with the structure of the modules. It's also why Phaser 4 exists, as that was its primary goal.

However, you cannot import Phaser as a module directly in a web page using the CJS/UMD version. Browsers simply don't support that. So by producing an ESM version, you can now import it directly and start coding immediately without any packager or bundler required at all, which is significantly useful for testing things fast, producing Codepens, etc.
