### ISSUE TITLE
Some suggestions of new Particles class

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6445]
- Method `emitter.addEmitZone` accepts an array of zoneConfig, but only return a zone object.
  - Might remove array of zoneConfig supporting, or return zone object array.
- Add a `name` property of emit zone, or death zone object, then user can remove zone by name.
- Please add examples of using `setAnim` method.
- Typo. ParticleEmitter.js, line 1465, 1466 : scale -> speed

**Comment by rexrainbow** [comment]
Bug report:

[Test code](https://codepen.io/rexrainbow/pen/BaqBERw), there are 2 curves

Case 1: Start and end point are at the same position, will emit particles at (0,0)
Case 2: Start and end point are not at the same position, will emit particles along curve.

**Comment by photonstorm** [comment]
`addEmitZone` now returns an array always and I fixed the scale speed typo.

**Comment by photonstorm** [comment]
Forgot to close this one after making the beta changes.
