### ISSUE TITLE
TypeScript error TS2345 in tweens

### ISSUE THREAD

**Issue by Smirnov48** [phaserjs/phaser#6448]
## Version

* Phaser Version: 3.60.0-beta.22

## Description
TypeScript error:
```
 TS2345: Argument of type '{ targets: Phaser.GameObjects.Image; alpha: number; }' is not assignable to parameter of type 'Tween | TweenBuilderConfig | TweenChainBuilderConfig | TweenChain'.
  Object literal may only specify known properties, and 'alpha' does not exist in type 'Tween | TweenBuilderConfig | TweenChainBuilderConfig | TweenChain'.
```

Seems it broke in commit [9fbf2e2](https://github.com/photonstorm/phaser/commit/9fbf2e22f3ab41151adeafd1658ce78b455ce4f9)

I think a possible solution might be add one more type to "add" method. This one - Phaser.Types.GameObjects.GameObjectConfig

@param {Phaser.Types.Tweens.TweenBuilderConfig|Phaser.Types.Tweens.TweenChainBuilderConfig|Phaser.Tweens.Tween|Phaser.Tweens.TweenChain **|Phaser.Types.GameObjects.GameObjectConfig**} config - A Tween Configuration object, or a Tween or TweenChain instance.

## Example Test Code
            this.tweens.add({
                targets: this.background,
                alpha: 0 // TypeScript error TS2345
            });

**Comment by photonstorm** [comment]
Hmm, yes - sadly your PR won't fix it, as if you then try to tween, for example, a Sound, or FX, it will still error.

I think the solution is to have `@typedef {object} Phaser.Types.Tweens.TweenBuilderConfig` extend a base type like `object`.

**Comment by Smirnov48** [comment]
Oh right, I completely forgot about this usage. Thank you!
