### ISSUE TITLE
Remove/clear postFX's pixelate effect of camera

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6451]
## Version

* Phaser Version: 3.60-beta22

* Operating system: win11

* Browser: chrome, firefox

## Description

[Test code](https://codepen.io/rexrainbow/pen/dyqLpRq): Add pixelate post pipeline to camera then remove it.
It seems that `camera.postFX.remove` do nothing. The [`this.list`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/FX.js#L288) is empty in camera.

BTW, postFX of game object can be removed correctly from last bug fixing.

**Comment by photonstorm** [comment]
Isn't this just #6440 again? :)

**Comment by photonstorm** [comment]
Ahh no, specifically from a Camera. Ok.

**Comment by photonstorm** [comment]
Ok, looking at what I did last time it was wrong - I've now added a much more sensible `clearFX` method directly on the Game Object and tidied up the code within the FX Component too.

**Comment by rexrainbow** [comment]
Had not fixed in 3.60-beta.23 yet. 
See [previous test](https://codepen.io/rexrainbow/pen/dyqLpRq), the error message shown on console

```
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at initialize.getPostPipeline (phaser.min.js:1:195590)
```

**Comment by photonstorm** [comment]
There we go, definitely works now.

**Comment by rexrainbow** [comment]
Confirmed that postFX of game object and camera could be removed correctly. 👍
