### ISSUE TITLE
Missing tsdefs for scene pack files' AtlasJSONFileConfig

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6455]
* Phaser Version: 3.60b19

## Description
Please provide missing tsdefs for scene pack files' `AtlasJSONFileConfig`, as shown in picture:
<img width="487" alt="scene-pack-files" src="https://user-images.githubusercontent.com/36237028/230175480-dd943cd1-956a-415b-8ef7-bc50e8895f6a.png">

docs:
https://newdocs.phaser.io/docs/3.54.0/Phaser.Types.Loader.FileTypes.AtlasJSONFileConfig

Additional missing tsdefs for the other possible pack files objects (multi atlas, compressed multiatlas etc would be awesome to have as well). Originally i was looking to PR this myself, but i later found out its autogenerated from JSDocs using tsgen (which i dont know how to do yet, so i passed).

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
