### ISSUE TITLE
TweenBuilderConfig type is not support to other parameter likes x or y

### ISSUE THREAD

**Issue by PeterJSung** [phaserjs/phaser#6458]
## Version

* Phaser Version: 3.60.0-beta.22

* Operating system: macOS Ventura 13.0.1

* Browser: chrome 

## Description

The problem occurs when i run the application to that repository. (https://github.com/photonstorm/phaser3-typescript-project-template)
The code causing the problem is as follows.
```     
this.tweens.add({
    targets: logo,
    y: 350, // there is no y defined
    duration: 1500,
    ease: 'Sine.inOut',
    yoyo: true,
    repeat: -1
})
```

The y value or x value is not defined in the parameters of the add function. (actually, it works well)

The parameter definition of the add function is as follows, and it seems to actually use 'TweenBuilderConfig'.
```
add(config: Phaser.Types.Tweens.TweenBuilderConfig | Phaser.Types.Tweens.TweenChainBuilderConfig | Phaser.Tweens.Tween | Phaser.Tweens.TweenChain): Phaser.Tweens.Tween;
```

The problem is that the type of this 'TweenBuilderConfig' is composed of object Intersection Types, but an error occurs because the y or x parameter value cannot be included in the object type.
Here is the definition of 'TweenBuilderConfig' in 'phaser.d.ts'.

```
type TweenBuilderConfig = object & {
    targets: any;
    .........
```

I suggest converting object type to Record type.(Of course, it would be better to have a type like the actual x or y value.)

```
type TweenBuilderConfig = Record<string, any> & {
    targets: any;
    .........
```

thanks

**Comment by photonstorm** [comment]
Yeah this is already fixed in the master branch. Beta 24 will roll it out to the template repo.
