### ISSUE TITLE
Tile Rendering bug

### ISSUE THREAD

**Issue by VatsaDev** [phaserjs/phaser#6460]
## Version
* Phaser Version: v3.52.0
* Operating system: MacOS/Windows

## Description

So I have a tile map rendering in phaser, and whenever the character is not in movement, the tiles have green/black borders on them, as seen in this picture
![Screen Shot 2023-04-07 at 8 43 05 AM](https://user-images.githubusercontent.com/71975550/230620482-2122ee22-a6d6-4c89-bee9-51eb6eca3747.png)

I think this is a phaser related bug, but am I doing something wrong?

**Comment by photonstorm** [comment]
See https://github.com/sporadic-labs/tile-extruder
