### ISSUE TITLE
GetLayer can have undefined behaviour after removing a layer from a tilemap

### ISSUE THREAD

**Issue by JaroVDH** [phaserjs/phaser#6463]
## Version

* Phaser Version: 3.55.2
* Operating system: Any
* Browser: Any

## Description
Removing a Tilemap Layer from a Tilemap through the Layer itself causes some Tilemap functionality to break.
One example is map.getLayer/map.getLayerIndex, which indirectly breaks other stuff like worldToTileX

I believe it's happening because the Tilemap's currentLayerIndex is getting out of sync with the actual layer count.

## Example Test Code

```
const map = this.make.tilemap({ data: [[0]]}),
        tileset = map.addTilesetImage('tiles'),
        layer = map.createLayer(0, tileset, 0, 0);

    layer.destroy(true);

    // Exception
    map.worldToTileX(1);
```
Inside map.worldToTileX(), the [getLayer call](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/Tilemap.js#L2601) returns `undefined`, and worldToTileX only checks for `null`.
It returns `undefined` because it's trying to read a [currentLayerIndex](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/Tilemap.js#L1275) higher than the current layer count.

Another easy way to reproduce this is by slightly changing [this example](https://labs.phaser.io/edit.html?src=src/tilemap/map%20vs%20layer%20with%20multiple%20layers.js&v=3.55.2) and adding this somewhere near the end  in the create function:
```
waterLayer.destroy(true);
map.worldToTileX(1); // crash
```
That also shows it's not just because of removing the last layer as the example has 4.

**Comment by photonstorm** [comment]
I cannot reproduce this. If I add:

```js
        this.waterLayer.destroy(true);
        this.map.worldToTileX(1); // crash
```

at the end of the example you linked, it works fine. Because `TilemapLayer.destroy` calls `Tilemap.removeLayer`, which resyncs all of the layer IDs and resets the current layer index as well. This works fine on v3.70 but also I tested 3.55.2 and was fine on there too! So I think something else was going on with this issue.
