### ISSUE TITLE
Warning Message in Console when assets to Preload are not found.

### ISSUE THREAD

**Issue by whatevea** [phaserjs/phaser#6464]
It would be helpful if the assets file that are to be loaded are not found  SHOWN BY WARNING MESSAGE , Just like when Frames in Spritesheet doesn't exist It does. 

![dsddd](https://user-images.githubusercontent.com/49833723/230817439-c2500d79-ed58-43e7-97ea-c43282ae101b.png)

for example in preload i could do ``` this.load.image("img","something.png") ``` 
And even if there is no file with such name, it would not show any warnings.

**Comment by photonstorm** [comment]
Thanks for the suggestion but I won't be adding this because Dev Tools already provides a highly detailed network panel, from which it's easy to spot missing or broken files. Whereas nothing can help you with missing animation frames other than Phaser itself.
