### ISSUE TITLE
Video game object can't setDisplaySize

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6475]
## Version

* Phaser Version: 3.60.0

* Operating system: win11

* Browser: chrome/firefox

## Description

Video game object does not have `frame` property, thus it can't get [`video.frame.realWidth`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/components/Size.js#L68) for setDisplaySize method

## Example Test Code

From this [test code](https://labs.phaser.io/edit.html?src=src\game%20objects\video\play%20video.js),

Replace line 15 to

```js
const intro = this.add.video(640, 360, 'spaceace').setDisplaySize(200, 200);
```

And it will show error message

```
caught TypeError: Cannot read properties of null (reading 'realWidth')
    at Video.set [as displayWidth] (Size.js:73:1)
    at Video.setDisplaySize (Size.js:181:1)
    ...
 ```

BTW, how to preload video coss-origin? 
Previously, `asBlob` parameter seems can be used for coss-origin.

**Comment by photonstorm** [comment]
LoadURL method has crossOrigin parameter now.

**Comment by JoeSiu** [comment]
Facing the same issue in Phaser 3.60.0 with the video game object does not have frame property. I am using rex's UI plugin (v1.60.2) as well, and for example if I try to add a video object into a UI sizer, same error `Cannot read properties of null (reading 'realWidth') at Video.get [as displayWidth]` will be shown.

A temporary solution I found is to assign a random placeholder texture to the video. For example, from the same [test code](https://labs.phaser.io/edit.html?src=src%5Cgame%20objects%5Cvideo%5Cplay%20video.js), add an image load to the preloader

```js
this.load.image('placeholder', 'assets/textures/grass.png');
```

then replace line 15 to

```js 
const intro = this.add.video(640, 360, 'spaceace').setTexture('placeholder').setDisplaySize(200, 200);
```

will result in no error and the size is changed, although the size seems to be dependent to the placeholder's texture size

**Comment by rgk** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the master branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
