### ISSUE TITLE
The "Hello world" in the "Getting Started" documentation is broken when using the latest phaser version

### ISSUE THREAD

**Issue by bfanger** [phaserjs/phaser#6476]
## Version

* Phaser Version: 3.60.0

* Operating system: all

* Browser: all

## Description

`Uncaught Error: createEmitter removed. See ParticleEmitter docs for info`

## Example Test Code

https://phaser.io/tutorials/getting-started-phaser3/part5

The new notation is:
```
  const emitter = this.add.particles(0, 0, "red", {
    speed: 100,
    scale: { start: 1, end: 0 },
    blendMode: "ADD",
  });
```

**Comment by rationality6** [comment]
Thank you, I solved it with this.

**Comment by baiseng** [comment]
how tuo fix?

**Comment by photonstorm** [comment]
@baiseng the guide was updated just now with more content and fixed code, so please just refresh the page to see!
