### ISSUE TITLE
Provide a way to kill tweens#addCounter similar to tweens#killTweensOf for tweens

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6481]
Currently there is no way to kill a running counter tween (unless i'm missing something), without making a referential variable for it and calling `counterRef.destroy()` (or `remove`).

Tweens created using `this.tweens.add` can be killed using `killTweensOf` on their `target`, in addition to being able to clear them using a reference variable.

It might be preferred to keep it CLEAN and provide a method to clear number tweens this way too. There is probably an internal `target` counter tweens use? Would it be reasonable to have a `this.tweens.killCounters` or similar? Or an optional `target` to kill by target as well?

**Comment by samme** [comment]
Counter tweens have a target (the counter), which you can use with `killTweensOf()`.

```js
const [ counter ] = counterTween.targets;

this.tweens.killTweensOf(counter);
```

You could search the running tweens yourself and identify the counters with

    typeof tween.targets[0].value === 'number'

**Comment by michalfialadev** [comment]
^ fair enough, thanks!
