### ISSUE TITLE
Orientation fault

### ISSUE THREAD

**Issue by spayton** [phaserjs/phaser#6484]
## Version

* Phaser Version: 3.60.0

* Operating system: iPhone iOS 14/15/16

* Browser: Chrome

## Description

On iPhone ios14/15/16 the orientation is switched on Chrome but correct on Safari.

This was noticed in my app then reproduced with labs orientation example, here: [https://labs.phaser.io/mobile.html?src=src/scalemanager/orientation%20check.js](url)

On an iPhone13 ios16, this is Chrome incorrectly identifying portrait mode and requesting switch to landscape

![image](https://user-images.githubusercontent.com/4949575/233209792-bf1dec31-3874-4a31-888f-7d03f4b5cc8c.png)

On same phone, this is safari correctly identifying landscape and not requesting any change.

![image](https://user-images.githubusercontent.com/4949575/233210092-14c7d955-1397-4f8d-9276-3539ff3a0f09.png)

## Additional Information

Whilst both browsers correctly start, the problem occurs on the 1st device rotation and thereafter.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
