### ISSUE TITLE
*BLOCKED* on school chromebook.

### ISSUE THREAD

**Issue by maverickteckh** [phaserjs/phaser#6485]
**We're constantly trying to make Phaser 3 better**
So, in my school district Phaser is blocked so can you guys provide an unblocked IDE or a downloadable IDE.
![image](https://user-images.githubusercontent.com/74848706/234867089-16024116-5103-4a89-955e-f53179302ec3.png)

**Comment by photonstorm** [comment]
There is no IDE for Phaser. It's a JavaScript library, and you're in the right place to download it (GitHub). Pick whatever editor you fancy using (Visual Studio Code, Sublime, Atom, etc).
