### ISSUE TITLE
3.55.2 vs 3.60.0 android perfomance

### ISSUE THREAD

**Issue by ddanushkin** [phaserjs/phaser#6495]
After using [this](https://github.com/themoonrat/webgl-benchmark) benchmark, I noticed that the performance of 3.60.0 is lower than 3.55.2, at least on my android)

Benchmark dont support 3.60 out of the box
Modify [this](https://github.com/themoonrat/webgl-benchmark/blob/master/src/js/phaser3/load.js) file
`const versions = [..., 3.60.0]`

I used this query parameters:
`/?library=Phaser3&version=3.60.0&scene=1&objectCount=20000`
`/?library=Phaser3&version=3.55.2&scene=1&objectCount=20000` 

![image](https://user-images.githubusercontent.com/42466730/236641610-2fd4f28a-36f5-495d-88e9-a21ad052dabf.png)
![image](https://user-images.githubusercontent.com/42466730/236641628-9de99f22-83f6-42e3-9808-3f7856dc7112.png)
![image](https://user-images.githubusercontent.com/42466730/236641636-f22cd1c6-576b-4b18-9a05-55602b5e3f2d.png)

**Comment by ProgrammingLife** [comment]
Is WebGL2 supported on your device? What's the device it is?

**Comment by ddanushkin** [comment]
> Is WebGL2 supported on your device? What's the device it is?

Yes, Xiaomi Mi 9T Pro.
Currently we use WebGL2 context with 3.55.2 because it give us better perfomance on iOS.
Like [so](https://labs.phaser.io/edit.html?src=src/game%20config/custom%20webgl2%20canvas.js).
update: Oh i think it's not WebGL2 itself, it's diffrent contextAttributes

**Comment by photonstorm** [comment]
We tested this on quite a range of hardware. Here is 3.70 doing 105k sprites on an ancient Samsung Tab:

![image](https://github.com/phaserjs/phaser/assets/164476/c0895f6b-b0e4-4d0b-bc05-0dc7c60df592)

You can force Phaser to use the `MobilePipeline` by setting `defaultPipeline="MobilePipeline"` in the game config. You can also disable Post and Pre FX, to cut down on shader creation, and also adjust the batch size and anti-aliasing to tweak performance further. If you've a Phaser code sample that demonstrates the difference, and you've tried the various renderer config options we make available, feel free to post it. As it stands, the vast majority of mobile devices will perform infinitely better in any version past 3.55.
