### ISSUE TITLE
Typescript bug. VideoFrameCallbackMetadata

### ISSUE THREAD

**Issue by pabloNeuronup** [phaserjs/phaser#6496]
Version Phaser 3.60
When executting the project with Angular:

Error messages:
- Error: node_modules/phaser/types/phaser.d.ts:52598:23 - error TS2304: Cannot find name 'VideoFrameCallbackMetadata'.
  Line 52598: metadata: VideoFrameCallbackMetadata;
- Error: node_modules/phaser/types/phaser.d.ts:52720:67 - error TS2304: Cannot find name 'VideoFrameCallbackMetadata'.
  Line 52720: requestVideoFrame(now: DOMHighResTimeStamp, metadata: VideoFrameCallbackMetadata): void;

Seems ok to delete 'metadata' from phaser.d.ts

**Comment by Blockost** [comment]
I encountered the same problem, so I rolled back to `v3.55.2` 😞

**Comment by photonstorm** [comment]
This is a valid data type, part of the W3C standard. But it's brand new, so needs an up to date lib.dom. Pretty sure TS5 handles it natively now.

**Comment by johanlindfors** [comment]
Can confirm that upgrading Typescript to latest (5.1.3) solves this issue.

**Comment by photonstorm** [comment]
Closing this as all it needs is a current version of TypeScript.
