### ISSUE TITLE
Add letterSpacing to GameObjects.Text

### ISSUE THREAD

**Issue by Ariorh1337** [phaserjs/phaser#6504]
Add the ability to set the letterSpacing parameter for GameObjects.Text
Currently similar logic exists for GameObjects.BitmapText

**Comment by Gathaa** [comment]
Hello , in order to add spacing you can set the letterspacing method on GameObjects.text , let's assume you have create a text 
```
text.setLetterSpacing = function(letterSpacing) {
  this.style.letterSpacing = letterSpacing;
};
```
now if you test it with a text as you can see here :
text.setLetterSpacing(n); 
this will set the letterspacing to n pixels , is this what you requested  ?

**Comment by Ariorh1337** [comment]
> Hello , in order to add spacing you can set the letterspacing method on GameObjects.text , let's assume you have create a text
> 
> ```
> text.setLetterSpacing = function(letterSpacing) {
>   this.style.letterSpacing = letterSpacing;
> };
> ```
> 
> now if you test it with a text as you can see here : text.setLetterSpacing(n); this will set the letterspacing to n pixels , is this what you requested ?

The (letterSpacing) property you refer to in the TextStyle class does not exist, and therefore the example you provided will not work. You can verify this by looking at the class file: [Phaser.GameObjects.TextStyle](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/text/TextStyle.js)

**Comment by Gathaa** [comment]
i really do appologize for the missunderstanding  

```
const letters = text.split('');

  const textObjects = [];

  for (let i = 0; i < letters.length; i++) {
    const letter = letters[i];

    const letterText = scene.add.text(x + (i * letterSpacing), y, letter, style);

    textObjects.push(letterText);
  }

  return textObjects;
}
```
i have red the textStyle File , maybe if i start by creating an empty array called textObjects to store the individual Text objects representing each letter and then we iterate over each letter and The x position of each letterText is adjusted to create the desired letter spacing effect. We calculate the adjusted x position using the formula x + (i * letterSpacing). Here, i represents the index of the current letter, and letterSpacing is the desired spacing between letters. by multiplying i with letterSpacing, we increment the x position for each letter based on the desired spacing. at the end we push it in our array called textObjects.

**Comment by Ariorh1337** [comment]
This task was created just to attach my pull request to it which add the feature.

You can check my solution from the link: https://github.com/photonstorm/phaser/pull/6505/commits/b84ee33cc23604583c77a4a04b476e8cdb2ccefe


> i have red the textStyle File , maybe if i start by creating an empty array called textObjects to store the individual Text objects representing each letter and then we iterate over each letter and The x position of each letterText is adjusted to create the desired letter spacing effect. We calculate the adjusted x position using the formula x + (i * letterSpacing). Here, i represents the index of the current letter, and letterSpacing is the desired spacing between letters. by multiplying i with letterSpacing, we increment the x position for each letter based on the desired spacing. at the end we push it in our array called textObjects.

The solution you're suggesting doesn't work, because creating many separate game objects will definitely result in performance degradation. In addition, this solution will add complexity if the text should change as a result of something, for example, add a line break.

**Comment by Gathaa** [comment]
You're right, creating multiple separate Text objects can lead to performance degradation and add complexity, especially when the text needs to change dynamically or include line breaks. In such cases, an alternative approach is to extend the `Phaser.GameObjects.Text` class and override its `updateText` method to incorporate letter spacing.

**Comment by rexrainbow** [comment]
@Gathaa There has no `letterSpacing` parameter in text.style, neither in member of text game object.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
