### ISSUE TITLE
Camera jitter when camera rounds pixels

### ISSUE THREAD

**Issue by bushdiver** [phaserjs/phaser#6509]
## Version

* Phaser Version: 3.60

* Operating system: macOS 13.3.1

* Browser: Chrome 113

## Description

There seems to be an issue with tileset bleeding and camera jittering in Phaser 3.50+ when using pixel art and camera follow along with a tileset. The camera's roundPixels property, when set to true, fixes the tileset bleeding issue but introduces camera jittering when following the player sprite.

## Example Test Code

The "Follow zoom" example exhibits the jittering issue when the camera is using round pixels with the version set to 3.50 or higher: 
https://labs.phaser.io/view.html?src=src/camera/follow%20zoom.js 

The jitter problem does not occur in Phaser version 3.24.

## Additional Information

We found a temporary solution by modifying the preRender function in the Camera object in Phaser 3.60 to match the version in Phaser 3.24, which resolved the jitter and tile bleeding issue. It might be worth investigating the changes made to the preRender function between these versions to identify potential causes of this issue.

**Comment by onurusluca** [comment]
Getting this also. Can you share your temporary solution?
Also for others who are having the same problem, maybe take a look at this:
https://phaser.discourse.group/t/roundpixels-is-causing-jittering-with-cameras-main-startfollow/11880/8

**Comment by samme** [comment]
You can use Phaser [3.60.0-beta.21](https://labs.phaser.io/view.html?src=src/camera/follow%20zoom.js&v=3.60.0-beta.21) if that's acceptable.

**Comment by likwidgames** [comment]
Any updates on this? It seems to have broken after beta.21, including the full 3.60 release.

**Comment by likwidgames** [comment]
Something after 3.60.0-beta.21 caused camera jitters again.

Working fine, no jitter:
https://labs.phaser.io/view.html?src=src/camera/follow%20zoom.js&v=3.60.0-beta.21

Jittery movement again:
https://labs.phaser.io/view.html?src=src/camera/follow%20zoom.js&v=3.60.0-beta.22

Happens in 3.61.0-beta.1 as well, so I don't believe this has been addressed.

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser/commit/6d49b9430516cc6f2007b536c9e175d7e2c6a8bc

**Comment by likwidgames** [comment]
@photonstorm do you have an ETA on fixing the issue introduced in the commit you posted above?

**Comment by photonstorm** [comment]
Closing as this is finally fixed in the master branch, partly thanks to the new round pixel shader code and also an internal change in how it's calculated. See the change log for full details about what's new regarding this.
