### ISSUE TITLE
Error: GetLast function not implemented correctly

### ISSUE THREAD

**Issue by dmokel** [phaserjs/phaser#6513]
## Version

* Phaser Version: v3.60.0

* Operating system: macOS Monterey

* Browser: Chrome

## Description

From a semantic perspective, the GetFirst method returns the first element in the array that has properties which match all of those specified in the compare object and the GetLast method returns the last element in the array that has properties which match all of those specified in the compare object. But their source codes are the same now.

The GetLast function code is incorrect.
![image](https://github.com/photonstorm/phaser/assets/68946469/7a235dfa-2f2a-4b99-93cc-820e2a3b7e38)
![image](https://github.com/photonstorm/phaser/assets/68946469/834fe67f-521e-40aa-950f-2b231bd45435)

**Comment by Arunabh-gupta** [comment]
Hey is anyone working on this issue?? If not can you assign it to me??

**Comment by rexrainbow** [comment]
@Arunabh-gupta Already [PR](https://github.com/photonstorm/phaser/pull/6514) by author of this thread

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
