### ISSUE TITLE
ParticleEmitter explodes on creation, when both advance > 0 and emitting: false are present

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6516]
## Version
* Phaser Version: 3.60.b19

## Description
ParticleEmitter explodes on creation when using (example values):
```ts
advance: 5000,
emitting: false,
```
Expected behavior: nothing emits, until `emitting` is set to `true`. 

Current workaround is to 1) not set `advance` in config, 2) set `emitting` to `true` and call 3) `myParticleSystem.fastForward(5000);` but that defeats the purpose of having both props settable using config.

**Comment by samme** [comment]
I would consider this expected. 🙂 And the alternative seems super complicated.

**Comment by photonstorm** [comment]
You've advanced the time of the emitter via `advance`, thereby implicitly making it start emitting. Both properties are valid in the config, but they serve different purposes, really.
