### ISSUE TITLE
Korean texts do not render correctly in custom fonts

### ISSUE THREAD

**Issue by klaritan** [phaserjs/phaser#6521]
## Version

* Phaser Version: 3.60

* Operating system: Windows Firefox, Android 13 WebView, etc. 

## Description

There are many methods (using invisible DOM objects on the HTML file, attempting to load fonts via various scripts like Google's webfontloader, using css and @font-face, etc.) to load custom/local fonts.

No matter what, Korean texts do not render correctly in specified font (we tried .ttf). It would look like either one or two letter is applied while other letter looks like it's falling back to the default font in the same text object. This usually happens when you load the page for the first time (or Ctrl+F5 on Firefox for clean refresh), or all the time on WebView via Android simulators and real phones. On WebView specifically, since they do not cache fonts, they do not load the font at all and falls back to default font every boot.

Reports we got from our Korean customers vary, but it simply does work well.

We've used loading fonts in the preload() function, using CSS and hiding DOM using those fonts off the screen, or using various font loading libraries to pre-load them, but Korean letters only seem to have issues with it on Phaser.
We don't have any Japanese or Chinese users yet, but they also may be suffering from the same issue. We were only able to verify Korean at the moment.

English fonts RARELY have this issue when we spam Ctrl+F5 refresh as well, but it's much harder to reproduce.

**Comment by photonstorm** [comment]
I'm going to need to see the actual code for this because I've worked on a number of massive Korean language games with a Korean game studio that obviously uses Korean text everywhere without issue in Phaser CE, 3.55, and 3.60, so this issue has to do with the implementation I'm afraid.

![image](https://github.com/photonstorm/phaser/assets/164476/cd38b36f-d818-4fa0-a61e-49a96b560daf)
