### ISSUE TITLE
Is it possible to easily build Phaser without any physics engine in it?

### ISSUE THREAD

**Issue by ProgrammingLife** [phaserjs/phaser#6525]
I am a big fan of small builds. There are many projects those don't use physics at all. Maybe it would be a good feature to distribute a Phaser without physics engines? Or easily make a such build on my own but I think it's a lot of work to remove physics from every Phaser version.
What do you think guys?

**Comment by photonstorm** [comment]
It's pretty easy to do, and we have a guide on how to do it linked from our README: https://github.com/photonstorm/phaser3-custom-build#creating-custom-phaser-3-builds
