### ISSUE TITLE
Please add the window syntax for spine 4.x runtimes build command

### ISSUE THREAD

**Issue by MagicalMontra** [phaserjs/phaser#6528]
## Version
3.6.0

## Description
I ran into a problem while trying to build a runtimes lib of spine with windows

## Code
Please add a new command for windows for make it work within the same 'plugin.spine4.x.runtimes' command,
within windows environment you need to use this instead

`cd plugins/spine4.1/spine-runtimes/spine-ts && npm run build:canvas && npm run build:webgl && copy spine-canvas\\dist\\iife\\* ..\\..\\src\\runtimes && copy spine-webgl\\dist\\iife\\* ..\\..\\src\\runtimes`

**Comment by photonstorm** [comment]
Please use a more featured console app on Windows. I use ConEmu and the Spine npm commands work fine on it.

https://conemu.github.io/

Also, make sure you have the runtimes repo checked out in the spine4.1 folder.
