### ISSUE TITLE
RenderTexture drawFrame() doesn't honour the padding of a trimmed frame

### ISSUE THREAD

**Issue by spayton** [phaserjs/phaser#6530]
## Version

* Phaser Version: 3.60

## Description

Using a renderTexture's drawFrame() method doesn't take into account any trimming set in the frame, so will not be drawn to the expected location.

## Example Test Code

I'll create an example.

**Comment by spayton** [comment]
Go to an editable labs example, eg [here](https://labs.phaser.io/edit.html?src=src/game%20objects/render%20texture/atlas%20frame%20to%20render%20texture.js&v=3.60.0-beta.23) and replace code with the following.

```js
class Example extends Phaser.Scene {

    preload() {
        this.load.atlas('match3', 'assets/atlas/match3.png', 'assets/atlas/match3.json');
    }

    create() {

        // 1st image, frame has padding so appears offset from origin
        const img = this.add.image(0, 0, 'match3', 'Match3_Icon_32')
            .setOrigin(0);

        // 2nd image, same frame drawn to rt at origin, should overlap 1st image
        const rt = this.add.renderTexture(0, 0, 800, 600)
            .setOrigin(0)
            .drawFrame('match3', 'Match3_Icon_32');
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: Example
};

const game = new Phaser.Game(config);
```

I would expect the two heart images to draw at the same place and overlap exactly, instead I see two hearts drawn at different positions, like this:

![image](https://github.com/photonstorm/phaser/assets/4949575/fd4c05ac-283f-4167-a6d4-971c7e0b4cdc)

**Comment by photonstorm** [comment]
Internally this is how `batchTextureFrame` needs to work (Dynamic Texture just piggy backs off this pipeline function). To get around it, you could use the `stamp` method instead, as that uses the internal Sprite instance for all drawing, so it should pick up the padding too.

**Comment by spayton** [comment]
ok, understood.  The stamp method did pick up the padding.  Thanks

**Comment by spayton** [comment]
based on reply, not a fault and the desired behaviour can be accomplished using a different method
