### ISSUE TITLE
Tween.remove() causes error "Cannot read properties of null (reading 'remove')"

### ISSUE THREAD

**Issue by orcomarcio** [phaserjs/phaser#6539]
## Version

* Phaser Version: 3.60

* Operating system: Windows 11

* Browser: Chrome

## Description
Launching .remove() on a tween causesthe following error: 
`Uncaught TypeError: Cannot read properties of null (reading 'remove')`

This call used to work on the previous patch.

## Additional Information
![image](https://github.com/photonstorm/phaser/assets/102031127/7d2db7bb-9f7b-43cb-a523-3e781f1562ad)

**Comment by photonstorm** [comment]
How are you removing it? Because this works fine:

```js
        const van = this.add.image(100, 100, 'van');

        const tween = this.tweens.add({
            targets: van,
            x: 700,
            y: 500,
            duration: 2000,
            loop: 4
        });

        this.input.on('pointerdown', () => {
            tween.remove();
        });
```

**Comment by orcomarcio** [comment]
Sorry, I purposefully didn't add the code example because the whole process is spread across my framework and there wasn't a easy way to put it here concisely.

I'm gonna investigate further. I wonder if in the old patch tweens weren't automatically removed when they finished, so removing it after the fact didn't give error. The weird thing is that if i put stop() instead of remove() it doesn't give an error, and reading the comments on these function i think stop() is the cleanest way to remove a tween anyway.

**Comment by photonstorm** [comment]
In 3.60 (Final) Tweens are automatically cleaned-up and destroyed by the Tween Manager. If you need to do this early, you can call `stop` on them to create the same result. Doing this _after_ the Tween is already destroyed will cause an error. If you don't want this feature and need your Tween to be long-lived and fully under your control, you can add the `persists: true` parameter to the tween config. It's then up to you when you nuke it (handy for stuff like tweens linked to UI events).
