### ISSUE TITLE
Make Tiled tile layer ID accessible from Phaser.Tilemaps.LayerData

### ISSUE THREAD

**Issue by rui-han-crh** [phaserjs/phaser#6541]
In Tiled, unique layers are identified by their layer ID. Two layers may have the same name in Tiled, but can be disambiguated via their ID. While all other properties, such as name, x, y, alpha, height and width can be accessed from a `LayerData` object, the ID is seeming not parsed from the map.

### Request
To make the id property accessible from the LayerData, after creation of a tilemapLayer via `createLayer`.

### Example usage

```ts
const tilemapLayer = this.tilemap.createLayer(this.tilemap.layers[i].name, this.tilemap.tilesets) as TilemapLayer;

console.log(tilemapLayer.layer.name); // -> Logs name as shown in Tiled
console.log(tilemapLayer.layer.id); // -> Logs unique layer id as shown in Tiled
```

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.
