### ISSUE TITLE
PostFX of Rope game object

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6550]
## Version

* Phaser Version: 3.60

* Operating system:

* Browser: 

## Description

Rope game object has [PostPipeline component](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rope/Rope.js#L70), but it does not invoke `this.initPostPipeline()` inside constructor, thus it won't have preFX neither postFX instances, imo.

**Comment by photonstorm** [comment]
Fixed. You cannot use PreFX on Rope, but Post FX is fine.
