### ISSUE TITLE
Particles' alpha value "wraps" if greater than 1 (ex. 1.7 behaves like 0.7)

### ISSUE THREAD

**Issue by orcomarcio** [phaserjs/phaser#6551]
## Version

* Phaser Version: 3.60

* Operating system: Windows 11

* Browser: Chrome

## Description
When giving particles an alpha greater than 1, the applied alpha is wrapped. For example, if a particle has alpha 1.5 it shows on screen as if it had alpha 0.5. This behaviour is not mirrored by other objects like sprites.
The value doesn't wrap the other way around (-0.5 shows as 0 for example).

If you wonder why that creates problems for me, I often key alpha with out of bounds values to manipulate the timings, for example if want something to finish fading in half way through the tween i will set value like this **alpha: { from: 0, to: 2 }**

I think i can use an Interpolation Object instead now in 3.6, but I though this might be of interest since it doesn't aling with how alpha works with normal objects.

## Example Test Code
![image](https://github.com/photonstorm/phaser/assets/102031127/8f4e4912-8531-498a-a78a-42ee9f50a399)

In this particular example particles fade in 3 times.

## Additional Information
P.S. I tried using an **Interpolation Object** and it works, although in the documentation it says that by default interpolation is linear, but if I dont declare it it doesn't work.
![image](https://github.com/photonstorm/phaser/assets/102031127/6a321326-95db-434a-84cd-dea953ea4f21)

Works:
![image](https://github.com/photonstorm/phaser/assets/102031127/fb7b4202-4b48-48ec-9961-4fe124d5eb74)

Doesn't work:
![image](https://github.com/photonstorm/phaser/assets/102031127/d661aefb-a648-404c-a61a-37983f09f5b9)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by orcomarcio** [comment]
Tested and it works propery now thanks
