### ISSUE TITLE
addSpriteSheet fails with texture as the second argument

### ISSUE THREAD

**Issue by saaska** [phaserjs/phaser#6552]
## Version

* Phaser Version: 3.60.0

* Operating system: Windows 11

* Browser:

## Description

The addSpriteSheet method of Texture Manager errors out when passed a Texture as the second argument. 

**Expected behavior:** a sprite sheet is added to an existing Phaser Texture. 

**Actual behavior:** an exception is thrown: `Uncaught TypeError: Cannot read properties of null (reading 'key')
    at TextureManager2.addSpriteSheet (phaser.js:211841:27)`

## Example Test Code

```js
this.tilesheet = this.textures.addSpriteSheet(
    'tilesheet', 
    this.textures.get('thesheet'), 
    {frameWidth: 64, frameHeight: 64, margin: 1, spacing: 2, startFrame: 1}
)
```
[(codepen)](https://codepen.io/av-pavlov/pen/oNQyXLq)

## Additional Information

The error is caused by the addSpriteSheet method assigning a local variable `texture` to null and trying to access `the .key` property on this variable.
```js
addSpriteSheet: function (key, source, config, dataSource)
{
        var texture = null;

        if (source instanceof Texture)
        {
            key = texture.key;
        texture = source;
        }

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
