### ISSUE TITLE
Accept Vector2Likes for Path creation

### ISSUE THREAD

**Issue by wayfu** [phaserjs/phaser#6557]
Currently, we can start a path with a separate x and y or a JSON object in the creator function, and then functions like lineTo and moveTo accept separate x and y values or Vector2s. It would be convenient if Vector2Like were added to the input options, so that we could easily build paths using existing objects' positions, output from various Phaser operations, etc.

**Comment by MohamedElhawy** [comment]
❤️

**Comment by rgk** [comment]
Both `lineTo` and `moveTo` now support Vector2Like, actually `moveTo` already worked but now it is documented.

Thank you for submitting this issue. We have fixed this and the fix has been pushed to the master branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
