### ISSUE TITLE
Tampering with the html just after game.destroy() might cause an endless chain of error

### ISSUE THREAD

**Issue by orcomarcio** [phaserjs/phaser#6559]
## Version

* Phaser Version: 3.60

* Operating system: Windows 11

* Browser: Chrome

## Description
For a few reason that are too long to explain I empty the parent of the DOM container "by hand" after calling game.destroy(). In the 3.5 it didn't give any problem, but in the 3.6 causes endless errors.
![image](https://github.com/photonstorm/phaser/assets/102031127/5dd41aad-ed28-48fd-a627-fb66c5fcc3de)

The main issue is this code in **Phaser.Game#runDestroy** 
![image](https://github.com/photonstorm/phaser/assets/102031127/215db703-1f64-4b6e-9e82-349b3aa6da5a)

As you can see it checks if **_this.domContainer_** is valid, but not for **_this.domContainer.parentNode_**.
Changing the condition like this prevents the error.
![image](https://github.com/photonstorm/phaser/assets/102031127/7f02f87d-ba36-4fc5-8819-0fea828d40bc)

## Example Test Code
I destroy de game calling this (I tried putting false as the first argument but it still gives the error);
`gameStage.destroy(true, true);` 

This is how I empty the parent container
` mainContDiv.innerHTML = ""; `

I call them one after the other in the same function. I was thinking about clearing the html inside an onDestroy event, but phaser waits a bit before removing the div, so intead of closing right away you see black for a fraction of a second, something that I want to avoid.

**Comment by photonstorm** [comment]
Part of me thinks this is what you get for treating an async operation as synchronous (there is an event for a reason! and nothing stops you using a little CSS to hide the canvas immediately to avoid this 'black for a fraction'). However, it's also an easy guard to add in, so I'll consider it for 3.61 - just be aware there are potentially other things going on internally as well, that this won't cover.

**Comment by orcomarcio** [comment]
Thanks.
I agree with you, apparently though we're not allowed to change that part of our company's framework for compatibility reasons (I proposed to use the onDestroy event).

FYI I had managed to temporarely "solve" it by doing this
```
game.domContainer = undefined;
game.destroy(true, true);
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
