### ISSUE TITLE
weightedPick() looks biased

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6562]
## Version

* Phaser Version: 3.0.0 to 3.60.0

## Description

**shy** and **wayfinder** reported/tested this on Discord.

It looks like [weightedPick()](https://codepen.io/samme/pen/qBQKYxN??editors=0110) undersamples the first and last array members.

![Log-linear plot of weightedPick distribution](https://github.com/photonstorm/phaser/assets/435681/f9d1922e-dc69-46c8-831f-0ac4aba267e8)

## Example Test Code

<https://codepen.io/samme/pen/qBQKYxN?editors=0110>

## Additional Information

I think it's supposed to be

    return array[~~(Math.pow(this.frac(), 2) * array.length)];

**Comment by photonstorm** [comment]
Thanks. I think the distribution looks better with `return array[~~(Math.pow(this.frac(), 2) * array.length + 0.5)];`:

![image](https://github.com/photonstorm/phaser/assets/164476/d228752a-cb57-4cdc-8568-ec90bd3dbb63)

As without the 0.5, the first element is _massively_ favoured:

![image](https://github.com/photonstorm/phaser/assets/164476/bba7345d-4d38-4e13-b38d-8165ddbb3f03)

But it definitely looks wrong with the `array.length - 1`.
