### ISSUE TITLE
addAtlasJSONArray() method fails

### ISSUE THREAD

**Issue by 1DAfT** [phaserjs/phaser#6565]
## Version

* Phaser Version: 3.60.0

* Operating system: Windows 10

* Browser: Chrome

## Description

The addAtlas and addAtlasJSONArray methods of Texture Manager errors out when trying addAtlas.

Expected behavior: an Atlas array is added to an existing Phaser Texture.

Actual behavior: an exception is thrown:
`Uncaught TypeError: Cannot read properties of null (reading 'key')
    at TextureManager.addAtlasJSONArray (phaser.js:211602:1)`

## Example Test Code

```
this.textures.on(LOAD, (key: string, texture: Phaser.Textures.Texture)=>{
      if(key === 'flares'){
        this.textures.addAtlas(FS_KEYS.FLARES, texture, flaresAtlas)
      }
```

## Additional Information

Similar problem like here https://github.com/photonstorm/phaser/issues/6553 , tries to access key property on 'null'

```
addAtlasJSONArray: function (key, source, data, dataSource)
    {
        var texture = null;

        if (source instanceof Texture)
        {
            key = texture.key;
            texture = source;
        }
        else if (this.checkKey(key))
        {
            texture = this.create(key, source);
        }
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
