### ISSUE TITLE
Timeline.pause() not pause tween

### ISSUE THREAD

**Issue by gohack0322** [phaserjs/phaser#6574]
## Version

* Phaser Version: v3.60.0

* Operating system: Mac

* Browser: Chrome

## Description

if i want the timeline pause at 4500 ms (use the `onUpdate` event to check the time), it will also pause after the tween is complete.
I tried calling pause() on `onStart`, `onComplete`, and `onUpdate`, but the effect was the same as calling it on `onComplete`.

## Example Test Code

```
const timeline = this.add.timeline([
        {
            at: 2000,
            tween: {
                targets: sprite,
                y: 400,
                ease: 'bounce.out',
                duration: 1500
            }
        },
        {
            at: 4000,
            tween: {
                targets: sprite,
                x: 200,
                angle: 30,
                ease: 'sine.out',
                duration: 1000,
                onStart: () => timeline.pause() // it will pause when second tween is completed, just like onComplete
            }
        },
        {
            at: 6000,
            tween: {
                targets: sprite,
                x: 600,
                angle: -30,
                ease: 'sine.out',
                duration: 1000
            }
        }
    ]);

    timeline.play();
```

## Additional Information

My goal is to pause A timeline halfway through and play another B timeline, and then continue to play A timeline after B timeline is completed.
Is it possible for same sprite of B timeline to repeat the targets of A timeline?

**Comment by Riversedgedesigns** [comment]
## Version
* Phaser Version: ^3.60.0
* Vite Version: ^4.4.9
* Operating system: Windows
* Browser: Firefox *EDIT* just tried Chrome. No difference

## Description
Not sure if same issue, but calling .pause() on a tween doesnt work at all for me.
Currently trying to find quick fix as I am working on clients project.

## Code
```
let tween = scene.tweens.add({
    targets: object,
    ease: 'Linear',
    x: {
         value: xValue,
         ease: 'Linear'
   },
   duration: duration,
   // paused: true, // If I start paused and play() right after same results below
})

// tween.play() // no difference
setTimeout(() => {
    tween.pause() // doesnt happen, tween continues
    console.log('paused') // I see this in console after shortDuration while the tween keeps moving
    tween.stop() // same
}, shortDuration)
```

**Comment by photonstorm** [comment]
@Riversedgedesigns unrelated issue entirely. You cannot pause a tween that hasn't started playing. Playing is not immediate. It's put into a queue and started on the next game frame. If your setTimeout (never, ever, use setTimeout) is short enough, it will fire before the tween has had a chance to begin. If you set the timeout high enough, i.e. you can literally see the tween playing out, and then call pause on it, and it doesn't pause, then there's something wrong with your tween reference. Either open a new issue / discussion or come onto Discord, this isn't the right place for it.

**Comment by photonstorm** [comment]
Sorry, but this isn't possible because the Timeline doesn't keep track of which tweens it has fired, or sounds it has started, etc, so it is unable to pause them. I've updated the docs to at least make it clear that this will happen.
