### ISSUE TITLE
The result will be NaN, if dx1===0  (GetLineToLine.js)

### ISSUE THREAD

**Issue by finscn** [phaserjs/phaser#6579]
https://github.com/photonstorm/phaser/blob/c5d53f9e94928746770176ea1db3d29b495b9b05/src/geom/intersects/GetLineToLine.js#L66

if  `(x3 + dx2 * t - x1)===0` and `dx1 === 0`, `u & s` will be NaN.
then  the `out.x & out.y` will be NaN

**Comment by zekeatchan** [comment]
This issue has been resolved.

We have investigated the problem and have implemented a solution to check whenever `dx1` or `dy1` values are zero. 

The fix will be reflected in the next Phaser update.
