### ISSUE TITLE
Text Shadow + Gradient issue on Safari

### ISSUE THREAD

**Issue by meetpatel1989** [phaserjs/phaser#6580]
## Version

* Phaser Version: 3.60.0

* Operating system: iOS

* Browser: Safari

## Description

Expected behavior: If I add the gradient to the text object which has stroke & shadow, it should be working fine on all platforms & browsers. 

Actual behavior: It adds the shadow to the last character only on iOS Safari while it is working fine on the Chrome browser. It also works fine on Android devices.

## Example Test Code

> let titleText1 = this.scene.add.text(10, 10, 'HELLO', {
      fontSize: 80,
      color: '#ffffff',
      align: 'center'
    })
    titleText1.setStroke('#000000', 8)
    titleText1.setShadow(0, 4, '#000000', 10, true, true)
    const gradient = titleText1.context.createLinearGradient(
      0,
      0,
      titleText1.width,
      titleText1.height
    )
    gradient.addColorStop(0.25, '#FFDD33')
    gradient.addColorStop(1, '#DC8319')
    titleText1.setFill(gradient)

## Additional Information

<img width="198" alt="Screenshot 2023-08-14 at 11 13 33 pm" src="https://github.com/photonstorm/phaser/assets/47215461/4e7446e9-bffc-41e7-babc-7272b5a6f5d6">
<img width="188" alt="Screenshot 2023-08-14 at 11 13 24 pm" src="https://github.com/photonstorm/phaser/assets/47215461/3e0a2527-a6e0-433e-959a-917865a820b9">

**Comment by AlbertMontagutCasero** [comment]
I am experiencing the same issue.


The code I am using to replicate the issue.
```js
this.text = scene.add.text(200 ,200, "HELLO").setFontSize(99)
this.text.setStroke("#5C2500", 8)
this.text.setShadow(0, 2, "#360100", 20, false, true)
const configuration = [
  { color: '#35271a', percent: 0 },
  { color: '#eab24d', percent: 0.35 },
  { color: '#f1ebbb', percent: 0.45 },
  { color: '#eab24d', percent: 0.65 },
  { color: '#35271a', percent: 1 },
]
const gradient = this.text.context.createLinearGradient(0, 0, 0, this.text.height)
for (let i = 0; i < configuration.length; i++) {
  const { color, percent } = configuration[i]
  gradient.addColorStop(percent, color)
}
this.text.setFill(gradient)
```

This is the result in safari, it occurs on mobile iOS and MacOS.
![image](https://github.com/photonstorm/phaser/assets/23361386/62d35c2f-40ab-49b9-9eb6-dab62b99e001)

In Chrome works fine.
![image](https://github.com/photonstorm/phaser/assets/23361386/5425989a-d986-4e0a-b1a0-554639da72da)

**Comment by AlbertMontagutCasero** [comment]
Update:

It happens in 3.55.x and 3.22.0 versions

![image](https://github.com/photonstorm/phaser/assets/23361386/9e811d67-2e7d-41be-b37f-949d726c7132)
![image](https://github.com/photonstorm/phaser/assets/23361386/ff894fd6-124d-475a-b6f6-7cd0883c2cf0)

**Comment by photonstorm** [comment]
This looks very much like a bug in Safari. Here's a pure canvas implementation of your code (no Phaser anywhere):

https://codepen.io/photonstorm/pen/PoXJLzP?editors=1010

and this is an iPad running iOS 16:

![image](https://github.com/photonstorm/phaser/assets/164476/9b2e3a03-1984-4f0f-81b2-bf8aa0a1a81e)

Exact same issue.

**Comment by photonstorm** [comment]
I'm sure you'll be thrilled to know this bug was already reported to webkit 3 years ago and still not looked at / fixed: https://bugs.webkit.org/show_bug.cgi?id=217556

As such, there's nothing I can do about it. Once Safari fix it, this will just work (like it does in other browsers), there's nothing I can do from the Phaser side. If you need this kind of text effect, use BitmapText I guess :(
