### ISSUE TITLE
Add CSS property 'unicode-bidi' to text style

### ISSUE THREAD

**Issue by xbelanch** [phaserjs/phaser#6581]
Implementing a simple calculator I set rtl text direction to display the number value. What happens when it displays negative numbers? For example: -123

If text direction is set to ltr everything is OK and the negative sign shows in the left of number. But setting to rtl the negative sign shows in the right of the number:

123-

It could help a lot that Phaser 3  have the unicode-bidi as a text style property: https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi and then it could allows the negative sign (in this case) always show it at the beginning of the numbers, independently of text direction.

**Comment by photonstorm** [comment]
Phaser renders text using the Canvas API. According to MDN, there is no such `unicode-bidi` setting for Canvas. All we can set are `ltr` and `rtl`: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction

**Comment by xbelanch** [comment]
Then the only workaround here is to maniputate the string before it displays?

**Comment by photonstorm** [comment]
Looks like it, yes. It might be worth doing some googling to see if this has been solved before _specifically with the Canvas API_, because if it has, we can do so within Phaser. Outside of that, there's no immediate solution beyond modifying the string.
