### ISSUE TITLE
I cannot render large images on mobile devices.

### ISSUE THREAD

**Issue by pyf0** [phaserjs/phaser#6583]
It appears that the images are displaying as black on my mobile devices and tablets, while they are properly displayed on my computer. I believe this issue may be due to the large size of the images. The image on the left has a resolution of 7866X4701, while the one on the right is 4264X389. I have also tried opening them on different browsers on my tablet, but the problem persists.

![Screenshot_20230816_001505_com huawei browser](https://github.com/photonstorm/phaser/assets/37735873/f50664a6-52b1-46c1-a97f-5f7188badd2a)
![Screenshot_20230816_001509_com huawei browser](https://github.com/photonstorm/phaser/assets/37735873/26e5a8d1-30a6-4593-a7f3-cd1603193387)

However, when I switch to using CANVAS rendering on my mobile device (tablet), the images are displayed properly. Why is this happening? They are also displayed correctly on my computer.

![Screenshot_20230816_001500_com huawei browser](https://github.com/photonstorm/phaser/assets/37735873/39c659ed-1cb8-47e9-a1f5-d2708c509fe2)

This is my approach. 
right
   this.load.spritesheet('allGoal', 'assets/img/allGoal.png', { frameWidth: 342, frameHeight: 470 });
     
this.goalFrame = this.add.image(180, this.scale.height / 2 + 120, "allGoal", this.loadGoalInfo(this.levelInfo[this.level - 1].goalIndex)).setScale(0.8)

left 
    this.load.spritesheet('boomAnimation1', 'assets/img/boom/red/a2.png', { frameWidth: 388, frameHeight: 388 });
        this.anims.create({
            key: 'boom1',
            frames: this.anims.generateFrameNumbers("boomAnimation1", { start: 0, end: 9 }),
            //frameNames.map(name => ({ key: name })), //this.anims.generateFrameNumbers("boomAnimation", { start: 0, end: 10 }),
            frameRate: 16, //24 64
            //repeat: -1
        });

But I just realized that I have another large image that has been rendered, and its resolution is 4004 x 1232

this.load.spritesheet('allCenterGoal', 'assets/img/centerAllGoal.png', { frameWidth: 154, frameHeight: 154 });

        initGoal.gem.setTexture("allCenterGoal");
        initGoal.gem.setFrame(this.loadCenterGoalInfo(this.levelInfo[this.level - 1].goalIndex) + this.goalCount);

**Comment by pyf0** [comment]
cant render picture
1 animation resolution is  4264X389

2 another resolution is  7866X4701 is an image object

**Comment by photonstorm** [comment]
The images are too large for whatever GPU the mobile you're testing with has. The resolution (not file size) is too high, so the GPU fails to upload them, which is why they appear black. Desktop GPUs nearly always have much more power, so can handle much larger textures.

Make the images smaller. Use a Texture Atlas rather than a sprite sheet. Software like Texture Packer will remove loads of extra space from the images and pack them as efficiently as possible, plus it can split them over lots of PNG files. You want to use a maximum of 2048x2048 per PNG for mobile, really.
