### ISSUE TITLE
Spine plugin function call parameter mismatch

### ISSUE THREAD

**Issue by machineman1357** [phaserjs/phaser#6585]
## Version
* Phaser Version: v3.60.0
* Operating system: Windows 10
* Browser: not specific

## Description

The parameters do not line up in the line `return this.setSkeleton(atlasDataKey, skeletonJSON, animationName, loop)` in the spine plugin.
Here is what the called function looks like `setSkeleton: function (atlasDataKey, animationName, loop, skeletonJSON)`.
As you can see, the parameter `skeletonJSON` should be at the end of the call.

## Example Test Code

`spine.setSkeleton("raptor", skeletonJSON, "roar", false);`
This code will result in the spine not playing an animation.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
