### ISSUE TITLE
[Plane] Rendering size is not correct while frame changing like play animation

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6586]
## Version

* Phaser Version: 3.60

* Operating system: win10

* Browser: chrome, firefox

## Description

[Test code](https://codepen.io/rexrainbow/pen/RwEbqGB). Any clicking to play the same animation on sprite and plane game objects. 
Rendering size of these sprite and plane game objects should be the same, but plane looks like larger than sprite. 
Perhaps the rendering size does not change with current frame (i.e. fixed by first rendering frame) in Plane game object.

**Comment by rgk** [comment]
Added some documentation about this for now.

**Comment by rexrainbow** [comment]
Might reset vertices for new frame size when frame changing under [`preUpdate` method](https://github.com/phaserjs/phaser/blob/master/src/gameobjects/plane/Plane.js#L729-L734).

**Comment by zekeatchan** [comment]
This issue will not be fixed.

We are currently focusing our efforts on developing a new renderer (that will address this issue) and the next version of PhaserJS.

Thanks for bringing this to our attention.
