### ISSUE TITLE
`CONTEXT_LOST` event no longer fired in 3.60

### ISSUE THREAD

**Issue by vzhou842** [phaserjs/phaser#6588]
## Version

* Phaser Version: 3.60

* Operating system: Mac OS

## Description

The `CONTEXT_LOST` event is no longer fired in 3.60 despite it being fired in 3.55. AFAICT this is a bug because all the docs I can find seem to suggest this should still work? I know `CONTEXT_RESTORED` was removed, but seemingly not `CONTEXT_LOST`

**Comment by photonstorm** [comment]
This is correct, there is no event for this in 3.60 anymore. Please point me to where in the 3.60 docs it says this event should be dispatched.
