### ISSUE TITLE
"Trim" frame property not properly applied when cropping Sprite that's using an Atlas

### ISSUE THREAD

**Issue by orcomarcio** [phaserjs/phaser#6589]
## Version

* Phaser Version: 3.60

* Operating system: Window 11

* Browser: Chrome

## Description
Cropping a trimmed sprite seems to not work appropriately. The frame I'm using belongs to an atlas, in case that matters.

Without crop:
![image](https://github.com/photonstorm/phaser/assets/102031127/2da540c7-3210-4cb8-9755-26fe6a4869a9)

With  `sprite.setCrop(0, 0, sprite.width, sprite.height)`
![image](https://github.com/photonstorm/phaser/assets/102031127/4431bdc6-4ec8-4689-893f-220164a761a9)

## Example Test Code
this is wat happen if I use the following codes:

 `sprite.setCrop(0, 0, 100, 100)`
![image](https://github.com/photonstorm/phaser/assets/102031127/c19938fe-aead-4051-a1f6-b437fe06b6c9)

`sprite.setCrop(0, 0, sprite.width, sprite.height)`
or `sprite.setCrop(0, 0, 100000, 100000);` (to make sure I'm not being short with w and h)
![image](https://github.com/photonstorm/phaser/assets/102031127/4431bdc6-4ec8-4689-893f-220164a761a9)

A noteworthy thing is that, in this case, the trim is a 11 and the crop changes only below `width - trim*2`, meaning that with
`sprite.setCrop(0, 0, sprite.width, sprite.height)` and `sprite.setCrop(0, 0, sprite.width-22, sprite.height-22)` I don't se changes, but below `sprite.setCrop(0, 0, sprite.width-23, sprite.height-23)` I start to see changes in the trimming. 

These are this partucalr trim values if i do `sprite.setCrop(0, 0, sprite.width, sprite.height)`
![image](https://github.com/photonstorm/phaser/assets/102031127/c8dd5a13-c48c-4bfa-a1df-611cb5cbbbb7)

This is the frame config in the atlas.json
![image](https://github.com/photonstorm/phaser/assets/102031127/cc719ee2-a256-4bda-8382-fbf2f3179e7e)

**Comment by photonstorm** [comment]
This is the correct behaviour, although it's probably worth adding to the docs. Cropping just lets you set the UV coordinates of the texture. So if the texture has been trimmed, you're working from those coordinates, not the sprite size, as that's outside of the UV coords. All it really lets you do is make the UV coords _smaller_ than the defaults.
