### ISSUE TITLE
Camara class does not use zoomX and zoomY when setting display width in prerender call

### ISSUE THREAD

**Issue by Scross086** [phaserjs/phaser#6597]
## Version

* Phaser Version:

## Description

preamble: this might be intentional - but i wanted to get your thoughts:

Camara class negates zoomX and zoomY properties during the prerender method when setting the displayHeight and displayWtidth,. Instead, it uses the zoom getter, which combines both variables and negates the ability to independently set each zoom level. the base camera class has this functionality implemented in its prerender. Is this intentional?

**Comment by photonstorm** [comment]
You're right; BaseCamera does use zoomX/Y, whereas Camera doesn't. Honestly, I can't remember why. It has been this way for many years now, so I'm highly reluctant to change it, as who knows what it may now break as a result 🤔 Going to have to leave it as 'just one of those things'.
