### ISSUE TITLE
Webgl broken on latest IOS 17 beta

### ISSUE THREAD

**Issue by elgerm** [phaserjs/phaser#6599]
* IOS 17 beta (21A5319a)

* Browser: ios safari

## Description

having the renderer set to AUTO makes phaser quitting with the error: "Webgl unsupported"

## Example Test Code

config.ts

export default {
    type: Phaser.AUTO
}

if specifying Phaser.CANVAS things run fine.

## Additional Information

It seems more projects are having this issue (like felt maps), but google maps (which uses webgl) appears to be working fine on IOS 17.

**Comment by photonstorm** [comment]
I doubt this matters too much. There's no way they'll release iOS17 with WebGL1 disabled. At least, you'd hope not. But I guess this is Apple after all.

**Comment by elgerm** [comment]
> I doubt this matters too much. There's no way they'll release iOS17 with WebGL1 disabled. At least, you'd hope not. But I guess this is Apple after all.

Guess it's too early to tell, I'll close the issue and reopen if the release version still has the problem.

**Comment by photonstorm** [comment]
Nah let's leave it open. I'll check it once we've an iOS 17 RC out, but Phaser is doing _nothing_ weird or complex with its WebGL detection, so this is almost certainly just an Apple screw-up for now.

**Comment by photonstorm** [comment]
I've installed the final iOS17 release, and all the Phaser examples I tested work fine on my iPhone, so happy to close this.
