### ISSUE TITLE
GameObjects "disappear" when zoom combined with invalid Camera#setOrigin parameter values

### ISSUE THREAD

**Issue by paxperscientiam** [phaserjs/phaser#6603]
## Version

* Phaser Version: 3.60.0

* Operating system: macos 13.5 on M1 macbook

* Browser: known to occur in both firefox and safari

## Description

The objects in a scene will disappear under this set of conditions:
- camera rotation origin parameter values are out of bounds (see below)
- camera zoom is other than `1`

Per [the docs](https://newdocs.phaser.io/docs/3.60.0/Phaser.Cameras.Scene2D.Camera#setOrigin), acceptable values for either `x` or `y` are numbers between zero and one.

Well, I know this now. However, when I first tried this method, I had falsely assumed that the parameters were for pixel coordinates as with `Camera::setDeadzone(...)`.

Even so, I didn't realize my error until after I tried to use camera zoom in the scene. For some reason, the combination of the above error with zoom values other than one, causes objects to disappear.

## Example Test Code

Example code: https://stackblitz.com/edit/vitejs-vite-tmm2sc?file=src%2Fmain.ts

One can change the zoom level on line 53 of src/main.ts

## Thoughts on remediation

Maybe throw an error when parameters are set to values out of range?

EDIT: Stackblitz project should look like this after it auto installs npm packages and starts the server:
<img width="1086" alt="Screenshot 2023-08-31 at 11 15 43 PM" src="https://github.com/photonstorm/phaser/assets/7539871/80909286-559c-401b-ad65-410a84b31df6">

**Comment by photonstorm** [comment]
Thanks for opening this issue. While I understand the mistake that was made, I don't feel like it needs capturing in the code itself, as it's covered in the docs and TypeScript defs.
