### ISSUE TITLE
Can angle cropping be added?

### ISSUE THREAD

**Issue by pyf0** [phaserjs/phaser#6611]
Can angle cropping be added?

The current cropping methods are all rectangular (setCrop()).

I have worked on two games before, and it seems that having angle cropping would make things a bit easier, especially in terms of art and resource loading.

Alternatively, is it possible to add an angle to this.add.renderTexture()?

If it's not too much trouble for you, 

for example, in the image below, I would like to divide it into six parts. Since setCrop only allows for rectangular cropping, it is not possible to divide it into six parts.

![`@U}C~X 49F2F0NHXH @_@B](https://github.com/photonstorm/phaser/assets/37735873/5f09be4e-0c5e-4a35-a379-523aca6576fd)

**Comment by photonstorm** [comment]
This can't be added, I'm afraid. Cropping is handled internally by modifying the _rectangular_ UV coordinates of the texture and making them smaller than the texture size, resulting in the 'crop' effect. It's always a rectangle shape.

**Comment by pyf0** [comment]
> This can't be added, I'm afraid. Cropping is handled internally by modifying the _rectangular_ UV coordinates of the texture and making them smaller than the texture size, resulting in the 'crop' effect. It's always a rectangle shape.


Is there a method in Phaser that can achieve the effect I want? Is it possible to combine with certain JavaScript libraries to modify the texture?

**Comment by rexrainbow** [comment]
For a circle mask, you can use built-in *Circle Outline* preFX effect.
```js
gameObject.preFX.addCircle(thickness, color, backgroundColor, scale, feather);
```

**Comment by pyf0** [comment]
> For a circle mask, you can use built-in _Circle Outline_ preFX effect.
> 
> ```js
> gameObject.preFX.addCircle(thickness, color, backgroundColor, scale, feather);
> ```

Thank you for your suggestion. I tried it and found that there is no 'angle' option. For example, if I want to create a 1/6 section of a circle, this method still cannot achieve it.

**Comment by photonstorm** [comment]
You can do this with a CanvasTexture. You'd need to define the arc clipping path, then draw an image to it, but it would respect the clipping path and give you that 'pizza slice' effect. Could also do it to a DynamicTexture, but I think a CT would be easier. You'll find plenty of canvas path API examples / tutorials on the web.
