### ISSUE TITLE
Multi atlases in pack files do not get prefixed

### ISSUE THREAD

**Issue by machineman1357** [phaserjs/phaser#6614]
* Phaser Version: 3.60.0
* Operating system: Windows 10
* Browser: not specific

## Description

When a pack file is loaded that has a prefix, files of type "multiatlas" will not be prefixed in the textures list.

## Example Test Code

[Codepen](https://codepen.io/Machineman1357-the-flexboxer/pen/GRPmmdj)

## Additional Information

Go to the console and you will see I have logged out the game's texture list. There you will see "megaset" has no prefix.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
