### ISSUE TITLE
[RenderTexture] postion of fill rectangle is not correct

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6615]
## Version

* Phaser Version: v3.61.0-beta.2

* Operating system: win 11

* Browser: chrome

## Description

[Test code](https://codepen.io/rexrainbow/pen/XWoRzzJ) , fill rectange at (0,0) and draw frame at (0,0)
- draw frame at top-left, works fine.
- fill rectangle at bottom-left, seems that y axis of fill method is not correct.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
