### ISSUE TITLE
[RenderTexture] Invoke renderTexture.stamp() method under scene.create()

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6616]
## Version

* Phaser Version: v3.61.0-beta.2

* Operating system: win11

* Browser: chrome

## Description

[Test code](https://codepen.io/rexrainbow/pen/OJrmdvb) : Invoke renderTexture.stamp() method under scene.create()

Case 1,  do noting in preload : Rise error `Uncaught TypeError: Cannot read properties of undefined (reading 'setCrop')` , see console
Case 2, load assets in preload (open comment at line 9): `renderTexture.stamp()` works fine.

It seems that [`texture.stamp`](https://github.com/photonstorm/phaser/blob/master/src/textures/TextureManager.js#L212) is created too late in case 1.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
