### ISSUE TITLE
Scene `physics.add.staticBody` throws when called with both width and height

### ISSUE THREAD

**Issue by Legend-Master** [phaserjs/phaser#6630]
## Version

* Phaser Version: 3.60.0 / 3.61.0-beta.2

* Operating system: Windows 10

* Browser: Chrome 117

## Description

> Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'getCenter')

https://github.com/photonstorm/phaser/blob/cbb802bcff470e3dc222986f5b71126d6741307c/src/physics/arcade/StaticBody.js#L612

## Example Test Code

```typescript
new Game({
	physics: {
		default: 'arcade',
	},
	scene: {
		create() {
			this.physics.add.staticBody(0, 0, 10, 10)
		},
	},
})
```

## Additional Information

Probably caused by 6b55ac6

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Legend-Master** [comment]
Thanks! I think I got the time to take a look tomorrow

**Comment by Legend-Master** [comment]
Just tried the newest version on master branch, works great
