### ISSUE TITLE
`sound.isPlaying` is `true` after `sound.destroy()`

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6645]
## Version

* Phaser Version: 3.60.0

* Operating system: win11

* Browser: chrome

## Description

[Test code](https://codepen.io/rexrainbow/pen/yLGGKGz), `sound.isPlaying` still return `true` after `sound.destory()`. 
Might invoke `sound.stop()` inside `sound.destory()`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
