### ISSUE TITLE
Matter physics object sticks to world bounds on bounce

### ISSUE THREAD

**Issue by RocketRonz** [phaserjs/phaser#6650]
## Version

* Phaser Version: 3.60.0

* Operating system: Windows 11

## Description

When gravity is disabled and the game object has bounce set to 1 and friction set to 0, the object sticks to the world bounds. This can be seen after one or two bounces in some of the Phaser examples in version 3.60.0 and also happens with earlier versions (but seems to take a bit longer to happen)

## Example Test Code

https://phaser.io/examples/v3/view/physics/matterjs/body-scale
https://phaser.io/examples/v3/view/physics/matterjs/circle-body

**Comment by photonstorm** [comment]
Known issue in Matter. Once resolved there, the fix will come downstream: https://github.com/liabru/matter-js/issues/710
