### ISSUE TITLE
Support drag with Mesh and Plane

### ISSUE THREAD

**Issue by Neppord** [phaserjs/phaser#6652]
Many game objects like `Image` allows `setInteractive` to take a draggable argument in its config. Meshes, and Planes, don't. This leads to less portable code when moving from one game object to another and makes the API a tiny bit harder to learn, due to its inconsistency.

Here is two examples of almost the same functionality, written first with use of the image game object and then in the second version with the plane object.

https://github.com/Neppord/challenge/blob/main/cards.js

https://github.com/Neppord/challenge/blob/main/cards2.js

The changes i had to make where bigger and not related to the change I ment to be doing due to also need to implement the drag mechanic by hand for the plane, instead of only focusing on the rotation.

I am wiling to help implement the new feature if given time and guidance.

**Comment by rgk** [comment]
This has been solved with #6510, you can now use drag events with enabling `draggable` via an interactive config for `Mesh` and `Plane`.
