### ISSUE TITLE
NineSlice does not respect pivot point of texture set by TexturePacker

### ISSUE THREAD

**Issue by michalfialadev** [phaserjs/phaser#6655]
When `Phaser.Gameobjects.Image` from an atlas made by TexturePacker is added to scene, and the Frame of such image has a custom Pivot Point, this image in Phaser will automatically have it's pivot point set to the pivot point set inside the TexturePacker IDE. 

Is same possible to be done, when NineSlice is used for such atlas Frame? Currently the NineSlice created using frame with custom Pivot point will not inherit this custom pivot point. This introduces a discrepancy, when Image or NineSlice is used for same Frame.

<img width="645" alt="image" src="https://github.com/photonstorm/phaser/assets/36237028/a858e398-8ef4-41d2-b170-9de72ad1bc1e">

The image above, when NineSlice is used to display it, will not take it's custom pivot point into account, but will have its origin set to (0.5,0.5)

EDIT: it seems NineSlice doesnt support `setOrigin` at all. Can it be made to support custom origin?

**Comment by CodeAndWeb** [comment]
setOrigin seems to work.
However loading the origin from the sprite sheet does not - I can confirm this.

button.png has a pivot point of 0/0 set in TexturePacker.

~~~
        this.add.nineslice(50,50,'cityscene', 'button.png', 100, 50);
        this.add.sprite(50,50,'cityscene', 'button.png');
~~~

When loaded as a Sprite, it's positioned correctly. The NineSlice is misaligned with the origin of 0.5/0.5

<img width="377" alt="2023-11-13_17-05-57" src="https://github.com/photonstorm/phaser/assets/716009/285ae80e-a8d2-4588-bdbc-73937e61eafb">

Both should be in the same position.

**Comment by rgk** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the master branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
