### ISSUE TITLE
HIDPI monitor support resolution

### ISSUE THREAD

**Issue by hujinliang** [phaserjs/phaser#6656]
I'm choosing an engine to develop my game with, but i found that rendering is blurry on HIDPI monitors;  why doesn’t phaser3 support it? I find a way to handle it:  scale all the elements (x,y,size etc...) manually to that resolution by multiplying it (so 12px becomes 12*resolution px), it looks good now, but this is not an official way, so I'm worried about compatibility issues. Any good ideas?
<img width="64" alt="image" src="https://github.com/photonstorm/phaser/assets/17648734/63f7ac3c-c5b2-4ab4-9038-78befba4544c">
<img width="75" alt="image" src="https://github.com/photonstorm/phaser/assets/17648734/009a22cb-4abd-4ccf-8b94-6068ccff4699">
The difference is quite big

**Comment by samme** [comment]
https://github.com/photonstorm/phaser/blob/master/changelog/3.50/CHANGELOG-v3.50.md#removal-of-resolution-property-from-across-the-api
