### ISSUE TITLE
DynamicTexture doesn't work in beta-4

### ISSUE THREAD

**Issue by vforsh** [phaserjs/phaser#6664]
## Version
* Phaser Version: 3.61.beta-4

## Description
An image that uses DynamicTexture doesn't display anything until you call `dynamicTexture.setFromRenderTarget()` explicitly. Is that desired behavior? I didn't need to call it in previous 3.61 betas. 

## Example Test Code
```typescript
let dt = new Phaser.Textures.DynamicTexture(this.textures, "piggy-dt", 600, 600)
dt.setIsSpriteTexture(true)
dt.beginDraw()
dt.drawFrame("piggy_bank")
dt.endDraw()

// for beta-4 we need to call this explicitly
// dt.setFromRenderTarget()

this.add.image(this.scale.width / 2, this.scale.height / 2, dt)
```

## Additional Information
https://codesandbox.io/s/phaser-3-61-beta4-dynamic-texture-8928gs?file=/src/index.ts

**Comment by DavidTalevski** [comment]
Same as https://github.com/photonstorm/phaser/issues/6654

**Comment by photonstorm** [comment]
This is fixed in the master branch.
