### ISSUE TITLE
Phaser 3.70 reintroduced the dynamic texture memory leak

### ISSUE THREAD

**Issue by DavidTalevski** [phaserjs/phaser#6669]
## Description
Phaser 3.70 seems to have reintroduced the dynamic texture memory leak when creating and destroying textures.

## Example Test Code
https://labs.phaser.io/viewmem.html?src=src%5Cbugs%5C0000%20dt%20mem.js&v=dev

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
