### ISSUE TITLE
Typedefs for new Phaser.Time.Timeline don't show it extending eventEmitter

### ISSUE THREAD

**Issue by ghclark2** [phaserjs/phaser#6673]
## Version

* Phaser Version: 3.70

* Operating system: Windows

* Browser: Chrome

## Description
Typedefs for new Phaser.Time.Timeline don't show it extending eventEmitter. Eslint will give the following error with the code below: Property 'on' does not exist on type 'Timeline'.

Eslint will also give an error if you try to create an empty timeline: 'An argument for 'config' was not provided'. Config argument should be optional.

## Example Test Code

    const timeline = this.scene.add.timeline()
    timeline.on('complete', () => {doSomething})

## Additional Information
Thanks!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
