### ISSUE TITLE
GameObjects added to Layers are destroyed twice on Scene shutdown causing crashes

### ISSUE THREAD

**Issue by crockergd** [phaserjs/phaser#6675]
## Version

* Phaser Version: 3.70.0

* Operating system: Windows 10

* Browser: 

## Description

Adding a GameObject to a Layer throws unhandled exceptions when the Scene they're added to shuts down (such as when transitioning to a new scene). 

The Scene destroys the Layer, then the Layer destroys the Sprite which causes it to emit its DESTROY event. This event is caught by the Layer which removes the Sprite from its list as well as attempts to destroy it again because the Layer is being destroyed by the scene. The destroy attempted by the Layer throws an exception in Sprite.preDestroy when this.anims is null because it was already removed by the original destroy.

## Example Test Code

https://codepen.io/crockergd/pen/RwvMxNG

The demo attempts to add a Sprite to a Layer, then transition to a different Scene which displays a small green square. Currently, the demo crashes while trying to stop the current scene. The demo completes successfully if the line adding SceneA's rect to the layer is removed, or if the Phaser dependency is set to a version before 3.70.0.

## Additional Information

The exception thrown by the demo doesn't trace the source of the issue well, I've attached an image of a call stack from a debugger as well.
 
![layercrashstack](https://github.com/photonstorm/phaser/assets/5075184/8bfdbe82-74c5-4602-a390-a1e24fb4cac5)

**Comment by zommerfelds** [comment]
I'm having the same issue. But for me it only happens when I restart the scene (`this.scene.restart()`). If I switch to a new scene this is not a problem.

**Comment by zommerfelds** [comment]
In case it helps anyone, my workaround is to run something like this before restarting the scene:

```
        for (let child of this.children.getAll()) {
            if (child instanceof Phaser.GameObjects.Layer) {
                child.destroy();
            }
        }
```

**Comment by valuks** [comment]
My example with an error and temporary fix (check the comments): https://codepen.io/valentoros/pen/VwRvGqW

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
