### ISSUE TITLE
Phaser.Scale.RESIZE WebGL has weird scaling and positioning

### ISSUE THREAD

**Issue by LazeKer** [phaserjs/phaser#6678]
## Version

* Phaser Version: 3.70.0

* Operating system: Windows 11

* Browser: Chrome 119.0.6045.160

## Description

In RESIZE scale mode and WEBGL there is positionning/scaling issues while moving game objects and during the resize.
Could also be related, Shaders (ex: PostFX) are stretch weirdly (ex: Blur)

## Example Test Code

It can easily be tested through the example: https://labs.phaser.io/100.html?src=src\scalemanager\manually%20resize.js
Load the page with the developper console open in responsive, configure the viewport very small (ex:10x10) then rezise up, the text should bump as if it was tring to snap on a grid. Every gameobject wil do the same while moving (ex: tween)

You can do the same on multiple example like : https://labs.phaser.io/edit.html?src=src\scalemanager\mobile%20game%20example.js

## Additional Information

Could be related to https://github.com/photonstorm/phaser/issues/6674

**Comment by photonstorm** [comment]
This is now fixed in master. Please see #6674 for the related commits.
