### ISSUE TITLE
add extern object not working with three.js for phaser 3.6.0+

### ISSUE THREAD

**Issue by ChSolution** [phaserjs/phaser#6680]
## Version

* Phaser Version: 3.70.0

* Operating system: 

* Browser: chrome

## Description

Hi yall, i'm trying to render threejs by extern object with phaser 3.70.0
but it give 
[.WebGL-00007D4C01CC8600] GL_INVALID_OPERATION: Must have element array buffer bound

it works fine with phaser 3.55.0

## Example Test Code

https://codepen.io/1coldcube/pen/XWOdrVO

## Additional Information

Also it's not working with new threejs runs on webgl2,
is there away to make it run on webgl2?
thanx

**Comment by photonstorm** [comment]
This is ThreeJS running with 3.70: https://labs.phaser.io/view.html?src=src/game%20objects/extern/threejs%20cube.js

You _have_ to use a `THREE.WebGL1Renderer`. You cannot use WebGL2.
