### ISSUE TITLE
Render Texture does not clear correctly on Firefox

### ISSUE THREAD

**Issue by BrandonMakin** [phaserjs/phaser#6687]
## Version

* Phaser Version: 3.70.0

* Operating system: Windows 11

* Browser: Firefox

## Description

Render Texture does not clear when `clear()` is called in Firefox.  It seems to still work correctly for both desktop Chrome and iOS Safari.

## Example Test Code

This bug can be seen in these phaser demos:
https://labs.phaser.io/view.html?src=src/game%20objects\render%20texture\static%20bitmap%20text%20to%20render%20texture.js
https://labs.phaser.io/view.html?src=src/game%20objects\render%20texture\text%20to%20render%20texture.js&v=3.70.0

## Additional Information

The demos do seem to work correctly (the render texture is cleared) in Firefox on the 3.60.0 version and all 3.61.0 beta versions. This appears to be a regression in 3.70.0.

**Comment by gammafp** [comment]
Work fine for me:
![image](https://github.com/photonstorm/phaser/assets/9221946/a152cb06-2091-4de4-8bcc-310fcf7d4e3e)

**Comment by photonstorm** [comment]
Just tested this on Firefox 121.0 and 122.0 (64-bit) on Windows 11 and it works fine on both. Would urge re-testing on a recent release of FF.
