### ISSUE TITLE
Factory.staticBody wrong return type description (body instead of staticbody)

### ISSUE THREAD

**Issue by ddhaiby** [phaserjs/phaser#6693]
## Version
* Phaser Version: 3.70

## Description

There seems to be an issue with the return type for Factory.staticBody function the phaser.d.ts.
The return type is body but it should be staticbody. The right type is returned **but the indication is wrong** so my project will complainas I use typescript.

## Example Test Code
`
const myStaticBody = this.physics.addbody(0,0); // Will say that it returns a body (okay!) 
const myStaticBody = this.physics.add.staticBody(0,0); // Will also that it returns a body (not okay!!) 
`

## Additional Information
![image](https://github.com/photonstorm/phaser/assets/72042952/4ffa564d-f3ba-4acd-9aea-b648fd9373a0)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
