### ISSUE TITLE
Video bug that happens when the video is loaded but the play isnt triggered and the user switches tabs.

### ISSUE THREAD

**Issue by EliasIoannou** [phaserjs/phaser#6695]
## Version

* Phaser Version:
3.70 but the issue occurs in 3.55 and 3.60 as well

* Operating system: Windows

* Browser:
Opera GX, Chrome, Brave (Those are the ones I tested it on)

## Description

its basically a video bug. I have games that have videos in them that are loaded at the start. And I have a play button to start playing them. If the user changes tab on pc and goes back to the game window it starts playing the sound of the video without playing the actual video. Also if u press the play button after the bug occurs its just a black screen with the sound keep playing but it breaks the whole game without errors and forces people to restart the window.
Sometimes it doesn't happen when you do it but it happens often enough to be annoying.

## Example Test Code

create() {
       this.video= this.add.video(0,0,'oliviaVideo').setOrigin(0)
       let playButton = this.add.image(this.config.width/2,this.config.height/2-30,'playButtonVideo').setInteractive().setDepth(5000).setScale(.3).setOrigin(.5);
       playButton.on("pointerup",()=>{
            this.video.play()
            playButton.destroy()
        })
       

}

**Comment by photonstorm** [comment]
This is now handled properly via its own `Video.getFirstFrame` method, and no longer exhibits the issue described here.
