### ISSUE TITLE
Scaling Tween on Phaser 3.70 not smooth compared to Phaser 3.60

### ISSUE THREAD

**Issue by asafSpino** [phaserjs/phaser#6700]
When using a scale tween on the new phaser version the scale seems to work in different steps in scaleX and in scaleY causing the animation to seem jittery.
**Example Code**:

targets: this.testObj,
scale: { from: 1, to: 2 },
duration: 30000,
yoyo: true,
repeat: -1,
 
**Phaser 3.70**:
![phaser1](https://github.com/photonstorm/phaser/assets/155071025/ff3c4533-b6d3-401a-a353-e70cc90d5f82)

**Phaser 3.60**
![phaser2](https://github.com/photonstorm/phaser/assets/155071025/c6223b78-f7fc-4e2d-af57-2db8a7ba351f)

**Comment by photonstorm** [comment]
There's no difference in the way things are scaled. This is likely to do with `roundPixels` being enabled by default in the game config now - set it to false and it should return to the way it looked in 3.60.
