### ISSUE TITLE
When using setOrigin() on a Phaser.GameObjects.Group each object origin is adjusted instead of setting the an origin for the group

### ISSUE THREAD

**Issue by taulant** [phaserjs/phaser#6704]
## Version

* Phaser Version: 3.70.0

* Operating system: MacOS 13.5.2

* Browser: Chrome 120.0.6099.129

## Example Test Code

```javascript
create(): void {
    const textArray: Phaser.GameObjects.Text[] = [] // This is an array with Text Objects
    this.textGroup = new Phaser.GameObjects.Group(this, textArray);
    this.textGroup.setOrigin(0,0) // I am expecting this to set a new local origin for all the objects in the array
}

update(): void {
    this.textGroup.rotate(1, 1); // This is causing each text object to rotate along their local origin instead of the whole group being rotated
}
```

### What I am expecting
When using `setOrigin()` on `Phaser.GameObjects.Group` I am expecting this to set a single origin for the all the game objects in this group. I want to rotate all the objects in relation to this single origin.

### What is happening
When using `setOrigin()` on `Phaser.GameObjects.Group` the local origin of each object is changed. When I try to rotate the group all the objects are rotating individually based on their local origin.

## Additional Information

I think calling `setOrigin()` on `Phaser.GameObjects.Group` should create a new origin for the group of objects. 

A good analogy is how shapes are grouped in a common 2D image editor. The origin of the group then can be used for rotating and resizing in relation to its origin. I think Unity also works similarly. When grouping objects in a prefab you can rotate all the objects in relation to the prefab's origin.

**Comment by taulant** [comment]
Update: I discovered `rotateAround()` method which is sort of doing what I needed which is `Text` objects moving around an origin. 

The problem with `rotateAround()` is that it is not adjusting the rotation of the child objects when rotating. See the example [here](https://phaser.io/examples/v3/view/actions/rotate-around).

My expectation is that the objects would still change their rotation with the group origin.

**Comment by photonstorm** [comment]
A Phaser Group isn't a Game Object in its own right, so you cannot set an origin for it. Think of it being more like an advanced pool, for quickly grabbing, using and releasing objects into. If you want a transform hierarchy (like this issue implies), then I would recommend using a Container instead. With careful positioning of Container children you can create them to function the way your code was expecting. See the Labs examples for further details.

**Comment by taulant** [comment]
@photonstorm Thanks for your note. Will keep this in mind to use a container for next time I want to manipulate a group of objects.

As per the solution I ended up incrementing the rotation angle of each letter to to the radius interval change of `rotateAround` to get the effect of all the letters rotating around a given centre coordinate.
