### ISSUE TITLE
Some PostFX Shaders creating a freak frame at shader activation and persistent issues on game resize for Phaser.Scale.NONE / Phaser.Scale.RESIZE

### ISSUE THREAD

**Issue by saintflow47** [phaserjs/phaser#6706]
It seems the issue does not affect every PostFX. All the Game Objects are part of different layers and the postFX is added to the layers.

Affected PostFX: Colormatrix, Bloom, Blur, Displacement
Not affected PostFX: Pixelate, Barrel, Bokeh, Circle, Gradient

Freak Frame view:
![2024_01_02_125716](https://github.com/photonstorm/phaser/assets/32780344/13326ac7-7cc7-4a46-bd9d-e34521f75074)

Normal view:
![2024_01_02_125734](https://github.com/photonstorm/phaser/assets/32780344/495ad720-091c-4560-9ac1-8aaad51d319a)

Possibly linked issues #6681 #6678 #6677

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

(Will re-open if this still doesn't fix it, and you can provide test case we can run)

**Comment by moufmouf** [comment]
Just tested this. It works! :+1:
