### ISSUE TITLE
fx wipe example click back to menu trigger "TypeError: Cannot read properties of undefined (reading 'sys')"

### ISSUE THREAD

**Issue by ixqbar** [phaserjs/phaser#6707]
<img width="906" alt="image" src="https://github.com/photonstorm/phaser/assets/960982/4af18efd-b2a9-4555-a9f1-19932a7768ea">
https://labs.phaser.io/view.html?src=src\fx\wipe\wipe%20to%20a%20scene.js

Phaser v3.70.0
TypeError: Cannot read properties of undefined (reading 'sys')

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that. Note: v3.80 fixes this issue.
