### ISSUE TITLE
createFromTiles should take into account flip/rotation from tiled

### ISSUE THREAD

**Issue by Nerodon** [phaserjs/phaser#6711]
Simply, in tiled, I am able to rotate tiles, and when generating the tileset they are correctly rotated.
But when converting them to an object, that information is lost, the the created sprites are upright and ignore the rotation/flip the tile had.

I think it would be useful to have the created sprites to match the rotation/flip of the tile they come from.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
