### ISSUE TITLE
Changing Nineslice size using setSize causes hitareas to be incorrect

### ISSUE THREAD

**Issue by dhashvir** [phaserjs/phaser#6713]
## Version

* Phaser Version: 3.70.0

* Operating system: All

* Browser: All

## Description

If enabling input on a ninesplice game object and using the default hitarea, when you use the setSize function to resize the nineslice image the hitareas become incorrect. 

## Example Test Code

Using the example nine slice code
```js
class Example extends Phaser.Scene {
  preload() {
    this.load.atlas('buttons', 'nine-slice.png', 'nine-slice.json');
  }

  create() {
    var button = this.add.nineslice(400, 300, 'buttons', 'button-bg', 400, 110, 64, 64);
    button.setInteractive();
    button.on('pointerup', this.onButtonPressed, this);
    button.input.cursor = 'pointer';
    button.setSize(100, 50);
  }

  onButtonPressed() {
    console.log('button pressed');
  }
}

const config = {
  type: Phaser.AUTO,
  width: 800,
  height: 600,
  backgroundColor: '#000000',
  parent: 'phaser-example',
  scene: Example
};

const game = new Phaser.Game(config);
```

## Additional Information

Using the code above, if you hover your mouse over the button, you can see the hand icon changes at the incorrect places. If you comment out the setSize code, and hover over again, you can see the hand icon changes correctly. 

The issue is the setSize function does not reset the origin of the nineslice and the input manager uses this for the hit test.

**Comment by dhashvir** [comment]
I have created a PR that fixes the issue.

**Comment by rgk** [comment]
Thank you for submitting this issue and pull request. The pull request has been pushed to the master branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
