### ISSUE TITLE
Resetting a static body should reapply the offset

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6729]
## Version

* Phaser Version: 3.70.0 and earlier

## Description

Create a game object with a static Arcade Physics body. Give the body an offset with `setOffset(x, y)`.

Reset the body with any coordinates. Now the body position doesn't include the offset.

Call `setOffset(x, y)` again. The body position is the same — still no offset. 

## Example Test Code

```js
const image = this.physics.add.staticImage(0, 0, '32x32').setOffset(16, 16);

// These pass.
console.assert(image1.body.x === 0);
console.assert(image1.body.y === 0);

// Reset on the original position.
image.body.reset(0, 0);

// These fail.
console.assert(image1.body.x === 0);
console.assert(image1.body.y === 0);
```

Also <https://codepen.io/samme/pen/wvOjoGK?editors=0010>

**Comment by rgk** [comment]
:v:
