### ISSUE TITLE
Example Dead Link 

### ISSUE THREAD

**Issue by jauntyjocularjay** [phaserjs/phaser#6738]
## Version
* Phaser Version: 3
* Operating system: Windows 10
* Browser: Chrome

## Description

Example for [grid movement](https://phaser.io/examples/v3/view/tilemap/grid-movement) GitHub link is broken.

## Example Test Code

n/a

## Additional Information

This is the block:
> Download
> Get the source code and assets for every example from the [Phaser 3 Examples GitHub repository](https://github.com/phaserjs/phaser3-examples).

**Comment by rgk** [comment]
For that example you would use the WASD keys to move the car, the errors are unrelated.

The examples repo is: https://github.com/phaserjs/examples for future issues.

**Comment by jauntyjocularjay** [comment]
You're right, I didn't see that. Updating the issue.
