### ISSUE TITLE
After updating to Phaser 3.80 using Capacitor and Ionic

### ISSUE THREAD

**Issue by ulsoftnaver** [phaserjs/phaser#6747]
After updating to Phaser 3.80 using Capacitor and Ionic, the existing TAB buttons and click events in Ionic do not occur. Everything worked fine up to Phaser 3.70. Is there a solution?

Touch events worked well with all events of Ionic's buttons up to Phaser 3.70, but after the upgrade, the button events do not occur.

Is there a way to make both Ionic events and Phaser 3.80 work well together? Do I have to give up on Ionic when using Phaser 3.80?

After updating to Phaser 3.80, click events in the Ionic framework should all work properly, but they do not.

**Comment by ulsoftnaver** [comment]
Is there a way to make both Ionic events and Phaser 3.80 work well together? Do I have to give up on Ionic when using Phaser 3.80?

**Comment by ulsoftnaver** [comment]
In Phaser 3.80, there seems to be a conflict that prevents click events on Ionic components from being triggered, which doesn't happen with Phaser 3.70. Please provide a solution.

**Comment by ulsoftnaver** [comment]
After updating to Phaser 3.80, click events in the Ionic framework should all work properly, but they do not.

**Comment by photonstorm** [comment]
@rgk one for you to have a look at as a priority please, because I assume this is a result of the change with prevent default in 3.80.

**Comment by rgk** [comment]
@ulsoftnaver which framework? Vue, react, angular?

I created a Vue Ionic App to try and reproduce this, built for the web but it still received @click events and @keydown.tab on ion-buttons.

![image](https://github.com/phaserjs/phaser/assets/631018/4c069309-4d69-4574-b951-a89af93c0708)
[phaser-vue.zip](https://github.com/phaserjs/phaser/files/14406996/phaser-vue.zip)

**Comment by jaxtheking** [comment]
I was going to report the same issue after upgrading to 3.80.

The issue is not exclusive to Ionic or any specific framework. It can be replicated easily in plain JS: alongside the Phaser canvas, just have a link or button with a 'click' event listener assigned to it.
When you click the element on a touch device (also in the Chrome mobile emulator), the callback is never fired. Events like 'touchend' or 'pointerdown' are instead fired.

The culprit is the fix for #6697:
```
this.onTouchEndWindow = function (event)
{
    if (!event.defaultPrevented && _this.enabled && manager && manager.enabled && event.target !== canvas)
    {
        //  Only process the event if the target isn't the canvas
        manager.onTouchEnd(event);

        if (_this.capture && event.cancelable)
        {
            event.preventDefault();
        }
    }
};
```

Reverting the function to how it was in version 3.70 restores clicking on external HTML elements:
```
this.onTouchEndWindow = function (event)
{
    if (!event.defaultPrevented && _this.enabled && manager && manager.enabled && event.target !== canvas)
    {
        //  Only process the event if the target isn't the canvas
        manager.onTouchEnd(event);
    }
};
```

Hope that helps.

**Comment by ulsoftnaver** [comment]
Thank you for your response.
It works well on the web currently.
However, when running on an Android device, there is an issue where clicks and touches do not work.

**Comment by ulsoftnaver** [comment]
> 3.80으로 업그레이드 한 후에도 동일한 문제를보고하려고했습니다.
> 
> 이 문제는 Ionic 또는 특정 프레임 워크에만 국한되지 않습니다. 일반 JS에서 쉽게 복제 할 수 있습니다 : Phaser 캔버스와 함께 '클릭'이벤트 리스너가 할당 된 링크 또는 버튼 만 있으면 됩니다. 터치 장치(Chrome 모바일 에뮬레이터에서도 포함)에서 요소를 클릭하면 콜백이 실행되지 않습니다. 대신 'touchend' 또는 'pointerdown'과 같은 이벤트가 발생합니다.
> 
> 범인은 [# 6697](https://github.com/phaserjs/phaser/issues/6697)에 대한 수정 사항입니다.
> 
> ```
> this.onTouchEndWindow = function (event)
> {
>     if (!event.defaultPrevented && _this.enabled && manager && manager.enabled && event.target !== canvas)
>     {
>         //  Only process the event if the target isn't the canvas
>         manager.onTouchEnd(event);
> 
>         if (_this.capture && event.cancelable)
>         {
>             event.preventDefault();
>         }
>     }
> };
> ```
> 
> 함수를 버전 3.70의 방식으로 되돌리면 외부 HTML 요소를 클릭하면 복원됩니다.
> 
> ```
> this.onTouchEndWindow = function (event)
> {
>     if (!event.defaultPrevented && _this.enabled && manager && manager.enabled && event.target !== canvas)
>     {
>         //  Only process the event if the target isn't the canvas
>         manager.onTouchEnd(event);
>     }
> };
> ```
> 
> 도움이 되었기를 바랍니다.


Thank you for your reply. If I modify the source as you mentioned, will there be no problem in using it?

**Comment by ulsoftnaver** [comment]
> 어떤 프레임워크? 뷰, 리액션, 앵귤러?
> 
> 웹용으로 제작된 Vue Ionic App을 만들었지만 여전히 이벤트와 이온 버튼의 @keydown.tab을 수신 했습니다.
> 
> ![이미지](https://private-user-images.githubusercontent.com/631018/307856124-4c069309-4d69-4574-b951-a89af93c0708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjcyNjcsIm5iZiI6MTcwOTAyNjk2NywicGF0aCI6Ii82MzEwMTgvMzA3ODU2MTI0LTRjMDY5MzA5LTRkNjktNDU3NC1iOTUxLWE4OWFmOTNjMDcwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwOTQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThkNWFlNGVkOWM5YWM1NzNiM2NhMDg1NmViMDg2YjVmN2U4NmU1ZmNhODE2MDU5NmRjNzUwOWVhYjExNmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jQC0GOulmbLaEX9Hu4P2tgD6yz6UmzLMV8ixbIgygmc) [phaser-vue.zip](https://github.com/phaserjs/phaser/files/14406996/phaser-vue.zip)

답변 감사합니다.
현재 웹에서 잘 작동합니다.
그러나 Android 기기에서 실행할 때 클릭과 터치가 작동하지 않는 문제가 있습니다.

**Comment by rgk** [comment]
At the current moment, reverting the change only will cause a double click while using touch to happen when clicking on DOM objects over the Canvas as stated in the initial bug, this will be fixed shortly.

@jaxtheking Thank you for the explanation, this made it very clear what was going wrong.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
Please update to v3.80.1 to resolve this issue.

**Comment by ulsoftnaver** [comment]
Thank you.
I will update you again after upgrading to 3.80.1

**Comment by ulsoftnaver** [comment]
After testing, I will provide feedback
