### ISSUE TITLE
WebGLPipelineConfig Type is missing uniforms property from the type definition

### ISSUE THREAD

**Issue by scottwestover** [phaserjs/phaser#6751]
## Version

* Phaser Version: 3.80.0

* Operating system: macOS Monterey Version 12.6.3

* Browser: N/A

## Description

The examples for shaders that extend the `Phaser.Renderer.WebGL.Pipelines.PostFXPipeline` class, include a property called `uniforms`, that is passed to to the parent class. When you use the same code with TypeScript, there is a warning about this property not existing on the `WebGLPipelineConfig` type.

Reference:

https://labs.phaser.io/edit.html?src=src/renderer/color%20post%20fx%20pipeline.js&v=3.80.1 and https://labs.phaser.io/assets/pipelines/BendPostFX.js

## Example Test Code

Example code can be found here: https://github.com/scottwestover/template-vite-ts-bug-example.
The main file is https://github.com/scottwestover/template-vite-ts-bug-example/blob/main/src/BendPostFX.ts, which is a slightly modified version of https://labs.phaser.io/assets/pipelines/BendPostFX.js.

To reproduce, in a TypeScript project, create a class that extends the `Phaser.Renderer.WebGL.Pipelines.PostFXPipeline` class, and in the `super` call, add in `uniforms`. You should see a TypeScript warning of uniforms not existing on the `WebGLPipelineConfig` type.

## Additional Information

<img width="1173" alt="Screen Shot 2024-02-28 at 10 36 54 AM" src="https://github.com/phaserjs/phaser/assets/9931822/bb67686e-1095-429e-825a-fe75e8866bbc">

Not sure if relevant, but when I don't provide the `uniforms` property to the configuration that is provide to the parent class, the code still works.

This might be related to https://github.com/phaserjs/phaser/issues/6737.

**Comment by photonstorm** [comment]
Hi Scott - This property is no longer required. A shader will automatically extract the uniforms via a WebGL call, so you don't need to list them anymore. However, it appears the examples have not been updated to reflect this. If you remove them from the example code, the example will still work just fine.

btw nice Phaser RPG series YouTube videos! Hopefully that's you? :)

**Comment by scottwestover** [comment]
Nice! Thanks for the quick response, and for your help.

Yes, that is me. Also, thank you for the kinds words about the series, really appreciate it :)

**Comment by photonstorm** [comment]
Ok, I have now fixed all of the pipeline examples so they no longer set `uniforms`.
