### ISSUE TITLE
Missing type define of useSpriteSheet parameter

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6752]
## Version

* Phaser Version: 3.80.1

* Operating system:

* Browser:

## Description

Parameter [`useSpriteSheet`](https://github.com/phaserjs/phaser/blob/master/src/tilemaps/components/CreateFromTiles.js#L83) is part of `spriteConfig`, which is [Phaser.Types.GameObjects.Sprite.SpriteConfig](https://github.com/phaserjs/phaser/blob/master/src/tilemaps/components/CreateFromTiles.js#L22) type.
However, type define [Phaser.Types.GameObjects.Sprite.SpriteConfig](https://github.com/phaserjs/phaser/blob/master/src/gameobjects/sprite/typedefs/SpriteConfig.js) does not include `useSpriteSheet`.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
