### ISSUE TITLE
Phaser 3 tutorial dead resource link

### ISSUE THREAD

**Issue by jauntyjocularjay** [phaserjs/phaser#6757]
## Version
* Phaser Version: 3

* Operating system: Windows 10

* Browser: Chrome

## Description

The tutorial resource link on [this page](https://phaser.io/tutorials/making-your-first-phaser-3-game/part1) is dead. The resources [phaser3-tutorial-src.zip](https://phaser.io/tutorials/making-your-first-phaser-3-game/phaser3-tutorial-src.zip) cannot be downloaded.

## Example Test Code

na

## Additional Information

Looks like it was moved [here](https://github.com/phaserjs/examples/blob/master/public/3.55/src/games/firstgame/phaser3-tutorial-src.zip).

**Comment by Neamar** [comment]
Came here for the same issue,

Worth noting that the linked zip file may not be exactly the same: instead of

```js
    this.load.image('sky', 'assets/sky.png');
    this.load.image('ground', 'assets/platform.png');
    this.load.image('star', 'assets/star.png');
    this.load.image('bomb', 'assets/bomb.png');
```

it includes additional path in the URL:

```js
    this.load.image('sky', 'src/games/firstgame/assets/sky.png');
    this.load.image('ground', 'src/games/firstgame/assets/platform.png');
    this.load.image('star', 'src/games/firstgame/assets/star.png');
    this.load.image('bomb', 'src/games/firstgame/assets/bomb.png');
```

**Comment by photonstorm** [comment]
The correct link is: https://cdn.phaser.io/tutorials/making-your-first-phaser-3-game/phaser3-tutorial-src.zip

This has now been updated in the tutorial as well.
