### ISSUE TITLE
Tween.isFinished() not working since 3.80.0

### ISSUE THREAD

**Issue by Baegus** [phaserjs/phaser#6760]
## Version

* Phaser Version: 3.80.0 and 3.80.1

* Operating system: Windows, Mac OS X

* Browser: All browsers

## Description

Since upgrading to Phaser 3.80, I'm unable to check if a Tween or a TweenChain is finished by using the `.isFinished()` function. It always returns `false`. Same problem on 3.80.1. It works fine on 3.70 (as you can see in my CodePen example).

## Example Test Code

[CodePen](https://codepen.io/baegus/pen/RwOPWbZ)

**Comment by rgk** [comment]
You have to set `persist: true` in the tween config for `isFinished()` to work as expected.

This change is from:
https://github.com/phaserjs/phaser/commit/74515f6437d2ebb37971babcd07610bf0ec31b15

**Comment by Baegus** [comment]
> You have to set `persist: true` in the tween config for `isFinished()` to work as expected.

Thank you. In that case, [this documentation](https://newdocs.phaser.io/docs/3.80.0/focus/Phaser.Tweens.BaseTween-persist) is wrong about TweenChains persisting by default.

**Comment by Baegus** [comment]
@zekeatchan I'm afraid the [documentation](https://newdocs.phaser.io/docs/3.80.0/focus/Phaser.Tweens.BaseTween-persist) is still wrong.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
