### ISSUE TITLE
 Tutorial is now out of order

### ISSUE THREAD

**Issue by digitaldeja0** [phaserjs/phaser#6762]
The learn tutorial is now out of order, part 10 is located in the slot of part 2: https://phaser.io/tutorials/making-your-first-phaser-3-game/part10
In the screenshot, in the left menu, it goes 
introduction - part 1
bouncing bomb - part 10
...
![part10](https://github.com/phaserjs/phaser/assets/90660363/b9a363ee-1e53-4c3a-acb6-9ec30318db6e)

**Comment by photonstorm** [comment]
This is now fixed, thanks for reporting it.
