### ISSUE TITLE
Cursor not refreshing after disableInteractive()

### ISSUE THREAD

**Issue by pabloNeuronup** [phaserjs/phaser#6766]
## Version

* Phaser Version: >3.70
* Operating system: All
* Browser: All

## Description
After a disableInteractive() on a game object cursor doesn't refresh to original state. Despite removeInteractive() works correctly.

## Example Test Code
```js
class Example extends Phaser.Scene {
    constructor() {
        super();
    }

    preload() {

    }

    create() {
        const rect = this.add.rectangle(200, 200, 50, 50, 0xff0000);

        rect.setInteractive({ cursor: 'pointer' });
        rect.on('pointerdown', () => { rect.disableInteractive() });
        //rect.on('pointerdown', () => { rect.removeInteractive() });
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    pixelArt: true,
    scene: Example
};

const game = new Phaser.Game(config);
```

**Comment by photonstorm** [comment]
While this could be done, disabling _any_ interactive object that sets the cursor would reset the cursor again, no matter how that disable was triggered. This is actually currently an issue with `removeInteractive`.  The cursor has no idea which object made it change; it only knows that it has changed, so a blanket reset would fix this while also having equally unintended side effects.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
