### ISSUE TITLE
When graphic object is removed from container, it continues to be rendered

### ISSUE THREAD

**Issue by pavels** [phaserjs/phaser#6772]
When you remove object like sprite or mesh from container, it continues to be rendered.

See example bellow:

```
class Example extends Phaser.Scene
{
    constructor ()
    {
        super();
    }

    preload ()
    {
        this.load.image('ayu', 'assets/pics/ayu.png');
    }

    create ()
    {
        const mesh = new Phaser.GameObjects.Mesh(this, 400, 150, 'ayu');
        const sprite = new Phaser.GameObjects.Sprite(this, 400, 450, 'ayu');

        sprite.setScale(0.5)

        const container = this.add.container(0, 0);

        Phaser.Geom.Mesh.GenerateGridVerts({
            mesh,
            widthSegments: 6,
            width: mesh.width / 4,
            height: mesh.height / 4
        });

        mesh.hideCCW = false;
        mesh.setOrtho(mesh.width, mesh.height);

        this.debug = this.add.graphics();
        mesh.setDebug(this.debug);

        container.add(mesh);
        container.add(sprite);

        this.input.on('pointerdown', pointer => {
            mesh.parentContainer.remove(mesh)
            sprite.parentContainer.remove(sprite)
        })         
    }

    update ()
    {
        this.debug.clear();
        this.debug.lineStyle(1, 0x00ff00);
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#0a440a',
    parent: 'phaser-example',
    scene: Example
};

let game = new Phaser.Game(config);
```

This problem was introduced in 3.53.0 and is present in 3.80.1 still.

**Comment by photonstorm** [comment]
It renders because it's a member of the Scene. Removing it from a Container doesn't remove it from the Scene, it just removes it from the Container. If you want it to stop rendering it needs removing from the display list.

**Comment by pavels** [comment]
In 3.52 it stopped being rendered

Also, if you remove this code from example:

```
container.add(mesh);
container.add(sprite);
```

it is not being rendered

does it mean that if i add object to container it gets automatically added to scene displaylist and if i remove object from the container, it stays on that display list?

**Comment by photonstorm** [comment]
Yes, when you add it to the Container it becomes part of the Display List the Container belongs to (which could be a Scene or a Layer.) When you remove it, as it doesn't have another parent to go to, it gets removed from whatever list it was on and then re-assigned to the Scene Display List. The Game Object will also emit the `ADDED_TO_SCENE` event (as will the Display List), so it can be captured at this point and adjusted as needed.

**Comment by pavels** [comment]
Ok, understood

Thank you for explanation
