### ISSUE TITLE
Jittering png sequence animation

### ISSUE THREAD

**Issue by Yakir-R** [phaserjs/phaser#6779]
I'm dealing with minor jittering issue in png sequence animation in mobile, specifically older android and IOS versions.

The asset is exported as sprite-sheet from TexturePacker with size of 2048x2048, no trimming and no extrusion and gets imported into Phaser as atlas. I have tried importing it as sprite-sheet as well with no luck.
I will mention that the sprite-sheet gets scaled down in TexturePacker to 0.75 for mobile, but the issue also happens when the sprite-sheet is scale 1.

video was recorded in phaser 3.60 but it also happens in phaser 3.80.1.
I'm sharing an exaggerated video of the issue.

https://github.com/phaserjs/phaser/assets/97833654/5bd5ede0-1c7f-4b00-be1b-045f771f3396

**Comment by photonstorm** [comment]
Sorry for not spotting this earlier - but first of all, please test against the current master branch, and I believe the latest release will address this (as it looks like you've for the Shine FX running on that sprite). If you're not using any FX, then please upload the code and sample assets so we can look at it, as we can't really debug videos. We will re-open this issue after that is done.
