### ISSUE TITLE
The last touch input pointer is never activated

### ISSUE THREAD

**Issue by samme** [phaserjs/phaser#6783]
## Version

* Phaser Version: 3.80.1 and earlier

## Description

The Input Manager seems to use one fewer touch pointer than its [pointersTotal](https://newdocs.phaser.io/docs/3.80.0/focus/Phaser.Input.InputManager-pointersTotal).

## Example Test Code

See <https://codepen.io/samme/pen/VwdeZEL>.

The game config has `activePointers: 4`. The Input Manager has 4 touch pointers (IDs 1 to 4). This is correct.

Put 4 fingertips on the game canvas. Only 3 touch pointers activate.

**Comment by rgk** [comment]
Nice find!

Thank you for submitting this issue. We have fixed this and the fix has been pushed to the master branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
