### ISSUE TITLE
Official Ready-to-Use Fiddle Template with latest version

### ISSUE THREAD

**Issue by monteiz** [phaserjs/phaser#6786]
## Feature Request: Official Ready-to-Use Fiddle Template

**Description:**

Implement an official, ready-to-use fiddle template for Phaser 3. This template would expedite the process of submitting code examples for new issues, bug reports, and feature requests.

**Benefits:**

1. **Simplified Contribution:** Standardized template streamlines code example setup for contributors.
  
2. **Consistency:** Ensures uniformity across code examples for easier understanding and reproduction.
   
3. **Lower Barrier to Entry:** Facilitates participation from new contributors and those unfamiliar with fiddle setups.

**Proposed Implementation:**

Host a basic fiddle template on platforms like CodePen or JSFiddle, including:
1. Boilerplate HTML structure with necessary Phaser 3 scripts and stylesheets.
2. Placeholder code demonstrating a basic Phaser 3 setup with instructional comments.
3. Optional sections for additional assets if required.
4. Clear instructions on customizing and expanding the template.

**Conclusion:**

Introducing an official fiddle template would enhance contribution experience within the Phaser 3 community, aligning with our goals of collaboration and community engagement.

**Comment by monteiz** [comment]
So far, I found the quickest method to submit a test code is to edit a Phaser example, and past the code into the Issue ticket (with the link to the original example, even if that's not really necessary).

It would be nice to have this (or any other quick way) explained in the Issue template.

**Comment by photonstorm** [comment]
Going to close this off as we now have our Phaser Sandbox, and that is by far the easiest way to submit an example to us now.
