### ISSUE TITLE
Bug : Lines do not display correctly if Text is added to the scene

### ISSUE THREAD

**Issue by DoodahProductions** [phaserjs/phaser#6788]
### Discussed in https://github.com/phaserjs/phaser/discussions/6787

<div type='discussions-op-text'>

<sup>Originally posted by **DoodahProductions** April 10, 2024</sup>
Hello,

I encounter this display issue where Lines do not display correctly if Text is added to the scene.

Lines added without any Text display correctly in all directions :
<img width="891" alt="Screenshot 2024-04-10 at 12 30 12 PM" src="https://github.com/phaserjs/phaser/assets/23157833/a5063c4d-073f-44e4-b1a3-c0ab735c72e4">

Lines added with any Text display correctly only when vertical / horizontal : 
<img width="745" alt="Screenshot 2024-04-10 at 12 29 27 PM" src="https://github.com/phaserjs/phaser/assets/23157833/d18d71bc-52c0-4724-a2f2-840613a822a1">
<img width="717" alt="Screenshot 2024-04-10 at 12 29 33 PM" src="https://github.com/phaserjs/phaser/assets/23157833/d267f3da-07ca-4cda-849c-6483fbc4b5d0">

Tested on : Google Chrome
Phaser 3.80.1

Repro steps : 
- Create a class 'Block' that extends Phaser.GameObjects.Container. This class should add a Rectangle as child and be draggable.
- Add two 'Block' to your scene
- On update, draw a Line that will link the two Block
- Drag and Drop any of the Block and see that Line is correctly displayed in any direction.

- Add a Phaser.GameObjects.Text to the Block
- Drag and Drop any of the Block and see that Line is only displayed when Blocks are aligned horizontally/vertically.

</div>

**Comment by photonstorm** [comment]
Hi - we need a code example if we're to debug this. Feel free to use the Phaser Sandbox to submit one (https://phaser.io/sandbox)

**Comment by photonstorm** [comment]
Hi - we can't replicate this. See example below. Please adjust this code to make the issue happen and we can re-test it:

```js
class Example extends Phaser.Scene
{
    create ()
    {
        this.add.line(100, 100, 100, 100, 400, 300, 0x00ff00);
        
        this.add.text(100, 100, 'Hello World', { fontFamily: 'Arial', fontSize: 32, color: '#00ff00' });

        this.add.line(400, 300, 100, 100, -200, 150, 0x00ff00);
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: Example
};

const game = new Phaser.Game(config);
```
