### ISSUE TITLE
Nineslice object bug

### ISSUE THREAD

**Issue by IvanDem** [phaserjs/phaser#6804]
## Version
* Phaser Version:
Phaser Version: 3.80.1 and earlier
* Operating system:
Windows 11
* Browser:
Chrome

## Description
Occasionally, my game encounters a loading issue, after adding a nineslice object to my language menu, which creates on game load. This problem surfaced recently and has been noticed by two different testers. The bug occurs randomly, but once triggered, a page refresh isn't effective in resolving it. The issue persists as long as the nineslice object is being created. To resolve it, users need to restart Chrome.
<img width="1680" alt="Screenshot 2024-04-26 at 10 11 59" src="https://github.com/phaserjs/phaser/assets/22764524/e3e7604e-f637-43d7-90a7-f0f68ed24faf">

## Additional Information

Might be need to add extra condition here: 
https://github.com/phaserjs/phaser/blob/master/src/gameobjects/nineslice/NineSlice.js
if (frame.scale9 && !skipScale9) => if (**frame** && frame.scale9 && !skipScale9)
if (textureFrame.scale9) = > if (**textureFrame** && textureFrame.scale9)

A second testers told be, he stopped to got any loading freeze after he updated GPU driver and chrome, the first one still have this sometimes.
I've asked to test it out phaser's 3 labs nineslice examples. Will update once got more information

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
