### ISSUE TITLE
Inconsistent Versioning and the Case for Adopting SemVer

### ISSUE THREAD

**Issue by monteiz** [phaserjs/phaser#6805]
#### Description
Phaser 3 has historically followed a versioning approach that doesn't strictly adhere to the Semantic Versioning (SemVer) convention. This inconsistency in versioning practices, along with the use of nicknames for releases, can lead to confusion and frustration for developers and users when trying to understand the significance of each release.

#### Why it Matters
1. **Clarity**: SemVer provides a standardized way to communicate changes in a release (major, minor, patch), allowing developers to quickly understand the nature and impact of updates.
2. **Predictability**: With SemVer, developers can anticipate how upgrading to a new version might affect their projects, reducing unexpected compatibility issues.
3. **Dependency Management**: SemVer simplifies dependency management by enabling developers to specify version ranges, ensuring that dependencies are updated appropriately.
4. **Incremental Development**: SemVer encourages incremental development practices, facilitating more frequent and iterative updates.

#### Concerns about Nicknames
1. **Memorability**: While nicknames can add personality to releases, they may not be as memorable or intuitive as version numbers, leading to confusion among developers and users.
2. **Lack of Information**: Nicknames often do not convey information about the changes introduced in a release, making it harder for users to understand the significance of each update.
3. **Risk of Ambiguity**: Without a clear versioning scheme, relying solely on nicknames can introduce ambiguity and make it challenging to manage dependencies and track compatibility.

#### Proposal
I propose that Phaser 3 adopts a clearer versioning strategy, such as embracing SemVer, while reconsidering the use of nicknames for releases. This would provide developers and users with a more consistent and predictable experience when upgrading and maintaining their projects, reducing confusion and improving overall usability.

#### Suggestions
1. **Clearly Defined Versioning Policy**: Establish a clear versioning policy that outlines how version numbers will be incremented based on the nature of changes (major, minor, patch).
2. **Consistent Release Notes**: Ensure that release notes are comprehensive and clearly communicate the changes introduced in each release, including any breaking changes or notable new features.
3. **Community Engagement**: Seek input and feedback from the Phaser 3 community to ensure that any changes to versioning practices align with their needs and expectations.

#### Conclusion
Adopting SemVer or a similar clear versioning strategy, while reevaluating the use of nicknames, would not only benefit developers by providing greater clarity and predictability but also contribute to a more user-friendly and accessible development experience for the Phaser 3 community.

Thank you for considering this proposal. I look forward to hearing your thoughts and discussing how we can improve versioning practices in Phaser 3.

**Comment by photonstorm** [comment]
This smells like an AI generated issue. We've covered how we handle versioning many times in the past (see our Dev Logs for details). Our Change Logs are extensive and detailed and always have been. The nicknames are never used to refer to a version in our documentation, it's all version number based. No, it doesn't strictly follow semver and at this stage in the projects life, it never can. That boat has sailed. When we move over to v4 versioning we can revisit it, but not until then.

**Comment by monteiz** [comment]
Yes, it is AI generated under my supervision. It's 10x faster and its English is surely better than mine :)

Happy to hear that SemVer is considered for v4.

I agree that the Change Logs are very extensive and I appreciate that. The benefit of SemVer is that you don't really need to read all the Change Logs every time (I think it's very unlikely that one is interested in all the changes, most likely a small part of it).

With SemVer, you just read the number and you know if your code will break or not, if you upgrade. That improves productivity a lot.

Plus, it forces you to strengthen your test suite to check retro-compatibility issues, which makes the framework more robust.
