### ISSUE TITLE
[Input] disableInteractive() with NOT topOnly case

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6820]
## Version

* Phaser Version: 3.80.1

* Operating system: win11

* Browser: chrome, firefox

## Description

[Test code](https://phaser.io/sandbox/3ZubqoQs), set `secne.input.topOnly` to `false`
- Disable line 19 `this.disableInteractive()`, it will log `0`, `1` shown that 2 game objects has been touched
- Enable line 19, only `1` will be shown

The root cause might be:
1. In `processDragUpEvent` method, the loop is based on [`this._drag` list](https://github.com/phaserjs/phaser/blob/master/src/input/InputPlugin.js#L1402)
2. In `disableInteractive()` method called under 'dragend' event, it will [remove game object from `this._drag` list](https://github.com/phaserjs/phaser/blob/master/src/input/InputPlugin.js#L839-L854), that will cause loop error of step1

Might copy `this._drag` list in step 1 to fix this bug (if length of this._drag is larger than 1).

**Comment by zekeatchan** [comment]
Thanks @rexrainbow for submitting a PR for this issue. The fix has been pushed to the `master` branch and will be part of the next release.
