### ISSUE TITLE
SceneManager.getScene has wrong return type in ts definition

### ISSUE THREAD

**Issue by vankop** [phaserjs/phaser#6821]
## Version

* Phaser Version: latest

* Operating system:

* Browser:

## Description

`SceneManager.getScene` has wrong return type in ts definition. see `types/phaser.d.ts`. Should be `Phaser.Scene` if `typeof key === "string"`

**Comment by zekeatchan** [comment]
Hi @vankop, kindly provide test code examples so we can investigate further and have a better understanding of the issue you're facing. Thanks!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by BenAfonso** [comment]
This seems to have broken the type definition in 3.86.0:

Behaviour:
```
SceneManager.getScene<T extends Phaser.Scene>(key: (T|string)): Phaser.Scene | null

ScenePlugin.get<T extends Phaser.Scene>(key: (T|string)): Phaser.Scene;
```

Expected:
```
SceneManager.getScene<T extends Phaser.Scene>(key: (T|string)): T | null

ScenePlugin.get<T extends Phaser.Scene>(key: (T|string)): T | null;
```
