### ISSUE TITLE
Tilemap support for spacing and/or margin broken since 3.80

### ISSUE THREAD

**Issue by damian-pastorini** [phaserjs/phaser#6823]
## Version
3.80.1
* Phaser Version:
since 3.80
* Operating system:
Any
* Browser:
Any

## Description
Since 3.80 if you try to use a Tilemap with spacing and/or margin the Tilemap displayes fully broken (tiles out of place):

![image](https://github.com/phaserjs/phaser/assets/1211779/8af84bda-b57c-4763-a8cb-d9654707f90f)

## Example Test Code
My code base is quite big by now, but it's open source, so my implementation can be see between:
https://github.com/damian-pastorini/reldens/blob/master/lib/game/client/scene-preloader.js
and 
https://github.com/damian-pastorini/reldens/blob/master/lib/game/client/scene-dynamic.js

To summarize it, I'm using:
```
scene.load.spritesheet(imageKey, `/maps/${imageFileName}`, tileData);
```

And then:
```
scene.map.addTilesetImage(
                imageFileName,
                imageKey,
                tileData.width,
                tileData.height,
                tileData.margin,
                tileData.spacing
            )
```

These files will show the broken case:

- [reldens-house-1.json](https://github.com/phaserjs/phaser/files/15437701/reldens-house-1.json)

![reldens-house-1](https://github.com/phaserjs/phaser/assets/1211779/ae7351dc-9ec5-4d08-85d9-e183420e9db4)

These are loaded fine in the TileMapEditor app and work fine in version <=3.70.
You can see it in my demo (https://demo.reldens.com):

![image](https://github.com/phaserjs/phaser/assets/1211779/6393b0e1-b614-456a-acf9-1ec42a6272b9)

![image](https://github.com/phaserjs/phaser/assets/1211779/b207a24e-2a98-41ac-b97c-cbb5ae10b12d)

If I remove the margin and spacing then it works fine in >=3.80:

- [reldens-house-1.json](https://github.com/phaserjs/phaser/files/15437774/reldens-house-1.json)

![reldens-house-1](https://github.com/phaserjs/phaser/assets/1211779/2335bc16-b56d-414a-b128-abf2e8ce58cd)

## Additional Information

I've been using the Tile extruder and adding margin and spacing to the maps because prior to 3.80 I've always had the "extrude" issue when the player moves and then you see the lines between the tiles, but if I resize the files to their original 32x32 and remove the spacing and margin the "extrude" issue is not visible anymore, so though the spacing support is broken now I was able to avoid the original issue anyway.

Thanks for all your hard work!!!

**Comment by damian-pastorini** [comment]
After further test "extrude" the tiles is still required in some cases:

![image](https://github.com/phaserjs/phaser/assets/1211779/f9b92021-93e2-4031-a4d5-6020f0b23593)

I'm trying to fix the tileset in betwee, but getting the spacing / margin support fixed would help.

Thanks again!

**Comment by damian-pastorini** [comment]
Update: the issue is when you combine: load.spritesheet with tilemaps with spacing / margin, it just doesn't work since 3.80.

scene.load.spritesheet(imageFile, /assets/maps/${imageFile}, tileData);
scene.load.image('Desert', 'https://demo.reldens.com/assets/maps/reldens-house-1.png');

Issue visible here: https://phaser.io/sandbox/5orKEN3E switch between 3.80 and 3.70.

**Comment by photonstorm** [comment]
Strangely, simply swapping the example to `load.image` worked perfectly (instead of `load.spritesheet` which is rarely needed for a tileset), which at least allowed me to narrow it down and find a fix in the Texture class.
