### ISSUE TITLE
Lottie / Vector based Animation Support

### ISSUE THREAD

**Issue by Bubba83** [phaserjs/phaser#6827]
I know GIF and PNG sequence support is available in Phaser, but I am pretty sure vector based/Lottie animations are not available from some of the searching I have done on Google, Game Dev Forums, and StackOverflow.

https://lottiefiles.com/what-is-lottie

I was hoping this could be added as a new feature, as I have a project in mind where we have existing Lottie animations that we would like to use as part of a new Phaser game we are developing.

Until this support is added, I can transform these into GIFs, but they would then have some limitations of that are inherent with the animations being raster.

**Comment by photonstorm** [comment]
Lottie uses its own C++ runtime (ThorVG) to handle all rendering. This is turned into a WASM bundle via Emscripten. There is no easy path from here to Phaser, or frankly, anywhere other than embedding their web player on your site. This in turn renders to a canvas element, so I guess you could use that as a texture within Phaser - but it would be highly inefficient, so this isn't something we're going to explore any time soon, sorry.

**Comment by Bubba83** [comment]
Thanks for the detailed explanation of why not. This is very useful information for us so we will know which way to develop our animations, realizing this won't be supported any time soon. We love the framework, keep up the great work!
