### ISSUE TITLE
In TPhaser3.9  rectangle is err

### ISSUE THREAD

**Issue by woshisheji** [phaserjs/phaser#6830]
this.aaa=this.add.rectangle(100,100,100,100,0,1);

In TPhaser3.9, the rectangle creation has already reported an error, both 3.9s have reported errors, and I have not tested the other functions yet. Only one creation rectangle was tested

**Comment by photonstorm** [comment]
This is correct, as none of the Shape Game Objects are in TP1 or TP2. Only Sprites, Images, Text and Video Game Objects will work. We will add more into TP3.
