### ISSUE TITLE
Different behavior of input events between 3.50 and 3.80.1

### ISSUE THREAD

**Issue by ddanushkin** [phaserjs/phaser#6833]
## Version
* Phaser Version: 3.80.1, 3.55.2
* Operating system: Windows 11
* Browser: Edge

## Description
Setting GO input.enabled to false, stops scene input events from triggering

## Example Test Code
https://phaser.io/sandbox/UH7Jeo51
(3.80.1 by default, you can change phaser version in editor)

## Additional Information
Here is console.log from 3.80 and 3.50 after a tap on GO
![image](https://github.com/phaserjs/phaser/assets/42466730/385ce953-ba3a-4e65-98a9-635d034ed927)
![image](https://github.com/phaserjs/phaser/assets/42466730/b1034e8e-1a51-49bd-9d42-bff4c7322f36)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
