### ISSUE TITLE
Docs website typo

### ISSUE THREAD

**Issue by riprsa** [phaserjs/phaser#6834]
Sorry, did not find a right place to report this issue. On a tutorial page a nav bar `Making your first game` button has a wrong `href`. It is `https://phaser.io/tutorials/making-your-first-phaser-game/part1`, while it should be `https://phaser.io/tutorials/making-your-first-phaser-3-game/part1`. That's just a small typo with a link, but because of it the button sends you to 404 page. Please, find attached the screenshot with that nav button selected

<img width="335" alt="image" src="https://github.com/phaserjs/phaser/assets/44776391/54b39077-0c41-43e0-b39a-7642c9537316">

**Comment by photonstorm** [comment]
Thanks, this has now been fixed.
