### ISSUE TITLE
scaleManager.isPortrait and scaleManager.isLandscape 

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6837]
## Version

* Phaser Version: 3.80.1

* Operating system: ios

* Browser: Safari

## Description

4 results ([portrait-primary](https://www.w3.org/TR/screen-orientation/#dfn-primary), [landscape-primary](https://www.w3.org/TR/screen-orientation/#dfn-primary), [portrait-secondary](https://www.w3.org/TR/screen-orientation/#dfn-secondary), [landscape-secondary](https://www.w3.org/TR/screen-orientation/#dfn-secondary)) returned when orientation-changed.
However, phaser3 engine tests `isPortrait`, `isLandscape` with `'portrait-primary'`, `'landscape-primary'` only ([ref](https://github.com/phaserjs/phaser/blob/master/src/scale/const/ORIENTATION_CONST.js))
Thus it will miss `'portrait-secondary'`, `'landscape-secondary'`. In these orientation states, `isPortrait`, `isLandscape` are return `false`.

[Test code](https://phaser.io/sandbox/CJaF51Wg), rotate mobile device to change orientation

**Comment by rexrainbow** [comment]
BTW, [Window: orientationchange event is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event)

**Comment by zekeatchan** [comment]
Hi @rexrainbow. Thank you for submitting this feature request.

We have implemented:

1. additional `landscape-secondary` and `portrait-secondary` orientation change events
2. updated the handlers to use the `screen.orientation` `change` event

These updates have been pushed to the `master` branch and will be part of the next release. Do test it out at your convenience.
