### ISSUE TITLE
Documentation clarification or bug?

### ISSUE THREAD

**Issue by ssotangkur** [phaserjs/phaser#6839]
## Version
* Phaser Version: 3.53.1 (also see in 3.80.0)

* Operating system: Windows 11

* Browser: (not browser specific)

## Description

The docs for [LeftButtonReleased ](https://newdocs.phaser.io/docs/3.80.0/focus/Phaser.Input.Pointer-leftButtonReleased) state that it returns:

> true if the left button was just released.

However the phrase "just released" seems very ambiguous so it's unclear if the existing behavior is correct or not. 
What I noticed by adding the example test code below is that after left-clicking only once, the function returns true indefinitely (even minutes later). This does not seem consistent with what many people would describe as "just released". I think the expectation is that after a short while the state would reset back to false. How short could be an optional parameter to the function.

## Example Test Code

```javascript
update() {
...
  console.log(this.input.mousePointer.leftButtonReleased());
}
```

**Comment by photonstorm** [comment]
The docs need changing, it's not possible to pass a time value to this method, as the down durations are not recorded for every single button, only the active (most recent) one.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
