### ISSUE TITLE
The jsDeliver's `phaser@3.80.1/+esm` link doesn't work

### ISSUE THREAD

**Issue by ivan-enzhaev** [phaserjs/phaser#6840]
I don't know is it an issue of jsDeliver or Phaser. I have created both. The jsDeliver's issue: https://github.com/jsdelivr/jsdelivr/issues/18585

This link doesn't work: https://cdn.jsdelivr.net/npm/phaser@3.80.1/+esm Try to run the example below.

Playground: https://plnkr.co/edit/MCZZM4MzkMSkFf4V?preview

index.html

```html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The jsDeliver's `phaser@3.80.1/+esm` link doesn't work</title>
</head>

<body>
    <p><a href="https://github.com/phaserjs/phaser/issues/6840" target="_black">Issue for Phaser</a></p>
    <p><a href="https://github.com/jsdelivr/jsdelivr/issues/18585" target="_black">Issue for jsDelivr</a></p>

    <script type="importmap">
        {
            "imports": {
                "phaser3": "https://cdn.jsdelivr.net/npm/phaser@3.80.1/+esm"
                // "phaser3": "https://8observer8.github.io/libs/phaser@3.80.1/phaser.esm.min.js"
            }
        }
    </script>

    <script type="module" src="./js/index.js"></script>
</body>

</html>
```

index.js

```js
import { WEBGL, Game } from "phaser3";

const config = {
    type: WEBGL,
    width: 400,
    height: 300,
    scene: { preload, create, update },
    backgroundColor: "#555",
};

const game = new Game(config);

function preload() {
    console.log("preload");
}
function create() {}
function update() {}
```

**Comment by photonstorm** [comment]
jsDelivr is taking a perfectly valid ESM module and then running it through Rollup and Terser again. For reasons best known only to them. I assume it's screwing-up Phaser in the process. Maybe this works on some projects, but I doubt it will on Phaser until we move to being a purely ESM based library.

**Comment by samme** [comment]
You can use <https://cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.esm.js> etc. instead.

**Comment by ivan-enzhaev** [comment]
I prefer to use GitHub Pages because there are problems sometimes with UNPKG and jsDelivr. I have made this page for some libraries: https://8observer8.github.io/tutorials/setup/how-to-setup-js-libraries-as-es6-modules/public/index.html

Phaser 3:

- GitHub Pages: https://8observer8.github.io/libs/phaser@3.80.1/phaser.esm.min.js
- UNPKG: https://unpkg.com/phaser@3.80.1/dist/phaser.esm.min.js
- jsDelivr: https://cdn.jsdelivr.net/npm/phaser@3.80.1/dist/phaser.esm.min.js
- The jsDelivr's "phaser@3.80.1/+esm" link: [issue](https://github.com/phaserjs/phaser/issues/6840)
- The Skypack's link: [issue](https://github.com/phaserjs/phaser/issues/6838)

You can use these links for @box2d/core:

GitHub Pages:

- @box2d/core@0.10.0: https://8observer8.github.io/libs/box2d-core@0.10.0/box2d-core.min.js
- @box2d/debug-draw@0.10.0: [https://8observer8.github.io/libs/box2d-debug-draw@0.10.0/box2d-debug-draw.min.js](https://8observer8.github.io/libs/box2d-debug-draw@0.10.0/box2d-core.min.js)
- @box2d/particles@0.10.0: [https://8observer8.github.io/libs/box2d-debug-draw@0.10.0/box2d-particles.min.js](https://8observer8.github.io/libs/box2d-particles@0.10.0/box2d-core.min.js)
- @box2d/controllers@0.10.0: [https://8observer8.github.io/libs/box2d-debug-draw@0.10.0/box2d-controllers.min.js](https://8observer8.github.io/libs/box2d-controllers@0.10.0/box2d-core.min.js)
- @box2d/lights@0.10.0: [https://8observer8.github.io/libs/box2d-debug-draw@0.10.0/box2d-lights.min.js](https://8observer8.github.io/libs/box2d-lights@0.10.0/box2d-lights.min.js)

Skypack:

- @box2d/core@0.10.0: https://cdn.skypack.dev/@box2d/core@0.10.0
- @box2d/debug-draw@0.10.0: https://cdn.skypack.dev/@box2d/debug-draw@0.10.0
- @box2d/particles@0.10.0: https://cdn.skypack.dev/@box2d/particles@0.10.0
- @box2d/lights@0.10.0: https://cdn.skypack.dev/@box2d/lights@0.10.0
- @box2d/controllers@0.10.0: https://cdn.skypack.dev/@box2d/controllers@0.10.0

jsDelivr:

- @box2d/core: https://cdn.jsdelivr.net/npm/@box2d/core@0.10.0/+esm
- @box2d/debug-draw: https://cdn.jsdelivr.net/npm/@box2d/debug-draw@0.10.0/+esm
- @box2d/particles: https://cdn.jsdelivr.net/npm/@box2d/particles@0.10.0/+esm
- @box2d/lights: https://cdn.jsdelivr.net/npm/@box2d/lights@0.10.0/+esm
- @box2d/controllers: https://cdn.jsdelivr.net/npm/@box2d/controllers@0.10.0/+esm

These links do not work:

- UNPKG: https://unpkg.com/@box2d/core@0.10.0/dist/index.js
- jsDelivr: https://cdn.jsdelivr.net/npm/@box2d/core@0.10.0/dist/index.js
