### ISSUE TITLE
Allow a way to update the particle emitter with an incremental configuration

### ISSUE THREAD

**Issue by PhaserEditor2D** [phaserjs/phaser#6843]
It would be great if we can use a ParticleEmitter method to do an incremental update. Right now we can use the `setConfig()` method to do a full reset  of the properties. However, if we keep track of the latest config set by `setConfig()` we can implement a `addConfig()` method. Like this:

```js
setConfig(config) {
    this._config = config;
    // everything else
}

addConfig(config) {
    this.setConfig({...this._config, ...config});
}
```

Well, the `addConfig` name is a suggestion.

This is a method required by Phaser Editor to implement particle emitter nested prefab support.

**Comment by zekeatchan** [comment]
Hi @PhaserEditor2D. Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by arianfornaris** [comment]
Thanks @zekeatchan I will take a look!

**Comment by PhaserEditor2D** [comment]
Thanks @zekeatchan I will take a look!
