### ISSUE TITLE
Drag game object on multiple cameras scene

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser#6845]
## Version

* Phaser Version: 3.80.1

* Operating system: window11

* Browser: chrome, firefox

## Description

[Test code](https://phaser.io/sandbox/1ci38HRF)

There has 2 game objects,
- Attach bg game object to main camera named *'BG'*, this main camera does not have scrolling. This bg game object has input detect, but can't drag.
- Attach circle game object to another camera named *'GO'*, with camera scrolling. This circle won't be seen by main camera.

Dragging circle game object fast. You will see the position of circle game object does not sync with dragging.
Dump the camera name of current pointer under drag event, I will expect that this camera is *'GO'* camera. But in console, it will dump 'BG' sometimes.

After tracing the input plugin, I found that [hitTestPointer](https://github.com/phaserjs/phaser/blob/master/src/input/InputPlugin.js#L691) will catch bg game object, when dragging/pointermove fast.
Then it will use BG camera to calculate world position for dragging event. However, the [dragging target](https://github.com/phaserjs/phaser/blob/master/src/input/InputPlugin.js#L1283) is circle game object with GO camera ...

**Comment by zekeatchan** [comment]
Thanks @rexrainbow for submitting this PR. The update has been pushed to the `master` branch and will be part of the next release.
