### ISSUE TITLE
Phaser Game app instructions using Yarn

### ISSUE THREAD

**Issue by Davichobits** [phaserjs/phaser#6847]
When I create a new project using the Phaser Game app and Yarn, the final instructions say:

Next steps:
1. cd my-first-game
2. npm install
3. npm run dev

But I didn't use `npm`, I used `yarn` instead.

The instructions must be dynamically generated.

**Comment by askadityapandey** [comment]
I've addressed this issue in the create-app repository. The PR with the fix can be found here: [PR Link](https://github.com/phaserjs/create-game/pull/2)

The help message has been updated to include instructions for both npm and Yarn users. Once this PR is merged, it should resolve the reported issue.

Suggesting this issue be closed and redirected to the PR for further discussion if needed.

**Comment by Davichobits** [comment]
Thank you!

**Comment by gammafp** [comment]
Hi @askadityapandey and @Davichobits. Thanks to your proposals, we have updated the CLI (create-game). Starting from version 1.2.3, the package manager name is dynamic.

![image](https://github.com/phaserjs/phaser/assets/9221946/869a66ee-d046-4357-ac7c-fe9782c566e6)
