### ISSUE TITLE
The quality of the images is lost

### ISSUE THREAD

**Issue by nvphi91** [phaserjs/phaser#6848]
I have a problem with image quality in phaser 3. When resizing or setDisplaySize, the quality of the images is lost. Is this a issue in Phaser 3?
I'm using ver 3.80.1

**Comment by photonstorm** [comment]
More context needed: What size is your canvas? What size are the images, and what size are you scaling them to? All of these factors dictate what the end result looks like.

**Comment by photonstorm** [comment]
Closed due to lack of response.
