### ISSUE TITLE
When will the bug in 3.8.01 with resize causing blurriness when using masks be fixed?

### ISSUE THREAD

**Issue by woshisheji** [phaserjs/phaser#6851]
Could you please let me know when the issue with using resize and mask simultaneously in 3.8.01, which causes abnormal blurring of mask pixels, will be fixed? It's been a long wait... Now we have to revert the project back to development on 3.5.

**Comment by cy920820** [comment]
Is it just a mask? All the renderings here have become blurry

**Comment by woshisheji** [comment]
> 它只是一个面具吗？这里的所有渲染都变得模糊不清
mask下的对象就会模糊不清，其他对象还是正常的。 反复测试只要设置了resize就会出现这问题。。 目前只有3.55没事儿

**Comment by cy920820** [comment]
> > 它只是一个面具吗？这里的所有渲染都变得模糊不清
> > mask下的对象就会模糊不清，其他对象还是正常的。 反复测试只要设置了resize就会出现这问题。。 目前只有3.55没事儿

Everything displayed here feels blurry or jagged, especially the text

**Comment by zekeatchan** [comment]
Hi @woshisheji. Is this related to this #6769 ?

If yes, we're currently working on new renderer to address this issue.

If not, could you provide more details? Thanks!

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by joebnb** [comment]
> Hi @woshisheji. Is this related to this #6769 ?
> 
> If yes, we're currently working on new renderer to address this issue.
> 
> If not, could you provide more details? Thanks!

is there any update about this? it's too blurry

<img width="397" alt="image" src="https://github.com/user-attachments/assets/abc1670c-da64-4aed-86be-eafd39f91b91">

actual

<img width="712" alt="image" src="https://github.com/user-attachments/assets/04997f44-f34b-4fb6-8849-7496ab21de59">

**Comment by photonstorm** [comment]
> is there any update about this? it's too blurry

Don't comment closed issues. Open a new one and include code and a runnable sample that demonstrates the issue, otherwise it just wastes everyone's time, yours included.
