### ISSUE TITLE
Textures should have a way to `erase` a portion of the texture via a size / width / height

### ISSUE THREAD

**Issue by SelfDevTV** [phaserjs/phaser#6853]
# The problem

I have a dynamic texture I draw 1000s of numbers on it (via `Phaser.Gameobjects.Text` or `BitmapText`) and via `tex.draw()`. Sometimes I want to remove the text from a specific location on the texture. The only way I found this was via `.erase`. 
Problem is it only takes in a Gameobject but not the size itself. When i give it my text gameobject it will remove it but in a very weird way. Here is a screenshot:

![image](https://github.com/phaserjs/phaser/assets/48333000/b9058428-8537-430a-b24c-c9999a64a30a)

A fellow discord mate helped me out with a workaround:
```ts
const rect = this.add.rectangle(0, 0, 10, 10, 0);
dynTexture.erase(rect, 0, 0);
```

But still I thought why not implement another way of this function, that will also take in a size or width + height parameter. I would also like to try to implement it. 

API for example for a `DynamicTexture` might look like this: `dynTexture.erase(width: number, height: number = width, x: ....)`

**[Optional] Do you want to help provide this feature?**
Yes. API for example for a `DynamicTexture` might look like this: `dynTexture.erase(width: number, height: number = width, x: ....)`

**Comment by rexrainbow** [comment]
How about `clearRect` method name, similar as [`clearRect` in canvas api](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect)

**Comment by SelfDevTV** [comment]
Yes that could work too. Infact i was searching for this method at first, but then found it's called erase. 
@rexrainbow do you know how that normally works? Should I just create a fork go ahead and send a PR or do we talk about it first / have to get assigned first. etc? 
Sorry would be my first contribution kinda

**Comment by photonstorm** [comment]
`clear` already exists - it would be easier to just allow you to pass 4 optional parameters to it, rather than increase the API size.

`erase` is not the same thing, that uses a special blend mode and the pixels from the textures to remove it, and then you have to factor in alpha blending on non-opaque pixels too. It's meant more as a way to punch a 'shape' into a dynamic texture, than to clear an area.

**Comment by SelfDevTV** [comment]
> `clear` already exists - it would be easier to just allow you to pass 4 optional parameters to it, rather than increase the API size.

Yes that would be the best way I think. It should take  4 optional parameters ala `x: number, y: number, width: number, height: number = width` or something like that. 

> `erase` is not the same thing, that uses a special blend mode and the pixels from the textures to remove it, and then you have to factor in alpha blending on non-opaque pixels too. It's meant more as a way to punch a 'shape' into a dynamic texture, than to clear an area.

Ok understood now :) thx for clarifying

**Comment by cy920820** [comment]
> # The problem
> I have a dynamic texture I draw 1000s of numbers on it (via `Phaser.Gameobjects.Text` or `BitmapText`) and via `tex.draw()`. Sometimes I want to remove the text from a specific location on the texture. The only way I found this was via `.erase`. Problem is it only takes in a Gameobject but not the size itself. When i give it my text gameobject it will remove it but in a very weird way. Here is a screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/48333000/344629228-b9058428-8537-430a-b24c-c9999a64a30a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzU0ODUsIm5iZiI6MTcxOTk3NTE4NSwicGF0aCI6Ii80ODMzMzAwMC8zNDQ2MjkyMjgtYjkwNTg0MjgtODUzNy00MzBhLWIyNGMtYzk5OTlhNjRhMzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAyNTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTA2NDNmMGRjMDE3OGE5ODkzOGM3NWE2OThjZmZkYzQ1OWQ5MGQ4ZDc0ZWRmMTgxM2NhNjQ2Y2RiNDM4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oAah5ytzSAvHY0a6BxBKqy_8TfZv4Gvp4WM1h2Q0BSk)
> 
> A fellow discord mate helped me out with a workaround:
> 
> ```ts
> const rect = this.add.rectangle(0, 0, 10, 10, 0);
> dynTexture.erase(rect, 0, 0);
> ```
> 
> But still I thought why not implement another way of this function, that will also take in a size or width + height parameter. I would also like to try to implement it.
> 
> API for example for a `DynamicTexture` might look like this: `dynTexture.erase(width: number, height: number = width, x: ....)`
> 
> **[Optional] Do you want to help provide this feature?** Yes. API for example for a `DynamicTexture` might look like this: `dynTexture.erase(width: number, height: number = width, x: ....)`

Are you running full screen on a mobile device? The font is so blurry

**Comment by SelfDevTV** [comment]
Just zoomed in by a lot with the main cam. Maybe that's why

**Comment by zekeatchan** [comment]
Hi @SelfDevTV, thanks for submitting this feature request.

We have implemented the feature that will allow you to clear a specified area of a dynamic texture like so:
`dynamicTexture.clear(x, y, width, height)`

This update has been pushed to the `master` branch and will be part of the next release. Do test it out and feel free to reach out if you need further assistance.

**Comment by SelfDevTV** [comment]
> Hi @SelfDevTV, thanks for submitting this feature request.
> 
> We have implemented the feature that will allow you to clear a specified area of a dynamic texture like so: `dynamicTexture.clear(x, y, width, height)`
> 
> This update has been pushed to the `master` branch and will be part of the next release. Do test it out and feel free to reach out if you need further assistance.

OMG you guys are awesome. Keep it up :) Thank you very much!
