### ISSUE TITLE
add svg image in iOS not work

### ISSUE THREAD

**Issue by cy920820** [phaserjs/phaser#6855]
case: https://codepen.io/cy920820/pen/ExBYJZo

**Comment by photonstorm** [comment]
It can (see image below) - but you shouldn't load SVGs via `load.image`. Use `load.svg` for this, or use bitmap images. iOS does something weird when loading SVGs as Image data, which for some reason often takes a while for them to decode. In short, don't do it the way you're doing it.

![image](https://github.com/phaserjs/phaser/assets/164476/1c6dafa8-1c8c-4d1f-8447-b04d67d4fd27)
