### ISSUE TITLE
phaser3 nineslice Inconsistent display on different mobile devices

### ISSUE THREAD

**Issue by cy920820** [phaserjs/phaser#6858]
## Version

* Phaser Version: 3.80.1

* Operating system: android 11, iOS 16

* Browser: chrome

## Description

Using Nineslice to render a rounded background image, it was found that each terminal has differences in the rounded display

## Example Test Code
```js
let leftBubbleBg = scene.add
        .nineslice(
          marginX,
          y + screenHeight,
          ResourceManager.getUIKey('optionBgL'),
          null,
          textWidth,
          height,
          50,
          50,
          50,
          50
        )
        .setOrigin(0, 0)
```

**Comment by zekeatchan** [comment]
Hi @cy920820. 

It would be good if you could always include a link to a live example for us to check OR a complete test code like what you see in the labs (https://labs.phaser.io/) whenever you post an issue.

You can use our existing [nine-slice examples here](http://127.0.0.1:5500/public/index.html?dir=game%20objects/nine%20slice/&q=) for reference.

This would help us tremendously so we will not need to recreate your test code or go through our existing examples to figure out the problem you are facing.
