### ISSUE TITLE
TextStyle.setStyle mutates the given style parameter object

### ISSUE THREAD

**Issue by stormpanda** [phaserjs/phaser#6863]
## Version
* Phaser Version: 3.80.1
* Operating system: MacOS
* Browser: all browsers

## Description

https://github.com/phaserjs/phaser/blob/master/src/gameobjects/text/TextStyle.js

TextStyle.setStyle normalizes the given fontSize by adding "px" if it is just a number. However, the function will mutate the original given "style" parameter, which is a counterintuitive side-effect that is also unnecessary. This makes hard to define global font styles for reuse, since after the first setStyle call a font size of for example 32 (number) will be "32px" (string) afterwards, meaning it cannot be used for calculation of relative font sizes anymore.

The "style" parameter should not be mutated. Cloning it before changing it would fix the problem, I guess a shallow copy would also suffice.

## Example Test Code

https://phaser.io/sandbox/zvb8G5ux

**Comment by stormpanda** [comment]
Good bot.

**Comment by photonstorm** [comment]
No need to waste CPU/mem cloning the object, can just handle it a different way. 

Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by stormpanda** [comment]
Wow, that was quick! Thanks a lot :) Looks good to me and works as expected 👍
