### ISSUE TITLE
tilemap object position doesn't move if parent container moves position

### ISSUE THREAD

**Issue by HawkenKing** [phaserjs/phaser#6864]
## Version
* Phaser Version: 3.80.1

## Description

Expectation of tilemap and other objects to move when added to a container and moving the container.
Result: other objects move with container, tilemap is stays where it was generated.

## Example Test Code

`        this.gameContainer = this.add.container(0, 0);

        const map = this.make.tilemap({ key: 'map' });
        const tileset = map.addTilesetImage('tiles', 'tiles');
        const groundLayer = map.createLayer('Tile Layer 1', tileset);

        this.gameContainer.add(groundLayer);

        this.gameContainer.setPosition(20,20);`

## Additional Information

In this screen shot, a sprite is also added at 0,0 then the container is moved to 20,20. The sprite moves with the container but the tilemap stays at its initial added position of 0,0.

![Screenshot 2024-07-15 at 10 59 10](https://github.com/user-attachments/assets/bc349513-1e76-44cd-b7f5-221939a6064e)

**Comment by photonstorm** [comment]
Tilemaps should not be added to Containers. They are stand-alone rendering objects. We will add this to the documentation, but you shouldn't use them in this way.
