### ISSUE TITLE
iOS add sprite appear snowflake screen 

### ISSUE THREAD

**Issue by cy920820** [phaserjs/phaser#6865]
## Version

* Phaser Version: 3.80.1

* Operating system:iOS

* Browser:chrome

## Description

Create a background image using add.sprite, occasionally featuring a black snowflake screen

## Example Test Code

```js
const sprite = this.add.sprite(100, 100, spriteKey);
```

**Comment by photonstorm** [comment]
What is it _supposed_ to look like? When does it happen? What actually happens?

Upload the actual assets and sample code that shows what happens.

You need to give a lot more details in your issues, they are next to impossible to help with.

This isn't a forum or Discord. If you need real-time feedback on code, those would be much better places to ask. GitHub is for bugs in Phaser you have identified and can _demonstrate_ with a clear test case.
