### ISSUE TITLE
The Loader retries loading errored files

### ISSUE THREAD

**Issue by pavle-goloskokovic** [phaserjs/phaser#6872]
To avoid connectivity issues, usually with poor mobile networks, from breaking games – the Loader could make multiple attempts to reload errored files with exponential delay increase.

Currently if a file errors, depending on file type, it will either cause a breaking error or undesired behavior.

Here are code examples that demonstrate how playcanvas handles described behavior:

Enabling retry on loader level:
https://github.com/playcanvas/engine/blob/v1.73.0/src/framework/handlers/loader.js#L325-L338

On file type handler level:
https://github.com/playcanvas/engine/blob/v1.73.0/src/framework/handlers/handler.js#L39-L55

And on request level:
https://github.com/playcanvas/engine/blob/v1.73.0/src/platform/net/http.js#L504-L525

Ideally, `maxRetries` setting could be added to the `LoaderConfig` to be set when creating a game and used globally for loading all files, but also be changed per file type, and even set per file by adding `maxRetries` option to the `xhrSettings`.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
