### ISSUE TITLE
RoundPixels: true image scaling pixels off

### ISSUE THREAD

**Issue by saintflow47** [phaserjs/phaser#6874]
## Version

* Phaser Version:
3.85.0.beta-2
* Operating system:
W10
* Browser:
Chrome

## Description
https://phaser.io/sandbox/x8mumpYw

Basically this code leads to me having the image not fully cover the screen in the new beta with RoundPixels: true. setting roundPixels false or rolling the version back leads to it working as expected again.

![2024_07_24_141300](https://github.com/user-attachments/assets/fa534ff7-b2da-49ae-bccd-6a0ddd40caff)

I have encountered another issue that might be related as well that i havent seen before, its thin lines appearing between the outline blocks at certain window resolutions

![2024_07_27_005640](https://github.com/user-attachments/assets/839198b0-5ab9-4380-a1fa-4ab286ae6c3d)

**Comment by photonstorm** [comment]
I can't replicate this - can you have a look here and tell me what needs changing please: https://labs.phaser.io/view.html?src=src/bugs/6874%20rp.js

I've uploaded 3.85 Beta 1, Beta 2 and the current build of master ('dev' version) which you can switch between

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment]
@saintflow47  re: your Discord message. I tested your Sandbox and the labs link above in v3.85 and it fills the canvas entirely (where-as 3.80 gives you the green line across the bottom) - do you have an updated sandbox that demonstrates this with 3.85?

**Comment by saintflow47** [comment]
Updated Sandbox to show the issue: https://phaser.io/sandbox/QQFb7SU5

**Comment by photonstorm** [comment]
Ok, do a fresh build from the main branch of 3.85.2 and then test that please.
