### ISSUE TITLE
Inconsistency between the documentation and the name of parameters for the Config.js file

### ISSUE THREAD

**Issue by IvGaLa** [phaserjs/phaser#6875]
## Version

* Phaser Version: 3.80.1
* Operating system: Windows 10
* Browser: Chrome 126.0.6478.182

## Description
Hello, according to the documentation to hide the information banner with the version it is necessary to use the "hideBanner" variable for the config (https://newdocs.phaser.io/docs/3.80.0/Phaser.Core.Config#hideBanner) but with that name it doesn't work.

As can be seen in the "Config.js" file (https://github.com/phaserjs/phaser/blob/v3.80.1/src/core/Config.js) "banner" is expected as the parameter name instead from "hideBanner".

Setting the variable in the config to "banner: false" does not display the banner with the Phaser name and version.

I leave an example in the following links:
Not working: https://jsfiddle.net/IvGaLa/6gLbfzhj/8
It works: https://jsfiddle.net/IvGaLa/6gLbfzhj/9

Additionally, for the "hidePhaser" variable in the documentation it is also incorrect in the Config.js file, since it is expected as the name of the parameter "banner.hidePhaser".

Thanks greetings.

## Example Test Code
Not working: https://jsfiddle.net/IvGaLa/6gLbfzhj/8
![8](https://github.com/user-attachments/assets/972c616c-28a6-4b53-8fd3-6973a5c3fa70)

It works: https://jsfiddle.net/IvGaLa/6gLbfzhj/9
![9](https://github.com/user-attachments/assets/142a279b-d629-4665-aed3-615bda5803d2)

## Additional Information
I consider that the Config.js file is incorrect in expecting those parameter names and different ones are indicated in the configuration.

**Comment by photonstorm** [comment]
The config file is correct - it doesn't say it expects `hideBanner` to _exist in the config_. It's just an internal property within that class.

If you look at the typedef for the object that you should give to the Game instance: https://newdocs.phaser.io/docs/3.80.0/Phaser.Types.Core.GameConfig then you can see the properties this object should contain. `banner` links to https://newdocs.phaser.io/docs/3.80.0/Phaser.Types.Core.BannerConfig - or it can be a boolean (false) to disable the banner entirely.
