### ISSUE TITLE
camera follow with deadzone and high zoom no longer smooth on v3.85.0 Beta 2

### ISSUE THREAD

**Issue by Antriel** [phaserjs/phaser#6878]
Demo: https://phaser.io/sandbox/5rxAdUsy
It's jittery in 85 beta 2, smooth before.
Happens because of https://github.com/phaserjs/phaser/commit/26d85978d2494310c95760020ea62dca8b8b122a I think. Now the values jump a whole pixel, and then it smoothly follows to align. Before it smoothly followed constantly, as there was no rounding happening.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
