### ISSUE TITLE
images with preFX jitter

### ISSUE THREAD

**Issue by Antriel** [phaserjs/phaser#6879]
Demo: https://phaser.io/sandbox/oWd6hjDQ
See the every second white square. The discriminating factor seems to be camera having `roundPixels: false`, it does happen regardless of camera zoom or `pixelArt` mode. Happens on any Phaser version since preFX was added.

My best guess is that some rounding happens in a different place across the rendering pipeline for images with preFX, than it does for standard ones, which results in them getting out of sync as camera scrolls around.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by Antriel** [comment]
This improved it a lot, but there's still 1 pixel offset happening, seems like it depends on relative position to camera. E.g. camera scroll (midpoint or something) being above vs below the objects will shift them 1 px in y axis.
I would say it's issue of flooring negative numbers, but the code is using rounding, so not sure.

**Comment by aelesia** [comment]
Tested on latest master branch build and can confirm it's working
