### ISSUE TITLE
RenderTexture is broken in 3.85.0 beta 2

### ISSUE THREAD

**Issue by leha-games** [phaserjs/phaser#6884]
## Version

* Phaser Version: 3.85.0-beta.2

* Operating system: Windows 11

* Browser: Chrome

## Description

RenderTexture is broken on game resize. It just turns black, or black and white when there is mask on RenderTexture. 

## Example Test Code

Try to resize browser window

```
class Example extends Phaser.Scene {
    preload () {
        this.load.image('pic', 'https://labs.phaser.io/assets/pics/brilliance-jim-sachs.png');
    }

    create () {
        const rt = this.add.renderTexture(400, 300, 800, 600);
        rt.draw('pic');
    }
}

const config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    backgroundColor: '#aaaaaa',
    scale: {
        mode: Phaser.Scale.ScaleModes.RESIZE,
        width: 800,
        height: 600,
    },
    scene: Example
};

const game = new Phaser.Game(config);
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
