### ISSUE TITLE
leave fullscreen event fires twice

### ISSUE THREAD

**Issue by Antriel** [phaserjs/phaser#6885]
`Phaser.Scale.Events.LEAVE_FULLSCREEN` fires twice when leaving fullscreen.

Demo: https://phaser.io/sandbox/S32a1tbU

It only happens when using the API to quit. Pressing ESC key to leave fullscreen will only fire the event once.

**Comment by zekeatchan** [comment]
Hi @Antriel. Thanks for submitting this issue. A fix has been pushed to the `master` branch. It will be part of the next release. Do test it out and let us know if you encounter any issues.
