### ISSUE TITLE
Emulated touch events not being handled correctly

### ISSUE THREAD

**Issue by HarrisonKeys-wymac** [phaserjs/phaser#6888]
## Version

* Phaser Version: 3.80.1

* Operating system: Windows

* Browser:

## Description

While using emulated devices in Chrome or Microsoft Edge, pointer down is only called once the touch is released. This only occurs the first time the project is ran, if you refresh the page touch events will work as expected, but if you close the tab and open a new one, they will be broken again. 

## Example Test Code

This can be reproduced using the webpack template, I added a comment inside each of the input.once('pointerdown') to log that the event had been called.
https://github.com/phaserjs/template-webpack

**Comment by photonstorm** [comment]
We cannot duplicate this. Have tested on Windows 11 in several browsers (Edge, Chrome, FF). Here is a video showing it working fine in Win 11 Chrome in Mobile Emulation mode:

https://github.com/user-attachments/assets/d2f73a52-f926-42a2-bcdb-a06f528212eb

The console is logging the down event immediately, without releasing the pointer first.

I would suggest testing this on another device. It could well be something local (browser extension, plugin, etc)
