### ISSUE TITLE
webgl not supported ios version 17.5 

### ISSUE THREAD

**Issue by jebarpg** [phaserjs/phaser#6891]
## Version

* Phaser Version: 3.80.1

* Operating system: iOS version 17.5

* Browser: iOS version 17.5 emulator depends on safari browser

## Description

This is an issue with the iOS version 17.5 emulator. I saw here: 
https://discussions.unity.com/t/webgl-context-lost-ios-17-safari/930432/11
That it could be an issue with “Run in Background” enabled
I also read your post here:
https://github.com/phaserjs/phaser/issues/6599
and saw that things were working back in last September. 

here is the phaser.js section of the error

```
JS Eval error at JavaScript exception occurred
phaser-nD4EcAQo.js:4704:2645
```

Is there any setting I can toggle to get around this error?

## Example Test Code

I'm use the https://github.com/phaserjs/template-bun
with no modifications to the project. Just running it as is from the repo.

**Comment by photonstorm** [comment]
On an actual device running iOS 17.5.1 Phaser under WebGL works perfectly well. iOS 17.6.1 is the current version of iOS and under that it works perfectly as well. So as it stands, I don't believe there are any active issues with WebGL games not working on iOS.

Having them recover from a context loss is another issue, but actually running we see no problems on _real hardware_.

**Comment by jebarpg** [comment]
Thank you for such quick feedback. I had a friend test on real hardware as well and they too are able to run it just fine. I'll see what I can find out on Apple forums.
