### ISSUE TITLE
Split type definitions

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [phaserjs/phaser#6897]
Hey, any chance we could get the type definitions split up into many smaller files? My IDE (IntelliJ Idea Ultimate) is really struggling to load and navigate [the single 5.71 MB types file](https://github.com/phaserjs/phaser/blob/master/types/phaser.d.ts).

**Comment by photonstorm** [comment]
Hi - do you have any evidence to suggest this would actually resolve it? It's still going to have 5.71MB of type files, just in smaller chunks, because that's just how big and comprehensive our docs are. Especially as VSCode, even Monaco, has no issues with the size.

**Comment by hubertgrzeskowiak** [comment]
I did some more experimenting, and it seems that the culprit is Idea's default rendering of comments as markdown. It becomes much more responsive when you disable the "reader mode". The memory footprint that Idea reports is all over the place, with about 1000MB heap used when I only have a few files open, and about 1050-1250 with the `phaser.d.ts` opened in plain mode. When I switch to the "reader mode" (markdown rendering), it jumps to around 1500-2300 and makes the editor unresponsive for a few seconds.

That said, I think disabling the "reader mode" for this file works as a good workaround. Having multiple files instead of one would prevent Idea from rendering it all at once.

Feel free to close the issue, as I'm personally happy with the workaround.


![Screenshot 2024-08-31 at 9 52 19 PM](https://github.com/user-attachments/assets/3ced0dc0-3dd8-4fb3-9393-657d936d48af)

**Comment by photonstorm** [comment]
I'm glad you found a workaround, but this genuinely sounds like a bug / poor implementation within IntelliJ IDEA. There's no way a 5MB defs file should create 1GB worth of heap, unless the way they handle it internally is extremely poorly written.

The problem with splitting it up is that Phaser isn't based on ES Modules, which is the natural point at which you'd split defs. When we make that migration it should be easier to do this, and the IDEs should then identify the module being imported and pull in those defs - but right now, it's impossible for it to do this as it's all namespace based.

**Comment by JernejHabjan** [comment]
+1 on this one. It really laggs the entire IDE if you turn on reader mode because of huge docs file.
