### ISSUE TITLE
Typescript bug: GameConfig white, missing and default images type error

### ISSUE THREAD

**Issue by AlvaroNeuronup** [phaserjs/phaser#6904]
There is a type error with the missing, white and default images. Type is `string | undefined` it should be `string | undefined | null`

## Version

3.85.1 using typescript npm package

## Description

According to 3.85 version, you can set images to null:

- Added Default Image Handling in TextureManager. In the game config, set defaultImage to null to ignore loading the defaultImage.
- Added Missing Image Handling in TextureManager. In the game config, set missingImage to null to ignore loading the missingImage.
- Added White Image Support in TextureManager. In the game config, set whiteImage to null to ignore loading the whiteImage.

## Example Test Code

![image](https://github.com/user-attachments/assets/3af4a5ea-64cb-4325-8b3c-0897458e119e)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
