### ISSUE TITLE
WebGLRenderer: this.init.setupExtensions is undefined

### ISSUE THREAD

**Issue by RedRoosterMobile** [phaserjs/phaser#6905]
## Version

* Phaser Version: 3.85.1 WebGL

* Operating system: iOS Apple A12 GPU + Android  with arm mali-g72 GPU

* Browser: Safari, but not specific

## Description

In WebGLRenderer:
```
// Restore GL extensions.
this.init.setupExtensions();
```
When executed results in:
`this.init.setupExtensions is not a function. (In 'this.init.setupExtensions()', 'this.init.setupExtensions' is undefined)`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
