### ISSUE TITLE
Input event is not being emitted

### ISSUE THREAD

**Issue by UnaiNeuronUp** [phaserjs/phaser#6908]
## Version
* Phaser Version: 3.85.2

* Operating system: Windows

* Browser: Chrome / edge

## Description
When a game object with interactive is set to alpha 0 or visible false it blocks behind scene input until you interact with it after hiding the game object (moving the mouse or clicking in the scene).

## Example Test Code

https://phaser.io/sandbox/eM8NoA75

To reproduce the error just put the cursor in the intersection between red and green rects, wait to red rect disappear and click without moving the mouse. That click is ignored and will show no logs in the console, but if you click again or you move the mouse before that first click it will show the logs of the MainScene.

**Comment by photonstorm** [comment]
This is correct behaviour - we don't constantly poll the objects below the mouse, we do it on movement only. If you want to set it to constantly poll every frame you can do so (just be aware of the impact it may have if you've a really busy Scene), or you can disable input on the game object that has now vanished, that would also clear it from the input cache it is stored in.

**Comment by rexrainbow** [comment]
Hidden game object (alpha is 0 and/or invisible) will be ignored during input detecting process. It is design intend, imo.

A normal solution is to add a render-able game object into a container, then attach touch events on that parent container, therefore, this render-able game object could be hidden, and parent container can still receive touch events.

If you still need Clickable-when-hidden in a single game object, might try this hack solution : 

```javascript
var ClickableWhenHidden = function (GOClass) {
    var WillRender = GOClass.prototype.willRender;
    return class Base extends GOClass {
        // Override default behavior, always return trun even if this game object is invisible.
        willRender(camera) {
            return true;
        }

        renderWebGL(renderer, src, camera, parentMatrix) {
            // Don't render any thing if Default willRender method return false
            if (!WillRender.call(this, camera)) {
                return;
            }
            super.renderWebGL(renderer, src, camera, parentMatrix);
        }

        renderCanvas(renderer, src, camera, parentMatrix) {
            // Don't render any thing if Default willRender method return false
            if (!WillRender.call(this, camera)) {
                return;
            }
            super.renderCanvas(renderer, src, camera, parentMatrix);
        }
    }
}
```

[Demo](https://phaser.io/sandbox/RmZYwcar)
