### ISSUE TITLE
Add a citation file to repository

### ISSUE THREAD

**Issue by thompson318** [phaserjs/phaser#6911]
I've been using phaser in my research and would like to cite phaser in an academic paper to acknowledge your awesome work. Currently there's no easy way to do this so I've just included a link to https://phaser.io in the paper. We usually include a CITATION.cff file in the repository to make this easier [this for example](https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/master/CITATION.cff)
If you're interested in doing this I'm happy to contribute the CITATION.cff file via a pull request, but I'm not sure what to put on the author list as you have > 600 contributors. Could just be something generic like "Phaser Core Developers" or it could list literally very contributor.
To do 
- [ ] Decide on author list
- [ ] Add citation.cff
- [ ] Add to https://phaser.io ?

**Comment by photonstorm** [comment]
Hmm, that's an interesting idea. I don't think we need to list everyone - hundreds of those contributions aren't even in the current version of Phaser! They just remain on that list (as they should) even though the framework evolves and changes.

I'll review your PR and probably add in the core team and then we'll have to be a bit more generic for the rest.
