### ISSUE TITLE
Video is displaying larger than expected

### ISSUE THREAD

**Issue by mikaleerhart** [phaserjs/phaser#6925]
## Version

* Phaser Version: 3.86.0

* Operating system: macOS 15

* Browser: Firefox, Safari, Chrome

## Description

Video size is rendering way larger then the size set. Happening with setDisplaySize and setScale methods.

## Example Test Code

```
this.load.video('testvideo', 'assets/somevideo.mp4');
const video = this.add.video(0, 0, 'testvideo').setOrigin(0, 0);
video.setDisplaySize(this.scale.width, this.scale.height);
video.play();
```
result: (game size is 1024x768, but video is so large that only the top left of the sky displays)
![Screenshot 2024-10-18 at 1 40 12 PM](https://github.com/user-attachments/assets/8ddaf7b4-326e-40d3-b398-b4c56dbdce01)

`video.setDisplaySize(100, 100);`

result: (game size is 1024x768, so should only be taking up ~1/10th of screen.
![Screenshot 2024-10-18 at 1 39 37 PM](https://github.com/user-attachments/assets/8826a6b9-7f5e-4438-b54b-3d763533eef8)

## Additional Information

I discovered this issue in my project, but to reproduce I downloaded the [Phaser 3 Vite template](https://github.com/phaserjs/template-vite), downloaded [a random video](https://videos.pexels.com/video-files/3151454/3151454-uhd_4096_2160_24fps.mp4) at 1080p and added the above code to the Game scene create function. Also tried with both .mp4 and .webm videos at different resolutions, getting the same result.

**Comment by mikaleerhart** [comment]
Something I discovered: if I resize the video in the update method of my scene, it works properly. Obviously not ideal though. I must be trying to resize it too early? I'm now trying

`video.addListener('addedtoscene', this.scaleVideo);`

but my function is not getting called. What am I missing here?

**Comment by photonstorm** [comment]
The moment game object is created it is added to the Scene. As per our examples, you need to resize it when it starts playing - because it doesn't have any of the size data for the video until it actually starts streaming down, after play is called:

```js
        const vid = this.add.video(0, 0, 'pumpkins').setOrigin(0, 0).play(true);

        vid.once('play', () => {

            vid.setDisplaySize(400, 300);

        });
 ```
