### ISSUE TITLE
[Docs] Phaser Editor Navbar element not show as active

### ISSUE THREAD

**Issue by scottwestover** [phaserjs/phaser#6928]
## Description

First, just wanted to say nice job on the new documentation site! It is really nice.

While going through the docs, I noticed a few issues and wanted to share with the team.

For the first one, when you click on the `Phaser Editor` navbar item, or navigate to any of the Phaser Editor wiki pages, the `Phaser` navbar element is showing as active instead of the `Phaser Editor` navbar element. 

Example page: https://docs.phaser.io/phaser-editor/intro/welcome

![Oct-21-2024 20-32-17](https://github.com/user-attachments/assets/a047c8b9-c149-4227-b10a-8d095472baf7)

For the second issue, when you click the `Discord` navbar element, this just opens the page Discord home page (https://discord.com/),  instead of the Discord invite page: https://discord.com/invite/phaser. This also opens in the same browser tab, and it be nice if this opened in a new tab.

## Additional Information

I apologize in advance if the documentation bugs should go to another repo. Not sure if it is planned, but maybe on the docs site there could be a link for opening a new issue if an error is found.

**Comment by photonstorm** [comment]
Yeah we already reported the navbar bug to Hashnode, they will fix it in the morning! So it should be resolved in a few hours time :)

The Discord bug is weird - but I suspect also related to the navbar, as the link should be `https://discord.gg/phaser` as that is our custom link! This is the link that shows in our server settings, but for some reason it doesn't work now. I'll ping Discord and figure out why.

**Comment by photonstorm** [comment]
The navbar issue is now fixed, thanks :)
