### ISSUE TITLE
Documentation links all redirect to "https://docs.phaser.io/phaser/getting-started/what-is-phaser"

### ISSUE THREAD

**Issue by edstef** [phaserjs/phaser#6933]
I know this is not a bug with the Phaser 3 library but want to bring it up as it is definitely an issue and related to Phaser 3.

When i google search for a phaser method:

<img width="1470" alt="Screenshot 2024-10-27 at 1 18 33 PM" src="https://github.com/user-attachments/assets/6ea80643-78a6-4541-a778-b40404f74da2">

It always redirects me to this page:

<img width="1469" alt="Screenshot 2024-10-27 at 1 18 21 PM" src="https://github.com/user-attachments/assets/5dfb9aa2-3ebe-4a7f-8fc5-4f8b9c720995">

If i copy the URL: https://newdocs.phaser.io/docs/3.60.0/focus/Phaser.Cameras.Scene2D.Camera-zoomTo

It redirects me to: https://docs.phaser.io/phaser/getting-started/what-is-phaser

This happens with every method i try to search for, and makes development really annoying.

**Comment by Antonio-Riccelli** [comment]
Same here. Very annoying.

**Comment by photonstorm** [comment]
We updated over 500 redirects last week, that captures all of the core classes, so we're going to close this issue off for now. Search on the docs site itself has also been overhauled, so use that instead of google to ensure you remain local.
