### ISSUE TITLE
MUCH LIKE THIS ISSUE, THE EVENT DOCUMENTATION SHOULD NOT BE IN ALL CAPS

### ISSUE THREAD

**Issue by HyperCrowd** [phaserjs/phaser#6934]
HELLO

I AM TYPING THIS IN ALL CAPS AND I KNOW THIS IS A BIG SOCIAL FAUX PAS, BUT HEAR ME OUT

THE DOCUMENTATION (SORRY, URLS ARE IN LOWER CASE https://docs.phaser.io/api-documentation/namespace/core-events#ready) SAYS THE READY EVENT IS IN ALL CAPS

SO WHEN I MAKE A LISTENER, I HAVE IT LISTEN TO '`READY`'

THIS DOESN'T WORK.  WHY?

BECAUSE THE CODE SHOWS THE EVENT NAME FOR READY TO BE IN ALL LOWER CASE https://github.com/phaserjs/phaser/blob/v3.85.2/src/core/events/READY_EVENT.js#L17

YOU KNOW WHAT'S MORE ANNOYING THAN HAVING A GITHUB ISSUE WRITTEN IN ALL CAPS?  HAVING DOCUMENTATION THAT SAYS EVENTS ARE IN ALL CAPS WHILE THE CODE SAYS ITS ALL IN LOWER CASE

THANK YOU, HAVE A BLESSED DAY, NAMASTE

**Comment by photonstorm** [comment]
Nowhere does it say the event string is in caps. The constant used for it is:

this.events.on(Phaser.Core.Events.READY)

Or

this.events.on('ready')
