### ISSUE TITLE
Docs missing Phaser.Actions.WrapInRectangle

### ISSUE THREAD

**Issue by Hyllesen** [phaserjs/phaser#6944]
Docs seems to be missing description on WrapInRectangle. I can see some description when googling but the link doesn't lead to info on docs.

[https://docs.phaser.io/phaser/concepts/actions#wrap-in-rectangle](https://docs.phaser.io/phaser/concepts/actions#wrap-in-rectangle)

**Comment by samme** [comment]
It should be <https://docs.phaser.io/api-documentation/function/actions#wrapinrectangle>.
