### ISSUE TITLE
Set The Câmera position on Game Config Object

### ISSUE THREAD

**Issue by Haruki-Hotarou-2021** [phaserjs/phaser#6950]
I'm trying to add the camera position to center the origin in all scenes using only one object in the game configuration:

```javascript
const game = new Phaser.Game({
  type: Phaser.AUTO,
  width: window.innerWidth,
  height: window.innerHeight,
  camera: {
    center: [0.5, 0.5]
  },
  scene: [Scene1, Scene2]
});
```

However, when doing this nothing changes, I searched and tried several entries for the object, but I was unable to center the origin of the screen for all

**Comment by photonstorm** [comment]
It doesn't do anything, because this code is just made up. The property doesn't even exist. Please check the API documentation to see what is actually valid in the game config. To do this, create your own default Scene and set the Camera position in there, then extend and use that.
