### ISSUE TITLE
Error when adding rectangle in Firefox on MacOS (Phaser v4)

### ISSUE THREAD

**Issue by GillesVermeulen** [phaserjs/phaser#6954]
## Version

* Phaser Version: 4.0.0-beta.1

* Operating system: MacOS 15.1

* Browser: Firefox 132.0.2 (aarch64)

## Description

When adding a rectangle in Phaser 4 beta, you get the following error in Firefox:
**Error: Link Shader failed:Uniform `uResolution` is not linkable between attached shaders.**

It works in other browsers (Chrome, Safari).

## Example Test Code

Example code: [https://phaser.io/sandbox/qVcCJw76](https://phaser.io/sandbox/qVcCJw76)

**Comment by photonstorm** [comment]
Thanks for opening this issue. We've already fixed this! You can read the comment here: https://github.com/phaserjs/phaser/issues/6951#issuecomment-2482052560 and the fix will be in Beta 2, which honestly we'll probably release tomorrow.

**Comment by GillesVermeulen** [comment]
Great news, sorry for not noticing the other/older issue.
