### ISSUE TITLE
Copying the sample code to clipboard pastes odd results 

### ISSUE THREAD

**Issue by meems1996** [phaserjs/phaser#6960]
## Version

* Phaser Version: Phaser3 but this is an issue with the learning documentation

* Operating system: MacOS

* Browser: Chrome

## Description

In the learning documentation (https://docs.phaser.io/phaser/getting-started/set-up-dev-environment ) I was going over the page Working with Phaser in the Getting Started portion of the docs. Under the section for Hello World there is a sample code that users are encouraged to copy and paste. When I copy the code in my clipboard using the copy button and paste it, I get the following result: 

```
<!DOCTYPE ,[object Object],>
<,[object Object],>
<,[object Object],>
    <,[object Object], ,[object Object],=,[object Object],></,[object Object],>
</,[object Object],>
<,[object Object],>

    <,[object Object],>
    ,[object Object], ,[object Object], ,[object Object], ,[object Object],
    {
        preload ()
        {
            ,[object Object],.,[object Object],.,[object Object],(,[object Object],);

            ,[object Object],.,[object Object],.,[object Object],(,[object Object],, ,[object Object],);
            ,[object Object],.,[object Object],.,[object Object],(,[object Object],, ,[object Object],);
            ,[object Object],.,[object Object],.,[object Object],(,[object Object],, ,[object Object],);
        }

        create ()
        {
            ,[object Object],.,[object Object],.,[object Object],(,[object Object],, ,[object Object],, ,[object Object],);

            ,[object Object], particles = ,[object Object],.,[object Object],.,[object Object],(,[object Object],, ,[object Object],, ,[object Object],, {
                ,[object Object],: ,[object Object],,
                ,[object Object],: { ,[object Object],: ,[object Object],, ,[object Object],: ,[object Object], },
                ,[object Object],: ,[object Object],
            });

            ,[object Object], logo = ,[object Object],.,[object Object],.,[object Object],.,[object Object],(,[object Object],, ,[object Object],, ,[object Object],);

            logo.,[object Object],(,[object Object],, ,[object Object],);
            logo.,[object Object],(,[object Object],, ,[object Object],);
            logo.,[object Object],(,[object Object],);

            particles.,[object Object],(logo);
        }
    }

    ,[object Object], config = {
        ,[object Object],: ,[object Object],.,[object Object],,
        ,[object Object],: ,[object Object],,
        ,[object Object],: ,[object Object],,
        ,[object Object],: ,[object Object],,
        ,[object Object],: {
            ,[object Object],: ,[object Object],,
            ,[object Object],: {
                ,[object Object],: { ,[object Object],: ,[object Object], }
            }
        }
    };

    ,[object Object], game = ,[object Object], ,[object Object],.,[object Object],(config);
    </,[object Object],>

</,[object Object],>
</,[object Object],>

```

instead of the desired code: 

<img width="473" alt="image" src="https://github.com/user-attachments/assets/0805a956-5e84-42f3-9102-9a9bc91147c2">

## Example Test Code

No source code is necessary here I imagine. This is just related to copying the sample code in the learning docs. 

## Additional Information

To reproduce this error the only thing I can think of would be to try and use the copy button in the code sample on the page https://docs.phaser.io/phaser/getting-started/set-up-dev-environment and paste it anywhere. I tried pasting it in my code editor, in a note on my laptop and here on the ticket.

**Comment by photonstorm** [comment]
Thanks for reporting this. We have raised the issue with HashNode (our docs host). Will update this when they have a fix in place.

**Comment by photonstorm** [comment]
Ok, Hashnode has rolled out a fix, and this should be working properly now! Again, thank you for reporting it :)
