### ISSUE TITLE
ColorMatrix PreFX not working in Firefox on Linux (image goes black)

### ISSUE THREAD

**Issue by Baegus** [phaserjs/phaser#6964]
## Version

* Phaser Version: 3.87.0 (or lower)

* Operating system: Ubuntu, Arch Linux, Steam OS

* Browser: Firefox 132.0.2 (or lower)

## Description

When using any ColorMatrix PreFX, the image goes completely black (or white, in some cases). I tried Ubuntu, Arch Linux and Steam OS (running on my Steam Deck). Doesn't happen on Android version of Firefox.

## Example Test Code

Everything is apparent from [this Labs example](https://labs.phaser.io/view.html?src=src\fx\colormatrix\colormatrix%20fx.js).

## Additional Information

Screenshot from Ubuntu:

![VirtualBoxVM_obk5ysGYUD](https://github.com/user-attachments/assets/3ce1d3c2-0d42-44ff-a51c-a7fa9c7123f5)

**Comment by Baegus** [comment]
Tried using postFX instead of preFX and it seems to work fine. 👍

**Comment by photonstorm** [comment]
This is a known issue that we've resolved in the v4.0.0 renderer. In the meantime, please use PostFX and then upgrade when the time is right.
